DB_ALTERAC_MOUNTAINS_GENERAL = {
  ["region"] = "Eastern Kingdoms",
  ["mapID"] = 1416,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Thanthaldis Snowgleam",
      ["id"] = "13217",
      ["description"] = "Stormpike Supply Officer",
      ["comment"] = "",
      ["mainLocation"] = "Alterac Mountains",
      ["subLocation"] = "Alterac Mountains",
      ["x"] = 0.39399999999999996,
      ["y"] = 0.816,
    },
    {
      ["category"] = "repair",
      ["name"] = "Jekyll Flandring",
      ["id"] = "13219",
      ["description"] = "Frostwolf Supply Officer",
      ["comment"] = "",
      ["mainLocation"] = "Alterac Mountains",
      ["subLocation"] = "Alterac Mountains",
      ["x"] = 0.628,
      ["y"] = 0.594,
    },
    {
      ["category"] = "banker",
      ["name"] = "Teller Rames",
      ["id"] = "275210",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "Alterac Mountains",
      ["subLocation"] = "Alterac Mountains",
      ["x"] = 0.228,
      ["y"] = 0.644,
    },
    {
      ["category"] = "banker",
      ["name"] = "Teller Hanners",
      ["id"] = "275212",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "Alterac Mountains",
      ["subLocation"] = "Alterac Mountains",
      ["x"] = 0.23,
      ["y"] = 0.65,
    },
    {
      ["category"] = "banker",
      ["name"] = "Teller Althiellis",
      ["id"] = "275214",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "Alterac Mountains",
      ["subLocation"] = "Alterac Mountains",
      ["x"] = 0.22399999999999998,
      ["y"] = 0.6559999999999999,
    },
    {
      ["category"] = "banker",
      ["name"] = "Teller Almeida",
      ["id"] = "275240",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "Alterac Mountains",
      ["subLocation"] = "Alterac Mountains",
      ["x"] = 0.11,
      ["y"] = 0.688,
    },
    {
      ["category"] = "banker",
      ["name"] = "Teller Gee",
      ["id"] = "275243",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "Alterac Mountains",
      ["subLocation"] = "Alterac Mountains",
      ["x"] = 0.10400000000000001,
      ["y"] = 0.684,
    },
    {
      ["category"] = "banker",
      ["name"] = "Paymaster Chang",
      ["id"] = "275251",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "Alterac Mountains",
      ["subLocation"] = "Alterac Mountains",
      ["x"] = 0.10800000000000001,
      ["y"] = 0.68,
    },
    {
      ["category"] = "banker",
      ["name"] = "Teller Plushner",
      ["id"] = "275253",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "Alterac Mountains",
      ["subLocation"] = "Alterac Mountains",
      ["x"] = 0.10400000000000001,
      ["y"] = 0.69,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Fahrad",
      ["id"] = "6707",
      ["description"] = "Grand Master Rogue",
      ["comment"] = "",
      ["mainLocation"] = "Alterac Mountains",
      ["subLocation"] = "Alterac Mountains",
      ["x"] = 0.8440000000000001,
      ["y"] = 0.802,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Bro'kin",
      ["id"] = "2480",
      ["description"] = "Alchemy Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Alterac Mountains",
      ["subLocation"] = "Alterac Mountains",
      ["x"] = 0.384,
      ["y"] = 0.38799999999999996,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Rizz Loosebolt",
      ["id"] = "2684",
      ["description"] = "Engineering Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Alterac Mountains",
      ["subLocation"] = "Alterac Mountains",
      ["x"] = 0.47200000000000003,
      ["y"] = 0.35200000000000004,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Zan Shivsproket",
      ["id"] = "6777",
      ["description"] = "Speciality Engineer",
      ["comment"] = "",
      ["mainLocation"] = "Alterac Mountains",
      ["subLocation"] = "Alterac Mountains",
      ["x"] = 0.86,
      ["y"] = 0.8,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Smudge Thunderwood",
      ["id"] = "6779",
      ["description"] = "Poison Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Alterac Mountains",
      ["subLocation"] = "Alterac Mountains",
      ["x"] = 0.86,
      ["y"] = 0.7959999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Mirvyna Jinglepocket",
      ["id"] = "14961",
      ["description"] = "Smokywood Pastures",
      ["comment"] = "",
      ["mainLocation"] = "Alterac Mountains",
      ["subLocation"] = "Alterac Mountains",
      ["x"] = 0.4,
      ["y"] = 0.802,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Dillord Copperpinch",
      ["id"] = "14962",
      ["description"] = "Smokywood Pastures",
      ["comment"] = "",
      ["mainLocation"] = "Alterac Mountains",
      ["subLocation"] = "Alterac Mountains",
      ["x"] = 0.62,
      ["y"] = 0.586,
    },
  }
}
