DB_ARATHI_HIGHLANDS_GENERAL = {
  ["region"] = "Kalimdor",
  ["mapID"] = 1417,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Jannos Ironwill",
      ["id"] = "1471",
      ["description"] = "Superior Macecrafter",
      ["comment"] = "",
      ["mainLocation"] = "Arathi Highlands",
      ["subLocation"] = "Arathi Highlands",
      ["x"] = 0.46,
      ["y"] = 0.47600000000000003,
    },
    {
      ["category"] = "repair",
      ["name"] = "Mu'uta",
      ["id"] = "9555",
      ["description"] = "Bowyer",
      ["comment"] = "",
      ["mainLocation"] = "Arathi Highlands",
      ["subLocation"] = "Arathi Highlands",
      ["x"] = 0.726,
      ["y"] = 0.33399999999999996,
    },
    {
      ["category"] = "repair",
      ["name"] = "Rutherford Twing",
      ["id"] = "15126",
      ["description"] = "Defilers Supply Officer",
      ["comment"] = "",
      ["mainLocation"] = "Arathi Highlands",
      ["subLocation"] = "Arathi Highlands",
      ["x"] = 0.7340000000000001,
      ["y"] = 0.298,
    },
    {
      ["category"] = "repair",
      ["name"] = "Samuel Hawke",
      ["id"] = "15127",
      ["description"] = "League of Arathor Supply Officer",
      ["comment"] = "",
      ["mainLocation"] = "Arathi Highlands",
      ["subLocation"] = "Arathi Highlands",
      ["x"] = 0.46,
      ["y"] = 0.452,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Innkeeper Adegwa",
      ["id"] = "9501",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Arathi Highlands",
      ["subLocation"] = "Arathi Highlands",
      ["x"] = 0.738,
      ["y"] = 0.326,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Tharlidun",
      ["id"] = "9976",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "Arathi Highlands",
      ["subLocation"] = "Arathi Highlands",
      ["x"] = 0.738,
      ["y"] = 0.332,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Cedrik Prose",
      ["id"] = "2835",
      ["description"] = "Gryphon Master",
      ["comment"] = "",
      ["mainLocation"] = "Arathi Highlands",
      ["subLocation"] = "Arathi Highlands",
      ["x"] = 0.456,
      ["y"] = 0.46,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Urda",
      ["id"] = "2851",
      ["description"] = "Wind Rider Master",
      ["comment"] = "",
      ["mainLocation"] = "Arathi Highlands",
      ["subLocation"] = "Arathi Highlands",
      ["x"] = 0.73,
      ["y"] = 0.326,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Slagg",
      ["id"] = "2818",
      ["description"] = "Superior Butcher",
      ["comment"] = "",
      ["mainLocation"] = "Arathi Highlands",
      ["subLocation"] = "Arathi Highlands",
      ["x"] = 0.74,
      ["y"] = 0.33799999999999997,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Brumn Winterhoof",
      ["id"] = "7869",
      ["description"] = "Master Elemental Leatherworker",
      ["comment"] = "",
      ["mainLocation"] = "Arathi Highlands",
      ["subLocation"] = "Arathi Highlands",
      ["x"] = 0.282,
      ["y"] = 0.45,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jannos Ironwill",
      ["id"] = "1471",
      ["description"] = "Superior Macecrafter",
      ["comment"] = "",
      ["mainLocation"] = "Arathi Highlands",
      ["subLocation"] = "Arathi Highlands",
      ["x"] = 0.46,
      ["y"] = 0.47600000000000003,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Deneb Walker",
      ["id"] = "2805",
      ["description"] = "Scrolls & Potions",
      ["comment"] = "",
      ["mainLocation"] = "Arathi Highlands",
      ["subLocation"] = "Arathi Highlands",
      ["x"] = 0.27,
      ["y"] = 0.588,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Vikki Lonsav",
      ["id"] = "2808",
      ["description"] = "General Goods",
      ["comment"] = "",
      ["mainLocation"] = "Arathi Highlands",
      ["subLocation"] = "Arathi Highlands",
      ["x"] = 0.46399999999999997,
      ["y"] = 0.474,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Hammon Karwn",
      ["id"] = "2810",
      ["description"] = "Superior Tradesman",
      ["comment"] = "",
      ["mainLocation"] = "Arathi Highlands",
      ["subLocation"] = "Arathi Highlands",
      ["x"] = 0.46399999999999997,
      ["y"] = 0.474,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Drovnar Strongbrew",
      ["id"] = "2812",
      ["description"] = "Alchemy Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Arathi Highlands",
      ["subLocation"] = "Arathi Highlands",
      ["x"] = 0.46399999999999997,
      ["y"] = 0.47,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Narj Deepslice",
      ["id"] = "2814",
      ["description"] = "Butcher",
      ["comment"] = "",
      ["mainLocation"] = "Arathi Highlands",
      ["subLocation"] = "Arathi Highlands",
      ["x"] = 0.456,
      ["y"] = 0.47600000000000003,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Androd Fadran",
      ["id"] = "2816",
      ["description"] = "Leatherworking Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Arathi Highlands",
      ["subLocation"] = "Arathi Highlands",
      ["x"] = 0.45,
      ["y"] = 0.46799999999999997,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Tunkk",
      ["id"] = "2819",
      ["description"] = "Leatherworking Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Arathi Highlands",
      ["subLocation"] = "Arathi Highlands",
      ["x"] = 0.748,
      ["y"] = 0.34600000000000003,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Graud",
      ["id"] = "2820",
      ["description"] = "General Goods",
      ["comment"] = "",
      ["mainLocation"] = "Arathi Highlands",
      ["subLocation"] = "Arathi Highlands",
      ["x"] = 0.74,
      ["y"] = 0.324,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Keena",
      ["id"] = "2821",
      ["description"] = "Trade Goods",
      ["comment"] = "",
      ["mainLocation"] = "Arathi Highlands",
      ["subLocation"] = "Arathi Highlands",
      ["x"] = 0.74,
      ["y"] = 0.326,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Uttnar",
      ["id"] = "4954",
      ["description"] = "Butcher",
      ["comment"] = "",
      ["mainLocation"] = "Arathi Highlands",
      ["subLocation"] = "Arathi Highlands",
      ["x"] = 0.742,
      ["y"] = 0.33799999999999997,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jun'ha",
      ["id"] = "6574",
      ["description"] = "Tailoring Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Arathi Highlands",
      ["subLocation"] = "Arathi Highlands",
      ["x"] = 0.726,
      ["y"] = 0.364,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Innkeeper Adegwa",
      ["id"] = "9501",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Arathi Highlands",
      ["subLocation"] = "Arathi Highlands",
      ["x"] = 0.738,
      ["y"] = 0.326,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Mu'uta",
      ["id"] = "9555",
      ["description"] = "Bowyer",
      ["comment"] = "",
      ["mainLocation"] = "Arathi Highlands",
      ["subLocation"] = "Arathi Highlands",
      ["x"] = 0.726,
      ["y"] = 0.33399999999999996,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Targot Jinglepocket",
      ["id"] = "15124",
      ["description"] = "Smokywood Pastures",
      ["comment"] = "",
      ["mainLocation"] = "Arathi Highlands",
      ["subLocation"] = "Arathi Highlands",
      ["x"] = 0.46399999999999997,
      ["y"] = 0.45399999999999996,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kosco Copperpinch",
      ["id"] = "15125",
      ["description"] = "Smokywood Pastures",
      ["comment"] = "",
      ["mainLocation"] = "Arathi Highlands",
      ["subLocation"] = "Arathi Highlands",
      ["x"] = 0.74,
      ["y"] = 0.292,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Rutherford Twing",
      ["id"] = "15126",
      ["description"] = "Defilers Supply Officer",
      ["comment"] = "",
      ["mainLocation"] = "Arathi Highlands",
      ["subLocation"] = "Arathi Highlands",
      ["x"] = 0.7340000000000001,
      ["y"] = 0.298,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Samuel Hawke",
      ["id"] = "15127",
      ["description"] = "League of Arathor Supply Officer",
      ["comment"] = "",
      ["mainLocation"] = "Arathi Highlands",
      ["subLocation"] = "Arathi Highlands",
      ["x"] = 0.46,
      ["y"] = 0.452,
    },
    {
      ["category"] = "spirithealer",
      ["name"] = "Spirit Healer",
      ["id"] = "6491",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Arathi Highlands",
      ["subLocation"] = "Arathi Highlands",
      ["x"] = 0.486,
      ["y"] = 0.556,
    },
    {
      ["category"] = "book",
      ["name"] = "Aftermath of the Second War",
      ["id"] = "21581",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Arathi Highlands",
      ["subLocation"] = "Arathi Highlands",
      ["x"] = 0.226,
      ["y"] = 0.24,
    },
    {
      ["category"] = "book",
      ["name"] = "Beyond the Dark Portal",
      ["id"] = "21582",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Arathi Highlands",
      ["subLocation"] = "Arathi Highlands",
      ["x"] = 0.226,
      ["y"] = 0.24,
    },
    {
      ["category"] = "book",
      ["name"] = "Sargeras and the Betrayal",
      ["id"] = "175724",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Arathi Highlands",
      ["subLocation"] = "Arathi Highlands",
      ["x"] = 0.742,
      ["y"] = 0.321,
    },
    {
      ["category"] = "book",
      ["name"] = "Rise of the Blood Elves",
      ["id"] = "175760",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Arathi Highlands",
      ["subLocation"] = "Arathi Highlands",
      ["x"] = 0.741,
      ["y"] = 0.32299999999999995,
    },
    {
      ["category"] = "mailbox",
      ["name"] = "Mailbox",
      ["id"] = "32349",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Arathi Highlands",
      ["subLocation"] = "Arathi Highlands",
      ["x"] = 0.738,
      ["y"] = 0.331,
    },
  }
}
