DB_ASHENVALE_GENERAL = {
  ["region"] = "Kalimdor",
  ["mapID"] = 1440,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Bhaldaran Ravenshade",
      ["id"] = "3951",
      ["description"] = "Bowyer",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.502,
      ["y"] = 0.672,
    },
    {
      ["category"] = "repair",
      ["name"] = "Aeolynn",
      ["id"] = "3952",
      ["description"] = "Clothier",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.344,
      ["y"] = 0.496,
    },
    {
      ["category"] = "repair",
      ["name"] = "Tandaan Lightmane",
      ["id"] = "3953",
      ["description"] = "Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.34600000000000003,
      ["y"] = 0.498,
    },
    {
      ["category"] = "repair",
      ["name"] = "Burkrum",
      ["id"] = "6028",
      ["description"] = "Heavy Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.7340000000000001,
      ["y"] = 0.604,
    },
    {
      ["category"] = "repair",
      ["name"] = "Xai'ander",
      ["id"] = "11137",
      ["description"] = "Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.358,
      ["y"] = 0.52,
    },
    {
      ["category"] = "repair",
      ["name"] = "Illiyana Moonblaze",
      ["id"] = "14753",
      ["description"] = "Silverwing Supply Officer",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.614,
      ["y"] = 0.838,
    },
    {
      ["category"] = "repair",
      ["name"] = "Quartermaster Kyleen",
      ["id"] = "222685",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.8959999999999999,
      ["y"] = 0.406,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Innkeeper Kimlya",
      ["id"] = "6738",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.37,
      ["y"] = 0.49200000000000005,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Innkeeper Kaylisk",
      ["id"] = "12196",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.74,
      ["y"] = 0.606,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Maluressian",
      ["id"] = "10052",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.364,
      ["y"] = 0.504,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Qeeju",
      ["id"] = "15131",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.7340000000000001,
      ["y"] = 0.61,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Daelyshia",
      ["id"] = "4267",
      ["description"] = "Hippogryph Master",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.344,
      ["y"] = 0.48,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Andruk",
      ["id"] = "11901",
      ["description"] = "Wind Rider Master",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.122,
      ["y"] = 0.33799999999999997,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Vhulgra",
      ["id"] = "12616",
      ["description"] = "Wind Rider Master",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.732,
      ["y"] = 0.616,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Bolyun",
      ["id"] = "3698",
      ["description"] = "Pet Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.18,
      ["y"] = 0.6,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Danlaar Nightstride",
      ["id"] = "3963",
      ["description"] = "Hunter Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.5,
      ["y"] = 0.6779999999999999,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Kylanna",
      ["id"] = "3964",
      ["description"] = "Expert Alchemist",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.508,
      ["y"] = 0.67,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Cylania Rootstalker",
      ["id"] = "3965",
      ["description"] = "Herbalist",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.506,
      ["y"] = 0.67,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Aayndia Floralwind",
      ["id"] = "3967",
      ["description"] = "Expert Leatherworker",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.358,
      ["y"] = 0.52,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Caelyb",
      ["id"] = "4320",
      ["description"] = "Pet Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.498,
      ["y"] = 0.67,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Jayla",
      ["id"] = "6288",
      ["description"] = "Skinner",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.5,
      ["y"] = 0.672,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Alenndaar Lapidaar",
      ["id"] = "8308",
      ["description"] = "Hunter Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.18,
      ["y"] = 0.598,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Kil'Hiwana",
      ["id"] = "12961",
      ["description"] = "Fisherman",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.10800000000000001,
      ["y"] = 0.336,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Bhaldaran Ravenshade",
      ["id"] = "3951",
      ["description"] = "Bowyer",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.502,
      ["y"] = 0.672,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Aeolynn",
      ["id"] = "3952",
      ["description"] = "Clothier",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.344,
      ["y"] = 0.496,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Tandaan Lightmane",
      ["id"] = "3953",
      ["description"] = "Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.34600000000000003,
      ["y"] = 0.498,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Dalria",
      ["id"] = "3954",
      ["description"] = "Trade Goods",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.35,
      ["y"] = 0.52,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Shandrina",
      ["id"] = "3955",
      ["description"] = "Trade Goods",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.494,
      ["y"] = 0.67,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Harklan Moongrove",
      ["id"] = "3956",
      ["description"] = "Alchemy Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.508,
      ["y"] = 0.67,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Lardan",
      ["id"] = "3958",
      ["description"] = "Leatherworking Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.348,
      ["y"] = 0.498,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Nantar",
      ["id"] = "3959",
      ["description"] = "Baker",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.37,
      ["y"] = 0.498,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Ulthaan",
      ["id"] = "3960",
      ["description"] = "Butcher",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.5,
      ["y"] = 0.6659999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Maliynn",
      ["id"] = "3961",
      ["description"] = "Food & Drink Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.366,
      ["y"] = 0.498,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Haljan Oakheart",
      ["id"] = "3962",
      ["description"] = "General Goods",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.348,
      ["y"] = 0.508,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Fahran Silentblade",
      ["id"] = "3969",
      ["description"] = "Tools & Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.364,
      ["y"] = 0.494,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Llana",
      ["id"] = "3970",
      ["description"] = "Reagent Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.35,
      ["y"] = 0.484,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Burkrum",
      ["id"] = "6028",
      ["description"] = "Heavy Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.7340000000000001,
      ["y"] = 0.604,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Harlown Darkweave",
      ["id"] = "6731",
      ["description"] = "Leatherworking Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.182,
      ["y"] = 0.6,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Innkeeper Kimlya",
      ["id"] = "6738",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.37,
      ["y"] = 0.49200000000000005,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Xai'ander",
      ["id"] = "11137",
      ["description"] = "Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.358,
      ["y"] = 0.52,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Innkeeper Kaylisk",
      ["id"] = "12196",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.74,
      ["y"] = 0.606,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Wik'Tar",
      ["id"] = "12962",
      ["description"] = "Fish Merchant & Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.11800000000000001,
      ["y"] = 0.34,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Illiyana Moonblaze",
      ["id"] = "14753",
      ["description"] = "Silverwing Supply Officer",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.614,
      ["y"] = 0.838,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Gapp Jinglepocket",
      ["id"] = "14963",
      ["description"] = "Smokywood Pastures",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.62,
      ["y"] = 0.828,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Quartermaster Kyleen",
      ["id"] = "222685",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.8959999999999999,
      ["y"] = 0.406,
    },
    {
      ["category"] = "spirithealer",
      ["name"] = "Spirit Healer",
      ["id"] = "6491",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.17800000000000002,
      ["y"] = 0.11,
    },
    {
      ["category"] = "book",
      ["name"] = "Ancient Inscription",
      ["id"] = "19025",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.503,
      ["y"] = 0.396,
    },
    {
      ["category"] = "book",
      ["name"] = "Monument to Grom Hellscream",
      ["id"] = "21004",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.8290000000000001,
      ["y"] = 0.7909999999999999,
    },
    {
      ["category"] = "book",
      ["name"] = "Charge of the Dragonflights",
      ["id"] = "175726",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.348,
      ["y"] = 0.498,
    },
    {
      ["category"] = "book",
      ["name"] = "The Scourge of Lordaeron",
      ["id"] = "175756",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.348,
      ["y"] = 0.498,
    },
    {
      ["category"] = "book",
      ["name"] = "Sunwell - The Fall of Quel'Thalas",
      ["id"] = "175757",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.345,
      ["y"] = 0.5,
    },
    {
      ["category"] = "book",
      ["name"] = "Carved Stone",
      ["id"] = "410082",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.8690000000000001,
      ["y"] = 0.43200000000000005,
    },
    {
      ["category"] = "mailbox",
      ["name"] = "Mailbox",
      ["id"] = "32349",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Ashenvale",
      ["subLocation"] = "Ashenvale",
      ["x"] = 0.363,
      ["y"] = 0.503,
    },
  }
}
