DB_AZSHARA_GENERAL = {
  ["region"] = "Kalimdor <Horde>",
  ["mapID"] = 1447,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Gruul Darkblade",
      ["id"] = "10361",
      ["description"] = "Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Azshara",
      ["subLocation"] = "Azshara",
      ["x"] = 0.222,
      ["y"] = 0.512,
    },
    {
      ["category"] = "repair",
      ["name"] = "Brinna Valanaar",
      ["id"] = "14301",
      ["description"] = "Bowyer",
      ["comment"] = "",
      ["mainLocation"] = "Azshara",
      ["subLocation"] = "Azshara",
      ["x"] = 0.12,
      ["y"] = 0.782,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Kroum",
      ["id"] = "8610",
      ["description"] = "Wind Rider Master",
      ["comment"] = "",
      ["mainLocation"] = "Azshara",
      ["subLocation"] = "Azshara",
      ["x"] = 0.22,
      ["y"] = 0.496,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Jarrodenus",
      ["id"] = "12577",
      ["description"] = "Hippogryph Master",
      ["comment"] = "",
      ["mainLocation"] = "Azshara",
      ["subLocation"] = "Azshara",
      ["x"] = 0.11800000000000001,
      ["y"] = 0.774,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Peter Galen",
      ["id"] = "7866",
      ["description"] = "Master Dragonscale Leatherworker",
      ["comment"] = "",
      ["mainLocation"] = "Azshara",
      ["subLocation"] = "Azshara",
      ["x"] = 0.374,
      ["y"] = 0.654,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kurll",
      ["id"] = "3621",
      ["description"] = "Food & Drink",
      ["comment"] = "",
      ["mainLocation"] = "Azshara",
      ["subLocation"] = "Azshara",
      ["x"] = 0.218,
      ["y"] = 0.52,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jubie Gadgetspring",
      ["id"] = "8678",
      ["description"] = "Engineering Supplier",
      ["comment"] = "",
      ["mainLocation"] = "Azshara",
      ["subLocation"] = "Azshara",
      ["x"] = 0.452,
      ["y"] = 0.9079999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Gruul Darkblade",
      ["id"] = "10361",
      ["description"] = "Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Azshara",
      ["subLocation"] = "Azshara",
      ["x"] = 0.222,
      ["y"] = 0.512,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Blimo Gadgetspring",
      ["id"] = "12957",
      ["description"] = "Trade Supplier",
      ["comment"] = "",
      ["mainLocation"] = "Azshara",
      ["subLocation"] = "Azshara",
      ["x"] = 0.452,
      ["y"] = 0.9079999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Duke Hydraxis",
      ["id"] = "13278",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Azshara",
      ["subLocation"] = "Azshara",
      ["x"] = 0.792,
      ["y"] = 0.736,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Brinna Valanaar",
      ["id"] = "14301",
      ["description"] = "Bowyer",
      ["comment"] = "",
      ["mainLocation"] = "Azshara",
      ["subLocation"] = "Azshara",
      ["x"] = 0.12,
      ["y"] = 0.782,
    },
    {
      ["category"] = "spirithealer",
      ["name"] = "Spirit Healer",
      ["id"] = "6491",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Azshara",
      ["subLocation"] = "Azshara",
      ["x"] = 0.14400000000000002,
      ["y"] = 0.784,
    },
    {
      ["category"] = "book",
      ["name"] = "Shrine of the Beast",
      ["id"] = "441947",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Azshara",
      ["subLocation"] = "Azshara",
      ["x"] = 0.34600000000000003,
      ["y"] = 0.49,
    },
  }
}
