DB_BADLANDS_GENERAL = {
  ["region"] = "Eastern Kingdoms",
  ["mapID"] = 1418,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Sranda",
      ["id"] = "1407",
      ["description"] = "Light Armor & Weapons Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Badlands",
      ["subLocation"] = "Badlands",
      ["x"] = 0.03,
      ["y"] = 0.474,
    },
    {
      ["category"] = "repair",
      ["name"] = "Jazzrik",
      ["id"] = "9179",
      ["description"] = "Blacksmithing Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Badlands",
      ["subLocation"] = "Badlands",
      ["x"] = 0.424,
      ["y"] = 0.526,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Innkeeper Shul'kar",
      ["id"] = "9356",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Badlands",
      ["subLocation"] = "Badlands",
      ["x"] = 0.027999999999999997,
      ["y"] = 0.45799999999999996,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Greth",
      ["id"] = "10058",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "Badlands",
      ["subLocation"] = "Badlands",
      ["x"] = 0.038,
      ["y"] = 0.47600000000000003,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Gorrik",
      ["id"] = "2861",
      ["description"] = "Wind Rider Master",
      ["comment"] = "",
      ["mainLocation"] = "Badlands",
      ["subLocation"] = "Badlands",
      ["x"] = 0.04,
      ["y"] = 0.44799999999999995,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Thorkaf Dragoneye",
      ["id"] = "7867",
      ["description"] = "Master Dragonscale Leatherworker",
      ["comment"] = "",
      ["mainLocation"] = "Badlands",
      ["subLocation"] = "Badlands",
      ["x"] = 0.626,
      ["y"] = 0.574,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Sranda",
      ["id"] = "1407",
      ["description"] = "Light Armor & Weapons Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Badlands",
      ["subLocation"] = "Badlands",
      ["x"] = 0.03,
      ["y"] = 0.474,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Grawl",
      ["id"] = "2908",
      ["description"] = "General Goods",
      ["comment"] = "",
      ["mainLocation"] = "Badlands",
      ["subLocation"] = "Badlands",
      ["x"] = 0.03,
      ["y"] = 0.46,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Lotwil Veriatus",
      ["id"] = "2921",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Badlands",
      ["subLocation"] = "Badlands",
      ["x"] = 0.258,
      ["y"] = 0.45,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jazzrik",
      ["id"] = "9179",
      ["description"] = "Blacksmithing Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Badlands",
      ["subLocation"] = "Badlands",
      ["x"] = 0.424,
      ["y"] = 0.526,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Innkeeper Shul'kar",
      ["id"] = "9356",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Badlands",
      ["subLocation"] = "Badlands",
      ["x"] = 0.027999999999999997,
      ["y"] = 0.45799999999999996,
    },
    {
      ["category"] = "spirithealer",
      ["name"] = "Spirit Healer",
      ["id"] = "6491",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Badlands",
      ["subLocation"] = "Badlands",
      ["x"] = 0.08199999999999999,
      ["y"] = 0.5539999999999999,
    },
    {
      ["category"] = "mailbox",
      ["name"] = "Mailbox",
      ["id"] = "32349",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Badlands",
      ["subLocation"] = "Badlands",
      ["x"] = 0.039,
      ["y"] = 0.473,
    },
  }
}
