DB_BLASTED_LANDS_GENERAL = {
  ["region"] = "Eastern Kingdoms",
  ["mapID"] = 1419,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Strumner Flintheel",
      ["id"] = "5508",
      ["description"] = "Armor Crafter",
      ["comment"] = "",
      ["mainLocation"] = "Blasted Lands",
      ["subLocation"] = "Blasted Lands",
      ["x"] = 0.66,
      ["y"] = 0.172,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Alexandra Constantine",
      ["id"] = "8609",
      ["description"] = "Gryphon Master",
      ["comment"] = "",
      ["mainLocation"] = "Blasted Lands",
      ["subLocation"] = "Blasted Lands",
      ["x"] = 0.654,
      ["y"] = 0.244,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Bernie Heisten",
      ["id"] = "3546",
      ["description"] = "Food & Drink",
      ["comment"] = "",
      ["mainLocation"] = "Blasted Lands",
      ["subLocation"] = "Blasted Lands",
      ["x"] = 0.634,
      ["y"] = 0.168,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Strumner Flintheel",
      ["id"] = "5508",
      ["description"] = "Armor Crafter",
      ["comment"] = "",
      ["mainLocation"] = "Blasted Lands",
      ["subLocation"] = "Blasted Lands",
      ["x"] = 0.66,
      ["y"] = 0.172,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Nina Lightbrew",
      ["id"] = "8178",
      ["description"] = "Alchemy Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Blasted Lands",
      ["subLocation"] = "Blasted Lands",
      ["x"] = 0.6679999999999999,
      ["y"] = 0.182,
    },
    {
      ["category"] = "spirithealer",
      ["name"] = "Spirit Healer",
      ["id"] = "6491",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Blasted Lands",
      ["subLocation"] = "Blasted Lands",
      ["x"] = 0.51,
      ["y"] = 0.122,
    },
    {
      ["category"] = "book",
      ["name"] = "Aftermath of the Second War",
      ["id"] = "21581",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Blasted Lands",
      ["subLocation"] = "Blasted Lands",
      ["x"] = 0.643,
      ["y"] = 0.155,
    },
    {
      ["category"] = "book",
      ["name"] = "Beyond the Dark Portal",
      ["id"] = "21582",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Blasted Lands",
      ["subLocation"] = "Blasted Lands",
      ["x"] = 0.652,
      ["y"] = 0.228,
    },
    {
      ["category"] = "book",
      ["name"] = "The Dark Portal and the Fall of Stormwind",
      ["id"] = "175745",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Blasted Lands",
      ["subLocation"] = "Blasted Lands",
      ["x"] = 0.6679999999999999,
      ["y"] = 0.184,
    },
    {
      ["category"] = "mailbox",
      ["name"] = "Mailbox",
      ["id"] = "32349",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Blasted Lands",
      ["subLocation"] = "Blasted Lands",
      ["x"] = 0.6409999999999999,
      ["y"] = 0.193,
    },
  }
}
