DB_BURNING_STEPPES_GENERAL = {
  ["region"] = "Eastern Kingdoms",
  ["mapID"] = 1428,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Felder Stover",
      ["id"] = "1296",
      ["description"] = "Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Burning Steppes",
      ["subLocation"] = "Burning Steppes",
      ["x"] = 0.85,
      ["y"] = 0.684,
    },
    {
      ["category"] = "repair",
      ["name"] = "Yuka Screwspigot",
      ["id"] = "9544",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Burning Steppes",
      ["subLocation"] = "Burning Steppes",
      ["x"] = 0.66,
      ["y"] = 0.22,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Borgus Stoutarm",
      ["id"] = "2299",
      ["description"] = "Gryphon Master",
      ["comment"] = "",
      ["mainLocation"] = "Burning Steppes",
      ["subLocation"] = "Burning Steppes",
      ["x"] = 0.8440000000000001,
      ["y"] = 0.682,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Vahgruk",
      ["id"] = "13177",
      ["description"] = "Wind Rider Master",
      ["comment"] = "",
      ["mainLocation"] = "Burning Steppes",
      ["subLocation"] = "Burning Steppes",
      ["x"] = 0.6559999999999999,
      ["y"] = 0.242,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Felder Stover",
      ["id"] = "1296",
      ["description"] = "Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Burning Steppes",
      ["subLocation"] = "Burning Steppes",
      ["x"] = 0.85,
      ["y"] = 0.684,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Gabrielle Chase",
      ["id"] = "3298",
      ["description"] = "Food & Drink",
      ["comment"] = "",
      ["mainLocation"] = "Burning Steppes",
      ["subLocation"] = "Burning Steppes",
      ["x"] = 0.8420000000000001,
      ["y"] = 0.6779999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Gruna",
      ["id"] = "3708",
      ["description"] = "Food & Drink",
      ["comment"] = "",
      ["mainLocation"] = "Burning Steppes",
      ["subLocation"] = "Burning Steppes",
      ["x"] = 0.6559999999999999,
      ["y"] = 0.24,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Yuka Screwspigot",
      ["id"] = "9544",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Burning Steppes",
      ["subLocation"] = "Burning Steppes",
      ["x"] = 0.66,
      ["y"] = 0.22,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Gorzeeki Wildeyes",
      ["id"] = "14437",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Burning Steppes",
      ["subLocation"] = "Burning Steppes",
      ["x"] = 0.124,
      ["y"] = 0.316,
    },
    {
      ["category"] = "spirithealer",
      ["name"] = "Spirit Healer",
      ["id"] = "6491",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Burning Steppes",
      ["subLocation"] = "Burning Steppes",
      ["x"] = 0.632,
      ["y"] = 0.23399999999999999,
    },
    {
      ["category"] = "book",
      ["name"] = "Altar of Reverence",
      ["id"] = "456674",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Burning Steppes",
      ["subLocation"] = "Burning Steppes",
      ["x"] = 0.396,
      ["y"] = 0.28,
    },
  }
}
