DB_DALARAN_GENERAL = {
  ["region"] = "Eastern Kingdoms",
  ["mapID"] = 0,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Imindril Spearsong",
      ["id"] = "92184",
      ["description"] = "Blacksmithing Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.462,
      ["y"] = 0.272,
    },
    {
      ["category"] = "repair",
      ["name"] = "Hobart Grapplehammer",
      ["id"] = "93539",
      ["description"] = "Engineering Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.384,
      ["y"] = 0.25,
    },
    {
      ["category"] = "repair",
      ["name"] = "Aemara",
      ["id"] = "96778",
      ["description"] = "Bowyer",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.6,
      ["y"] = 0.526,
    },
    {
      ["category"] = "repair",
      ["name"] = "Dagna Flintlock",
      ["id"] = "96779",
      ["description"] = "Gunsmith",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.598,
      ["y"] = 0.522,
    },
    {
      ["category"] = "repair",
      ["name"] = "Kyunghee",
      ["id"] = "96801",
      ["description"] = "Throwing Axes",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.71,
      ["y"] = 0.32,
    },
    {
      ["category"] = "repair",
      ["name"] = "Paldesse",
      ["id"] = "96975",
      ["description"] = "Cloth Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.376,
      ["y"] = 0.56,
    },
    {
      ["category"] = "repair",
      ["name"] = "Cloth Merchant",
      ["id"] = "96976",
      ["description"] = "Cloth Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.374,
      ["y"] = 0.562,
    },
    {
      ["category"] = "repair",
      ["name"] = "Valerie Langrom",
      ["id"] = "96977",
      ["description"] = "Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.512,
      ["y"] = 0.726,
    },
    {
      ["category"] = "repair",
      ["name"] = "Rafael Langrom",
      ["id"] = "96978",
      ["description"] = "Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.508,
      ["y"] = 0.72,
    },
    {
      ["category"] = "repair",
      ["name"] = "Bragund Brightlink",
      ["id"] = "96979",
      ["description"] = "Mail Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.51,
      ["y"] = 0.7340000000000001,
    },
    {
      ["category"] = "repair",
      ["name"] = "Matilda Brightlink",
      ["id"] = "96980",
      ["description"] = "Mail Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.512,
      ["y"] = 0.732,
    },
    {
      ["category"] = "repair",
      ["name"] = "Kerta the Bold",
      ["id"] = "97007",
      ["description"] = "Mace & Polearm Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.544,
      ["y"] = 0.63,
    },
    {
      ["category"] = "repair",
      ["name"] = "Jawknee",
      ["id"] = "97009",
      ["description"] = "Axe Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.5379999999999999,
      ["y"] = 0.616,
    },
    {
      ["category"] = "repair",
      ["name"] = "Valaden Silverblade",
      ["id"] = "97011",
      ["description"] = "Sword Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.542,
      ["y"] = 0.632,
    },
    {
      ["category"] = "repair",
      ["name"] = "Wanda Chanter",
      ["id"] = "97012",
      ["description"] = "Wands",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.488,
      ["y"] = 0.738,
    },
    {
      ["category"] = "repair",
      ["name"] = "Icks",
      ["id"] = "97331",
      ["description"] = "Staves",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.49,
      ["y"] = 0.73,
    },
    {
      ["category"] = "repair",
      ["name"] = "Cho Ironpalm",
      ["id"] = "97339",
      ["description"] = "Dagger & Fist Weapon Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.532,
      ["y"] = 0.628,
    },
    {
      ["category"] = "repair",
      ["name"] = "Raethan",
      ["id"] = "97359",
      ["description"] = "Underbelly Guard Captain",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.684,
      ["y"] = 0.586,
    },
    {
      ["category"] = "repair",
      ["name"] = "Matthew Rabis",
      ["id"] = "97360",
      ["description"] = "Feral Warlock",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.47200000000000003,
      ["y"] = 0.56,
    },
    {
      ["category"] = "repair",
      ["name"] = "Oxana Demonslay",
      ["id"] = "97361",
      ["description"] = "Weapons and Secrets",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.674,
      ["y"] = 0.18,
    },
    {
      ["category"] = "repair",
      ["name"] = "Dazzik \"Proudmoore\"",
      ["id"] = "97362",
      ["description"] = "Magical Things",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.662,
      ["y"] = 0.75,
    },
    {
      ["category"] = "repair",
      ["name"] = "K'huta",
      ["id"] = "97363",
      ["description"] = "Portals and Jujus",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.6579999999999999,
      ["y"] = 0.794,
    },
    {
      ["category"] = "repair",
      ["name"] = "Laura Malley",
      ["id"] = "97364",
      ["description"] = "Creatures",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.58,
      ["y"] = 0.58,
    },
    {
      ["category"] = "repair",
      ["name"] = "The Widow",
      ["id"] = "97366",
      ["description"] = "Tools of Deception",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.716,
      ["y"] = 0.23600000000000002,
    },
    {
      ["category"] = "repair",
      ["name"] = "Filgo Scrapbottom",
      ["id"] = "102193",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.662,
      ["y"] = 0.536,
    },
    {
      ["category"] = "repair",
      ["name"] = "Kelsey Steelspark",
      ["id"] = "105986",
      ["description"] = "Quartermaster",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.27399999999999997,
      ["y"] = 0.358,
    },
    {
      ["category"] = "repair",
      ["name"] = "Arcanomancer Vridiel",
      ["id"] = "106655",
      ["description"] = "Blacksmithing Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.452,
      ["y"] = 0.28600000000000003,
    },
    {
      ["category"] = "repair",
      ["name"] = "Strap Bucklebolt",
      ["id"] = "107760",
      ["description"] = "Belts",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.6579999999999999,
      ["y"] = 0.8059999999999999,
    },
    {
      ["category"] = "repair",
      ["name"] = "Thuni",
      ["id"] = "107764",
      ["description"] = "Food, Drink, and Trade Materials",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.626,
      ["y"] = 0.8,
    },
    {
      ["category"] = "repair",
      ["name"] = "Merchant Maku",
      ["id"] = "142668",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.608,
      ["y"] = 0.446,
    },
    {
      ["category"] = "repair",
      ["name"] = "Valaden Silverblade",
      ["id"] = "220045",
      ["description"] = "Sword Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.54,
      ["y"] = 0.616,
    },
    {
      ["category"] = "repair",
      ["name"] = "Remembrancer Amuul",
      ["id"] = "223710",
      ["description"] = "Residual Memories Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.33399999999999996,
      ["y"] = 0.83,
    },
    {
      ["category"] = "repair",
      ["name"] = "Vaskarn",
      ["id"] = "231596",
      ["description"] = "Awakened Crest Exchange",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.31,
      ["y"] = 0.802,
    },
    {
      ["category"] = "repair",
      ["name"] = "Mecha-Scrapper",
      ["id"] = "237776",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.586,
      ["y"] = 0.45799999999999996,
    },
    {
      ["category"] = "auctioneer",
      ["name"] = "Brassbolt Mechawrench",
      ["id"] = "35594",
      ["description"] = "Steam-Powered Auctioneer",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.38799999999999996,
      ["y"] = 0.26,
    },
    {
      ["category"] = "auctioneer",
      ["name"] = "Reginald Arcfire",
      ["id"] = "35607",
      ["description"] = "Steam-Powered Auctioneer",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.39,
      ["y"] = 0.26,
    },
    {
      ["category"] = "auctioneer",
      ["name"] = "Collector Unta",
      ["id"] = "142666",
      ["description"] = "Auctioneer",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.516,
      ["y"] = 0.272,
    },
    {
      ["category"] = "banker",
      ["name"] = "Teller Rames",
      ["id"] = "96817",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.522,
      ["y"] = 0.14800000000000002,
    },
    {
      ["category"] = "banker",
      ["name"] = "Teller Hanners",
      ["id"] = "96818",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.53,
      ["y"] = 0.154,
    },
    {
      ["category"] = "banker",
      ["name"] = "Teller Hoag",
      ["id"] = "96819",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.54,
      ["y"] = 0.158,
    },
    {
      ["category"] = "banker",
      ["name"] = "Paymaster Alstein",
      ["id"] = "96820",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.528,
      ["y"] = 0.146,
    },
    {
      ["category"] = "banker",
      ["name"] = "Teller Gee",
      ["id"] = "96821",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.426,
      ["y"] = 0.8,
    },
    {
      ["category"] = "banker",
      ["name"] = "Teller Almeida",
      ["id"] = "96822",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.436,
      ["y"] = 0.8059999999999999,
    },
    {
      ["category"] = "banker",
      ["name"] = "Teller Plushner",
      ["id"] = "96823",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.418,
      ["y"] = 0.794,
    },
    {
      ["category"] = "banker",
      ["name"] = "Paymaster Chang",
      ["id"] = "96825",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.426,
      ["y"] = 0.8,
    },
    {
      ["category"] = "banker",
      ["name"] = "Paymaster Amadi",
      ["id"] = "96826",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.428,
      ["y"] = 0.7979999999999999,
    },
    {
      ["category"] = "banker",
      ["name"] = "Teller Hanners",
      ["id"] = "249873",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.528,
      ["y"] = 0.146,
    },
    {
      ["category"] = "banker",
      ["name"] = "Teller Hoag",
      ["id"] = "249874",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.5379999999999999,
      ["y"] = 0.152,
    },
    {
      ["category"] = "banker",
      ["name"] = "Teller Rames",
      ["id"] = "249875",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.52,
      ["y"] = 0.14,
    },
    {
      ["category"] = "banker",
      ["name"] = "Teller Almeida",
      ["id"] = "249887",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.436,
      ["y"] = 0.812,
    },
    {
      ["category"] = "banker",
      ["name"] = "Teller Gee",
      ["id"] = "249888",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.424,
      ["y"] = 0.7979999999999999,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Caliel Brightwillow",
      ["id"] = "96789",
      ["description"] = "Assistant Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.39,
      ["y"] = 0.7120000000000001,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Isirami Fairwind",
      ["id"] = "96790",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.44,
      ["y"] = 0.634,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Uda the Beast",
      ["id"] = "96796",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.65,
      ["y"] = 0.324,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Abohba",
      ["id"] = "96799",
      ["description"] = "Assistant Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.672,
      ["y"] = 0.35200000000000004,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Amisi Azuregaze",
      ["id"] = "96806",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.496,
      ["y"] = 0.396,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Afsaneh Asrar",
      ["id"] = "96807",
      ["description"] = "Assistant Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.484,
      ["y"] = 0.414,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Tassia Whisperglen",
      ["id"] = "96507",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.59,
      ["y"] = 0.37799999999999995,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Aludane Whitecloud",
      ["id"] = "96813",
      ["description"] = "Flight Master",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.698,
      ["y"] = 0.508,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Alard Schmied",
      ["id"] = "92183",
      ["description"] = "Blacksmithing Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.444,
      ["y"] = 0.28800000000000003,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Timofey Oshenko",
      ["id"] = "92194",
      ["description"] = "Engineering Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.382,
      ["y"] = 0.26,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Professor Pallin",
      ["id"] = "92195",
      ["description"] = "Inscription Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.414,
      ["y"] = 0.37200000000000005,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Linzy Blackbolt",
      ["id"] = "92456",
      ["description"] = "Alchemy Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.418,
      ["y"] = 0.32,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Deucus Valdera",
      ["id"] = "92458",
      ["description"] = "Alchemy Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.414,
      ["y"] = 0.32799999999999996,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Kuhuine Tenderstride",
      ["id"] = "92464",
      ["description"] = "Herbalism Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.428,
      ["y"] = 0.33799999999999997,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Mama Diggs",
      ["id"] = "93189",
      ["description"] = "Mining Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.462,
      ["y"] = 0.264,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Didi the Wrench",
      ["id"] = "93520",
      ["description"] = "Goblin Engineering Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.386,
      ["y"] = 0.25,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Diane Cannings",
      ["id"] = "93522",
      ["description"] = "Leather Armor Expert",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.354,
      ["y"] = 0.298,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Namha Moonwater",
      ["id"] = "93523",
      ["description"] = "Leatherworking Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.35200000000000004,
      ["y"] = 0.292,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Ainderu Summerleaf",
      ["id"] = "93525",
      ["description"] = "Tailoring Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.36200000000000004,
      ["y"] = 0.33799999999999997,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Timothy Jones",
      ["id"] = "93527",
      ["description"] = "Jewelcrafting Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.39799999999999996,
      ["y"] = 0.35,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Olisarra the Kind",
      ["id"] = "93529",
      ["description"] = "Bandage Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.36200000000000004,
      ["y"] = 0.374,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Enchanter Nalthanis",
      ["id"] = "93531",
      ["description"] = "Enchanting Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.384,
      ["y"] = 0.406,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Katherine Lee",
      ["id"] = "93534",
      ["description"] = "Cooking Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.39799999999999996,
      ["y"] = 0.664,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Awilo Lon'gomba",
      ["id"] = "93536",
      ["description"] = "Cooking Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.698,
      ["y"] = 0.384,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Dariness the Learned",
      ["id"] = "93538",
      ["description"] = "Archaeology Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.408,
      ["y"] = 0.264,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Kondal Huntsworn",
      ["id"] = "93541",
      ["description"] = "Skinning Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.358,
      ["y"] = 0.28600000000000003,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Tanithria",
      ["id"] = "93542",
      ["description"] = "Tailoring Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.35200000000000004,
      ["y"] = 0.342,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Marcia Chase",
      ["id"] = "95844",
      ["description"] = "Fishing Trainer & Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.524,
      ["y"] = 0.6559999999999999,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Archmage Celindra",
      ["id"] = "96786",
      ["description"] = "Portal Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.562,
      ["y"] = 0.47,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Alard Schmied",
      ["id"] = "97261",
      ["description"] = "Blacksmithing Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.444,
      ["y"] = 0.28800000000000003,
    },
    {
      ["category"] = "trainer",
      ["name"] = "The Amazing Zanzo",
      ["id"] = "97529",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.46,
      ["y"] = 0.272,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Thanid Glowergold",
      ["id"] = "98931",
      ["description"] = "Mail Armor Expert",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.34600000000000003,
      ["y"] = 0.28600000000000003,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Arcanomancer Vridiel",
      ["id"] = "106655",
      ["description"] = "Blacksmithing Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.452,
      ["y"] = 0.28600000000000003,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Lianna Tai",
      ["id"] = "151827",
      ["description"] = "Herbalism Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.426,
      ["y"] = 0.342,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Chapman",
      ["id"] = "34382",
      ["description"] = "Day of the Dead Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.342,
      ["y"] = 0.39399999999999996,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Imindril Spearsong",
      ["id"] = "92184",
      ["description"] = "Blacksmithing Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.462,
      ["y"] = 0.272,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Braeg Stoutbeard",
      ["id"] = "92185",
      ["description"] = "Fur & Leather Trader",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.46799999999999997,
      ["y"] = 0.28800000000000003,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Patricia Egan",
      ["id"] = "92457",
      ["description"] = "Alchemy Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.418,
      ["y"] = 0.322,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Edward Egan",
      ["id"] = "92460",
      ["description"] = "Herbalism Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.424,
      ["y"] = 0.34600000000000003,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Mei Francis",
      ["id"] = "92489",
      ["description"] = "Exotic Mounts",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.5760000000000001,
      ["y"] = 0.424,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Aimee",
      ["id"] = "92936",
      ["description"] = "Pie, Pastry & Cakes",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.506,
      ["y"] = 0.28800000000000003,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Mongar",
      ["id"] = "93188",
      ["description"] = "Mining Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.46399999999999997,
      ["y"] = 0.266,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Ranid Glowergold",
      ["id"] = "93521",
      ["description"] = "Leatherworking & Skinning Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.34600000000000003,
      ["y"] = 0.28600000000000003,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Lalla Brightweave",
      ["id"] = "93524",
      ["description"] = "Tailoring Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.36,
      ["y"] = 0.33399999999999996,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Tiffany Cartier",
      ["id"] = "93526",
      ["description"] = "Jewelcrafting Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.39799999999999996,
      ["y"] = 0.348,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Timothy Jones",
      ["id"] = "93527",
      ["description"] = "Jewelcrafting Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.39799999999999996,
      ["y"] = 0.35,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Angelique Butler",
      ["id"] = "93528",
      ["description"] = "First Aid Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.364,
      ["y"] = 0.376,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Ildine Sorrowspear",
      ["id"] = "93530",
      ["description"] = "Enchanting Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.384,
      ["y"] = 0.41200000000000003,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jessica Sellers",
      ["id"] = "93532",
      ["description"] = "Ink Trader",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.41200000000000003,
      ["y"] = 0.37,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Misensi",
      ["id"] = "93537",
      ["description"] = "Cooking Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.698,
      ["y"] = 0.39,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Dariness the Learned",
      ["id"] = "93538",
      ["description"] = "Archaeology Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.408,
      ["y"] = 0.264,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Hobart Grapplehammer",
      ["id"] = "93539",
      ["description"] = "Engineering Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.384,
      ["y"] = 0.25,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Sminx Glasseye",
      ["id"] = "93543",
      ["description"] = "Jewelry Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.396,
      ["y"] = 0.35,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jang Quillpaw",
      ["id"] = "93544",
      ["description"] = "Inscription Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.41200000000000003,
      ["y"] = 0.368,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Bradford Duncan",
      ["id"] = "93545",
      ["description"] = "Cooking Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.402,
      ["y"] = 0.66,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Marcia Chase",
      ["id"] = "95844",
      ["description"] = "Fishing Trainer & Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.524,
      ["y"] = 0.6559999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Breanni",
      ["id"] = "96479",
      ["description"] = "Pet Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.5820000000000001,
      ["y"] = 0.39399999999999996,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jepetto Joybuzz",
      ["id"] = "96483",
      ["description"] = "Toymaker",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.434,
      ["y"] = 0.456,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Clockwork Assistant",
      ["id"] = "96484",
      ["description"] = "Jepetto's Companion",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.434,
      ["y"] = 0.456,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Tassia Whisperglen",
      ["id"] = "96507",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.59,
      ["y"] = 0.37799999999999995,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Aemara",
      ["id"] = "96778",
      ["description"] = "Bowyer",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.6,
      ["y"] = 0.526,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Dagna Flintlock",
      ["id"] = "96779",
      ["description"] = "Gunsmith",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.598,
      ["y"] = 0.522,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Aerith Primrose",
      ["id"] = "96780",
      ["description"] = "Flower Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.57,
      ["y"] = 0.53,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Lucian Trias",
      ["id"] = "96782",
      ["description"] = "Bread & Cheese Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.542,
      ["y"] = 0.32,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Fialla Sweetberry",
      ["id"] = "96784",
      ["description"] = "Food & Drink",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.526,
      ["y"] = 0.35,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Christi Stockton",
      ["id"] = "96785",
      ["description"] = "Wine Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.534,
      ["y"] = 0.326,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Isirami Fairwind",
      ["id"] = "96790",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.44,
      ["y"] = 0.634,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Marcella Bloom",
      ["id"] = "96791",
      ["description"] = "Barmaid",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.428,
      ["y"] = 0.642,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Inzi Charmlight",
      ["id"] = "96792",
      ["description"] = "Barmaid",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.414,
      ["y"] = 0.6559999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Stefen Cotter",
      ["id"] = "96793",
      ["description"] = "Bartender",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.42200000000000004,
      ["y"] = 0.652,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Laire Brewgold",
      ["id"] = "96794",
      ["description"] = "Brewmaiden",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.382,
      ["y"] = 0.784,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Coira Longrifle",
      ["id"] = "96795",
      ["description"] = "Brewmaiden",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.366,
      ["y"] = 0.758,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Uda the Beast",
      ["id"] = "96796",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.65,
      ["y"] = 0.324,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kyunghee",
      ["id"] = "96801",
      ["description"] = "Throwing Axes",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.71,
      ["y"] = 0.32,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Umbiwa",
      ["id"] = "96802",
      ["description"] = "Barmaid",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.6659999999999999,
      ["y"] = 0.332,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Mimbihi",
      ["id"] = "96803",
      ["description"] = "Barmaid",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.69,
      ["y"] = 0.306,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Hamaka",
      ["id"] = "96804",
      ["description"] = "Bartender",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.71,
      ["y"] = 0.33399999999999996,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Mato",
      ["id"] = "96805",
      ["description"] = "Food & Drink",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.7020000000000001,
      ["y"] = 0.34600000000000003,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Amisi Azuregaze",
      ["id"] = "96806",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.496,
      ["y"] = 0.396,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Sandra Bartan",
      ["id"] = "96808",
      ["description"] = "Barmaid",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.47600000000000003,
      ["y"] = 0.386,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Arille Azuregaze",
      ["id"] = "96809",
      ["description"] = "Bartender",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.474,
      ["y"] = 0.382,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Elizabeth Ross",
      ["id"] = "96812",
      ["description"] = "Tabard Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.508,
      ["y"] = 0.552,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Alfred Copperworth",
      ["id"] = "96969",
      ["description"] = "Butler",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.23600000000000002,
      ["y"] = 0.39799999999999996,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Paldesse",
      ["id"] = "96975",
      ["description"] = "Cloth Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.376,
      ["y"] = 0.56,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Cloth Merchant",
      ["id"] = "96976",
      ["description"] = "Cloth Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.374,
      ["y"] = 0.562,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Valerie Langrom",
      ["id"] = "96977",
      ["description"] = "Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.512,
      ["y"] = 0.726,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Rafael Langrom",
      ["id"] = "96978",
      ["description"] = "Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.508,
      ["y"] = 0.72,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Bragund Brightlink",
      ["id"] = "96979",
      ["description"] = "Mail Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.51,
      ["y"] = 0.7340000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Matilda Brightlink",
      ["id"] = "96980",
      ["description"] = "Mail Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.512,
      ["y"] = 0.732,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Norvin Alderman",
      ["id"] = "96987",
      ["description"] = "Cloaks",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.37,
      ["y"] = 0.5579999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Applebough",
      ["id"] = "96990",
      ["description"] = "Fruit Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.43,
      ["y"] = 0.57,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Susana Averoy",
      ["id"] = "96999",
      ["description"] = "General Goods",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.53,
      ["y"] = 0.726,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Orton Bennet",
      ["id"] = "97001",
      ["description"] = "Offhand Offerings",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.514,
      ["y"] = 0.5539999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Sheddle Glossgleam",
      ["id"] = "97003",
      ["description"] = "Cobbler",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.45,
      ["y"] = 0.47200000000000003,
    },
    {
      ["category"] = "vendor",
      ["name"] = "\"Red\" Jack Findle",
      ["id"] = "97004",
      ["description"] = "Trade Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.528,
      ["y"] = 0.706,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Debbi Moore",
      ["id"] = "97005",
      ["description"] = "Trinkets & Charms",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.49200000000000005,
      ["y"] = 0.5579999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kerta the Bold",
      ["id"] = "97007",
      ["description"] = "Mace & Polearm Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.544,
      ["y"] = 0.63,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jawknee",
      ["id"] = "97009",
      ["description"] = "Axe Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.5379999999999999,
      ["y"] = 0.616,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Valaden Silverblade",
      ["id"] = "97011",
      ["description"] = "Sword Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.542,
      ["y"] = 0.632,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Wanda Chanter",
      ["id"] = "97012",
      ["description"] = "Wands",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.488,
      ["y"] = 0.738,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Windle Sparkshine",
      ["id"] = "97213",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.444,
      ["y"] = 0.586,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Icks",
      ["id"] = "97331",
      ["description"] = "Staves",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.49,
      ["y"] = 0.73,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Richard Hatstock",
      ["id"] = "97332",
      ["description"] = "Haberdasher",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.37200000000000005,
      ["y"] = 0.5539999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Cho Ironpalm",
      ["id"] = "97339",
      ["description"] = "Dagger & Fist Weapon Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.532,
      ["y"] = 0.628,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Salan Sunthread",
      ["id"] = "97342",
      ["description"] = "Clothier",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.376,
      ["y"] = 0.5579999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Raethan",
      ["id"] = "97359",
      ["description"] = "Underbelly Guard Captain",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.684,
      ["y"] = 0.586,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Matthew Rabis",
      ["id"] = "97360",
      ["description"] = "Feral Warlock",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.47200000000000003,
      ["y"] = 0.56,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Oxana Demonslay",
      ["id"] = "97361",
      ["description"] = "Weapons and Secrets",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.674,
      ["y"] = 0.18,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Dazzik \"Proudmoore\"",
      ["id"] = "97362",
      ["description"] = "Magical Things",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.662,
      ["y"] = 0.75,
    },
    {
      ["category"] = "vendor",
      ["name"] = "K'huta",
      ["id"] = "97363",
      ["description"] = "Portals and Jujus",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.6579999999999999,
      ["y"] = 0.794,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Laura Malley",
      ["id"] = "97364",
      ["description"] = "Creatures",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.58,
      ["y"] = 0.58,
    },
    {
      ["category"] = "vendor",
      ["name"] = "The Widow",
      ["id"] = "97366",
      ["description"] = "Tools of Deception",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.716,
      ["y"] = 0.23600000000000002,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Tiffy Trapspring",
      ["id"] = "98723",
      ["description"] = "Exotic Pets and Accessories",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.5920000000000001,
      ["y"] = 0.396,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Giada Goldleash",
      ["id"] = "98724",
      ["description"] = "Exotic Pets and Accessories",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.5820000000000001,
      ["y"] = 0.38,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Lio the Lioness",
      ["id"] = "98725",
      ["description"] = "Battle Pet Master",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.5920000000000001,
      ["y"] = 0.396,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jenri",
      ["id"] = "99863",
      ["description"] = "Spymaster",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.54,
      ["y"] = 0.4,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Warpweaver Tuviss",
      ["id"] = "99867",
      ["description"] = "Transmogrifier",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.39,
      ["y"] = 0.41200000000000003,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jabrul",
      ["id"] = "100500",
      ["description"] = "Jewelcrafting Master",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.39799999999999996,
      ["y"] = 0.344,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Calydus",
      ["id"] = "101097",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.564,
      ["y"] = 0.6459999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Nomi",
      ["id"] = "101846",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.402,
      ["y"] = 0.6579999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Filgo Scrapbottom",
      ["id"] = "102193",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.662,
      ["y"] = 0.536,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Filius Sparkstache",
      ["id"] = "102641",
      ["description"] = "Archivist",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.38799999999999996,
      ["y"] = 0.7040000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Nexus-Lord Donjon Rade Sr.",
      ["id"] = "103683",
      ["description"] = "PTR Instance Teleportation",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.484,
      ["y"] = 0.308,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Griftah",
      ["id"] = "103792",
      ["description"] = "Amazing Amulets",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.46,
      ["y"] = 0.27399999999999997,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Lily Locksprocket",
      ["id"] = "103834",
      ["description"] = "Borrowing Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.674,
      ["y"] = 0.524,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Tako Whisperpaw",
      ["id"] = "103839",
      ["description"] = "Tricks and Traps",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.47600000000000003,
      ["y"] = 0.248,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Val'zuun",
      ["id"] = "105333",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.6779999999999999,
      ["y"] = 0.626,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Miragohn Mixmaster",
      ["id"] = "105974",
      ["description"] = "Bartender",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.418,
      ["y"] = 0.466,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Sanzi",
      ["id"] = "105975",
      ["description"] = "Barmaid",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.442,
      ["y"] = 0.5,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Vinemaster Suntouched",
      ["id"] = "105976",
      ["description"] = "Wine & Spirits",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.43799999999999994,
      ["y"] = 0.462,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Elling Trias",
      ["id"] = "105977",
      ["description"] = "Master of Cheese",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.462,
      ["y"] = 0.526,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Smudge Thunderwood",
      ["id"] = "105982",
      ["description"] = "Herbal Concoctions",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.638,
      ["y"] = 0.456,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kelsey Steelspark",
      ["id"] = "105986",
      ["description"] = "Quartermaster",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.27399999999999997,
      ["y"] = 0.358,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kareth",
      ["id"] = "106054",
      ["description"] = "Blade Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.746,
      ["y"] = 0.5579999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Charles Seaton",
      ["id"] = "106056",
      ["description"] = "Blade Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.742,
      ["y"] = 0.5479999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Arcanomancer Vridiel",
      ["id"] = "106655",
      ["description"] = "Blacksmithing Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.452,
      ["y"] = 0.28600000000000003,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Cravitz Lorent",
      ["id"] = "106887",
      ["description"] = "Shady Book Dealer",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.522,
      ["y"] = 0.4,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Lieutenant Surtees",
      ["id"] = "106930",
      ["description"] = "Legion Gladiator",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.294,
      ["y"] = 0.75,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Xur'ios",
      ["id"] = "107109",
      ["description"] = "Vaultkeeper of the Void",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.486,
      ["y"] = 0.142,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Draemus",
      ["id"] = "107326",
      ["description"] = "Exotic Pet Supplier",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.584,
      ["y"] = 0.392,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Strap Bucklebolt",
      ["id"] = "107760",
      ["description"] = "Belts",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.6579999999999999,
      ["y"] = 0.8059999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Thuni",
      ["id"] = "107764",
      ["description"] = "Food, Drink, and Trade Materials",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.626,
      ["y"] = 0.8,
    },
    {
      ["category"] = "vendor",
      ["name"] = "The Mad Merchant",
      ["id"] = "108468",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.43200000000000005,
      ["y"] = 0.46399999999999997,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Yasmina Nerossa",
      ["id"] = "108792",
      ["description"] = "General Goods",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.376,
      ["y"] = 0.55,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Fizzi Liverzapper",
      ["id"] = "110642",
      ["description"] = "Experimental Potions",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.7559999999999999,
      ["y"] = 0.8320000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Mel Lynchen",
      ["id"] = "112007",
      ["description"] = "Barista",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.486,
      ["y"] = 0.382,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Rasil Fireborne",
      ["id"] = "112716",
      ["description"] = "Art Dealer",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.434,
      ["y"] = 0.494,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jemma Wilson",
      ["id"] = "112720",
      ["description"] = "Wine Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.442,
      ["y"] = 0.494,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Illnea Bloodthorn",
      ["id"] = "115264",
      ["description"] = "Blood Trader",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.44799999999999995,
      ["y"] = 0.322,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Serr'ah",
      ["id"] = "115287",
      ["description"] = "Battle Pet Master",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.584,
      ["y"] = 0.38,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Sarah the Savage",
      ["id"] = "119272",
      ["description"] = "Legion Elite Gladiator",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.57,
      ["y"] = 0.278,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Captain Roberts",
      ["id"] = "119484",
      ["description"] = "Legion Elite Gladiator",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.294,
      ["y"] = 0.75,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Lieutenant Dorgen",
      ["id"] = "119485",
      ["description"] = "Legion Combatant",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.292,
      ["y"] = 0.746,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Apothecary Lee",
      ["id"] = "119486",
      ["description"] = "Legion Gladiator",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.568,
      ["y"] = 0.278,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Talia Direhorn",
      ["id"] = "119487",
      ["description"] = "Legion Combatant",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.5720000000000001,
      ["y"] = 0.28,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Violet Shadowmend",
      ["id"] = "120687",
      ["description"] = "Gladiator Quartermaster",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.5920000000000001,
      ["y"] = 0.25,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Marshal Frazer",
      ["id"] = "120906",
      ["description"] = "Gladiator Quartermaster",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.33,
      ["y"] = 0.74,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Zan Shivsproket",
      ["id"] = "121282",
      ["description"] = "Specialities",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.42,
      ["y"] = 0.812,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Merchant Maku",
      ["id"] = "142668",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.608,
      ["y"] = 0.446,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Aridormi",
      ["id"] = "180899",
      ["description"] = "Timewalking Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.6859999999999999,
      ["y"] = 0.488,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Traveling Merchant",
      ["id"] = "194738",
      ["description"] = "Artisan's Consortium",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.46399999999999997,
      ["y"] = 0.696,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Valaden Silverblade",
      ["id"] = "220045",
      ["description"] = "Sword Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.54,
      ["y"] = 0.616,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Remembrancer Amuul",
      ["id"] = "223710",
      ["description"] = "Residual Memories Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.33399999999999996,
      ["y"] = 0.83,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Vaskarn",
      ["id"] = "231596",
      ["description"] = "Awakened Crest Exchange",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.31,
      ["y"] = 0.802,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Ludwin",
      ["id"] = "241192",
      ["description"] = "Storage Enthusiast",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.508,
      ["y"] = 0.188,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Momentus",
      ["id"] = "241744",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.426,
      ["y"] = 0.28,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Halenthos Brightstride",
      ["id"] = "252043",
      ["description"] = "Decor Specialist",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.672,
      ["y"] = 0.33399999999999996,
    },
    {
      ["category"] = "spirithealer",
      ["name"] = "Spirit Healer",
      ["id"] = "6491",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.462,
      ["y"] = 0.21,
    },
    {
      ["category"] = "book",
      ["name"] = "The Fjarnskaggl Fjormula",
      ["id"] = "244836",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.431,
      ["y"] = 0.332,
    },
    {
      ["category"] = "book",
      ["name"] = "The Tangled Beard",
      ["id"] = "244837",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.431,
      ["y"] = 0.332,
    },
    {
      ["category"] = "book",
      ["name"] = "Herblore of the Ancients",
      ["id"] = "244838",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.431,
      ["y"] = 0.332,
    },
    {
      ["category"] = "book",
      ["name"] = "Caution!",
      ["id"] = "248856",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.337,
      ["y"] = 0.575,
    },
    {
      ["category"] = "book",
      ["name"] = "Blood Ledger",
      ["id"] = "249517",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.379,
      ["y"] = 0.7020000000000001,
    },
    {
      ["category"] = "book",
      ["name"] = "Research Notes",
      ["id"] = "266761",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.47600000000000003,
      ["y"] = 0.41,
    },
    {
      ["category"] = "book",
      ["name"] = "Archmage Antonidas",
      ["id"] = "267068",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.45899999999999996,
      ["y"] = 0.213,
    },
    {
      ["category"] = "book",
      ["name"] = "Mel's Journal",
      ["id"] = "269989",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.486,
      ["y"] = 0.382,
    },
    {
      ["category"] = "anvil",
      ["name"] = "Anvil",
      ["id"] = "192628",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.608,
      ["y"] = 0.51,
    },
    {
      ["category"] = "forge",
      ["name"] = "Forge",
      ["id"] = "1685",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.29100000000000004,
      ["y"] = 0.48100000000000004,
    },
    {
      ["category"] = "treasure",
      ["name"] = "Desmond's Lockbox",
      ["id"] = "248854",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.284,
      ["y"] = 0.642,
    },
    {
      ["category"] = "treasure",
      ["name"] = "Large Plundered Sack",
      ["id"] = "252267",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.31,
      ["y"] = 0.691,
    },
    {
      ["category"] = "treasure",
      ["name"] = "Pack of Battle Potions",
      ["id"] = "252269",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.33799999999999997,
      ["y"] = 0.586,
    },
    {
      ["category"] = "treasure",
      ["name"] = "Mysterious Crate",
      ["id"] = "252270",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.302,
      ["y"] = 0.701,
    },
    {
      ["category"] = "treasure",
      ["name"] = "Smoky Boots",
      ["id"] = "252272",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.37200000000000005,
      ["y"] = 0.59,
    },
    {
      ["category"] = "treasure",
      ["name"] = "Box of Throwing Daggers",
      ["id"] = "252273",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.289,
      ["y"] = 0.621,
    },
    {
      ["category"] = "treasure",
      ["name"] = "Thistle Tea",
      ["id"] = "252277",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.34299999999999997,
      ["y"] = 0.634,
    },
    {
      ["category"] = "treasure",
      ["name"] = "Scroll of Teleportation",
      ["id"] = "252278",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.304,
      ["y"] = 0.7,
    },
    {
      ["category"] = "treasure",
      ["name"] = "Stolen Tome of Artifact Lore",
      ["id"] = "252279",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.363,
      ["y"] = 0.5539999999999999,
    },
    {
      ["category"] = "treasure",
      ["name"] = "Sparkling Set of Keys",
      ["id"] = "252282",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.368,
      ["y"] = 0.604,
    },
    {
      ["category"] = "treasure",
      ["name"] = "Pile of Sticky Bombs",
      ["id"] = "252284",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.292,
      ["y"] = 0.588,
    },
    {
      ["category"] = "treasure",
      ["name"] = "Vanishing Powder",
      ["id"] = "252289",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.303,
      ["y"] = 0.654,
    },
    {
      ["category"] = "treasure",
      ["name"] = "Xy'rath's Booby-Trapped Cache",
      ["id"] = "375536",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.32899999999999996,
      ["y"] = 0.8029999999999999,
    },
    {
      ["category"] = "mailbox",
      ["name"] = "Mailbox",
      ["id"] = "32349",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.159,
      ["y"] = 0.113,
    },
    {
      ["category"] = "vignettes",
      ["name"] = "Rotten Egg",
      ["id"] = "97589",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.62,
      ["y"] = 0.43200000000000005,
    },
    {
      ["category"] = "vignettes",
      ["name"] = "Crazed Mage",
      ["id"] = "97587",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.5920000000000001,
      ["y"] = 0.7,
    },
    {
      ["category"] = "vignettes",
      ["name"] = "Mana Seeper",
      ["id"] = "97387",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.49200000000000005,
      ["y"] = 0.38,
    },
    {
      ["category"] = "vignettes",
      ["name"] = "Screek",
      ["id"] = "97381",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.58,
      ["y"] = 0.6659999999999999,
    },
    {
      ["category"] = "vignettes",
      ["name"] = "Segacedi",
      ["id"] = "97384",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.674,
      ["y"] = 0.204,
    },
    {
      ["category"] = "vignettes",
      ["name"] = "Thieving Scoundrel",
      ["id"] = "97390",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.42200000000000004,
      ["y"] = 0.434,
    },
    {
      ["category"] = "vignettes",
      ["name"] = "Xullorax",
      ["id"] = "97388",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.39799999999999996,
      ["y"] = 0.42200000000000004,
    },
    {
      ["category"] = "vignettes",
      ["name"] = "Underbelly Hoard",
      ["id"] = "244597",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.541,
      ["y"] = 0.7140000000000001,
    },
    {
      ["category"] = "vignettes",
      ["name"] = "Underbelly Hoard",
      ["id"] = "244597",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dalaran",
      ["subLocation"] = "Dalaran",
      ["x"] = 0.46299999999999997,
      ["y"] = 0.555,
    },
  }
}
