DB_DARKSHORE_GENERAL = {
  ["region"] = "Kalimdor <Alliance>",
  ["mapID"] = 1439,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Naram Longclaw",
      ["id"] = "4183",
      ["description"] = "Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Darkshore",
      ["subLocation"] = "Darkshore",
      ["x"] = 0.376,
      ["y"] = 0.40399999999999997,
    },
    {
      ["category"] = "repair",
      ["name"] = "Shaldyn",
      ["id"] = "4185",
      ["description"] = "Clothier",
      ["comment"] = "",
      ["mainLocation"] = "Darkshore",
      ["subLocation"] = "Darkshore",
      ["x"] = 0.382,
      ["y"] = 0.40399999999999997,
    },
    {
      ["category"] = "repair",
      ["name"] = "Mavralyn",
      ["id"] = "4186",
      ["description"] = "Leather Armor & Leatherworking Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Darkshore",
      ["subLocation"] = "Darkshore",
      ["x"] = 0.37,
      ["y"] = 0.41200000000000003,
    },
    {
      ["category"] = "repair",
      ["name"] = "Harlon Thornguard",
      ["id"] = "4187",
      ["description"] = "Armorer & Shieldsmith",
      ["comment"] = "",
      ["mainLocation"] = "Darkshore",
      ["subLocation"] = "Darkshore",
      ["x"] = 0.37,
      ["y"] = 0.41200000000000003,
    },
    {
      ["category"] = "repair",
      ["name"] = "Elisa Steelhand",
      ["id"] = "6300",
      ["description"] = "Blacksmithing Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Darkshore",
      ["subLocation"] = "Darkshore",
      ["x"] = 0.382,
      ["y"] = 0.41200000000000003,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Innkeeper Shaussiy",
      ["id"] = "6737",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Darkshore",
      ["subLocation"] = "Darkshore",
      ["x"] = 0.37,
      ["y"] = 0.44,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Jaelysia",
      ["id"] = "10085",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "Darkshore",
      ["subLocation"] = "Darkshore",
      ["x"] = 0.374,
      ["y"] = 0.442,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Caylais Moonfeather",
      ["id"] = "3841",
      ["description"] = "Hippogryph Master",
      ["comment"] = "",
      ["mainLocation"] = "Darkshore",
      ["subLocation"] = "Darkshore",
      ["x"] = 0.364,
      ["y"] = 0.456,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Grondal Moonbreeze",
      ["id"] = "4193",
      ["description"] = "Journeyman Tailor",
      ["comment"] = "",
      ["mainLocation"] = "Darkshore",
      ["subLocation"] = "Darkshore",
      ["x"] = 0.382,
      ["y"] = 0.40399999999999997,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Kurdram Stonehammer",
      ["id"] = "6297",
      ["description"] = "Mining Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Darkshore",
      ["subLocation"] = "Darkshore",
      ["x"] = 0.382,
      ["y"] = 0.41,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Delfrum Flintbeard",
      ["id"] = "6299",
      ["description"] = "Journeyman Blacksmith",
      ["comment"] = "",
      ["mainLocation"] = "Darkshore",
      ["subLocation"] = "Darkshore",
      ["x"] = 0.382,
      ["y"] = 0.41,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Jenna Lemkenilli",
      ["id"] = "11037",
      ["description"] = "Journeyman Engineer",
      ["comment"] = "",
      ["mainLocation"] = "Darkshore",
      ["subLocation"] = "Darkshore",
      ["x"] = 0.382,
      ["y"] = 0.41,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Dalmond",
      ["id"] = "4182",
      ["description"] = "General Goods",
      ["comment"] = "",
      ["mainLocation"] = "Darkshore",
      ["subLocation"] = "Darkshore",
      ["x"] = 0.374,
      ["y"] = 0.40399999999999997,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Naram Longclaw",
      ["id"] = "4183",
      ["description"] = "Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Darkshore",
      ["subLocation"] = "Darkshore",
      ["x"] = 0.376,
      ["y"] = 0.40399999999999997,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Shaldyn",
      ["id"] = "4185",
      ["description"] = "Clothier",
      ["comment"] = "",
      ["mainLocation"] = "Darkshore",
      ["subLocation"] = "Darkshore",
      ["x"] = 0.382,
      ["y"] = 0.40399999999999997,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Mavralyn",
      ["id"] = "4186",
      ["description"] = "Leather Armor & Leatherworking Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Darkshore",
      ["subLocation"] = "Darkshore",
      ["x"] = 0.37,
      ["y"] = 0.41200000000000003,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Harlon Thornguard",
      ["id"] = "4187",
      ["description"] = "Armorer & Shieldsmith",
      ["comment"] = "",
      ["mainLocation"] = "Darkshore",
      ["subLocation"] = "Darkshore",
      ["x"] = 0.37,
      ["y"] = 0.41200000000000003,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Valdaron",
      ["id"] = "4189",
      ["description"] = "Tailoring Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Darkshore",
      ["subLocation"] = "Darkshore",
      ["x"] = 0.38,
      ["y"] = 0.406,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kyndri",
      ["id"] = "4190",
      ["description"] = "Baker",
      ["comment"] = "",
      ["mainLocation"] = "Darkshore",
      ["subLocation"] = "Darkshore",
      ["x"] = 0.368,
      ["y"] = 0.446,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Allyndia",
      ["id"] = "4191",
      ["description"] = "Food & Drink Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Darkshore",
      ["subLocation"] = "Darkshore",
      ["x"] = 0.37,
      ["y"] = 0.436,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Taldan",
      ["id"] = "4192",
      ["description"] = "Drink Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Darkshore",
      ["subLocation"] = "Darkshore",
      ["x"] = 0.368,
      ["y"] = 0.43799999999999994,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Ullanna",
      ["id"] = "4194",
      ["description"] = "Trade Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Darkshore",
      ["subLocation"] = "Darkshore",
      ["x"] = 0.43799999999999994,
      ["y"] = 0.764,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Tiyani",
      ["id"] = "4195",
      ["description"] = "Food & Drink Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Darkshore",
      ["subLocation"] = "Darkshore",
      ["x"] = 0.436,
      ["y"] = 0.7659999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Laird",
      ["id"] = "4200",
      ["description"] = "Fish Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Darkshore",
      ["subLocation"] = "Darkshore",
      ["x"] = 0.368,
      ["y"] = 0.442,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Heldan Galesong",
      ["id"] = "4307",
      ["description"] = "Fisherman",
      ["comment"] = "",
      ["mainLocation"] = "Darkshore",
      ["subLocation"] = "Darkshore",
      ["x"] = 0.37,
      ["y"] = 0.562,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Thelgrum Stonehammer",
      ["id"] = "6298",
      ["description"] = "Mining Supplier",
      ["comment"] = "",
      ["mainLocation"] = "Darkshore",
      ["subLocation"] = "Darkshore",
      ["x"] = 0.382,
      ["y"] = 0.41200000000000003,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Elisa Steelhand",
      ["id"] = "6300",
      ["description"] = "Blacksmithing Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Darkshore",
      ["subLocation"] = "Darkshore",
      ["x"] = 0.382,
      ["y"] = 0.41200000000000003,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Gorbold Steelhand",
      ["id"] = "6301",
      ["description"] = "General Trade Supplier",
      ["comment"] = "",
      ["mainLocation"] = "Darkshore",
      ["subLocation"] = "Darkshore",
      ["x"] = 0.38,
      ["y"] = 0.41200000000000003,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Innkeeper Shaussiy",
      ["id"] = "6737",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Darkshore",
      ["subLocation"] = "Darkshore",
      ["x"] = 0.37,
      ["y"] = 0.44,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Gubber Blump",
      ["id"] = "10216",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Darkshore",
      ["subLocation"] = "Darkshore",
      ["x"] = 0.36,
      ["y"] = 0.44799999999999995,
    },
    {
      ["category"] = "spirithealer",
      ["name"] = "Spirit Healer",
      ["id"] = "6491",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Darkshore",
      ["subLocation"] = "Darkshore",
      ["x"] = 0.418,
      ["y"] = 0.364,
    },
    {
      ["category"] = "book",
      ["name"] = "Mount Hyjal and Illidan's Gift",
      ["id"] = "175729",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Darkshore",
      ["subLocation"] = "Darkshore",
      ["x"] = 0.366,
      ["y"] = 0.44,
    },
    {
      ["category"] = "book",
      ["name"] = "The Founding of Quel'Thalas",
      ["id"] = "175733",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Darkshore",
      ["subLocation"] = "Darkshore",
      ["x"] = 0.366,
      ["y"] = 0.43799999999999994,
    },
    {
      ["category"] = "mailbox",
      ["name"] = "Mailbox",
      ["id"] = "32349",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Darkshore",
      ["subLocation"] = "Darkshore",
      ["x"] = 0.373,
      ["y"] = 0.43799999999999994,
    },
  }
}
