DB_DARNASSUS_GENERAL = {
  ["region"] = "Kalimdor <Alliance>",
  ["mapID"] = 1457,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Cylania",
      ["id"] = "4164",
      ["description"] = "Night Elf Armorer",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.59,
      ["y"] = 0.46,
    },
    {
      ["category"] = "repair",
      ["name"] = "Merelyssa",
      ["id"] = "4171",
      ["description"] = "Blade Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.652,
      ["y"] = 0.6,
    },
    {
      ["category"] = "repair",
      ["name"] = "Anadyia",
      ["id"] = "4172",
      ["description"] = "Robe Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.556,
      ["y"] = 0.8959999999999999,
    },
    {
      ["category"] = "repair",
      ["name"] = "Landria",
      ["id"] = "4173",
      ["description"] = "Bow Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.632,
      ["y"] = 0.664,
    },
    {
      ["category"] = "repair",
      ["name"] = "Vinasia",
      ["id"] = "4175",
      ["description"] = "Cloth Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.604,
      ["y"] = 0.722,
    },
    {
      ["category"] = "repair",
      ["name"] = "Melea",
      ["id"] = "4177",
      ["description"] = "Mail Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.5720000000000001,
      ["y"] = 0.772,
    },
    {
      ["category"] = "repair",
      ["name"] = "Ealyshia Dewwhisper",
      ["id"] = "4180",
      ["description"] = "Two Handed Weapon Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.608,
      ["y"] = 0.72,
    },
    {
      ["category"] = "repair",
      ["name"] = "Ariyell Skyshadow",
      ["id"] = "4203",
      ["description"] = "Weapon Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.586,
      ["y"] = 0.44799999999999995,
    },
    {
      ["category"] = "repair",
      ["name"] = "Kieran",
      ["id"] = "4231",
      ["description"] = "Weapon Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.652,
      ["y"] = 0.6,
    },
    {
      ["category"] = "repair",
      ["name"] = "Glorandiir",
      ["id"] = "4232",
      ["description"] = "Axe Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.64,
      ["y"] = 0.59,
    },
    {
      ["category"] = "repair",
      ["name"] = "Mythidan",
      ["id"] = "4233",
      ["description"] = "Mace & Staff Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.65,
      ["y"] = 0.604,
    },
    {
      ["category"] = "repair",
      ["name"] = "Andrus",
      ["id"] = "4234",
      ["description"] = "Staff Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.56,
      ["y"] = 0.89,
    },
    {
      ["category"] = "repair",
      ["name"] = "Turian",
      ["id"] = "4235",
      ["description"] = "Thrown Weapons Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.624,
      ["y"] = 0.6559999999999999,
    },
    {
      ["category"] = "repair",
      ["name"] = "Cyridan",
      ["id"] = "4236",
      ["description"] = "Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.53,
      ["y"] = 0.802,
    },
    {
      ["category"] = "repair",
      ["name"] = "Caynrus",
      ["id"] = "4240",
      ["description"] = "Shield Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.568,
      ["y"] = 0.762,
    },
    {
      ["category"] = "auctioneer",
      ["name"] = "Auctioneer Tolon",
      ["id"] = "8669",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.564,
      ["y"] = 0.52,
    },
    {
      ["category"] = "auctioneer",
      ["name"] = "Auctioneer Golothas",
      ["id"] = "8723",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.564,
      ["y"] = 0.5379999999999999,
    },
    {
      ["category"] = "auctioneer",
      ["name"] = "Auctioneer Silva'las",
      ["id"] = "15678",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.57,
      ["y"] = 0.534,
    },
    {
      ["category"] = "auctioneer",
      ["name"] = "Auctioneer Cazarez",
      ["id"] = "15679",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.5539999999999999,
      ["y"] = 0.528,
    },
    {
      ["category"] = "banker",
      ["name"] = "Idriana",
      ["id"] = "4155",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.39799999999999996,
      ["y"] = 0.424,
    },
    {
      ["category"] = "banker",
      ["name"] = "Lairn",
      ["id"] = "4208",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.4,
      ["y"] = 0.418,
    },
    {
      ["category"] = "banker",
      ["name"] = "Garryeth",
      ["id"] = "4209",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.4,
      ["y"] = 0.42200000000000004,
    },
    {
      ["category"] = "battlemaster",
      ["name"] = "Keras Wolfheart",
      ["id"] = "907",
      ["description"] = "Arathi Basin Battlemaster",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.58,
      ["y"] = 0.368,
    },
    {
      ["category"] = "battlemaster",
      ["name"] = "Aethalas",
      ["id"] = "2302",
      ["description"] = "Warsong Gulch Battlemaster",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.588,
      ["y"] = 0.368,
    },
    {
      ["category"] = "battlemaster",
      ["name"] = "Brogun Stoneshield",
      ["id"] = "5118",
      ["description"] = "Alterac Valley Battlemaster",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.578,
      ["y"] = 0.446,
    },
    {
      ["category"] = "battlemaster",
      ["name"] = "League of Arathor Emissary",
      ["id"] = "14991",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.426,
      ["y"] = 0.396,
    },
    {
      ["category"] = "battlemaster",
      ["name"] = "Silverwing Emissary",
      ["id"] = "15102",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.424,
      ["y"] = 0.39399999999999996,
    },
    {
      ["category"] = "battlemaster",
      ["name"] = "Stormpike Emissary",
      ["id"] = "15103",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.56,
      ["y"] = 0.452,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Innkeeper Saelienne",
      ["id"] = "6735",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.672,
      ["y"] = 0.158,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Alassin",
      ["id"] = "10056",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.39399999999999996,
      ["y"] = 0.1,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Arias'ta Bladesinger",
      ["id"] = "4087",
      ["description"] = "Warrior Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.584,
      ["y"] = 0.35,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Sildanair",
      ["id"] = "4089",
      ["description"] = "Warrior Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.618,
      ["y"] = 0.418,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Astarii Starseeker",
      ["id"] = "4090",
      ["description"] = "Priest Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.384,
      ["y"] = 0.8079999999999999,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Jandria",
      ["id"] = "4091",
      ["description"] = "Priest Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.38,
      ["y"] = 0.826,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Lariia",
      ["id"] = "4092",
      ["description"] = "Priest Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.4,
      ["y"] = 0.8740000000000001,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Jeen'ra Nightrunner",
      ["id"] = "4138",
      ["description"] = "Hunter Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.396,
      ["y"] = 0.057999999999999996,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Jocaste",
      ["id"] = "4146",
      ["description"] = "Hunter Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.402,
      ["y"] = 0.08800000000000001,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Astaia",
      ["id"] = "4156",
      ["description"] = "Fishing Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.47600000000000003,
      ["y"] = 0.568,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Me'lynn",
      ["id"] = "4159",
      ["description"] = "Expert Tailor",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.634,
      ["y"] = 0.222,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Ainethil",
      ["id"] = "4160",
      ["description"] = "Artisan Alchemist",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.55,
      ["y"] = 0.23800000000000002,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Syurna",
      ["id"] = "4163",
      ["description"] = "Rogue Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.368,
      ["y"] = 0.218,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Elissa Dumas",
      ["id"] = "4165",
      ["description"] = "Portal Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.40399999999999997,
      ["y"] = 0.82,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Firodren Mooncaller",
      ["id"] = "4204",
      ["description"] = "Herbalism Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.48,
      ["y"] = 0.684,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Dorion",
      ["id"] = "4205",
      ["description"] = "Hunter Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.42200000000000004,
      ["y"] = 0.076,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Alegorn",
      ["id"] = "4210",
      ["description"] = "Cooking Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.49,
      ["y"] = 0.212,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Dannelor",
      ["id"] = "4211",
      ["description"] = "First Aid Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.516,
      ["y"] = 0.126,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Telonis",
      ["id"] = "4212",
      ["description"] = "Artisan Leatherworker",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.644,
      ["y"] = 0.214,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Taladan",
      ["id"] = "4213",
      ["description"] = "Expert Enchanter",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.586,
      ["y"] = 0.132,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Erion Shadewhisper",
      ["id"] = "4214",
      ["description"] = "Rogue Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.34600000000000003,
      ["y"] = 0.256,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Anishar",
      ["id"] = "4215",
      ["description"] = "Rogue Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.37799999999999995,
      ["y"] = 0.212,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Mathrengyl Bearwalker",
      ["id"] = "4217",
      ["description"] = "Druid Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.35200000000000004,
      ["y"] = 0.08,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Denatharion",
      ["id"] = "4218",
      ["description"] = "Druid Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.348,
      ["y"] = 0.078,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Fylerian Nightwing",
      ["id"] = "4219",
      ["description"] = "Druid Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.336,
      ["y"] = 0.086,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Jartsam",
      ["id"] = "4753",
      ["description"] = "Nightsaber Riding Instructor",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.384,
      ["y"] = 0.158,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Eladriel",
      ["id"] = "6292",
      ["description"] = "Skinning Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.642,
      ["y"] = 0.218,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Darnath Bladesinger",
      ["id"] = "7315",
      ["description"] = "Warrior Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.586,
      ["y"] = 0.354,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Silvaria",
      ["id"] = "10089",
      ["description"] = "Pet Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.42200000000000004,
      ["y"] = 0.08800000000000001,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Milla Fairancora",
      ["id"] = "11041",
      ["description"] = "Journeyman Alchemist",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.552,
      ["y"] = 0.228,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Sylvanna Forestmoon",
      ["id"] = "11042",
      ["description"] = "Expert Alchemist",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.562,
      ["y"] = 0.242,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Trianna",
      ["id"] = "11050",
      ["description"] = "Journeyman Tailor",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.636,
      ["y"] = 0.214,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Lalina Summermoon",
      ["id"] = "11070",
      ["description"] = "Journeyman Enchanter",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.588,
      ["y"] = 0.13,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Faldron",
      ["id"] = "11081",
      ["description"] = "Expert Leatherworker",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.6459999999999999,
      ["y"] = 0.21600000000000003,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Darianna",
      ["id"] = "11083",
      ["description"] = "Journeyman Leatherworker",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.644,
      ["y"] = 0.212,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Priestess Alathea",
      ["id"] = "11401",
      ["description"] = "Priest Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.392,
      ["y"] = 0.81,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Ilyenia Moonfire",
      ["id"] = "11866",
      ["description"] = "Weapon Master",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.5760000000000001,
      ["y"] = 0.46399999999999997,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kyrai",
      ["id"] = "3561",
      ["description"] = "Poison Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.32799999999999996,
      ["y"] = 0.196,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Alaindia",
      ["id"] = "3562",
      ["description"] = "Reagent Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.386,
      ["y"] = 0.44799999999999995,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Cylania",
      ["id"] = "4164",
      ["description"] = "Night Elf Armorer",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.59,
      ["y"] = 0.46,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Elissa Dumas",
      ["id"] = "4165",
      ["description"] = "Portal Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.40399999999999997,
      ["y"] = 0.82,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Dendrythis",
      ["id"] = "4167",
      ["description"] = "Food & Drink Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.382,
      ["y"] = 0.20199999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Elynna",
      ["id"] = "4168",
      ["description"] = "Tailoring Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.642,
      ["y"] = 0.21600000000000003,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jaeana",
      ["id"] = "4169",
      ["description"] = "Meat Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.62,
      ["y"] = 0.5479999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Ellandrieth",
      ["id"] = "4170",
      ["description"] = "General Goods Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.644,
      ["y"] = 0.53,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Merelyssa",
      ["id"] = "4171",
      ["description"] = "Blade Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.652,
      ["y"] = 0.6,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Anadyia",
      ["id"] = "4172",
      ["description"] = "Robe Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.556,
      ["y"] = 0.8959999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Landria",
      ["id"] = "4173",
      ["description"] = "Bow Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.632,
      ["y"] = 0.664,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Vinasia",
      ["id"] = "4175",
      ["description"] = "Cloth Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.604,
      ["y"] = 0.722,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Melea",
      ["id"] = "4177",
      ["description"] = "Mail Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.5720000000000001,
      ["y"] = 0.772,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Ealyshia Dewwhisper",
      ["id"] = "4180",
      ["description"] = "Two Handed Weapon Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.608,
      ["y"] = 0.72,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Fyrenna",
      ["id"] = "4181",
      ["description"] = "Food & Drink Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.6940000000000001,
      ["y"] = 0.44799999999999995,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Ariyell Skyshadow",
      ["id"] = "4203",
      ["description"] = "Weapon Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.586,
      ["y"] = 0.44799999999999995,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Chardryn",
      ["id"] = "4216",
      ["description"] = "Herbalism Supplier",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.48200000000000004,
      ["y"] = 0.69,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Mathrengyl Bearwalker",
      ["id"] = "4217",
      ["description"] = "Druid Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.35200000000000004,
      ["y"] = 0.08,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Cyroen",
      ["id"] = "4220",
      ["description"] = "Reagent Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.34,
      ["y"] = 0.096,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Talaelar",
      ["id"] = "4221",
      ["description"] = "Fish Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.474,
      ["y"] = 0.57,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Voloren",
      ["id"] = "4222",
      ["description"] = "Fishing Supplier",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.47,
      ["y"] = 0.5660000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Fyldan",
      ["id"] = "4223",
      ["description"] = "Cooking Supplier",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.486,
      ["y"] = 0.214,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Saenorion",
      ["id"] = "4225",
      ["description"] = "Leatherworking Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.638,
      ["y"] = 0.22,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Ulthir",
      ["id"] = "4226",
      ["description"] = "Alchemy Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.556,
      ["y"] = 0.244,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Vaean",
      ["id"] = "4228",
      ["description"] = "Enchanting Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.586,
      ["y"] = 0.14400000000000002,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Mythrin'dir",
      ["id"] = "4229",
      ["description"] = "General Trade Supplier",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.61,
      ["y"] = 0.18,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Yldan",
      ["id"] = "4230",
      ["description"] = "Bag Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.654,
      ["y"] = 0.528,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kieran",
      ["id"] = "4231",
      ["description"] = "Weapon Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.652,
      ["y"] = 0.6,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Glorandiir",
      ["id"] = "4232",
      ["description"] = "Axe Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.64,
      ["y"] = 0.59,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Mythidan",
      ["id"] = "4233",
      ["description"] = "Mace & Staff Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.65,
      ["y"] = 0.604,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Andrus",
      ["id"] = "4234",
      ["description"] = "Staff Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.56,
      ["y"] = 0.89,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Turian",
      ["id"] = "4235",
      ["description"] = "Thrown Weapons Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.624,
      ["y"] = 0.6559999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Cyridan",
      ["id"] = "4236",
      ["description"] = "Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.53,
      ["y"] = 0.802,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Caynrus",
      ["id"] = "4240",
      ["description"] = "Shield Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.568,
      ["y"] = 0.762,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Mydrannul",
      ["id"] = "4241",
      ["description"] = "General Goods Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.706,
      ["y"] = 0.45,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Lelanai",
      ["id"] = "4730",
      ["description"] = "Saber Handler",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.384,
      ["y"] = 0.156,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Shalumon",
      ["id"] = "5191",
      ["description"] = "Tabard Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.7020000000000001,
      ["y"] = 0.23399999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Innkeeper Saelienne",
      ["id"] = "6735",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.672,
      ["y"] = 0.158,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Shylenai",
      ["id"] = "8665",
      ["description"] = "Owl Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.698,
      ["y"] = 0.45399999999999996,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Lunar Festival Vendor",
      ["id"] = "15898",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.344,
      ["y"] = 0.124,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Marcy Baker",
      ["id"] = "214101",
      ["description"] = "Supply Officer",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.598,
      ["y"] = 0.5660000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Rune Broker",
      ["id"] = "233335",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.28600000000000003,
      ["y"] = 0.39,
    },
    {
      ["category"] = "spirithealer",
      ["name"] = "Spirit Healer",
      ["id"] = "6491",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.768,
      ["y"] = 0.276,
    },
    {
      ["category"] = "book",
      ["name"] = "Aftermath of the Second War",
      ["id"] = "21581",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.5539999999999999,
      ["y"] = 0.13,
    },
    {
      ["category"] = "book",
      ["name"] = "The Old Gods and the Ordering of Azeroth",
      ["id"] = "175725",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.5539999999999999,
      ["y"] = 0.24,
    },
    {
      ["category"] = "book",
      ["name"] = "The War of the Ancients",
      ["id"] = "175727",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.489,
      ["y"] = 0.161,
    },
    {
      ["category"] = "book",
      ["name"] = "The World Tree and the Emerald Dream",
      ["id"] = "175730",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.562,
      ["y"] = 0.038,
    },
    {
      ["category"] = "book",
      ["name"] = "Exile of the High Elves",
      ["id"] = "175731",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.34299999999999997,
      ["y"] = 0.259,
    },
    {
      ["category"] = "book",
      ["name"] = "The Betrayer Ascendant",
      ["id"] = "175759",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.665,
      ["y"] = 0.7659999999999999,
    },
    {
      ["category"] = "book",
      ["name"] = "Rise of the Blood Elves",
      ["id"] = "175760",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.49200000000000005,
      ["y"] = 0.168,
    },
    {
      ["category"] = "mailbox",
      ["name"] = "Mailbox",
      ["id"] = "32349",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Darnassus",
      ["subLocation"] = "Darnassus",
      ["x"] = 0.414,
      ["y"] = 0.42100000000000004,
    },
  }
}
