DB_DESOLACE_GENERAL = {
  ["region"] = "Kalimdor",
  ["mapID"] = 1443,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Maxton Strang",
      ["id"] = "1322",
      ["description"] = "Mail Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Desolace",
      ["subLocation"] = "Desolace",
      ["x"] = 0.6779999999999999,
      ["y"] = 0.084,
    },
    {
      ["category"] = "repair",
      ["name"] = "Muuran",
      ["id"] = "8878",
      ["description"] = "Superior Macecrafter",
      ["comment"] = "",
      ["mainLocation"] = "Desolace",
      ["subLocation"] = "Desolace",
      ["x"] = 0.556,
      ["y"] = 0.564,
    },
    {
      ["category"] = "repair",
      ["name"] = "Hae'Wilani",
      ["id"] = "12045",
      ["description"] = "Axecrafter",
      ["comment"] = "",
      ["mainLocation"] = "Desolace",
      ["subLocation"] = "Desolace",
      ["x"] = 0.258,
      ["y"] = 0.71,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Innkeeper Lyshaerya",
      ["id"] = "11103",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Desolace",
      ["subLocation"] = "Desolace",
      ["x"] = 0.662,
      ["y"] = 0.066,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Innkeeper Sikewa",
      ["id"] = "11106",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Desolace",
      ["subLocation"] = "Desolace",
      ["x"] = 0.24,
      ["y"] = 0.682,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Shelgrayn",
      ["id"] = "11104",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "Desolace",
      ["subLocation"] = "Desolace",
      ["x"] = 0.6559999999999999,
      ["y"] = 0.078,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Aboda",
      ["id"] = "11105",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "Desolace",
      ["subLocation"] = "Desolace",
      ["x"] = 0.248,
      ["y"] = 0.688,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Baritanas Skyriver",
      ["id"] = "6706",
      ["description"] = "Hippogryph Master",
      ["comment"] = "",
      ["mainLocation"] = "Desolace",
      ["subLocation"] = "Desolace",
      ["x"] = 0.6459999999999999,
      ["y"] = 0.10400000000000001,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Thalon",
      ["id"] = "6726",
      ["description"] = "Wind Rider Master",
      ["comment"] = "",
      ["mainLocation"] = "Desolace",
      ["subLocation"] = "Desolace",
      ["x"] = 0.21600000000000003,
      ["y"] = 0.74,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Narv Hidecrafter",
      ["id"] = "8153",
      ["description"] = "Expert Leathercrafter",
      ["comment"] = "",
      ["mainLocation"] = "Desolace",
      ["subLocation"] = "Desolace",
      ["x"] = 0.552,
      ["y"] = 0.562,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Malux",
      ["id"] = "12030",
      ["description"] = "Skinning Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Desolace",
      ["subLocation"] = "Desolace",
      ["x"] = 0.23199999999999998,
      ["y"] = 0.698,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Lui'Mala",
      ["id"] = "12032",
      ["description"] = "Fisherman",
      ["comment"] = "",
      ["mainLocation"] = "Desolace",
      ["subLocation"] = "Desolace",
      ["x"] = 0.226,
      ["y"] = 0.7240000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Maxton Strang",
      ["id"] = "1322",
      ["description"] = "Mail Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Desolace",
      ["subLocation"] = "Desolace",
      ["x"] = 0.6779999999999999,
      ["y"] = 0.084,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Janet Hommers",
      ["id"] = "8150",
      ["description"] = "Food & Drink",
      ["comment"] = "",
      ["mainLocation"] = "Desolace",
      ["subLocation"] = "Desolace",
      ["x"] = 0.662,
      ["y"] = 0.066,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Harnor",
      ["id"] = "8152",
      ["description"] = "Food & Drink",
      ["comment"] = "",
      ["mainLocation"] = "Desolace",
      ["subLocation"] = "Desolace",
      ["x"] = 0.512,
      ["y"] = 0.532,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Muuran",
      ["id"] = "8878",
      ["description"] = "Superior Macecrafter",
      ["comment"] = "",
      ["mainLocation"] = "Desolace",
      ["subLocation"] = "Desolace",
      ["x"] = 0.556,
      ["y"] = 0.564,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kireena",
      ["id"] = "9636",
      ["description"] = "Trade Goods",
      ["comment"] = "",
      ["mainLocation"] = "Desolace",
      ["subLocation"] = "Desolace",
      ["x"] = 0.51,
      ["y"] = 0.534,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Innkeeper Lyshaerya",
      ["id"] = "11103",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Desolace",
      ["subLocation"] = "Desolace",
      ["x"] = 0.662,
      ["y"] = 0.066,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Innkeeper Sikewa",
      ["id"] = "11106",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Desolace",
      ["subLocation"] = "Desolace",
      ["x"] = 0.24,
      ["y"] = 0.682,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Tukk",
      ["id"] = "12027",
      ["description"] = "General Goods Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Desolace",
      ["subLocation"] = "Desolace",
      ["x"] = 0.25,
      ["y"] = 0.718,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Lah'Mawhani",
      ["id"] = "12028",
      ["description"] = "Trade Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Desolace",
      ["subLocation"] = "Desolace",
      ["x"] = 0.23,
      ["y"] = 0.716,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Mai'Lahii",
      ["id"] = "12031",
      ["description"] = "Fishing Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Desolace",
      ["subLocation"] = "Desolace",
      ["x"] = 0.226,
      ["y"] = 0.72,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Wulan",
      ["id"] = "12033",
      ["description"] = "Cooking Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Desolace",
      ["subLocation"] = "Desolace",
      ["x"] = 0.262,
      ["y"] = 0.698,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Hae'Wilani",
      ["id"] = "12045",
      ["description"] = "Axecrafter",
      ["comment"] = "",
      ["mainLocation"] = "Desolace",
      ["subLocation"] = "Desolace",
      ["x"] = 0.258,
      ["y"] = 0.71,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Vendor-Tron 1000",
      ["id"] = "12245",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Desolace",
      ["subLocation"] = "Desolace",
      ["x"] = 0.602,
      ["y"] = 0.382,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Super-Seller 680",
      ["id"] = "12246",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Desolace",
      ["subLocation"] = "Desolace",
      ["x"] = 0.40399999999999997,
      ["y"] = 0.792,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Christi Galvanis",
      ["id"] = "12960",
      ["description"] = "General Goods",
      ["comment"] = "",
      ["mainLocation"] = "Desolace",
      ["subLocation"] = "Desolace",
      ["x"] = 0.6659999999999999,
      ["y"] = 0.068,
    },
    {
      ["category"] = "spirithealer",
      ["name"] = "Spirit Healer",
      ["id"] = "6491",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Desolace",
      ["subLocation"] = "Desolace",
      ["x"] = 0.502,
      ["y"] = 0.628,
    },
    {
      ["category"] = "boss",
      ["name"] = "The Nameless Prophet",
      ["id"] = "13718",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Desolace",
      ["subLocation"] = "Desolace",
      ["x"] = 0.29600000000000004,
      ["y"] = 0.624,
    },
    {
      ["category"] = "book",
      ["name"] = "Archimonde's Return and the Flight to Kalimdor",
      ["id"] = "175758",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Desolace",
      ["subLocation"] = "Desolace",
      ["x"] = 0.6629999999999999,
      ["y"] = 0.077,
    },
    {
      ["category"] = "mailbox",
      ["name"] = "Mailbox",
      ["id"] = "32349",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Desolace",
      ["subLocation"] = "Desolace",
      ["x"] = 0.248,
      ["y"] = 0.688,
    },
  }
}
