DB_DUN_MOROGH_GENERAL = {
  ["region"] = "Eastern Kingdoms <Alliance>",
  ["mapID"] = 1426,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Durnan Furcutter",
      ["id"] = "836",
      ["description"] = "Cloth & Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.28800000000000003,
      ["y"] = 0.664,
    },
    {
      ["category"] = "repair",
      ["name"] = "Rybrad Coldbank",
      ["id"] = "945",
      ["description"] = "Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.28600000000000003,
      ["y"] = 0.6779999999999999,
    },
    {
      ["category"] = "repair",
      ["name"] = "Grundel Harkin",
      ["id"] = "1104",
      ["description"] = "Armorer",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.28800000000000003,
      ["y"] = 0.6779999999999999,
    },
    {
      ["category"] = "repair",
      ["name"] = "Gamili Frosthide",
      ["id"] = "1238",
      ["description"] = "Cloth & Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.452,
      ["y"] = 0.518,
    },
    {
      ["category"] = "repair",
      ["name"] = "Boran Ironclink",
      ["id"] = "1240",
      ["description"] = "Armorer",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.452,
      ["y"] = 0.518,
    },
    {
      ["category"] = "repair",
      ["name"] = "Hegnar Rumbleshot",
      ["id"] = "1243",
      ["description"] = "Gunsmith",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.406,
      ["y"] = 0.65,
    },
    {
      ["category"] = "repair",
      ["name"] = "Grawn Thromwyn",
      ["id"] = "1273",
      ["description"] = "Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.452,
      ["y"] = 0.52,
    },
    {
      ["category"] = "repair",
      ["name"] = "Thrawn Boltar",
      ["id"] = "1690",
      ["description"] = "Blacksmithing Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.452,
      ["y"] = 0.516,
    },
    {
      ["category"] = "repair",
      ["name"] = "Frast Dokner",
      ["id"] = "1698",
      ["description"] = "Apprentice Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.688,
      ["y"] = 0.5579999999999999,
    },
    {
      ["category"] = "repair",
      ["name"] = "Burdrak Harglhelm",
      ["id"] = "3162",
      ["description"] = "Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.302,
      ["y"] = 0.452,
    },
    {
      ["category"] = "repair",
      ["name"] = "Turuk Amberstill",
      ["id"] = "3177",
      ["description"] = "Dwarven Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.63,
      ["y"] = 0.498,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Innkeeper Belm",
      ["id"] = "1247",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.474,
      ["y"] = 0.524,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Shelby Stoneflint",
      ["id"] = "9980",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.47,
      ["y"] = 0.526,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Alamar Grimm",
      ["id"] = "460",
      ["description"] = "Warlock Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.28600000000000003,
      ["y"] = 0.662,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Branstock Khalder",
      ["id"] = "837",
      ["description"] = "Priest Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.28600000000000003,
      ["y"] = 0.664,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Thorgas Grimson",
      ["id"] = "895",
      ["description"] = "Hunter Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.29,
      ["y"] = 0.674,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Thran Khorman",
      ["id"] = "912",
      ["description"] = "Warrior Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.28800000000000003,
      ["y"] = 0.672,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Solm Hargrin",
      ["id"] = "916",
      ["description"] = "Rogue Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.284,
      ["y"] = 0.674,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Bromos Grummner",
      ["id"] = "926",
      ["description"] = "Paladin Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.28800000000000003,
      ["y"] = 0.682,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Marryk Nurribit",
      ["id"] = "944",
      ["description"] = "Mage Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.28600000000000003,
      ["y"] = 0.664,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Maxan Anvol",
      ["id"] = "1226",
      ["description"] = "Priest Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.47200000000000003,
      ["y"] = 0.522,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Magis Sparkmantle",
      ["id"] = "1228",
      ["description"] = "Mage Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.474,
      ["y"] = 0.52,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Granis Swiftaxe",
      ["id"] = "1229",
      ["description"] = "Warrior Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.47200000000000003,
      ["y"] = 0.526,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Grif Wildheart",
      ["id"] = "1231",
      ["description"] = "Hunter Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.45799999999999996,
      ["y"] = 0.53,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Azar Stronghammer",
      ["id"] = "1232",
      ["description"] = "Paladin Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.47600000000000003,
      ["y"] = 0.52,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Hogral Bakkan",
      ["id"] = "1234",
      ["description"] = "Rogue Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.47600000000000003,
      ["y"] = 0.526,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Tognus Flintfire",
      ["id"] = "1241",
      ["description"] = "Journeyman Blacksmith",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.452,
      ["y"] = 0.52,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Cook Ghilm",
      ["id"] = "1355",
      ["description"] = "Cooking Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.684,
      ["y"] = 0.544,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Gremlock Pilsnor",
      ["id"] = "1699",
      ["description"] = "Cooking Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.47600000000000003,
      ["y"] = 0.524,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Paxton Ganter",
      ["id"] = "1700",
      ["description"] = "Fisherman",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.354,
      ["y"] = 0.402,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Dank Drizzlecut",
      ["id"] = "1701",
      ["description"] = "Mining Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.6920000000000001,
      ["y"] = 0.5539999999999999,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Bronk Guzzlegear",
      ["id"] = "1702",
      ["description"] = "Journeyman Engineer",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.502,
      ["y"] = 0.504,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Thamner Pol",
      ["id"] = "2326",
      ["description"] = "Physician",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.47200000000000003,
      ["y"] = 0.526,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Peria Lamenur",
      ["id"] = "2878",
      ["description"] = "Pet Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.466,
      ["y"] = 0.5379999999999999,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Ultham Ironhorn",
      ["id"] = "4772",
      ["description"] = "Ram Riding Instructor",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.638,
      ["y"] = 0.502,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Yarr Hammerstone",
      ["id"] = "5392",
      ["description"] = "Mining Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.5,
      ["y"] = 0.504,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Gimrizz Shadowcog",
      ["id"] = "5612",
      ["description"] = "Warlock Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.47200000000000003,
      ["y"] = 0.536,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Binjy Featherwhistle",
      ["id"] = "7954",
      ["description"] = "Mechanostrider Pilot",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.49200000000000005,
      ["y"] = 0.48,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Adlin Pridedrift",
      ["id"] = "829",
      ["description"] = "General Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.3,
      ["y"] = 0.716,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Durnan Furcutter",
      ["id"] = "836",
      ["description"] = "Cloth & Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.28800000000000003,
      ["y"] = 0.664,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Rybrad Coldbank",
      ["id"] = "945",
      ["description"] = "Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.28600000000000003,
      ["y"] = 0.6779999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Grundel Harkin",
      ["id"] = "1104",
      ["description"] = "Armorer",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.28800000000000003,
      ["y"] = 0.6779999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kazan Mogosh",
      ["id"] = "1237",
      ["description"] = "Food & Drink Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.6859999999999999,
      ["y"] = 0.546,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Gamili Frosthide",
      ["id"] = "1238",
      ["description"] = "Cloth & Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.452,
      ["y"] = 0.518,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Boran Ironclink",
      ["id"] = "1240",
      ["description"] = "Armorer",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.452,
      ["y"] = 0.518,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Hegnar Rumbleshot",
      ["id"] = "1243",
      ["description"] = "Gunsmith",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.406,
      ["y"] = 0.65,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Innkeeper Belm",
      ["id"] = "1247",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.474,
      ["y"] = 0.524,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Veron Amberstill",
      ["id"] = "1261",
      ["description"] = "Ram Breeder",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.634,
      ["y"] = 0.506,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Yarlyn Amberstill",
      ["id"] = "1263",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.632,
      ["y"] = 0.51,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Grawn Thromwyn",
      ["id"] = "1273",
      ["description"] = "Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.452,
      ["y"] = 0.52,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Thrawn Boltar",
      ["id"] = "1690",
      ["description"] = "Blacksmithing Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.452,
      ["y"] = 0.516,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kreg Bilmn",
      ["id"] = "1691",
      ["description"] = "General Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.47200000000000003,
      ["y"] = 0.524,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Golorn Frostbeard",
      ["id"] = "1692",
      ["description"] = "Tradesman",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.466,
      ["y"] = 0.536,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Loslor Rudge",
      ["id"] = "1694",
      ["description"] = "Engineering Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.5,
      ["y"] = 0.494,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Keeg Gibn",
      ["id"] = "1697",
      ["description"] = "Ale and Wine",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.304,
      ["y"] = 0.46,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Frast Dokner",
      ["id"] = "1698",
      ["description"] = "Apprentice Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.688,
      ["y"] = 0.5579999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Burdrak Harglhelm",
      ["id"] = "3162",
      ["description"] = "Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.302,
      ["y"] = 0.452,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Turuk Amberstill",
      ["id"] = "3177",
      ["description"] = "Dwarven Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.63,
      ["y"] = 0.498,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Dannie Fizzwizzle",
      ["id"] = "6328",
      ["description"] = "Demon Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.47200000000000003,
      ["y"] = 0.536,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Wren Darkspring",
      ["id"] = "6376",
      ["description"] = "Demon Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.28800000000000003,
      ["y"] = 0.662,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Milli Featherwhistle",
      ["id"] = "7955",
      ["description"] = "Mechanostrider Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.49200000000000005,
      ["y"] = 0.48,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Gretta Ganter",
      ["id"] = "8508",
      ["description"] = "Fisherman Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.314,
      ["y"] = 0.446,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Wagner Hammerstrike",
      ["id"] = "15011",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.526,
      ["y"] = 0.36,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Rune Broker",
      ["id"] = "233335",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.294,
      ["y"] = 0.72,
    },
    {
      ["category"] = "spirithealer",
      ["name"] = "Spirit Healer",
      ["id"] = "6491",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.294,
      ["y"] = 0.698,
    },
    {
      ["category"] = "book",
      ["name"] = "Etched Note",
      ["id"] = "174746",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.526,
      ["y"] = 0.371,
    },
    {
      ["category"] = "book",
      ["name"] = "The Alliance of Lordaeron",
      ["id"] = "175746",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.47600000000000003,
      ["y"] = 0.52,
    },
    {
      ["category"] = "forge",
      ["name"] = "Forge",
      ["id"] = "1685",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.45299999999999996,
      ["y"] = 0.519,
    },
    {
      ["category"] = "mailbox",
      ["name"] = "Mailbox",
      ["id"] = "32349",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dun Morogh",
      ["subLocation"] = "Dun Morogh",
      ["x"] = 0.47,
      ["y"] = 0.524,
    },
  }
}
