DB_DUROTAR_GENERAL = {
  ["region"] = "Kalimdor <Horde>",
  ["mapID"] = 1411,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Kzan Thornslash",
      ["id"] = "3159",
      ["description"] = "Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.40399999999999997,
      ["y"] = 0.68,
    },
    {
      ["category"] = "repair",
      ["name"] = "Huklah",
      ["id"] = "3160",
      ["description"] = "Cloth & Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.406,
      ["y"] = 0.6779999999999999,
    },
    {
      ["category"] = "repair",
      ["name"] = "Rarc",
      ["id"] = "3161",
      ["description"] = "Armorer & Shieldcrafter",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.40399999999999997,
      ["y"] = 0.6779999999999999,
    },
    {
      ["category"] = "repair",
      ["name"] = "Uhgar",
      ["id"] = "3163",
      ["description"] = "Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.52,
      ["y"] = 0.40399999999999997,
    },
    {
      ["category"] = "repair",
      ["name"] = "Ghrawt",
      ["id"] = "3165",
      ["description"] = "Bowyer",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.53,
      ["y"] = 0.41,
    },
    {
      ["category"] = "repair",
      ["name"] = "Cutac",
      ["id"] = "3166",
      ["description"] = "Cloth & Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.53,
      ["y"] = 0.408,
    },
    {
      ["category"] = "repair",
      ["name"] = "Wuark",
      ["id"] = "3167",
      ["description"] = "Armorer & Shieldcrafter",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.52,
      ["y"] = 0.41200000000000003,
    },
    {
      ["category"] = "repair",
      ["name"] = "Trayexir",
      ["id"] = "10369",
      ["description"] = "Weapon Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.564,
      ["y"] = 0.732,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Innkeeper Grosk",
      ["id"] = "6928",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.516,
      ["y"] = 0.41600000000000004,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Shoja'my",
      ["id"] = "9987",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.52,
      ["y"] = 0.418,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Frang",
      ["id"] = "3153",
      ["description"] = "Warrior Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.428,
      ["y"] = 0.6940000000000001,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Jen'shan",
      ["id"] = "3154",
      ["description"] = "Hunter Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.428,
      ["y"] = 0.6920000000000001,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Rwag",
      ["id"] = "3155",
      ["description"] = "Rogue Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.41200000000000003,
      ["y"] = 0.68,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Nartok",
      ["id"] = "3156",
      ["description"] = "Warlock Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.406,
      ["y"] = 0.684,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Shikrik",
      ["id"] = "3157",
      ["description"] = "Shaman Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.424,
      ["y"] = 0.69,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Tarshaw Jaggedscar",
      ["id"] = "3169",
      ["description"] = "Warrior Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.542,
      ["y"] = 0.424,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Kaplak",
      ["id"] = "3170",
      ["description"] = "Rogue Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.52,
      ["y"] = 0.436,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Thotar",
      ["id"] = "3171",
      ["description"] = "Hunter Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.518,
      ["y"] = 0.434,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Dhugru Gorelust",
      ["id"] = "3172",
      ["description"] = "Warlock Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.542,
      ["y"] = 0.41200000000000003,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Swart",
      ["id"] = "3173",
      ["description"] = "Shaman Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.544,
      ["y"] = 0.426,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Dwukk",
      ["id"] = "3174",
      ["description"] = "Journeyman Blacksmith",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.52,
      ["y"] = 0.406,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Krunn",
      ["id"] = "3175",
      ["description"] = "Miner",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.518,
      ["y"] = 0.408,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Miao'zan",
      ["id"] = "3184",
      ["description"] = "Journeyman Alchemist",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.5539999999999999,
      ["y"] = 0.74,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Mishiki",
      ["id"] = "3185",
      ["description"] = "Herbalist",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.5539999999999999,
      ["y"] = 0.75,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Harruk",
      ["id"] = "3620",
      ["description"] = "Pet Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.52,
      ["y"] = 0.434,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Tai'jin",
      ["id"] = "3706",
      ["description"] = "Priest Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.542,
      ["y"] = 0.428,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Ken'jai",
      ["id"] = "3707",
      ["description"] = "Priest Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.424,
      ["y"] = 0.688,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Un'Thuwa",
      ["id"] = "5880",
      ["description"] = "Mage Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.562,
      ["y"] = 0.75,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Mai'ah",
      ["id"] = "5884",
      ["description"] = "Mage Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.424,
      ["y"] = 0.69,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Lau'Tiki",
      ["id"] = "5941",
      ["description"] = "Fisherman",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.532,
      ["y"] = 0.8140000000000001,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Rawrk",
      ["id"] = "5943",
      ["description"] = "First Aid Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.54,
      ["y"] = 0.42,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Xar'Ti",
      ["id"] = "7953",
      ["description"] = "Raptor Riding Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.552,
      ["y"] = 0.754,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Mukdrak",
      ["id"] = "11025",
      ["description"] = "Journeyman Engineer",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.522,
      ["y"] = 0.408,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Duokna",
      ["id"] = "3158",
      ["description"] = "General Goods",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.426,
      ["y"] = 0.674,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kzan Thornslash",
      ["id"] = "3159",
      ["description"] = "Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.40399999999999997,
      ["y"] = 0.68,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Huklah",
      ["id"] = "3160",
      ["description"] = "Cloth & Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.406,
      ["y"] = 0.6779999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Rarc",
      ["id"] = "3161",
      ["description"] = "Armorer & Shieldcrafter",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.40399999999999997,
      ["y"] = 0.6779999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Uhgar",
      ["id"] = "3163",
      ["description"] = "Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.52,
      ["y"] = 0.40399999999999997,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jark",
      ["id"] = "3164",
      ["description"] = "General Goods",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.542,
      ["y"] = 0.42200000000000004,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Ghrawt",
      ["id"] = "3165",
      ["description"] = "Bowyer",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.53,
      ["y"] = 0.41,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Cutac",
      ["id"] = "3166",
      ["description"] = "Cloth & Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.53,
      ["y"] = 0.408,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Wuark",
      ["id"] = "3167",
      ["description"] = "Armorer & Shieldcrafter",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.52,
      ["y"] = 0.41200000000000003,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Flakk",
      ["id"] = "3168",
      ["description"] = "Trade Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.528,
      ["y"] = 0.42,
    },
    {
      ["category"] = "vendor",
      ["name"] = "K'waii",
      ["id"] = "3186",
      ["description"] = "General Goods",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.562,
      ["y"] = 0.7340000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Tai'tasi",
      ["id"] = "3187",
      ["description"] = "Trade Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.564,
      ["y"] = 0.738,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Grimtak",
      ["id"] = "3881",
      ["description"] = "Butcher",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.512,
      ["y"] = 0.426,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Zlagk",
      ["id"] = "3882",
      ["description"] = "Butcher",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.426,
      ["y"] = 0.672,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Hai'zan",
      ["id"] = "3933",
      ["description"] = "Butcher",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.556,
      ["y"] = 0.736,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Zansoa",
      ["id"] = "5942",
      ["description"] = "Fishing Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.56,
      ["y"] = 0.7340000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kitha",
      ["id"] = "6027",
      ["description"] = "Demon Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.546,
      ["y"] = 0.414,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Innkeeper Grosk",
      ["id"] = "6928",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.516,
      ["y"] = 0.41600000000000004,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Zjolnir",
      ["id"] = "7952",
      ["description"] = "Raptor Handler",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.552,
      ["y"] = 0.7559999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Trayexir",
      ["id"] = "10369",
      ["description"] = "Weapon Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.564,
      ["y"] = 0.732,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Hraug",
      ["id"] = "12776",
      ["description"] = "Demon Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.406,
      ["y"] = 0.684,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Javnir Nashak",
      ["id"] = "15012",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.46,
      ["y"] = 0.136,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Rune Broker",
      ["id"] = "233428",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.428,
      ["y"] = 0.68,
    },
    {
      ["category"] = "spirithealer",
      ["name"] = "Spirit Healer",
      ["id"] = "6491",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.442,
      ["y"] = 0.6940000000000001,
    },
    {
      ["category"] = "book",
      ["name"] = "Rise of the Horde",
      ["id"] = "175742",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.596,
      ["y"] = 0.5820000000000001,
    },
    {
      ["category"] = "forge",
      ["name"] = "Forge",
      ["id"] = "1685",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.52,
      ["y"] = 0.408,
    },
    {
      ["category"] = "mailbox",
      ["name"] = "Mailbox",
      ["id"] = "32349",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Durotar",
      ["subLocation"] = "Durotar",
      ["x"] = 0.519,
      ["y"] = 0.42100000000000004,
    },
  }
}
