DB_DUSKWOOD_GENERAL = {
  ["region"] = "Eastern Kingdoms",
  ["mapID"] = 1431,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Gavin Gnarltree",
      ["id"] = "225",
      ["description"] = "Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Duskwood",
      ["subLocation"] = "Duskwood",
      ["x"] = 0.736,
      ["y"] = 0.488,
    },
    {
      ["category"] = "repair",
      ["name"] = "Morg Gnarltree",
      ["id"] = "226",
      ["description"] = "Armorer",
      ["comment"] = "",
      ["mainLocation"] = "Duskwood",
      ["subLocation"] = "Duskwood",
      ["x"] = 0.738,
      ["y"] = 0.486,
    },
    {
      ["category"] = "repair",
      ["name"] = "Avette Fellwood",
      ["id"] = "228",
      ["description"] = "Bowyer",
      ["comment"] = "",
      ["mainLocation"] = "Duskwood",
      ["subLocation"] = "Duskwood",
      ["x"] = 0.732,
      ["y"] = 0.44799999999999995,
    },
    {
      ["category"] = "repair",
      ["name"] = "Quartermaster Falinar",
      ["id"] = "222684",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Duskwood",
      ["subLocation"] = "Duskwood",
      ["x"] = 0.456,
      ["y"] = 0.512,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Innkeeper Trelayne",
      ["id"] = "6790",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Duskwood",
      ["subLocation"] = "Duskwood",
      ["x"] = 0.738,
      ["y"] = 0.444,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Steven Black",
      ["id"] = "10062",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "Duskwood",
      ["subLocation"] = "Duskwood",
      ["x"] = 0.74,
      ["y"] = 0.462,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Felicia Maline",
      ["id"] = "2409",
      ["description"] = "Gryphon Master",
      ["comment"] = "",
      ["mainLocation"] = "Duskwood",
      ["subLocation"] = "Duskwood",
      ["x"] = 0.774,
      ["y"] = 0.444,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Finbus Geargrind",
      ["id"] = "1676",
      ["description"] = "Expert Engineer",
      ["comment"] = "",
      ["mainLocation"] = "Duskwood",
      ["subLocation"] = "Duskwood",
      ["x"] = 0.774,
      ["y"] = 0.486,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Clarise Gnarltree",
      ["id"] = "3136",
      ["description"] = "Expert Blacksmith",
      ["comment"] = "",
      ["mainLocation"] = "Duskwood",
      ["subLocation"] = "Duskwood",
      ["x"] = 0.74,
      ["y"] = 0.484,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Matt Johnson",
      ["id"] = "3137",
      ["description"] = "Mining Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Duskwood",
      ["subLocation"] = "Duskwood",
      ["x"] = 0.74,
      ["y"] = 0.496,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Gavin Gnarltree",
      ["id"] = "225",
      ["description"] = "Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Duskwood",
      ["subLocation"] = "Duskwood",
      ["x"] = 0.736,
      ["y"] = 0.488,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Morg Gnarltree",
      ["id"] = "226",
      ["description"] = "Armorer",
      ["comment"] = "",
      ["mainLocation"] = "Duskwood",
      ["subLocation"] = "Duskwood",
      ["x"] = 0.738,
      ["y"] = 0.486,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Mabel Solaj",
      ["id"] = "227",
      ["description"] = "General Goods Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Duskwood",
      ["subLocation"] = "Duskwood",
      ["x"] = 0.74,
      ["y"] = 0.44799999999999995,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Avette Fellwood",
      ["id"] = "228",
      ["description"] = "Bowyer",
      ["comment"] = "",
      ["mainLocation"] = "Duskwood",
      ["subLocation"] = "Duskwood",
      ["x"] = 0.732,
      ["y"] = 0.44799999999999995,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Barkeep Hann",
      ["id"] = "274",
      ["description"] = "Bartender",
      ["comment"] = "",
      ["mainLocation"] = "Duskwood",
      ["subLocation"] = "Duskwood",
      ["x"] = 0.738,
      ["y"] = 0.442,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Antonio Perelli",
      ["id"] = "844",
      ["description"] = "Traveling Salesman",
      ["comment"] = "",
      ["mainLocation"] = "Duskwood",
      ["subLocation"] = "Duskwood",
      ["x"] = 0.75,
      ["y"] = 0.46399999999999997,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Gunder Thornbush",
      ["id"] = "960",
      ["description"] = "Tradesman",
      ["comment"] = "",
      ["mainLocation"] = "Duskwood",
      ["subLocation"] = "Duskwood",
      ["x"] = 0.738,
      ["y"] = 0.45,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Lohgan Eva",
      ["id"] = "1672",
      ["description"] = "Tailoring Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Duskwood",
      ["subLocation"] = "Duskwood",
      ["x"] = 0.7559999999999999,
      ["y"] = 0.446,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Alyssa Eva",
      ["id"] = "1673",
      ["description"] = "Reagent Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Duskwood",
      ["subLocation"] = "Duskwood",
      ["x"] = 0.76,
      ["y"] = 0.452,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Bliztik",
      ["id"] = "2481",
      ["description"] = "Alchemy Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Duskwood",
      ["subLocation"] = "Duskwood",
      ["x"] = 0.18,
      ["y"] = 0.544,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Danielle Zipstitch",
      ["id"] = "2668",
      ["description"] = "Tailoring Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Duskwood",
      ["subLocation"] = "Duskwood",
      ["x"] = 0.758,
      ["y"] = 0.45399999999999996,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Sheri Zipstitch",
      ["id"] = "2669",
      ["description"] = "Tailoring Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Duskwood",
      ["subLocation"] = "Duskwood",
      ["x"] = 0.7559999999999999,
      ["y"] = 0.45399999999999996,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Herble Baubbletump",
      ["id"] = "3133",
      ["description"] = "Engineering and Mining Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Duskwood",
      ["subLocation"] = "Duskwood",
      ["x"] = 0.778,
      ["y"] = 0.48200000000000004,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kzixx",
      ["id"] = "3134",
      ["description"] = "Rare Goods",
      ["comment"] = "",
      ["mainLocation"] = "Duskwood",
      ["subLocation"] = "Duskwood",
      ["x"] = 0.818,
      ["y"] = 0.198,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Malissa",
      ["id"] = "3135",
      ["description"] = "Poison Supplier",
      ["comment"] = "",
      ["mainLocation"] = "Duskwood",
      ["subLocation"] = "Duskwood",
      ["x"] = 0.794,
      ["y"] = 0.444,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Scott Carevin",
      ["id"] = "3138",
      ["description"] = "Mushroom Seller",
      ["comment"] = "",
      ["mainLocation"] = "Duskwood",
      ["subLocation"] = "Duskwood",
      ["x"] = 0.7559999999999999,
      ["y"] = 0.486,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Innkeeper Trelayne",
      ["id"] = "6790",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Duskwood",
      ["subLocation"] = "Duskwood",
      ["x"] = 0.738,
      ["y"] = 0.444,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Quartermaster Falinar",
      ["id"] = "222684",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Duskwood",
      ["subLocation"] = "Duskwood",
      ["x"] = 0.456,
      ["y"] = 0.512,
    },
    {
      ["category"] = "spirithealer",
      ["name"] = "Spirit Healer",
      ["id"] = "6491",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Duskwood",
      ["subLocation"] = "Duskwood",
      ["x"] = 0.2,
      ["y"] = 0.494,
    },
    {
      ["category"] = "book",
      ["name"] = "Eliza's Tombstone",
      ["id"] = "37",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Duskwood",
      ["subLocation"] = "Duskwood",
      ["x"] = 0.28800000000000003,
      ["y"] = 0.307,
    },
    {
      ["category"] = "book",
      ["name"] = "Mount Hyjal and Illidan's Gift",
      ["id"] = "175729",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Duskwood",
      ["subLocation"] = "Duskwood",
      ["x"] = 0.737,
      ["y"] = 0.446,
    },
    {
      ["category"] = "book",
      ["name"] = "The Founding of Quel'Thalas",
      ["id"] = "175733",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Duskwood",
      ["subLocation"] = "Duskwood",
      ["x"] = 0.737,
      ["y"] = 0.451,
    },
    {
      ["category"] = "book",
      ["name"] = "Kil'jaeden and the Shadow Pact",
      ["id"] = "175741",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Duskwood",
      ["subLocation"] = "Duskwood",
      ["x"] = 0.741,
      ["y"] = 0.45299999999999996,
    },
    {
      ["category"] = "book",
      ["name"] = "The Alliance of Lordaeron",
      ["id"] = "175746",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Duskwood",
      ["subLocation"] = "Duskwood",
      ["x"] = 0.721,
      ["y"] = 0.479,
    },
    {
      ["category"] = "book",
      ["name"] = "The Birth of the Lich King",
      ["id"] = "175748",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Duskwood",
      ["subLocation"] = "Duskwood",
      ["x"] = 0.72,
      ["y"] = 0.46399999999999997,
    },
    {
      ["category"] = "book",
      ["name"] = "Carved Stone",
      ["id"] = "410034",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Duskwood",
      ["subLocation"] = "Duskwood",
      ["x"] = 0.495,
      ["y"] = 0.34,
    },
    {
      ["category"] = "mailbox",
      ["name"] = "Mailbox",
      ["id"] = "32349",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Duskwood",
      ["subLocation"] = "Duskwood",
      ["x"] = 0.738,
      ["y"] = 0.462,
    },
  }
}
