DB_DUSTWALLOW_MARSH_GENERAL = {
  ["region"] = "Kalimdor",
  ["mapID"] = 1445,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Krak",
      ["id"] = "4883",
      ["description"] = "Armorer",
      ["comment"] = "",
      ["mainLocation"] = "Dustwallow Marsh",
      ["subLocation"] = "Dustwallow Marsh",
      ["x"] = 0.364,
      ["y"] = 0.308,
    },
    {
      ["category"] = "repair",
      ["name"] = "Zulrg",
      ["id"] = "4884",
      ["description"] = "Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Dustwallow Marsh",
      ["subLocation"] = "Dustwallow Marsh",
      ["x"] = 0.36200000000000004,
      ["y"] = 0.316,
    },
    {
      ["category"] = "repair",
      ["name"] = "Hans Weston",
      ["id"] = "4886",
      ["description"] = "Armorer & Shieldsmith",
      ["comment"] = "",
      ["mainLocation"] = "Dustwallow Marsh",
      ["subLocation"] = "Dustwallow Marsh",
      ["x"] = 0.6459999999999999,
      ["y"] = 0.504,
    },
    {
      ["category"] = "repair",
      ["name"] = "Marie Holdston",
      ["id"] = "4888",
      ["description"] = "Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Dustwallow Marsh",
      ["subLocation"] = "Dustwallow Marsh",
      ["x"] = 0.6459999999999999,
      ["y"] = 0.5,
    },
    {
      ["category"] = "repair",
      ["name"] = "Torq Ironblast",
      ["id"] = "4889",
      ["description"] = "Gunsmith",
      ["comment"] = "",
      ["mainLocation"] = "Dustwallow Marsh",
      ["subLocation"] = "Dustwallow Marsh",
      ["x"] = 0.674,
      ["y"] = 0.48,
    },
    {
      ["category"] = "repair",
      ["name"] = "Piter Verance",
      ["id"] = "4890",
      ["description"] = "Weaponsmith & Armorer",
      ["comment"] = "",
      ["mainLocation"] = "Dustwallow Marsh",
      ["subLocation"] = "Dustwallow Marsh",
      ["x"] = 0.674,
      ["y"] = 0.478,
    },
    {
      ["category"] = "repair",
      ["name"] = "Jensen Farran",
      ["id"] = "4892",
      ["description"] = "Bowyer",
      ["comment"] = "",
      ["mainLocation"] = "Dustwallow Marsh",
      ["subLocation"] = "Dustwallow Marsh",
      ["x"] = 0.6779999999999999,
      ["y"] = 0.498,
    },
    {
      ["category"] = "repair",
      ["name"] = "Zanara",
      ["id"] = "9552",
      ["description"] = "Bowyer",
      ["comment"] = "",
      ["mainLocation"] = "Dustwallow Marsh",
      ["subLocation"] = "Dustwallow Marsh",
      ["x"] = 0.354,
      ["y"] = 0.302,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Innkeeper Janene",
      ["id"] = "6272",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Dustwallow Marsh",
      ["subLocation"] = "Dustwallow Marsh",
      ["x"] = 0.6659999999999999,
      ["y"] = 0.452,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Michael",
      ["id"] = "10047",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "Dustwallow Marsh",
      ["subLocation"] = "Dustwallow Marsh",
      ["x"] = 0.66,
      ["y"] = 0.45399999999999996,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Baldruc",
      ["id"] = "4321",
      ["description"] = "Gryphon Master",
      ["comment"] = "",
      ["mainLocation"] = "Dustwallow Marsh",
      ["subLocation"] = "Dustwallow Marsh",
      ["x"] = 0.674,
      ["y"] = 0.512,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Shardi",
      ["id"] = "11899",
      ["description"] = "Wind Rider Master",
      ["comment"] = "",
      ["mainLocation"] = "Dustwallow Marsh",
      ["subLocation"] = "Dustwallow Marsh",
      ["x"] = 0.35600000000000004,
      ["y"] = 0.318,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Brant Jasperbloom",
      ["id"] = "4898",
      ["description"] = "Herbalist",
      ["comment"] = "",
      ["mainLocation"] = "Dustwallow Marsh",
      ["subLocation"] = "Dustwallow Marsh",
      ["x"] = 0.64,
      ["y"] = 0.47600000000000003,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Alchemist Narett",
      ["id"] = "4900",
      ["description"] = "Expert Alchemist",
      ["comment"] = "",
      ["mainLocation"] = "Dustwallow Marsh",
      ["subLocation"] = "Dustwallow Marsh",
      ["x"] = 0.64,
      ["y"] = 0.47600000000000003,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Brother Karman",
      ["id"] = "8140",
      ["description"] = "Paladin Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dustwallow Marsh",
      ["subLocation"] = "Dustwallow Marsh",
      ["x"] = 0.674,
      ["y"] = 0.474,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Captain Evencane",
      ["id"] = "8141",
      ["description"] = "Warrior Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Dustwallow Marsh",
      ["subLocation"] = "Dustwallow Marsh",
      ["x"] = 0.6779999999999999,
      ["y"] = 0.484,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Timothy Worthington",
      ["id"] = "11052",
      ["description"] = "Master Tailor",
      ["comment"] = "",
      ["mainLocation"] = "Dustwallow Marsh",
      ["subLocation"] = "Dustwallow Marsh",
      ["x"] = 0.662,
      ["y"] = 0.516,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Ogg'marr",
      ["id"] = "4879",
      ["description"] = "Butcher",
      ["comment"] = "",
      ["mainLocation"] = "Dustwallow Marsh",
      ["subLocation"] = "Dustwallow Marsh",
      ["x"] = 0.366,
      ["y"] = 0.31,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Gregor MacVince",
      ["id"] = "4885",
      ["description"] = "Horse Breeder",
      ["comment"] = "",
      ["mainLocation"] = "Dustwallow Marsh",
      ["subLocation"] = "Dustwallow Marsh",
      ["x"] = 0.652,
      ["y"] = 0.514,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Dwane Wertle",
      ["id"] = "4891",
      ["description"] = "Chef",
      ["comment"] = "",
      ["mainLocation"] = "Dustwallow Marsh",
      ["subLocation"] = "Dustwallow Marsh",
      ["x"] = 0.682,
      ["y"] = 0.474,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Bartender Lillian",
      ["id"] = "4893",
      ["description"] = "Bartender",
      ["comment"] = "",
      ["mainLocation"] = "Dustwallow Marsh",
      ["subLocation"] = "Dustwallow Marsh",
      ["x"] = 0.6659999999999999,
      ["y"] = 0.452,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Craig Nollward",
      ["id"] = "4894",
      ["description"] = "Cook",
      ["comment"] = "",
      ["mainLocation"] = "Dustwallow Marsh",
      ["subLocation"] = "Dustwallow Marsh",
      ["x"] = 0.6679999999999999,
      ["y"] = 0.452,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Charity Mipsy",
      ["id"] = "4896",
      ["description"] = "General Goods",
      ["comment"] = "",
      ["mainLocation"] = "Dustwallow Marsh",
      ["subLocation"] = "Dustwallow Marsh",
      ["x"] = 0.674,
      ["y"] = 0.516,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Helenia Olden",
      ["id"] = "4897",
      ["description"] = "Trade Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Dustwallow Marsh",
      ["subLocation"] = "Dustwallow Marsh",
      ["x"] = 0.664,
      ["y"] = 0.514,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Uma Bartulm",
      ["id"] = "4899",
      ["description"] = "Herbalism & Alchemy Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Dustwallow Marsh",
      ["subLocation"] = "Dustwallow Marsh",
      ["x"] = 0.64,
      ["y"] = 0.47600000000000003,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Ghok'kah",
      ["id"] = "6567",
      ["description"] = "Tailoring Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Dustwallow Marsh",
      ["subLocation"] = "Dustwallow Marsh",
      ["x"] = 0.35200000000000004,
      ["y"] = 0.308,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Nat Pagle",
      ["id"] = "12919",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dustwallow Marsh",
      ["subLocation"] = "Dustwallow Marsh",
      ["x"] = 0.584,
      ["y"] = 0.6,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Balai Lok'Wein",
      ["id"] = "13476",
      ["description"] = "Potions, Scrolls and Reagents",
      ["comment"] = "",
      ["mainLocation"] = "Dustwallow Marsh",
      ["subLocation"] = "Dustwallow Marsh",
      ["x"] = 0.364,
      ["y"] = 0.304,
    },
    {
      ["category"] = "spirithealer",
      ["name"] = "Spirit Healer",
      ["id"] = "6491",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dustwallow Marsh",
      ["subLocation"] = "Dustwallow Marsh",
      ["x"] = 0.396,
      ["y"] = 0.308,
    },
    {
      ["category"] = "mailbox",
      ["name"] = "Mailbox",
      ["id"] = "32349",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Dustwallow Marsh",
      ["subLocation"] = "Dustwallow Marsh",
      ["x"] = 0.659,
      ["y"] = 0.45299999999999996,
    },
  }
}
