DB_EASTERN_PLAGUELANDS_GENERAL = {
  ["region"] = "Eastern Kingdoms",
  ["mapID"] = 1423,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Craftsman Wilhelm",
      ["id"] = "16376",
      ["description"] = "Brotherhood of the Light",
      ["comment"] = "",
      ["mainLocation"] = "Eastern Plaguelands",
      ["subLocation"] = "Eastern Plaguelands",
      ["x"] = 0.81,
      ["y"] = 0.596,
    },
    {
      ["category"] = "repair",
      ["name"] = "G00 DV-1B3 Generator",
      ["id"] = "235164",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Eastern Plaguelands",
      ["subLocation"] = "Eastern Plaguelands",
      ["x"] = 0.48,
      ["y"] = 0.22,
    },
    {
      ["category"] = "repair",
      ["name"] = "Bryon Steelblade",
      ["id"] = "240248",
      ["description"] = "Scarlet Quartermaster",
      ["comment"] = "",
      ["mainLocation"] = "Eastern Plaguelands",
      ["subLocation"] = "Eastern Plaguelands",
      ["x"] = 0.9840000000000001,
      ["y"] = 0.84,
    },
    {
      ["category"] = "repair",
      ["name"] = "Anvil",
      ["id"] = "242954",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Eastern Plaguelands",
      ["subLocation"] = "Eastern Plaguelands",
      ["x"] = 0.9940000000000001,
      ["y"] = 0.778,
    },
    {
      ["category"] = "banker",
      ["name"] = "Scarlet Stash",
      ["id"] = "241862",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Eastern Plaguelands",
      ["subLocation"] = "Eastern Plaguelands",
      ["x"] = 0.986,
      ["y"] = 0.8240000000000001,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Jessica Chambers",
      ["id"] = "16256",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Eastern Plaguelands",
      ["subLocation"] = "Eastern Plaguelands",
      ["x"] = 0.816,
      ["y"] = 0.58,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Khaelyn Steelwing",
      ["id"] = "12617",
      ["description"] = "Gryphon Master",
      ["comment"] = "",
      ["mainLocation"] = "Eastern Plaguelands",
      ["subLocation"] = "Eastern Plaguelands",
      ["x"] = 0.816,
      ["y"] = 0.5920000000000001,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Georgia",
      ["id"] = "12636",
      ["description"] = "Bat Handler",
      ["comment"] = "",
      ["mainLocation"] = "Eastern Plaguelands",
      ["subLocation"] = "Eastern Plaguelands",
      ["x"] = 0.802,
      ["y"] = 0.57,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Caretaker Alen",
      ["id"] = "11038",
      ["description"] = "The Argent Dawn",
      ["comment"] = "",
      ["mainLocation"] = "Eastern Plaguelands",
      ["subLocation"] = "Eastern Plaguelands",
      ["x"] = 0.794,
      ["y"] = 0.638,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Quartermaster Miranda Breechlock",
      ["id"] = "11536",
      ["description"] = "The Argent Dawn",
      ["comment"] = "",
      ["mainLocation"] = "Eastern Plaguelands",
      ["subLocation"] = "Eastern Plaguelands",
      ["x"] = 0.816,
      ["y"] = 0.6,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Augustus the Touched",
      ["id"] = "12384",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Eastern Plaguelands",
      ["subLocation"] = "Eastern Plaguelands",
      ["x"] = 0.14400000000000002,
      ["y"] = 0.336,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jase Farlane",
      ["id"] = "12941",
      ["description"] = "Trade Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Eastern Plaguelands",
      ["subLocation"] = "Eastern Plaguelands",
      ["x"] = 0.804,
      ["y"] = 0.5760000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jessica Chambers",
      ["id"] = "16256",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Eastern Plaguelands",
      ["subLocation"] = "Eastern Plaguelands",
      ["x"] = 0.816,
      ["y"] = 0.58,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Craftsman Wilhelm",
      ["id"] = "16376",
      ["description"] = "Brotherhood of the Light",
      ["comment"] = "",
      ["mainLocation"] = "Eastern Plaguelands",
      ["subLocation"] = "Eastern Plaguelands",
      ["x"] = 0.81,
      ["y"] = 0.596,
    },
    {
      ["category"] = "vendor",
      ["name"] = "G00 DV-1B3 Generator",
      ["id"] = "235164",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Eastern Plaguelands",
      ["subLocation"] = "Eastern Plaguelands",
      ["x"] = 0.48,
      ["y"] = 0.22,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Brother Luctus",
      ["id"] = "238376",
      ["description"] = "Soul Seer",
      ["comment"] = "",
      ["mainLocation"] = "Eastern Plaguelands",
      ["subLocation"] = "Eastern Plaguelands",
      ["x"] = 0.804,
      ["y"] = 0.654,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Carrie Hearthfire",
      ["id"] = "240604",
      ["description"] = "Head Chef",
      ["comment"] = "",
      ["mainLocation"] = "Eastern Plaguelands",
      ["subLocation"] = "Eastern Plaguelands",
      ["x"] = 0.9520000000000001,
      ["y"] = 0.784,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Devon Woods",
      ["id"] = "240607",
      ["description"] = "Security",
      ["comment"] = "",
      ["mainLocation"] = "Eastern Plaguelands",
      ["subLocation"] = "Eastern Plaguelands",
      ["x"] = 0.9520000000000001,
      ["y"] = 0.802,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Taylor Stitchings",
      ["id"] = "240631",
      ["description"] = "Tailoring Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Eastern Plaguelands",
      ["subLocation"] = "Eastern Plaguelands",
      ["x"] = 0.946,
      ["y"] = 0.8340000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Tanya Hyde",
      ["id"] = "240632",
      ["description"] = "Leatherworking Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Eastern Plaguelands",
      ["subLocation"] = "Eastern Plaguelands",
      ["x"] = 0.9420000000000001,
      ["y"] = 0.932,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Smith",
      ["id"] = "240633",
      ["description"] = "Blacksmithing Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Eastern Plaguelands",
      ["subLocation"] = "Eastern Plaguelands",
      ["x"] = 0.986,
      ["y"] = 0.77,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Johnny",
      ["id"] = "241019",
      ["description"] = "Fresh Apples",
      ["comment"] = "",
      ["mainLocation"] = "Eastern Plaguelands",
      ["subLocation"] = "Eastern Plaguelands",
      ["x"] = 0.948,
      ["y"] = 0.912,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Gerald",
      ["id"] = "241663",
      ["description"] = "Bartender",
      ["comment"] = "",
      ["mainLocation"] = "Eastern Plaguelands",
      ["subLocation"] = "Eastern Plaguelands",
      ["x"] = 0.9520000000000001,
      ["y"] = 0.7879999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Malorie",
      ["id"] = "241664",
      ["description"] = "Food & Drink",
      ["comment"] = "",
      ["mainLocation"] = "Eastern Plaguelands",
      ["subLocation"] = "Eastern Plaguelands",
      ["x"] = 0.9520000000000001,
      ["y"] = 0.7879999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Abatha Rainwater",
      ["id"] = "242183",
      ["description"] = "Florist",
      ["comment"] = "",
      ["mainLocation"] = "Eastern Plaguelands",
      ["subLocation"] = "Eastern Plaguelands",
      ["x"] = 0.934,
      ["y"] = 0.794,
    },
    {
      ["category"] = "spirithealer",
      ["name"] = "Spirit Healer",
      ["id"] = "6491",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Eastern Plaguelands",
      ["subLocation"] = "Eastern Plaguelands",
      ["x"] = 0.382,
      ["y"] = 0.7040000000000001,
    },
    {
      ["category"] = "mailbox",
      ["name"] = "Mailbox",
      ["id"] = "32349",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Eastern Plaguelands",
      ["subLocation"] = "Eastern Plaguelands",
      ["x"] = 0.809,
      ["y"] = 0.584,
    },
  }
}
