DB_ELWYNN_FOREST_GENERAL = {
  ["region"] = "Eastern Kingdoms <Alliance>",
  ["mapID"] = 1429,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Corina Steele",
      ["id"] = "54",
      ["description"] = "Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.41600000000000004,
      ["y"] = 0.6579999999999999,
    },
    {
      ["category"] = "repair",
      ["name"] = "Kurran Steele",
      ["id"] = "74",
      ["description"] = "Cloth & Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.414,
      ["y"] = 0.6559999999999999,
    },
    {
      ["category"] = "repair",
      ["name"] = "Janos Hammerknuckle",
      ["id"] = "78",
      ["description"] = "Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.47200000000000003,
      ["y"] = 0.418,
    },
    {
      ["category"] = "repair",
      ["name"] = "Dermot Johns",
      ["id"] = "190",
      ["description"] = "Cloth & Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.47600000000000003,
      ["y"] = 0.414,
    },
    {
      ["category"] = "repair",
      ["name"] = "Veldan Lightfoot",
      ["id"] = "896",
      ["description"] = "Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.252,
      ["y"] = 0.738,
    },
    {
      ["category"] = "repair",
      ["name"] = "Morley Eberlein",
      ["id"] = "959",
      ["description"] = "Clothier",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.6459999999999999,
      ["y"] = 0.696,
    },
    {
      ["category"] = "repair",
      ["name"] = "Rallic Finn",
      ["id"] = "1198",
      ["description"] = "Bowyer",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.8320000000000001,
      ["y"] = 0.66,
    },
    {
      ["category"] = "repair",
      ["name"] = "Godric Rothgar",
      ["id"] = "1213",
      ["description"] = "Armorer & Shieldcrafter",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.47600000000000003,
      ["y"] = 0.414,
    },
    {
      ["category"] = "repair",
      ["name"] = "Quartermaster Hudson",
      ["id"] = "1249",
      ["description"] = "Armorer & Shieldcrafter",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.252,
      ["y"] = 0.74,
    },
    {
      ["category"] = "repair",
      ["name"] = "Quartermaster Hicks",
      ["id"] = "1645",
      ["description"] = "Master Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.252,
      ["y"] = 0.738,
    },
    {
      ["category"] = "repair",
      ["name"] = "Andrew Krighton",
      ["id"] = "2046",
      ["description"] = "Armorer & Shieldcrafter",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.41600000000000004,
      ["y"] = 0.6559999999999999,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Innkeeper Farley",
      ["id"] = "295",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.43799999999999994,
      ["y"] = 0.6579999999999999,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Erma",
      ["id"] = "6749",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.428,
      ["y"] = 0.6579999999999999,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Khelden Bremen",
      ["id"] = "198",
      ["description"] = "Mage Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.496,
      ["y"] = 0.39399999999999996,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Zaldimar Wefhellt",
      ["id"] = "328",
      ["description"] = "Mage Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.43200000000000005,
      ["y"] = 0.662,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Priestess Anetta",
      ["id"] = "375",
      ["description"] = "Priest Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.498,
      ["y"] = 0.396,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Priestess Josetta",
      ["id"] = "377",
      ["description"] = "Priest Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.43200000000000005,
      ["y"] = 0.6559999999999999,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Drusilla La Salle",
      ["id"] = "459",
      ["description"] = "Warlock Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.498,
      ["y"] = 0.426,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Smith Argus",
      ["id"] = "514",
      ["description"] = "Journeyman Blacksmith",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.41600000000000004,
      ["y"] = 0.6559999999999999,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Maximillian Crowe",
      ["id"] = "906",
      ["description"] = "Warlock Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.444,
      ["y"] = 0.66,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Llane Beshere",
      ["id"] = "911",
      ["description"] = "Warrior Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.502,
      ["y"] = 0.42200000000000004,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Lyria Du Lac",
      ["id"] = "913",
      ["description"] = "Warrior Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.41,
      ["y"] = 0.6579999999999999,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Jorik Kerridan",
      ["id"] = "915",
      ["description"] = "Rogue Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.504,
      ["y"] = 0.39799999999999996,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Keryn Sylvius",
      ["id"] = "917",
      ["description"] = "Rogue Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.43799999999999994,
      ["y"] = 0.6579999999999999,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Brother Sammuel",
      ["id"] = "925",
      ["description"] = "Paladin Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.504,
      ["y"] = 0.42,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Brother Wilhelm",
      ["id"] = "927",
      ["description"] = "Paladin Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.41,
      ["y"] = 0.66,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Eldrin",
      ["id"] = "1103",
      ["description"] = "Journeyman Tailor",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.792,
      ["y"] = 0.69,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Alchemist Mallory",
      ["id"] = "1215",
      ["description"] = "Journeyman Alchemist",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.39799999999999996,
      ["y"] = 0.484,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Herbalist Pomeroy",
      ["id"] = "1218",
      ["description"] = "Herbalism Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.39799999999999996,
      ["y"] = 0.484,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Tomas",
      ["id"] = "1430",
      ["description"] = "Cook",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.442,
      ["y"] = 0.66,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Adele Fielder",
      ["id"] = "1632",
      ["description"] = "Journeyman Leatherworker",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.46399999999999997,
      ["y"] = 0.622,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Lee Brown",
      ["id"] = "1651",
      ["description"] = "Fisherman",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.474,
      ["y"] = 0.622,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Michelle Belle",
      ["id"] = "2329",
      ["description"] = "Physician",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.434,
      ["y"] = 0.6559999999999999,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Randal Hunter",
      ["id"] = "4732",
      ["description"] = "Horse Riding Instructor",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.8420000000000001,
      ["y"] = 0.65,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Helene Peltskinner",
      ["id"] = "6306",
      ["description"] = "Skinner",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.462,
      ["y"] = 0.622,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Kitta Firewind",
      ["id"] = "11072",
      ["description"] = "Artisan Enchanter",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.648,
      ["y"] = 0.706,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Corina Steele",
      ["id"] = "54",
      ["description"] = "Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.41600000000000004,
      ["y"] = 0.6579999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Tharynn Bouden",
      ["id"] = "66",
      ["description"] = "Trade Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.418,
      ["y"] = 0.67,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kurran Steele",
      ["id"] = "74",
      ["description"] = "Cloth & Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.414,
      ["y"] = 0.6559999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Janos Hammerknuckle",
      ["id"] = "78",
      ["description"] = "Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.47200000000000003,
      ["y"] = 0.418,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Brog Hamfist",
      ["id"] = "151",
      ["description"] = "General Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.43799999999999994,
      ["y"] = 0.66,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Brother Danil",
      ["id"] = "152",
      ["description"] = "General Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.474,
      ["y"] = 0.41600000000000004,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Dermot Johns",
      ["id"] = "190",
      ["description"] = "Cloth & Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.47600000000000003,
      ["y"] = 0.414,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Joshua Maclure",
      ["id"] = "258",
      ["description"] = "Vintner",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.424,
      ["y"] = 0.892,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Innkeeper Farley",
      ["id"] = "295",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.43799999999999994,
      ["y"] = 0.6579999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Katie Hunter",
      ["id"] = "384",
      ["description"] = "Horse Breeder",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.84,
      ["y"] = 0.654,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Barkeep Dobbins",
      ["id"] = "465",
      ["description"] = "Bartender",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.43799999999999994,
      ["y"] = 0.6579999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Antonio Perelli",
      ["id"] = "844",
      ["description"] = "Traveling Salesman",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.426,
      ["y"] = 0.664,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Homer Stonefield",
      ["id"] = "894",
      ["description"] = "Fruit Seller",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.336,
      ["y"] = 0.83,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Veldan Lightfoot",
      ["id"] = "896",
      ["description"] = "Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.252,
      ["y"] = 0.738,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Sergeant De Vries",
      ["id"] = "955",
      ["description"] = "Morale Officer",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.24,
      ["y"] = 0.73,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Dawn Brightstar",
      ["id"] = "958",
      ["description"] = "Arcane Goods",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.648,
      ["y"] = 0.6920000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Morley Eberlein",
      ["id"] = "959",
      ["description"] = "Clothier",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.6459999999999999,
      ["y"] = 0.696,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Rallic Finn",
      ["id"] = "1198",
      ["description"] = "Bowyer",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.8320000000000001,
      ["y"] = 0.66,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Godric Rothgar",
      ["id"] = "1213",
      ["description"] = "Armorer & Shieldcrafter",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.47600000000000003,
      ["y"] = 0.414,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Quartermaster Hudson",
      ["id"] = "1249",
      ["description"] = "Armorer & Shieldcrafter",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.252,
      ["y"] = 0.74,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Drake Lindgren",
      ["id"] = "1250",
      ["description"] = "General & Trade Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.8320000000000001,
      ["y"] = 0.6659999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Quartermaster Hicks",
      ["id"] = "1645",
      ["description"] = "Master Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.252,
      ["y"] = 0.738,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Terry Palin",
      ["id"] = "1650",
      ["description"] = "Lumberjack",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.828,
      ["y"] = 0.634,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Andrew Krighton",
      ["id"] = "2046",
      ["description"] = "Armorer & Shieldcrafter",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.41600000000000004,
      ["y"] = 0.6559999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Toddrick",
      ["id"] = "3935",
      ["description"] = "Butcher",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.442,
      ["y"] = 0.66,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kira Songshine",
      ["id"] = "3937",
      ["description"] = "Traveling Baker",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.332,
      ["y"] = 0.516,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Donni Anthania",
      ["id"] = "6367",
      ["description"] = "Crazy Cat Lady",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.442,
      ["y"] = 0.532,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Dane Winslow",
      ["id"] = "6373",
      ["description"] = "Demon Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.5,
      ["y"] = 0.426,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Cylina Darkheart",
      ["id"] = "6374",
      ["description"] = "Demon Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.444,
      ["y"] = 0.66,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Sylannia",
      ["id"] = "14844",
      ["description"] = "Darkmoon Faire Drink Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.42,
      ["y"] = 0.7,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Stamp Thunderhorn",
      ["id"] = "14845",
      ["description"] = "Darkmoon Faire Food Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.42,
      ["y"] = 0.7,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Lhara",
      ["id"] = "14846",
      ["description"] = "Darkmoon Faire Exotic Goods",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.41200000000000003,
      ["y"] = 0.698,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Professor Thaddeus Paleo",
      ["id"] = "14847",
      ["description"] = "Darkmoon Faire Cards & Exotic Goods",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.41200000000000003,
      ["y"] = 0.698,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Flik",
      ["id"] = "14860",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.424,
      ["y"] = 0.6579999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Rune Broker",
      ["id"] = "233335",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.48,
      ["y"] = 0.414,
    },
    {
      ["category"] = "spirithealer",
      ["name"] = "Spirit Healer",
      ["id"] = "6491",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.39399999999999996,
      ["y"] = 0.604,
    },
    {
      ["category"] = "book",
      ["name"] = "Icecrown and the Frozen Throne",
      ["id"] = "175749",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.43799999999999994,
      ["y"] = 0.6579999999999999,
    },
    {
      ["category"] = "book",
      ["name"] = "Lethargy of the Orcs",
      ["id"] = "175751",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.853,
      ["y"] = 0.6970000000000001,
    },
    {
      ["category"] = "book",
      ["name"] = "Rise of the Blood Elves",
      ["id"] = "175760",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.6459999999999999,
      ["y"] = 0.695,
    },
    {
      ["category"] = "book",
      ["name"] = "Civil War in the Plaguelands",
      ["id"] = "175761",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.495,
      ["y"] = 0.396,
    },
    {
      ["category"] = "forge",
      ["name"] = "Forge",
      ["id"] = "1685",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.414,
      ["y"] = 0.6559999999999999,
    },
    {
      ["category"] = "mailbox",
      ["name"] = "Mailbox",
      ["id"] = "32349",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Elwynn Forest",
      ["subLocation"] = "Elwynn Forest",
      ["x"] = 0.429,
      ["y"] = 0.654,
    },
  }
}
