DB_FELWOOD_GENERAL = {
  ["region"] = "Kalimdor",
  ["mapID"] = 1448,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Altsoba Ragetotem",
      ["id"] = "10379",
      ["description"] = "Weapon Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Felwood",
      ["subLocation"] = "Felwood",
      ["x"] = 0.348,
      ["y"] = 0.53,
    },
    {
      ["category"] = "repair",
      ["name"] = "Mylini Frostmoon",
      ["id"] = "15315",
      ["description"] = "Weapon Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Felwood",
      ["subLocation"] = "Felwood",
      ["x"] = 0.624,
      ["y"] = 0.258,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Brakkar",
      ["id"] = "11900",
      ["description"] = "Wind Rider Master",
      ["comment"] = "",
      ["mainLocation"] = "Felwood",
      ["subLocation"] = "Felwood",
      ["x"] = 0.344,
      ["y"] = 0.5379999999999999,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Mishellena",
      ["id"] = "12578",
      ["description"] = "Hippogryph Master",
      ["comment"] = "",
      ["mainLocation"] = "Felwood",
      ["subLocation"] = "Felwood",
      ["x"] = 0.624,
      ["y"] = 0.242,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Nalesette Wildbringer",
      ["id"] = "543",
      ["description"] = "Pet Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Felwood",
      ["subLocation"] = "Felwood",
      ["x"] = 0.622,
      ["y"] = 0.242,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Kaerbrus",
      ["id"] = "5501",
      ["description"] = "Hunter Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Felwood",
      ["subLocation"] = "Felwood",
      ["x"] = 0.618,
      ["y"] = 0.23600000000000002,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Golhine the Hooded",
      ["id"] = "9465",
      ["description"] = "Druid Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Felwood",
      ["subLocation"] = "Felwood",
      ["x"] = 0.62,
      ["y"] = 0.244,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Meilosh",
      ["id"] = "11557",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Felwood",
      ["subLocation"] = "Felwood",
      ["x"] = 0.6559999999999999,
      ["y"] = 0.027999999999999997,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Malygen",
      ["id"] = "2803",
      ["description"] = "General Goods",
      ["comment"] = "",
      ["mainLocation"] = "Felwood",
      ["subLocation"] = "Felwood",
      ["x"] = 0.622,
      ["y"] = 0.256,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Bale",
      ["id"] = "2806",
      ["description"] = "General Goods",
      ["comment"] = "",
      ["mainLocation"] = "Felwood",
      ["subLocation"] = "Felwood",
      ["x"] = 0.348,
      ["y"] = 0.532,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Altsoba Ragetotem",
      ["id"] = "10379",
      ["description"] = "Weapon Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Felwood",
      ["subLocation"] = "Felwood",
      ["x"] = 0.348,
      ["y"] = 0.53,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Gorn One Eye",
      ["id"] = "11555",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Felwood",
      ["subLocation"] = "Felwood",
      ["x"] = 0.652,
      ["y"] = 0.026000000000000002,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Meilosh",
      ["id"] = "11557",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Felwood",
      ["subLocation"] = "Felwood",
      ["x"] = 0.6559999999999999,
      ["y"] = 0.027999999999999997,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Ur'dan",
      ["id"] = "14522",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Felwood",
      ["subLocation"] = "Felwood",
      ["x"] = 0.36200000000000004,
      ["y"] = 0.444,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Mylini Frostmoon",
      ["id"] = "15315",
      ["description"] = "Weapon Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Felwood",
      ["subLocation"] = "Felwood",
      ["x"] = 0.624,
      ["y"] = 0.258,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Shadowtooth Emissary",
      ["id"] = "222408",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Felwood",
      ["subLocation"] = "Felwood",
      ["x"] = 0.514,
      ["y"] = 0.82,
    },
    {
      ["category"] = "spirithealer",
      ["name"] = "Spirit Healer",
      ["id"] = "6491",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Felwood",
      ["subLocation"] = "Felwood",
      ["x"] = 0.494,
      ["y"] = 0.306,
    },
  }
}
