DB_FERALAS_GENERAL = {
  ["region"] = "Kalimdor",
  ["mapID"] = 1444,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Rendow",
      ["id"] = "1695",
      ["description"] = "Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.894,
      ["y"] = 0.45799999999999996,
    },
    {
      ["category"] = "repair",
      ["name"] = "Pratt McGrubben",
      ["id"] = "7852",
      ["description"] = "Leatherworking Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.306,
      ["y"] = 0.426,
    },
    {
      ["category"] = "repair",
      ["name"] = "Worb Strongstitch",
      ["id"] = "8159",
      ["description"] = "Light Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.746,
      ["y"] = 0.426,
    },
    {
      ["category"] = "repair",
      ["name"] = "Cawind Trueaim",
      ["id"] = "9548",
      ["description"] = "Gunsmith & Bowyer",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.748,
      ["y"] = 0.456,
    },
    {
      ["category"] = "repair",
      ["name"] = "Dulciea Frostmoon",
      ["id"] = "10293",
      ["description"] = "Cloth Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.308,
      ["y"] = 0.43200000000000005,
    },
    {
      ["category"] = "repair",
      ["name"] = "Quartermaster Valdane",
      ["id"] = "222687",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.484,
      ["y"] = 0.124,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Innkeeper Shyria",
      ["id"] = "7736",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.31,
      ["y"] = 0.434,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Innkeeper Greul",
      ["id"] = "7737",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.748,
      ["y"] = 0.45,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Shyrka Wolfrunner",
      ["id"] = "9986",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.7440000000000001,
      ["y"] = 0.43200000000000005,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Antarius",
      ["id"] = "10059",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.314,
      ["y"] = 0.43200000000000005,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Thyssiana",
      ["id"] = "4319",
      ["description"] = "Hippogryph Master",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.894,
      ["y"] = 0.45799999999999996,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Fyldren Moonfeather",
      ["id"] = "8019",
      ["description"] = "Hippogryph Master",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.302,
      ["y"] = 0.43200000000000005,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Shyn",
      ["id"] = "8020",
      ["description"] = "Wind Rider Master",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.754,
      ["y"] = 0.442,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Caryssia Moonhunter",
      ["id"] = "7870",
      ["description"] = "Tribal Leatherworking Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.894,
      ["y"] = 0.46399999999999997,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Brannock",
      ["id"] = "7946",
      ["description"] = "Fisherman",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.322,
      ["y"] = 0.41600000000000004,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Kylanna Windwhisper",
      ["id"] = "7948",
      ["description"] = "Master Alchemist",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.326,
      ["y"] = 0.43799999999999994,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Xylinnia Starshine",
      ["id"] = "7949",
      ["description"] = "Expert Enchanter",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.316,
      ["y"] = 0.442,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Jannos Lighthoof",
      ["id"] = "8142",
      ["description"] = "Druid Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.76,
      ["y"] = 0.42200000000000004,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Kulleg Stonehorn",
      ["id"] = "8144",
      ["description"] = "Skinning Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.7440000000000001,
      ["y"] = 0.43,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Ruw",
      ["id"] = "8146",
      ["description"] = "Herbalism Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.76,
      ["y"] = 0.434,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Hahrana Ironhide",
      ["id"] = "11098",
      ["description"] = "Master Leatherworker",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.7440000000000001,
      ["y"] = 0.43,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Rendow",
      ["id"] = "1695",
      ["description"] = "Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.894,
      ["y"] = 0.45799999999999996,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Tarhus",
      ["id"] = "3500",
      ["description"] = "Reagent Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.746,
      ["y"] = 0.44799999999999995,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jadenvis Seawatcher",
      ["id"] = "3700",
      ["description"] = "Reagent Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.308,
      ["y"] = 0.42,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Brienna Starglow",
      ["id"] = "6576",
      ["description"] = "Tailoring Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.89,
      ["y"] = 0.45799999999999996,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Innkeeper Shyria",
      ["id"] = "7736",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.31,
      ["y"] = 0.434,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Innkeeper Greul",
      ["id"] = "7737",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.748,
      ["y"] = 0.45,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kalin Windflight",
      ["id"] = "7772",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.49200000000000005,
      ["y"] = 0.198,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Gregan Brewspewer",
      ["id"] = "7775",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.45,
      ["y"] = 0.254,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Pratt McGrubben",
      ["id"] = "7852",
      ["description"] = "Leatherworking Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.306,
      ["y"] = 0.426,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jangdor Swiftstrider",
      ["id"] = "7854",
      ["description"] = "Leatherworking Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.7440000000000001,
      ["y"] = 0.428,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Quintis Jonespyre",
      ["id"] = "7879",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.324,
      ["y"] = 0.43799999999999994,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Mardrack Greenwell",
      ["id"] = "7941",
      ["description"] = "Food & Drink",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.31,
      ["y"] = 0.43200000000000005,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Faralorn",
      ["id"] = "7942",
      ["description"] = "General Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.306,
      ["y"] = 0.434,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Harklane",
      ["id"] = "7943",
      ["description"] = "Fish Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.31,
      ["y"] = 0.462,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Savanne",
      ["id"] = "7945",
      ["description"] = "Fishing Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.31,
      ["y"] = 0.46,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Vivianna",
      ["id"] = "7947",
      ["description"] = "Trade Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.312,
      ["y"] = 0.434,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Loorana",
      ["id"] = "8143",
      ["description"] = "Food & Drink",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.754,
      ["y"] = 0.43799999999999994,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Sheendra Tallgrass",
      ["id"] = "8145",
      ["description"] = "Trade Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.7440000000000001,
      ["y"] = 0.428,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Logannas",
      ["id"] = "8157",
      ["description"] = "Alchemy Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.326,
      ["y"] = 0.44,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Bronk",
      ["id"] = "8158",
      ["description"] = "Alchemy Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.76,
      ["y"] = 0.434,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Worb Strongstitch",
      ["id"] = "8159",
      ["description"] = "Light Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.746,
      ["y"] = 0.426,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Cawind Trueaim",
      ["id"] = "9548",
      ["description"] = "Gunsmith & Bowyer",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.748,
      ["y"] = 0.456,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Dulciea Frostmoon",
      ["id"] = "10293",
      ["description"] = "Cloth Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.308,
      ["y"] = 0.43200000000000005,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Zorbin Fandazzle",
      ["id"] = "14637",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.44799999999999995,
      ["y"] = 0.434,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Quartermaster Valdane",
      ["id"] = "222687",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.484,
      ["y"] = 0.124,
    },
    {
      ["category"] = "spirithealer",
      ["name"] = "Spirit Healer",
      ["id"] = "6491",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.314,
      ["y"] = 0.48,
    },
    {
      ["category"] = "boss",
      ["name"] = "Mushgog",
      ["id"] = "11447",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.626,
      ["y"] = 0.3,
    },
    {
      ["category"] = "boss",
      ["name"] = "The Razza",
      ["id"] = "11497",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.626,
      ["y"] = 0.3,
    },
    {
      ["category"] = "boss",
      ["name"] = "Skarr the Unbreakable",
      ["id"] = "11498",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.626,
      ["y"] = 0.3,
    },
    {
      ["category"] = "book",
      ["name"] = "The Sentinels and the Long Vigil",
      ["id"] = "175732",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.309,
      ["y"] = 0.428,
    },
    {
      ["category"] = "mailbox",
      ["name"] = "Mailbox",
      ["id"] = "32349",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Feralas",
      ["subLocation"] = "Feralas",
      ["x"] = 0.312,
      ["y"] = 0.43799999999999994,
    },
  }
}
