DB_HILLSBRAD_FOOTHILLS_GENERAL = {
  ["region"] = "Eastern Kingdoms <Horde>",
  ["mapID"] = 1424,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Kris Legace",
      ["id"] = "3536",
      ["description"] = "Freewheeling Tradeswoman",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.8,
      ["y"] = 0.39,
    },
    {
      ["category"] = "repair",
      ["name"] = "Zixil",
      ["id"] = "3537",
      ["description"] = "Merchant Supreme",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.608,
      ["y"] = 0.198,
    },
    {
      ["category"] = "repair",
      ["name"] = "Ott",
      ["id"] = "3539",
      ["description"] = "Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.604,
      ["y"] = 0.26,
    },
    {
      ["category"] = "repair",
      ["name"] = "Robert Aebischer",
      ["id"] = "3543",
      ["description"] = "Superior Armorsmith",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.512,
      ["y"] = 0.57,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Innkeeper Anderson",
      ["id"] = "2352",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.51,
      ["y"] = 0.588,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Innkeeper Shay",
      ["id"] = "2388",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.626,
      ["y"] = 0.19,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Wesley",
      ["id"] = "9978",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.504,
      ["y"] = 0.586,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Theodore Mont Claire",
      ["id"] = "10057",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.622,
      ["y"] = 0.198,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Zarise",
      ["id"] = "2389",
      ["description"] = "Bat Handler",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.602,
      ["y"] = 0.18600000000000003,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Darla Harris",
      ["id"] = "2432",
      ["description"] = "Gryphon Master",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.494,
      ["y"] = 0.522,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Donald Rabonne",
      ["id"] = "2367",
      ["description"] = "Fisherman",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.506,
      ["y"] = 0.61,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Aranae Venomblood",
      ["id"] = "2390",
      ["description"] = "Herbalist",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.616,
      ["y"] = 0.196,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Serge Hinott",
      ["id"] = "2391",
      ["description"] = "Expert Alchemist",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.616,
      ["y"] = 0.192,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Daryl Stack",
      ["id"] = "2399",
      ["description"] = "Master Tailor",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.636,
      ["y"] = 0.20800000000000002,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Hillsbrad Tailor",
      ["id"] = "2264",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.364,
      ["y"] = 0.444,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Hillsbrad Apprentice Blacksmith",
      ["id"] = "2265",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.32,
      ["y"] = 0.456,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Innkeeper Anderson",
      ["id"] = "2352",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.51,
      ["y"] = 0.588,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Merideth Carlson",
      ["id"] = "2357",
      ["description"] = "Horse Breeder",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.52,
      ["y"] = 0.556,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Neema",
      ["id"] = "2364",
      ["description"] = "Waitress",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.51,
      ["y"] = 0.59,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Bront Coldcleave",
      ["id"] = "2365",
      ["description"] = "Butcher",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.488,
      ["y"] = 0.5720000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Barkeep Kelly",
      ["id"] = "2366",
      ["description"] = "Bartender",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.514,
      ["y"] = 0.586,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Nandar Branson",
      ["id"] = "2380",
      ["description"] = "Alchemy Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.508,
      ["y"] = 0.57,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Micha Yance",
      ["id"] = "2381",
      ["description"] = "Trade Goods",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.49,
      ["y"] = 0.55,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Lindea Rabonne",
      ["id"] = "2383",
      ["description"] = "Tackle and Bait",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.506,
      ["y"] = 0.61,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Innkeeper Shay",
      ["id"] = "2388",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.626,
      ["y"] = 0.19,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Christoph Jeffcoat",
      ["id"] = "2393",
      ["description"] = "Tradesman",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.622,
      ["y"] = 0.19,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Mallen Swain",
      ["id"] = "2394",
      ["description"] = "Tailoring Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.62,
      ["y"] = 0.21,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Derak Nightfall",
      ["id"] = "2397",
      ["description"] = "Cook",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.63,
      ["y"] = 0.19399999999999998,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kayren Soothallow",
      ["id"] = "2401",
      ["description"] = "General Goods",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.624,
      ["y"] = 0.198,
    },
    {
      ["category"] = "vendor",
      ["name"] = "George Candarte",
      ["id"] = "2698",
      ["description"] = "Leatherworking Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.92,
      ["y"] = 0.382,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kris Legace",
      ["id"] = "3536",
      ["description"] = "Freewheeling Tradeswoman",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.8,
      ["y"] = 0.39,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Zixil",
      ["id"] = "3537",
      ["description"] = "Merchant Supreme",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.608,
      ["y"] = 0.198,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Ott",
      ["id"] = "3539",
      ["description"] = "Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.604,
      ["y"] = 0.26,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Hal McAllister",
      ["id"] = "3540",
      ["description"] = "Fish Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.498,
      ["y"] = 0.622,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Sarah Raycroft",
      ["id"] = "3541",
      ["description"] = "General Goods",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.49,
      ["y"] = 0.552,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jaysin Lanyda",
      ["id"] = "3542",
      ["description"] = "Poisons & Reagents",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.508,
      ["y"] = 0.59,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Robert Aebischer",
      ["id"] = "3543",
      ["description"] = "Superior Armorsmith",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.512,
      ["y"] = 0.57,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jason Lemieux",
      ["id"] = "3544",
      ["description"] = "Mushroom Seller",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.614,
      ["y"] = 0.2,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Sergeant Hartman",
      ["id"] = "15199",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.5,
      ["y"] = 0.5720000000000001,
    },
    {
      ["category"] = "spirithealer",
      ["name"] = "Spirit Healer",
      ["id"] = "6491",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.514,
      ["y"] = 0.526,
    },
    {
      ["category"] = "book",
      ["name"] = "Arathor and the Troll Wars",
      ["id"] = "175734",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.625,
      ["y"] = 0.204,
    },
    {
      ["category"] = "book",
      ["name"] = "The Alliance of Lordaeron",
      ["id"] = "175746",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.637,
      ["y"] = 0.20800000000000002,
    },
    {
      ["category"] = "book",
      ["name"] = "The Birth of the Lich King",
      ["id"] = "175748",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.52,
      ["y"] = 0.585,
    },
    {
      ["category"] = "book",
      ["name"] = "Kel'Thuzad and the Forming of the Scourge",
      ["id"] = "175754",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.517,
      ["y"] = 0.585,
    },
    {
      ["category"] = "book",
      ["name"] = "Civil War in the Plaguelands",
      ["id"] = "175761",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.514,
      ["y"] = 0.585,
    },
    {
      ["category"] = "book",
      ["name"] = "Decorated Headstone",
      ["id"] = "175933",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.518,
      ["y"] = 0.529,
    },
    {
      ["category"] = "book",
      ["name"] = "In Loving Memory",
      ["id"] = "181062",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.679,
      ["y"] = 0.84,
    },
    {
      ["category"] = "mailbox",
      ["name"] = "Mailbox",
      ["id"] = "32349",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Hillsbrad Foothills",
      ["subLocation"] = "Hillsbrad Foothills",
      ["x"] = 0.504,
      ["y"] = 0.586,
    },
  }
}
