DB_IRONFORGE_GENERAL = {
  ["mapID"] = 1455,
  ["zoneName"] = "Ironforge",
  ["region"] = "Eastern Kingdoms <Alliance>",
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Thurgrum Deepforge",
      ["id"] = "4259",
      ["description"] = "Blacksmithing Supplies",
      ["x"] = 0.514,
      ["y"] = 0.428,
    },
    {
      ["category"] = "repair",
      ["name"] = "Dolman Steelfury",
      ["id"] = "5102",
      ["description"] = "Weapon Merchant",
      ["x"] = 0.36,
      ["y"] = 0.66,
    },
    {
      ["category"] = "repair",
      ["name"] = "Grenil Steelfury",
      ["id"] = "5103",
      ["description"] = "Weapon Merchant",
      ["x"] = 0.362,
      ["y"] = 0.658,
    },
    {
      ["category"] = "repair",
      ["name"] = "Bromiir Ormsen",
      ["id"] = "5106",
      ["description"] = "Heavy Armor Merchant",
      ["x"] = 0.318,
      ["y"] = 0.578,
    },
    {
      ["category"] = "repair",
      ["name"] = "Mangorn Flinthammer",
      ["id"] = "5107",
      ["description"] = "Heavy Armor Merchant",
      ["x"] = 0.32,
      ["y"] = 0.582,
    },
    {
      ["category"] = "repair",
      ["name"] = "Raena Flinthammer",
      ["id"] = "5108",
      ["description"] = "Light Armor Merchant",
      ["x"] = 0.324,
      ["y"] = 0.578,
    },
    {
      ["category"] = "repair",
      ["name"] = "Hegnar Swiftaxe",
      ["id"] = "5119",
      ["description"] = "Axe Merchant",
      ["x"] = 0.618,
      ["y"] = 0.886,
    },
    {
      ["category"] = "repair",
      ["name"] = "Brenwyn Wintersteel",
      ["id"] = "5120",
      ["description"] = "Blade Merchant",
      ["x"] = 0.62,
      ["y"] = 0.888,
    },
    {
      ["category"] = "repair",
      ["name"] = "Kelomir Ironhand",
      ["id"] = "5121",
      ["description"] = "Maces & Staves",
      ["x"] = 0.62,
      ["y"] = 0.89,
    },
    {
      ["category"] = "repair",
      ["name"] = "Skolmin Goldfury",
      ["id"] = "5122",
      ["description"] = "Bow Merchant",
      ["x"] = 0.716,
      ["y"] = 0.662,
    },
    {
      ["category"] = "repair",
      ["name"] = "Bretta Goldfury",
      ["id"] = "5123",
      ["description"] = "Gun Merchant",
      ["x"] = 0.722,
      ["y"] = 0.658,
    },
    {
      ["category"] = "repair",
      ["name"] = "Dolkin Craghelm",
      ["id"] = "5125",
      ["description"] = "Mail Armor Merchant",
      ["x"] = 0.542,
      ["y"] = 0.882,
    },
    {
      ["category"] = "repair",
      ["name"] = "Olthran Craghelm",
      ["id"] = "5126",
      ["description"] = "Heavy Armor Merchant",
      ["x"] = 0.544,
      ["y"] = 0.872,
    },
    {
      ["category"] = "repair",
      ["name"] = "Lissyphus Finespindle",
      ["id"] = "5129",
      ["description"] = "Light Armor Merchant",
      ["x"] = 0.546,
      ["y"] = 0.882,
    },
    {
      ["category"] = "repair",
      ["name"] = "Harick Boulderdrum",
      ["id"] = "5133",
      ["description"] = "Wands Merchant",
      ["x"] = 0.228,
      ["y"] = 0.164,
    },
    {
      ["category"] = "repair",
      ["name"] = "Bingus",
      ["id"] = "5152",
      ["description"] = "Weapon Merchant",
      ["x"] = 0.226,
      ["y"] = 0.162,
    },
    {
      ["category"] = "repair",
      ["name"] = "Ingrys Stonebrow",
      ["id"] = "5155",
      ["description"] = "Cloth Armor Merchant",
      ["x"] = 0.384,
      ["y"] = 0.056,
    },
    {
      ["category"] = "repair",
      ["name"] = "Maeva Snowbraid",
      ["id"] = "5156",
      ["description"] = "Robe Merchant",
      ["x"] = 0.386,
      ["y"] = 0.056,
    },
    {
      ["category"] = "repair",
      ["name"] = "Hjoldir Stoneblade",
      ["id"] = "5170",
      ["description"] = "Blade Merchant",
      ["x"] = 0.452,
      ["y"] = 0.066,
    },
    {
      ["category"] = "repair",
      ["name"] = "Thalgus Thunderfist",
      ["id"] = "7976",
      ["description"] = "Weapon Merchant",
      ["x"] = 0.612,
      ["y"] = 0.892,
    },
    {
      ["category"] = "auctioneer",
      ["name"] = "Auctioneer Buckler",
      ["id"] = "8671",
      ["comment"] = "拍賣",
      ["x"] = 0.24,
      ["y"] = 0.72,
    },
    {
      ["category"] = "auctioneer",
      ["name"] = "Auctioneer Redmuse",
      ["id"] = "8720",
      ["x"] = 0.242,
      ["y"] = 0.744,
    },
    {
      ["category"] = "auctioneer",
      ["name"] = "Auctioneer Lympkin",
      ["id"] = "9859",
      ["x"] = 0.258,
      ["y"] = 0.752,
    },
    {
      ["category"] = "banker",
      ["name"] = "Barnum Stonemantle",
      ["id"] = "2460",
      ["description"] = "Banker",
      ["x"] = 0.346,
      ["y"] = 0.59,
    },
    {
      ["category"] = "banker",
      ["name"] = "Bailey Stonemantle",
      ["id"] = "2461",
      ["description"] = "Banker",
      ["comment"] = "銀行",
      ["x"] = 0.354,
      ["y"] = 0.606,
    },
    {
      ["category"] = "banker",
      ["name"] = "Soleil Stonemantle",
      ["id"] = "5099",
      ["description"] = "Banker",
      ["x"] = 0.364,
      ["y"] = 0.622,
    },
    {
      ["category"] = "battlemaster",
      ["name"] = "Donal Osgood",
      ["id"] = "857",
      ["description"] = "Arathi Basin Battlemaster",
      ["x"] = 0.698,
      ["y"] = 0.892,
    },
    {
      ["category"] = "battlemaster",
      ["name"] = "Glordrum Steelbeard",
      ["id"] = "12197",
      ["description"] = "Alterac Valley Battlemaster",
      ["x"] = 0.698,
      ["y"] = 0.904,
    },
    {
      ["category"] = "battlemaster",
      ["name"] = "Lylandris",
      ["id"] = "14982",
      ["description"] = "Warsong Gulch Battlemaster",
      ["x"] = 0.704,
      ["y"] = 0.892,
    },
    {
      ["category"] = "battlemaster",
      ["name"] = "League of Arathor Emissary",
      ["id"] = "14991",
      ["x"] = 0.696,
      ["y"] = 0.878,
    },
    {
      ["category"] = "battlemaster",
      ["name"] = "Silverwing Emissary",
      ["id"] = "15102",
      ["x"] = 0.698,
      ["y"] = 0.866,
    },
    {
      ["category"] = "battlemaster",
      ["name"] = "Stormpike Emissary",
      ["id"] = "15103",
      ["x"] = 0.688,
      ["y"] = 0.884,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Innkeeper Firebrew",
      ["id"] = "5111",
      ["description"] = "Innkeeper",
      ["comment"] = "民宿",
      ["x"] = 0.186,
      ["y"] = 0.514,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Ulbrek Firehand",
      ["id"] = "9984",
      ["description"] = "Stable Master",
      ["x"] = 0.694,
      ["y"] = 0.84,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Gryth Thurden",
      ["id"] = "1573",
      ["description"] = "Gryphon Master",
      ["comment"] = "鳥點",
      ["x"] = 0.558,
      ["y"] = 0.48,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Vosur Brakthel",
      ["id"] = "1246",
      ["description"] = "Journeyman Alchemist",
      ["x"] = 0.664,
      ["y"] = 0.552,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Gretta Finespindle",
      ["id"] = "1466",
      ["description"] = "Journeyman Leatherworker",
      ["x"] = 0.39,
      ["y"] = 0.328,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Uthrar Threx",
      ["id"] = "1703",
      ["description"] = "Journeyman Tailor",
      ["x"] = 0.436,
      ["y"] = 0.282,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Kelstrum Stonebreaker",
      ["id"] = "1901",
      ["description"] = "Warrior Trainer",
      ["x"] = 0.67,
      ["y"] = 0.896,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Milstaff Stormeye",
      ["id"] = "2489",
      ["description"] = "Portal Trainer",
      ["x"] = 0.256,
      ["y"] = 0.074,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Geofram Bouldertoe",
      ["id"] = "4254",
      ["description"] = "Mining Trainer",
      ["x"] = 0.502,
      ["y"] = 0.26,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Bengus Deepforge",
      ["id"] = "4258",
      ["description"] = "Artisan Blacksmith",
      ["comment"] = "鐵匠",
      ["x"] = 0.522,
      ["y"] = 0.416,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Kelv Sternhammer",
      ["id"] = "5113",
      ["description"] = "Warrior Trainer",
      ["x"] = 0.7,
      ["y"] = 0.906,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Bilban Tosslespanner",
      ["id"] = "5114",
      ["description"] = "Warrior Trainer",
      ["comment"] = "戰士",
      ["x"] = 0.662,
      ["y"] = 0.882,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Daera Brightspear",
      ["id"] = "5115",
      ["description"] = "Hunter Trainer",
      ["x"] = 0.71,
      ["y"] = 0.9,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Olmin Burningbeard",
      ["id"] = "5116",
      ["description"] = "Hunter Trainer",
      ["comment"] = "獵人",
      ["x"] = 0.706,
      ["y"] = 0.838,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Regnus Thundergranite",
      ["id"] = "5117",
      ["description"] = "Hunter Trainer",
      ["x"] = 0.698,
      ["y"] = 0.834,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Fimble Finespindle",
      ["id"] = "5127",
      ["description"] = "Expert Leatherworker",
      ["x"] = 0.398,
      ["y"] = 0.334,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Reyna Stonebranch",
      ["id"] = "5137",
      ["description"] = "Herbalism Trainer",
      ["comment"] = "採藥",
      ["x"] = 0.556,
      ["y"] = 0.588,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Theodrus Frostbeard",
      ["id"] = "5141",
      ["description"] = "Priest Trainer",
      ["x"] = 0.238,
      ["y"] = 0.09,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Braenna Flintcrag",
      ["id"] = "5142",
      ["description"] = "Priest Trainer",
      ["comment"] = "僧侶",
      ["x"] = 0.246,
      ["y"] = 0.092,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Toldren Deepiron",
      ["id"] = "5143",
      ["description"] = "Priest Trainer",
      ["x"] = 0.252,
      ["y"] = 0.102,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Bink",
      ["id"] = "5144",
      ["description"] = "Mage Trainer",
      ["comment"] = "法師",
      ["x"] = 0.27,
      ["y"] = 0.082,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Juli Stormkettle",
      ["id"] = "5145",
      ["description"] = "Mage Trainer",
      ["x"] = 0.262,
      ["y"] = 0.072,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Nittlebur Sparkfizzle",
      ["id"] = "5146",
      ["description"] = "Mage Trainer",
      ["x"] = 0.26,
      ["y"] = 0.058,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Valgar Highforge",
      ["id"] = "5147",
      ["description"] = "Paladin Trainer",
      ["x"] = 0.234,
      ["y"] = 0.05,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Beldruk Doombrow",
      ["id"] = "5148",
      ["description"] = "Paladin Trainer",
      ["comment"] = "聖騎士",
      ["x"] = 0.246,
      ["y"] = 0.05,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Brandur Ironhammer",
      ["id"] = "5149",
      ["description"] = "Paladin Trainer",
      ["x"] = 0.234,
      ["y"] = 0.062,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Nissa Firestone",
      ["id"] = "5150",
      ["description"] = "First Aid Trainer",
      ["comment"] = "急救",
      ["x"] = 0.548,
      ["y"] = 0.586,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Jormund Stonebrow",
      ["id"] = "5153",
      ["description"] = "Expert Tailor",
      ["x"] = 0.432,
      ["y"] = 0.29,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Gimble Thistlefuzz",
      ["id"] = "5157",
      ["description"] = "Expert Enchanter",
      ["comment"] = "附魔",
      ["x"] = 0.6,
      ["y"] = 0.454,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Daryl Riknussun",
      ["id"] = "5159",
      ["description"] = "Cooking Trainer",
      ["comment"] = "烹飪",
      ["x"] = 0.6,
      ["y"] = 0.368,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Grimnur Stonebrand",
      ["id"] = "5161",
      ["description"] = "Fishing Trainer",
      ["x"] = 0.482,
      ["y"] = 0.066,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Grumnus Steelshaper",
      ["id"] = "5164",
      ["description"] = "Armor Crafter",
      ["x"] = 0.502,
      ["y"] = 0.426,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Hulfdan Blackbeard",
      ["id"] = "5165",
      ["description"] = "Rogue Trainer",
      ["x"] = 0.516,
      ["y"] = 0.148,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Ormyr Flinteye",
      ["id"] = "5166",
      ["description"] = "Rogue Trainer",
      ["comment"] = "盜賊",
      ["x"] = 0.524,
      ["y"] = 0.15,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Fenthwick",
      ["id"] = "5167",
      ["description"] = "Rogue Trainer",
      ["x"] = 0.516,
      ["y"] = 0.15,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Thistleheart",
      ["id"] = "5171",
      ["description"] = "Warlock Trainer",
      ["x"] = 0.508,
      ["y"] = 0.066,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Briarthorn",
      ["id"] = "5172",
      ["description"] = "Warlock Trainer",
      ["x"] = 0.502,
      ["y"] = 0.06,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Springspindle Fizzlegear",
      ["id"] = "5174",
      ["description"] = "Artisan Engineer",
      ["x"] = 0.684,
      ["y"] = 0.44,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Tally Berryfizz",
      ["id"] = "5177",
      ["description"] = "Expert Alchemist",
      ["x"] = 0.666,
      ["y"] = 0.552,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Balthus Stoneflayer",
      ["id"] = "6291",
      ["description"] = "Skinning Trainer",
      ["comment"] = "剝皮",
      ["x"] = 0.396,
      ["y"] = 0.324,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Dink",
      ["id"] = "7312",
      ["description"] = "Mage Trainer",
      ["x"] = 0.268,
      ["y"] = 0.084,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Tinkmaster Overspark",
      ["id"] = "7944",
      ["description"] = "Master Gnome Engineer",
      ["x"] = 0.698,
      ["y"] = 0.502,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Belia Thundergranite",
      ["id"] = "10090",
      ["description"] = "Pet Trainer",
      ["comment"] = "寵物",
      ["x"] = 0.708,
      ["y"] = 0.854,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Rotgath Stonebeard",
      ["id"] = "10276",
      ["description"] = "Expert Blacksmith",
      ["x"] = 0.52,
      ["y"] = 0.424,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Groum Stonebeard",
      ["id"] = "10277",
      ["description"] = "Journeyman Blacksmith",
      ["x"] = 0.52,
      ["y"] = 0.42,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Jemma Quikswitch",
      ["id"] = "11028",
      ["description"] = "Journeyman Engineer",
      ["x"] = 0.678,
      ["y"] = 0.438,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Trixie Quikswitch",
      ["id"] = "11029",
      ["description"] = "Expert Engineer",
      ["x"] = 0.678,
      ["y"] = 0.432,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Thonys Pillarstone",
      ["id"] = "11065",
      ["description"] = "Journeyman Enchanter",
      ["x"] = 0.604,
      ["y"] = 0.45,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Ironus Coldsteel",
      ["id"] = "11146",
      ["description"] = "Special Weapon Crafter",
      ["x"] = 0.504,
      ["y"] = 0.43,
    },
    {
      ["category"] = "trainer",
      ["name"] = "High Priest Rohan",
      ["id"] = "11406",
      ["description"] = "Priest Trainer",
      ["x"] = 0.25,
      ["y"] = 0.084,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Buliwyf Stonehand",
      ["id"] = "11865",
      ["description"] = "Weapon Master",
      ["x"] = 0.614,
      ["y"] = 0.892,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Bixi Wobblebonk",
      ["id"] = "13084",
      ["description"] = "Weapon Master",
      ["comment"] = "武器",
      ["x"] = 0.62,
      ["y"] = 0.894,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Gerrig Bonegrip",
      ["id"] = "2786",
      ["x"] = 0.504,
      ["y"] = 0.06,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Golnir Bouldertoe",
      ["id"] = "4256",
      ["description"] = "Mining Supplier",
      ["comment"] = "採礦",
      ["x"] = 0.51,
      ["y"] = 0.26,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Thurgrum Deepforge",
      ["id"] = "4259",
      ["description"] = "Blacksmithing Supplies",
      ["x"] = 0.514,
      ["y"] = 0.428,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Lyesa Steelbrow",
      ["id"] = "5049",
      ["description"] = "Guild Tabard Vendor",
      ["comment"] = "公會",
      ["x"] = 0.36,
      ["y"] = 0.854,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Fillius Fizzlespinner",
      ["id"] = "5100",
      ["description"] = "Trade Supplier",
      ["x"] = 0.384,
      ["y"] = 0.736,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Bryllia Ironbrand",
      ["id"] = "5101",
      ["description"] = "General Goods Vendor",
      ["x"] = 0.39,
      ["y"] = 0.738,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Dolman Steelfury",
      ["id"] = "5102",
      ["description"] = "Weapon Merchant",
      ["x"] = 0.36,
      ["y"] = 0.66,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Grenil Steelfury",
      ["id"] = "5103",
      ["description"] = "Weapon Merchant",
      ["x"] = 0.362,
      ["y"] = 0.658,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Bromiir Ormsen",
      ["id"] = "5106",
      ["description"] = "Heavy Armor Merchant",
      ["x"] = 0.318,
      ["y"] = 0.578,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Mangorn Flinthammer",
      ["id"] = "5107",
      ["description"] = "Heavy Armor Merchant",
      ["x"] = 0.32,
      ["y"] = 0.582,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Raena Flinthammer",
      ["id"] = "5108",
      ["description"] = "Light Armor Merchant",
      ["x"] = 0.324,
      ["y"] = 0.578,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Myra Tyrngaarde",
      ["id"] = "5109",
      ["description"] = "Bread Vendor",
      ["x"] = 0.272,
      ["y"] = 0.71,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Barim Jurgenstaad",
      ["id"] = "5110",
      ["description"] = "Reagent Vendor",
      ["comment"] = "試劑",
      ["x"] = 0.194,
      ["y"] = 0.562,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Innkeeper Firebrew",
      ["id"] = "5111",
      ["description"] = "Innkeeper",
      ["x"] = 0.186,
      ["y"] = 0.514,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Gwenna Firebrew",
      ["id"] = "5112",
      ["description"] = "Barmaid",
      ["x"] = 0.188,
      ["y"] = 0.516,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Hegnar Swiftaxe",
      ["id"] = "5119",
      ["description"] = "Axe Merchant",
      ["x"] = 0.618,
      ["y"] = 0.886,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Brenwyn Wintersteel",
      ["id"] = "5120",
      ["description"] = "Blade Merchant",
      ["x"] = 0.62,
      ["y"] = 0.888,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kelomir Ironhand",
      ["id"] = "5121",
      ["description"] = "Maces & Staves",
      ["x"] = 0.62,
      ["y"] = 0.89,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Skolmin Goldfury",
      ["id"] = "5122",
      ["description"] = "Bow Merchant",
      ["x"] = 0.716,
      ["y"] = 0.662,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Bretta Goldfury",
      ["id"] = "5123",
      ["description"] = "Gun Merchant",
      ["comment"] = "槍械",
      ["x"] = 0.722,
      ["y"] = 0.658,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Sognar Cliffbeard",
      ["id"] = "5124",
      ["description"] = "Meat Vendor",
      ["x"] = 0.646,
      ["y"] = 0.694,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Dolkin Craghelm",
      ["id"] = "5125",
      ["description"] = "Mail Armor Merchant",
      ["x"] = 0.542,
      ["y"] = 0.882,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Olthran Craghelm",
      ["id"] = "5126",
      ["description"] = "Heavy Armor Merchant",
      ["x"] = 0.544,
      ["y"] = 0.872,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Bombus Finespindle",
      ["id"] = "5128",
      ["description"] = "Leatherworking Supplies",
      ["comment"] = "皮革",
      ["x"] = 0.394,
      ["y"] = 0.34,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Lissyphus Finespindle",
      ["id"] = "5129",
      ["description"] = "Light Armor Merchant",
      ["x"] = 0.546,
      ["y"] = 0.882,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Pithwick",
      ["id"] = "5132",
      ["description"] = "Bag Vendor",
      ["comment"] = "背包",
      ["x"] = 0.382,
      ["y"] = 0.746,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Harick Boulderdrum",
      ["id"] = "5133",
      ["description"] = "Wands Merchant",
      ["x"] = 0.228,
      ["y"] = 0.164,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Gwina Stonebranch",
      ["id"] = "5138",
      ["description"] = "Herbalism Supplier",
      ["x"] = 0.552,
      ["y"] = 0.588,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Edris Barleybeard",
      ["id"] = "5140",
      ["description"] = "Barmaid",
      ["x"] = 0.722,
      ["y"] = 0.76,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Ginny Longberry",
      ["id"] = "5151",
      ["description"] = "Reagent Vendor",
      ["x"] = 0.312,
      ["y"] = 0.274,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Bingus",
      ["id"] = "5152",
      ["description"] = "Weapon Merchant",
      ["x"] = 0.226,
      ["y"] = 0.162,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Poranna Snowbraid",
      ["id"] = "5154",
      ["description"] = "Tailoring Supplies",
      ["comment"] = "裁縫",
      ["x"] = 0.432,
      ["y"] = 0.284,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Ingrys Stonebrow",
      ["id"] = "5155",
      ["description"] = "Cloth Armor Merchant",
      ["x"] = 0.384,
      ["y"] = 0.056,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Maeva Snowbraid",
      ["id"] = "5156",
      ["description"] = "Robe Merchant",
      ["x"] = 0.386,
      ["y"] = 0.056,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Tilli Thistlefuzz",
      ["id"] = "5158",
      ["description"] = "Enchanting Supplies",
      ["x"] = 0.608,
      ["y"] = 0.442,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Emrul Riknussun",
      ["id"] = "5160",
      ["description"] = "Cooking Supplier",
      ["x"] = 0.6,
      ["y"] = 0.378,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Tansy Puddlefizz",
      ["id"] = "5162",
      ["description"] = "Fishing Supplier",
      ["comment"] = "釣魚",
      ["x"] = 0.478,
      ["y"] = 0.064,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Burbik Gearspanner",
      ["id"] = "5163",
      ["description"] = "Trade Supplier",
      ["comment"] = "商店",
      ["x"] = 0.464,
      ["y"] = 0.272,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Tynnus Venomsprout",
      ["id"] = "5169",
      ["description"] = "Shady Dealer",
      ["x"] = 0.528,
      ["y"] = 0.132,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Hjoldir Stoneblade",
      ["id"] = "5170",
      ["description"] = "Blade Merchant",
      ["x"] = 0.452,
      ["y"] = 0.066,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Alexander Calder",
      ["id"] = "5173",
      ["description"] = "Warlock Trainer",
      ["comment"] = "術士",
      ["x"] = 0.502,
      ["y"] = 0.068,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Gearcutter Cogspinner",
      ["id"] = "5175",
      ["description"] = "Engineering Supplies",
      ["x"] = 0.678,
      ["y"] = 0.43,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Soolie Berryfizz",
      ["id"] = "5178",
      ["description"] = "Alchemy Supplies",
      ["x"] = 0.666,
      ["y"] = 0.544,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Fizzlebang Booms",
      ["id"] = "5569",
      ["description"] = "Fireworks Vendor",
      ["x"] = 0.732,
      ["y"] = 0.532,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Bruuk Barleybeard",
      ["id"] = "5570",
      ["description"] = "Bartender",
      ["x"] = 0.722,
      ["y"] = 0.764,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jubahl Corpseseeker",
      ["id"] = "6382",
      ["description"] = "Demon Trainer",
      ["x"] = 0.528,
      ["y"] = 0.06,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Thalgus Thunderfist",
      ["id"] = "7976",
      ["description"] = "Weapon Merchant",
      ["x"] = 0.612,
      ["y"] = 0.892,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Bimble Longberry",
      ["id"] = "7978",
      ["description"] = "Fruit Vendor",
      ["comment"] = "水果",
      ["x"] = 0.284,
      ["y"] = 0.15,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Wizbang Booms",
      ["id"] = "8117",
      ["description"] = "Holiday Fireworks Vendor",
      ["x"] = 0.314,
      ["y"] = 0.626,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Outfitter Eric",
      ["id"] = "8681",
      ["description"] = "Speciality Tailoring Supplies",
      ["x"] = 0.432,
      ["y"] = 0.292,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Sraaz",
      ["id"] = "9099",
      ["description"] = "Pie Vendor",
      ["x"] = 0.5,
      ["y"] = 0.57,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Wulmort Jinglepocket",
      ["id"] = "13433",
      ["description"] = "Smokywood Pastures",
      ["x"] = 0.334,
      ["y"] = 0.67,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Macey Jinglepocket",
      ["id"] = "13434",
      ["description"] = "Smokywood Pastures",
      ["x"] = 0.332,
      ["y"] = 0.676,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Katrina Shimmerstar",
      ["id"] = "15353",
      ["description"] = "Hallow's End Treats",
      ["x"] = 0.338,
      ["y"] = 0.662,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Lunar Festival Vendor",
      ["id"] = "15898",
      ["x"] = 0.296,
      ["y"] = 0.144,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Tamelyn Aldridge",
      ["id"] = "214099",
      ["description"] = "Supply Officer",
      ["comment"] = "通用",
      ["x"] = 0.246,
      ["y"] = 0.676,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Wulmort Jinglepocket",
      ["id"] = "216902",
      ["description"] = "Smokywood Pastures",
      ["x"] = 0.334,
      ["y"] = 0.67,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Rune Broker",
      ["id"] = "233335",
      ["x"] = 0.538,
      ["y"] = 0.132,
    },
    {
      ["category"] = "book",
      ["name"] = "The Skull of Tyrannistrasz",
      ["id"] = "175679",
      ["x"] = 0.773,
      ["y"] = 0.273,
    },
    {
      ["category"] = "book",
      ["name"] = "Fossilized Egg",
      ["id"] = "175680",
      ["x"] = 0.762,
      ["y"] = 0.246,
    },
    {
      ["category"] = "book",
      ["name"] = "Roc Talon",
      ["id"] = "175681",
      ["x"] = 0.762,
      ["y"] = 0.237,
    },
    {
      ["category"] = "book",
      ["name"] = "Geru Strider",
      ["id"] = "175682",
      ["x"] = 0.767,
      ["y"] = 0.218,
    },
    {
      ["category"] = "book",
      ["name"] = "Toothgnasher's Skeleton",
      ["id"] = "175683",
      ["x"] = 0.741,
      ["y"] = 0.211,
    },
    {
      ["category"] = "book",
      ["name"] = "Saurial Egg",
      ["id"] = "175684",
      ["x"] = 0.779,
      ["y"] = 0.221,
    },
    {
      ["category"] = "book",
      ["name"] = "Pteradon Skeleton",
      ["id"] = "175685",
      ["x"] = 0.716,
      ["y"] = 0.174,
    },
    {
      ["category"] = "book",
      ["name"] = "Highborne Astrolabe",
      ["id"] = "175686",
      ["x"] = 0.696,
      ["y"] = 0.11,
    },
    {
      ["category"] = "book",
      ["name"] = "Uldaman Relics",
      ["id"] = "175687",
      ["x"] = 0.687,
      ["y"] = 0.051,
    },
    {
      ["category"] = "book",
      ["name"] = "Horde Catapult",
      ["id"] = "175688",
      ["x"] = 0.662,
      ["y"] = 0.063,
    },
    {
      ["category"] = "book",
      ["name"] = "Uldaman Reliefs",
      ["id"] = "175689",
      ["x"] = 0.644,
      ["y"] = 0.034,
    },
    {
      ["category"] = "book",
      ["name"] = "The Old Gods and the Ordering of Azeroth",
      ["id"] = "175725",
      ["x"] = 0.76,
      ["y"] = 0.111,
    },
    {
      ["category"] = "book",
      ["name"] = "Charge of the Dragonflights",
      ["id"] = "175726",
      ["x"] = 0.761,
      ["y"] = 0.11,
    },
    {
      ["category"] = "book",
      ["name"] = "Arathor and the Troll Wars",
      ["id"] = "175734",
      ["x"] = 0.77,
      ["y"] = 0.094,
    },
    {
      ["category"] = "book",
      ["name"] = "Ironforge - the Awakening of the Dwarves",
      ["id"] = "175736",
      ["x"] = 0.749,
      ["y"] = 0.091,
    },
    {
      ["category"] = "book",
      ["name"] = "War of the Three Hammers",
      ["id"] = "175739",
      ["x"] = 0.751,
      ["y"] = 0.091,
    },
    {
      ["category"] = "book",
      ["name"] = "Rise of the Horde",
      ["id"] = "175742",
      ["x"] = 0.771,
      ["y"] = 0.13,
    },
    {
      ["category"] = "book",
      ["name"] = "The Alliance of Lordaeron",
      ["id"] = "175746",
      ["x"] = 0.769,
      ["y"] = 0.122,
    },
    {
      ["category"] = "book",
      ["name"] = "The Battle of Grim Batol",
      ["id"] = "175750",
      ["x"] = 0.757,
      ["y"] = 0.111,
    },
    {
      ["category"] = "book",
      ["name"] = "Civil War in the Plaguelands",
      ["id"] = "175761",
      ["x"] = 0.768,
      ["y"] = 0.127,
    },
    {
      ["category"] = "book",
      ["name"] = "Pteradon Skeleton",
      ["id"] = "177222",
      ["x"] = 0.728,
      ["y"] = 0.128,
    },
    {
      ["category"] = "forge",
      ["name"] = "Forge",
      ["id"] = "1685",
      ["x"] = 0.49,
      ["y"] = 0.446,
    },
    {
      ["category"] = "mailbox",
      ["name"] = "Mailbox",
      ["id"] = "32349",
      ["x"] = 0.211,
      ["y"] = 0.529,
    },
  }
}

