DB_LOCH_MODAN_GENERAL = {
  ["region"] = "Eastern Kingdoms <Alliance>",
  ["mapID"] = 1432,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Morhan Coppertongue",
      ["id"] = "167",
      ["description"] = "Metalsmith",
      ["comment"] = "",
      ["mainLocation"] = "Loch Modan",
      ["subLocation"] = "Loch Modan",
      ["x"] = 0.34,
      ["y"] = 0.466,
    },
    {
      ["category"] = "repair",
      ["name"] = "Nillen Andemar",
      ["id"] = "222",
      ["description"] = "Macecrafter",
      ["comment"] = "",
      ["mainLocation"] = "Loch Modan",
      ["subLocation"] = "Loch Modan",
      ["x"] = 0.428,
      ["y"] = 0.1,
    },
    {
      ["category"] = "repair",
      ["name"] = "Kat Sampson",
      ["id"] = "954",
      ["description"] = "Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Loch Modan",
      ["subLocation"] = "Loch Modan",
      ["x"] = 0.826,
      ["y"] = 0.64,
    },
    {
      ["category"] = "repair",
      ["name"] = "Aldren Cordon",
      ["id"] = "1214",
      ["description"] = "Clothier",
      ["comment"] = "",
      ["mainLocation"] = "Loch Modan",
      ["subLocation"] = "Loch Modan",
      ["x"] = 0.648,
      ["y"] = 0.66,
    },
    {
      ["category"] = "repair",
      ["name"] = "Gothor Brumn",
      ["id"] = "1362",
      ["description"] = "Armorer",
      ["comment"] = "",
      ["mainLocation"] = "Loch Modan",
      ["subLocation"] = "Loch Modan",
      ["x"] = 0.24,
      ["y"] = 0.18,
    },
    {
      ["category"] = "repair",
      ["name"] = "Vrok Blunderblast",
      ["id"] = "1469",
      ["description"] = "Gunsmith",
      ["comment"] = "",
      ["mainLocation"] = "Loch Modan",
      ["subLocation"] = "Loch Modan",
      ["x"] = 0.358,
      ["y"] = 0.436,
    },
    {
      ["category"] = "repair",
      ["name"] = "Irene Sureshot",
      ["id"] = "1686",
      ["description"] = "Gunsmith",
      ["comment"] = "",
      ["mainLocation"] = "Loch Modan",
      ["subLocation"] = "Loch Modan",
      ["x"] = 0.83,
      ["y"] = 0.634,
    },
    {
      ["category"] = "repair",
      ["name"] = "Cliff Hadin",
      ["id"] = "1687",
      ["description"] = "Bowyer",
      ["comment"] = "",
      ["mainLocation"] = "Loch Modan",
      ["subLocation"] = "Loch Modan",
      ["x"] = 0.83,
      ["y"] = 0.63,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Innkeeper Hearthstove",
      ["id"] = "6734",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Loch Modan",
      ["subLocation"] = "Loch Modan",
      ["x"] = 0.354,
      ["y"] = 0.484,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Lina Hearthstove",
      ["id"] = "9989",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "Loch Modan",
      ["subLocation"] = "Loch Modan",
      ["x"] = 0.34600000000000003,
      ["y"] = 0.48,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Thorgrum Borrelson",
      ["id"] = "1572",
      ["description"] = "Gryphon Master",
      ["comment"] = "",
      ["mainLocation"] = "Loch Modan",
      ["subLocation"] = "Loch Modan",
      ["x"] = 0.33799999999999997,
      ["y"] = 0.508,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Ghak Healtouch",
      ["id"] = "1470",
      ["description"] = "Journeyman Alchemist",
      ["comment"] = "",
      ["mainLocation"] = "Loch Modan",
      ["subLocation"] = "Loch Modan",
      ["x"] = 0.37,
      ["y"] = 0.49200000000000005,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Kali Healtouch",
      ["id"] = "1473",
      ["description"] = "Herbalist",
      ["comment"] = "",
      ["mainLocation"] = "Loch Modan",
      ["subLocation"] = "Loch Modan",
      ["x"] = 0.364,
      ["y"] = 0.484,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Brock Stoneseeker",
      ["id"] = "1681",
      ["description"] = "Mining Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Loch Modan",
      ["subLocation"] = "Loch Modan",
      ["x"] = 0.37,
      ["y"] = 0.478,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Warg Deepwater",
      ["id"] = "1683",
      ["description"] = "Fisherman",
      ["comment"] = "",
      ["mainLocation"] = "Loch Modan",
      ["subLocation"] = "Loch Modan",
      ["x"] = 0.406,
      ["y"] = 0.396,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Deek Fizzlebizz",
      ["id"] = "3290",
      ["description"] = "Journeyman Engineer",
      ["comment"] = "",
      ["mainLocation"] = "Loch Modan",
      ["subLocation"] = "Loch Modan",
      ["x"] = 0.45799999999999996,
      ["y"] = 0.136,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Claude Erksine",
      ["id"] = "3545",
      ["description"] = "Pet Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Loch Modan",
      ["subLocation"] = "Loch Modan",
      ["x"] = 0.8220000000000001,
      ["y"] = 0.628,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Dargh Trueaim",
      ["id"] = "10930",
      ["description"] = "Hunter Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Loch Modan",
      ["subLocation"] = "Loch Modan",
      ["x"] = 0.8220000000000001,
      ["y"] = 0.624,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Morhan Coppertongue",
      ["id"] = "167",
      ["description"] = "Metalsmith",
      ["comment"] = "",
      ["mainLocation"] = "Loch Modan",
      ["subLocation"] = "Loch Modan",
      ["x"] = 0.34,
      ["y"] = 0.466,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Nillen Andemar",
      ["id"] = "222",
      ["description"] = "Macecrafter",
      ["comment"] = "",
      ["mainLocation"] = "Loch Modan",
      ["subLocation"] = "Loch Modan",
      ["x"] = 0.428,
      ["y"] = 0.1,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Karm Ironquill",
      ["id"] = "372",
      ["description"] = "Mining Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Loch Modan",
      ["subLocation"] = "Loch Modan",
      ["x"] = 0.37,
      ["y"] = 0.47200000000000003,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kat Sampson",
      ["id"] = "954",
      ["description"] = "Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Loch Modan",
      ["subLocation"] = "Loch Modan",
      ["x"] = 0.826,
      ["y"] = 0.64,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Aldren Cordon",
      ["id"] = "1214",
      ["description"] = "Clothier",
      ["comment"] = "",
      ["mainLocation"] = "Loch Modan",
      ["subLocation"] = "Loch Modan",
      ["x"] = 0.648,
      ["y"] = 0.66,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Gothor Brumn",
      ["id"] = "1362",
      ["description"] = "Armorer",
      ["comment"] = "",
      ["mainLocation"] = "Loch Modan",
      ["subLocation"] = "Loch Modan",
      ["x"] = 0.24,
      ["y"] = 0.18,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Drac Roughcut",
      ["id"] = "1465",
      ["description"] = "Tradesman",
      ["comment"] = "",
      ["mainLocation"] = "Loch Modan",
      ["subLocation"] = "Loch Modan",
      ["x"] = 0.35600000000000004,
      ["y"] = 0.49,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Vrok Blunderblast",
      ["id"] = "1469",
      ["description"] = "Gunsmith",
      ["comment"] = "",
      ["mainLocation"] = "Loch Modan",
      ["subLocation"] = "Loch Modan",
      ["x"] = 0.358,
      ["y"] = 0.436,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Rann Flamespinner",
      ["id"] = "1474",
      ["description"] = "Tailoring Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Loch Modan",
      ["subLocation"] = "Loch Modan",
      ["x"] = 0.36,
      ["y"] = 0.46,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Yanni Stoutheart",
      ["id"] = "1682",
      ["description"] = "General Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Loch Modan",
      ["subLocation"] = "Loch Modan",
      ["x"] = 0.348,
      ["y"] = 0.486,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Khara Deepwater",
      ["id"] = "1684",
      ["description"] = "Fishing Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Loch Modan",
      ["subLocation"] = "Loch Modan",
      ["x"] = 0.40399999999999997,
      ["y"] = 0.39399999999999996,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Xandar Goodbeard",
      ["id"] = "1685",
      ["description"] = "General Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Loch Modan",
      ["subLocation"] = "Loch Modan",
      ["x"] = 0.8240000000000001,
      ["y"] = 0.634,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Irene Sureshot",
      ["id"] = "1686",
      ["description"] = "Gunsmith",
      ["comment"] = "",
      ["mainLocation"] = "Loch Modan",
      ["subLocation"] = "Loch Modan",
      ["x"] = 0.83,
      ["y"] = 0.634,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Cliff Hadin",
      ["id"] = "1687",
      ["description"] = "Bowyer",
      ["comment"] = "",
      ["mainLocation"] = "Loch Modan",
      ["subLocation"] = "Loch Modan",
      ["x"] = 0.83,
      ["y"] = 0.63,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Greishan Ironstove",
      ["id"] = "3291",
      ["description"] = "Traveling Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Loch Modan",
      ["subLocation"] = "Loch Modan",
      ["x"] = 0.344,
      ["y"] = 0.47200000000000003,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Honni Goldenoat",
      ["id"] = "3948",
      ["description"] = "Baker",
      ["comment"] = "",
      ["mainLocation"] = "Loch Modan",
      ["subLocation"] = "Loch Modan",
      ["x"] = 0.35200000000000004,
      ["y"] = 0.496,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Innkeeper Hearthstove",
      ["id"] = "6734",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Loch Modan",
      ["subLocation"] = "Loch Modan",
      ["x"] = 0.354,
      ["y"] = 0.484,
    },
    {
      ["category"] = "spirithealer",
      ["name"] = "Spirit Healer",
      ["id"] = "6491",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Loch Modan",
      ["subLocation"] = "Loch Modan",
      ["x"] = 0.324,
      ["y"] = 0.46399999999999997,
    },
    {
      ["category"] = "book",
      ["name"] = "Ironforge - the Awakening of the Dwarves",
      ["id"] = "175736",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Loch Modan",
      ["subLocation"] = "Loch Modan",
      ["x"] = 0.35600000000000004,
      ["y"] = 0.49,
    },
    {
      ["category"] = "book",
      ["name"] = "The Last Guardian",
      ["id"] = "175740",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Loch Modan",
      ["subLocation"] = "Loch Modan",
      ["x"] = 0.37200000000000005,
      ["y"] = 0.47,
    },
    {
      ["category"] = "forge",
      ["name"] = "Forge",
      ["id"] = "1685",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Loch Modan",
      ["subLocation"] = "Loch Modan",
      ["x"] = 0.34299999999999997,
      ["y"] = 0.466,
    },
    {
      ["category"] = "mailbox",
      ["name"] = "Mailbox",
      ["id"] = "32349",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Loch Modan",
      ["subLocation"] = "Loch Modan",
      ["x"] = 0.348,
      ["y"] = 0.47700000000000004,
    },
  }
}
