DB_MOONGLADE_GENERAL = {
  ["region"] = "Kalimdor",
  ["mapID"] = 1450,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Geenia Sunshadow",
      ["id"] = "4184",
      ["description"] = "Speciality Dress Maker",
      ["comment"] = "",
      ["mainLocation"] = "Moonglade",
      ["subLocation"] = "Moonglade",
      ["x"] = 0.518,
      ["y"] = 0.33,
    },
    {
      ["category"] = "repair",
      ["name"] = "Kharedon",
      ["id"] = "12023",
      ["description"] = "Light Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Moonglade",
      ["subLocation"] = "Moonglade",
      ["x"] = 0.564,
      ["y"] = 0.3,
    },
    {
      ["category"] = "repair",
      ["name"] = "Meliri",
      ["id"] = "12024",
      ["description"] = "Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Moonglade",
      ["subLocation"] = "Moonglade",
      ["x"] = 0.512,
      ["y"] = 0.42200000000000004,
    },
    {
      ["category"] = "repair",
      ["name"] = "Narianna",
      ["id"] = "12029",
      ["description"] = "Bowyer",
      ["comment"] = "",
      ["mainLocation"] = "Moonglade",
      ["subLocation"] = "Moonglade",
      ["x"] = 0.532,
      ["y"] = 0.426,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Banteazo",
      ["id"] = "228176",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Moonglade",
      ["subLocation"] = "Moonglade",
      ["x"] = 0.562,
      ["y"] = 0.324,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Sindrayl",
      ["id"] = "10897",
      ["description"] = "Hippogryph Master",
      ["comment"] = "",
      ["mainLocation"] = "Moonglade",
      ["subLocation"] = "Moonglade",
      ["x"] = 0.48,
      ["y"] = 0.672,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Faustron",
      ["id"] = "12740",
      ["description"] = "Wind Rider Master",
      ["comment"] = "",
      ["mainLocation"] = "Moonglade",
      ["subLocation"] = "Moonglade",
      ["x"] = 0.322,
      ["y"] = 0.664,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Malvor",
      ["id"] = "12025",
      ["description"] = "Herbalist",
      ["comment"] = "",
      ["mainLocation"] = "Moonglade",
      ["subLocation"] = "Moonglade",
      ["x"] = 0.45399999999999996,
      ["y"] = 0.47,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Loganaar",
      ["id"] = "12042",
      ["description"] = "Druid Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Moonglade",
      ["subLocation"] = "Moonglade",
      ["x"] = 0.524,
      ["y"] = 0.40399999999999997,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Geenia Sunshadow",
      ["id"] = "4184",
      ["description"] = "Speciality Dress Maker",
      ["comment"] = "",
      ["mainLocation"] = "Moonglade",
      ["subLocation"] = "Moonglade",
      ["x"] = 0.518,
      ["y"] = 0.33,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Darnall",
      ["id"] = "7940",
      ["description"] = "Tailoring Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Moonglade",
      ["subLocation"] = "Moonglade",
      ["x"] = 0.516,
      ["y"] = 0.332,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Dargon",
      ["id"] = "12019",
      ["description"] = "Food & Drink Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Moonglade",
      ["subLocation"] = "Moonglade",
      ["x"] = 0.486,
      ["y"] = 0.392,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Daeolyn Summerleaf",
      ["id"] = "12021",
      ["description"] = "General Goods",
      ["comment"] = "",
      ["mainLocation"] = "Moonglade",
      ["subLocation"] = "Moonglade",
      ["x"] = 0.452,
      ["y"] = 0.34600000000000003,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Lorelae Wintersong",
      ["id"] = "12022",
      ["description"] = "Trade Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Moonglade",
      ["subLocation"] = "Moonglade",
      ["x"] = 0.48200000000000004,
      ["y"] = 0.4,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kharedon",
      ["id"] = "12023",
      ["description"] = "Light Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Moonglade",
      ["subLocation"] = "Moonglade",
      ["x"] = 0.564,
      ["y"] = 0.3,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Meliri",
      ["id"] = "12024",
      ["description"] = "Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Moonglade",
      ["subLocation"] = "Moonglade",
      ["x"] = 0.512,
      ["y"] = 0.42200000000000004,
    },
    {
      ["category"] = "vendor",
      ["name"] = "My'lanna",
      ["id"] = "12026",
      ["description"] = "Food & Drink Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Moonglade",
      ["subLocation"] = "Moonglade",
      ["x"] = 0.444,
      ["y"] = 0.34,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Narianna",
      ["id"] = "12029",
      ["description"] = "Bowyer",
      ["comment"] = "",
      ["mainLocation"] = "Moonglade",
      ["subLocation"] = "Moonglade",
      ["x"] = 0.532,
      ["y"] = 0.426,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Valadar Starsong",
      ["id"] = "15864",
      ["description"] = "Coin of Ancestry Collector",
      ["comment"] = "",
      ["mainLocation"] = "Moonglade",
      ["subLocation"] = "Moonglade",
      ["x"] = 0.536,
      ["y"] = 0.354,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Lunar Festival Vendor",
      ["id"] = "15898",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Moonglade",
      ["subLocation"] = "Moonglade",
      ["x"] = 0.366,
      ["y"] = 0.5820000000000001,
    },
    {
      ["category"] = "spirithealer",
      ["name"] = "Spirit Healer",
      ["id"] = "6491",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Moonglade",
      ["subLocation"] = "Moonglade",
      ["x"] = 0.62,
      ["y"] = 0.6940000000000001,
    },
  }
}
