DB_MULGORE_GENERAL = {
  ["region"] = "Kalimdor <Horde>",
  ["mapID"] = 1412,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Marjak Keenblade",
      ["id"] = "3073",
      ["description"] = "Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.44,
      ["y"] = 0.774,
    },
    {
      ["category"] = "repair",
      ["name"] = "Varia Hardhide",
      ["id"] = "3074",
      ["description"] = "Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.442,
      ["y"] = 0.772,
    },
    {
      ["category"] = "repair",
      ["name"] = "Bronk Steelrage",
      ["id"] = "3075",
      ["description"] = "Armorer and Shieldcrafter",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.442,
      ["y"] = 0.774,
    },
    {
      ["category"] = "repair",
      ["name"] = "Mahnott Roughwound",
      ["id"] = "3077",
      ["description"] = "Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.456,
      ["y"] = 0.586,
    },
    {
      ["category"] = "repair",
      ["name"] = "Kennah Hawkseye",
      ["id"] = "3078",
      ["description"] = "Gunsmith",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.456,
      ["y"] = 0.584,
    },
    {
      ["category"] = "repair",
      ["name"] = "Varg Windwhisper",
      ["id"] = "3079",
      ["description"] = "Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.45799999999999996,
      ["y"] = 0.586,
    },
    {
      ["category"] = "repair",
      ["name"] = "Harant Ironbrace",
      ["id"] = "3080",
      ["description"] = "Armorer and Shieldcrafter",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.45799999999999996,
      ["y"] = 0.586,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Innkeeper Kauth",
      ["id"] = "6747",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.466,
      ["y"] = 0.61,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Seikwa",
      ["id"] = "10050",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.46799999999999997,
      ["y"] = 0.602,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Harutt Thunderhorn",
      ["id"] = "3059",
      ["description"] = "Warrior Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.44,
      ["y"] = 0.76,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Gart Mistrunner",
      ["id"] = "3060",
      ["description"] = "Druid Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.45,
      ["y"] = 0.76,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Lanka Farshot",
      ["id"] = "3061",
      ["description"] = "Hunter Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.442,
      ["y"] = 0.758,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Meela Dawnstrider",
      ["id"] = "3062",
      ["description"] = "Shaman Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.45,
      ["y"] = 0.76,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Krang Stonehoof",
      ["id"] = "3063",
      ["description"] = "Warrior Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.494,
      ["y"] = 0.604,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Gennia Runetotem",
      ["id"] = "3064",
      ["description"] = "Druid Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.484,
      ["y"] = 0.596,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Yaw Sharpmane",
      ["id"] = "3065",
      ["description"] = "Hunter Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.478,
      ["y"] = 0.556,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Narm Skychaser",
      ["id"] = "3066",
      ["description"] = "Shaman Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.484,
      ["y"] = 0.5920000000000001,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Pyall Silentstride",
      ["id"] = "3067",
      ["description"] = "Cook",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.45399999999999996,
      ["y"] = 0.58,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Chaw Stronghide",
      ["id"] = "3069",
      ["description"] = "Journeyman Leatherworker",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.45399999999999996,
      ["y"] = 0.578,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Reban Freerunner",
      ["id"] = "3688",
      ["description"] = "Pet Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.47600000000000003,
      ["y"] = 0.556,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Kar Stormsinger",
      ["id"] = "3690",
      ["description"] = "Kodo Riding Instructor",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.47600000000000003,
      ["y"] = 0.584,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Uthan Stillwater",
      ["id"] = "5938",
      ["description"] = "Fisherman",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.444,
      ["y"] = 0.606,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Vira Younghoof",
      ["id"] = "5939",
      ["description"] = "First Aid Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.46799999999999997,
      ["y"] = 0.608,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Yonn Deepcut",
      ["id"] = "6290",
      ["description"] = "Skinner",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.45399999999999996,
      ["y"] = 0.578,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Twizwick Sprocketgrind",
      ["id"] = "10993",
      ["description"] = "Journeyman Engineer",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.618,
      ["y"] = 0.314,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kawnie Softbreeze",
      ["id"] = "3072",
      ["description"] = "General Goods",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.452,
      ["y"] = 0.764,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Marjak Keenblade",
      ["id"] = "3073",
      ["description"] = "Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.44,
      ["y"] = 0.774,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Varia Hardhide",
      ["id"] = "3074",
      ["description"] = "Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.442,
      ["y"] = 0.772,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Bronk Steelrage",
      ["id"] = "3075",
      ["description"] = "Armorer and Shieldcrafter",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.442,
      ["y"] = 0.774,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Moorat Longstride",
      ["id"] = "3076",
      ["description"] = "General Goods",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.45799999999999996,
      ["y"] = 0.5760000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Mahnott Roughwound",
      ["id"] = "3077",
      ["description"] = "Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.456,
      ["y"] = 0.586,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kennah Hawkseye",
      ["id"] = "3078",
      ["description"] = "Gunsmith",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.456,
      ["y"] = 0.584,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Varg Windwhisper",
      ["id"] = "3079",
      ["description"] = "Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.45799999999999996,
      ["y"] = 0.586,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Harant Ironbrace",
      ["id"] = "3080",
      ["description"] = "Armorer and Shieldcrafter",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.45799999999999996,
      ["y"] = 0.586,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Wunna Darkmane",
      ["id"] = "3081",
      ["description"] = "Trade Goods",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.462,
      ["y"] = 0.5820000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Harb Clawhoof",
      ["id"] = "3685",
      ["description"] = "Kodo Mounts",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.474,
      ["y"] = 0.584,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Moodan Sungrain",
      ["id"] = "3883",
      ["description"] = "Baker",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.446,
      ["y"] = 0.778,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jhawna Oatwind",
      ["id"] = "3884",
      ["description"] = "Baker",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.47600000000000003,
      ["y"] = 0.614,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Harn Longcast",
      ["id"] = "5940",
      ["description"] = "Fishing Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.474,
      ["y"] = 0.55,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Innkeeper Kauth",
      ["id"] = "6747",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.466,
      ["y"] = 0.61,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Sylannia",
      ["id"] = "14844",
      ["description"] = "Darkmoon Faire Drink Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.366,
      ["y"] = 0.382,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Stamp Thunderhorn",
      ["id"] = "14845",
      ["description"] = "Darkmoon Faire Food Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.366,
      ["y"] = 0.382,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Lhara",
      ["id"] = "14846",
      ["description"] = "Darkmoon Faire Exotic Goods",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.364,
      ["y"] = 0.38,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Professor Thaddeus Paleo",
      ["id"] = "14847",
      ["description"] = "Darkmoon Faire Cards & Exotic Goods",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.364,
      ["y"] = 0.38,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Flik",
      ["id"] = "14860",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.364,
      ["y"] = 0.36,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Rune Broker",
      ["id"] = "233428",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.444,
      ["y"] = 0.7659999999999999,
    },
    {
      ["category"] = "spirithealer",
      ["name"] = "Spirit Healer",
      ["id"] = "6491",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.426,
      ["y"] = 0.78,
    },
    {
      ["category"] = "book",
      ["name"] = "Ironforge - the Awakening of the Dwarves",
      ["id"] = "175736",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.316,
      ["y"] = 0.495,
    },
    {
      ["category"] = "book",
      ["name"] = "War of the Three Hammers",
      ["id"] = "175739",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.316,
      ["y"] = 0.494,
    },
    {
      ["category"] = "book",
      ["name"] = "The Battle of Grim Batol",
      ["id"] = "175750",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.315,
      ["y"] = 0.494,
    },
    {
      ["category"] = "mailbox",
      ["name"] = "Mailbox",
      ["id"] = "32349",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Mulgore",
      ["subLocation"] = "Mulgore",
      ["x"] = 0.46299999999999997,
      ["y"] = 0.635,
    },
  }
}
