DB_ORGRIMMAR_GENERAL = {
  ["region"] = "Kalimdor <Horde>",
  ["mapID"] = 1454,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Urtharo",
      ["id"] = "3314",
      ["description"] = "Weapon Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.474,
      ["y"] = 0.6859999999999999,
    },
    {
      ["category"] = "repair",
      ["name"] = "Tor'phan",
      ["id"] = "3315",
      ["description"] = "Cloth & Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.626,
      ["y"] = 0.504,
    },
    {
      ["category"] = "repair",
      ["name"] = "Handor",
      ["id"] = "3316",
      ["description"] = "Cloth & Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.628,
      ["y"] = 0.44799999999999995,
    },
    {
      ["category"] = "repair",
      ["name"] = "Ollanus",
      ["id"] = "3317",
      ["description"] = "Light Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.562,
      ["y"] = 0.736,
    },
    {
      ["category"] = "repair",
      ["name"] = "Sana",
      ["id"] = "3319",
      ["description"] = "Mail Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.5579999999999999,
      ["y"] = 0.73,
    },
    {
      ["category"] = "repair",
      ["name"] = "Morgum",
      ["id"] = "3321",
      ["description"] = "Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.56,
      ["y"] = 0.732,
    },
    {
      ["category"] = "repair",
      ["name"] = "Kaja",
      ["id"] = "3322",
      ["description"] = "Guns and Ammo Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.522,
      ["y"] = 0.624,
    },
    {
      ["category"] = "repair",
      ["name"] = "Muragus",
      ["id"] = "3330",
      ["description"] = "Staff Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.444,
      ["y"] = 0.484,
    },
    {
      ["category"] = "repair",
      ["name"] = "Kareth",
      ["id"] = "3331",
      ["description"] = "Blade Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.45399999999999996,
      ["y"] = 0.556,
    },
    {
      ["category"] = "repair",
      ["name"] = "Ukra'nor",
      ["id"] = "3349",
      ["description"] = "Staff Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.298,
      ["y"] = 0.74,
    },
    {
      ["category"] = "repair",
      ["name"] = "Sumi",
      ["id"] = "3356",
      ["description"] = "Blacksmithing Supplier",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.8240000000000001,
      ["y"] = 0.23800000000000002,
    },
    {
      ["category"] = "repair",
      ["name"] = "Kiro",
      ["id"] = "3359",
      ["description"] = "War Harness Maker",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.73,
      ["y"] = 0.42,
    },
    {
      ["category"] = "repair",
      ["name"] = "Koru",
      ["id"] = "3360",
      ["description"] = "Mace & Staves Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.816,
      ["y"] = 0.188,
    },
    {
      ["category"] = "repair",
      ["name"] = "Shoma",
      ["id"] = "3361",
      ["description"] = "Weapon Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.8140000000000001,
      ["y"] = 0.19,
    },
    {
      ["category"] = "repair",
      ["name"] = "Zendo'jian",
      ["id"] = "3409",
      ["description"] = "Weapon Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.812,
      ["y"] = 0.188,
    },
    {
      ["category"] = "repair",
      ["name"] = "Jin'sora",
      ["id"] = "3410",
      ["description"] = "Bow Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.778,
      ["y"] = 0.384,
    },
    {
      ["category"] = "repair",
      ["name"] = "Galthuk",
      ["id"] = "4043",
      ["description"] = "Two-Handed Weapons Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.82,
      ["y"] = 0.188,
    },
    {
      ["category"] = "repair",
      ["name"] = "Tumi",
      ["id"] = "5812",
      ["description"] = "Heavy Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.8240000000000001,
      ["y"] = 0.23600000000000002,
    },
    {
      ["category"] = "repair",
      ["name"] = "Katis",
      ["id"] = "5816",
      ["description"] = "Wand Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.442,
      ["y"] = 0.484,
    },
    {
      ["category"] = "repair",
      ["name"] = "Sergeant Ba'sha",
      ["id"] = "12799",
      ["description"] = "Accessories Quartermaster",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.414,
      ["y"] = 0.688,
    },
    {
      ["category"] = "auctioneer",
      ["name"] = "Auctioneer Thathung",
      ["id"] = "8673",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.556,
      ["y"] = 0.628,
    },
    {
      ["category"] = "auctioneer",
      ["name"] = "Auctioneer Wabang",
      ["id"] = "8724",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.5539999999999999,
      ["y"] = 0.648,
    },
    {
      ["category"] = "auctioneer",
      ["name"] = "Auctioneer Grimful",
      ["id"] = "9856",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.55,
      ["y"] = 0.62,
    },
    {
      ["category"] = "banker",
      ["name"] = "Karus",
      ["id"] = "3309",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.496,
      ["y"] = 0.6940000000000001,
    },
    {
      ["category"] = "banker",
      ["name"] = "Koma",
      ["id"] = "3318",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.5,
      ["y"] = 0.688,
    },
    {
      ["category"] = "banker",
      ["name"] = "Soran",
      ["id"] = "3320",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.49200000000000005,
      ["y"] = 0.696,
    },
    {
      ["category"] = "battlemaster",
      ["name"] = "Brakgul Deathbringer",
      ["id"] = "3890",
      ["description"] = "Warsong Gulch Battlemaster",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.792,
      ["y"] = 0.304,
    },
    {
      ["category"] = "battlemaster",
      ["name"] = "Kartra Bloodsnarl",
      ["id"] = "14942",
      ["description"] = "Alterac Valley Battlemaster",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.79,
      ["y"] = 0.312,
    },
    {
      ["category"] = "battlemaster",
      ["name"] = "Defilers Emissary",
      ["id"] = "14990",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.504,
      ["y"] = 0.6579999999999999,
    },
    {
      ["category"] = "battlemaster",
      ["name"] = "Deze Snowbane",
      ["id"] = "15006",
      ["description"] = "Arathi Basin Battlemaster",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.794,
      ["y"] = 0.292,
    },
    {
      ["category"] = "battlemaster",
      ["name"] = "Warsong Emissary",
      ["id"] = "15105",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.504,
      ["y"] = 0.6579999999999999,
    },
    {
      ["category"] = "battlemaster",
      ["name"] = "Frostwolf Emissary",
      ["id"] = "15106",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.504,
      ["y"] = 0.6579999999999999,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Innkeeper Gryshka",
      ["id"] = "6929",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.542,
      ["y"] = 0.684,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Xon'cha",
      ["id"] = "9988",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.7,
      ["y"] = 0.15,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Doras",
      ["id"] = "3310",
      ["description"] = "Wind Rider Master",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.452,
      ["y"] = 0.638,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Snarl",
      ["id"] = "1383",
      ["description"] = "Expert Blacksmith",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.7979999999999999,
      ["y"] = 0.23399999999999999,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Hanashi",
      ["id"] = "2704",
      ["description"] = "Weapon Master",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.8140000000000001,
      ["y"] = 0.19399999999999998,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Snang",
      ["id"] = "2855",
      ["description"] = "Journeyman Tailor",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.628,
      ["y"] = 0.494,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Thund",
      ["id"] = "2857",
      ["description"] = "Journeyman Engineer",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.758,
      ["y"] = 0.244,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Grol'dar",
      ["id"] = "3324",
      ["description"] = "Warlock Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.48,
      ["y"] = 0.462,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Mirket",
      ["id"] = "3325",
      ["description"] = "Warlock Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.484,
      ["y"] = 0.47,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Zevrost",
      ["id"] = "3326",
      ["description"] = "Warlock Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.484,
      ["y"] = 0.456,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Gest",
      ["id"] = "3327",
      ["description"] = "Rogue Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.428,
      ["y"] = 0.514,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Ormok",
      ["id"] = "3328",
      ["description"] = "Rogue Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.44,
      ["y"] = 0.544,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Lumak",
      ["id"] = "3332",
      ["description"] = "Fishing Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.696,
      ["y"] = 0.292,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Kardris Dreamseeker",
      ["id"] = "3344",
      ["description"] = "Shaman Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.38799999999999996,
      ["y"] = 0.366,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Godan",
      ["id"] = "3345",
      ["description"] = "Expert Enchanter",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.5379999999999999,
      ["y"] = 0.384,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Yelmak",
      ["id"] = "3347",
      ["description"] = "Expert Alchemist",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.5660000000000001,
      ["y"] = 0.332,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Ormak Grimshot",
      ["id"] = "3352",
      ["description"] = "Hunter Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.662,
      ["y"] = 0.182,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Grezz Ragefist",
      ["id"] = "3353",
      ["description"] = "Warrior Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.7959999999999999,
      ["y"] = 0.312,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Sorek",
      ["id"] = "3354",
      ["description"] = "Warrior Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.802,
      ["y"] = 0.324,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Saru Steelfury",
      ["id"] = "3355",
      ["description"] = "Artisan Blacksmith",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.8220000000000001,
      ["y"] = 0.23,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Makaru",
      ["id"] = "3357",
      ["description"] = "Mining Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.73,
      ["y"] = 0.264,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Magar",
      ["id"] = "3363",
      ["description"] = "Expert Tailor",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.634,
      ["y"] = 0.5,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Karolek",
      ["id"] = "3365",
      ["description"] = "Expert Leatherworker",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.628,
      ["y"] = 0.444,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Arnok",
      ["id"] = "3373",
      ["description"] = "First Aid Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.34,
      ["y"] = 0.8440000000000001,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Zamja",
      ["id"] = "3399",
      ["description"] = "Cooking Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.574,
      ["y"] = 0.536,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Shenthul",
      ["id"] = "3401",
      ["description"] = "Rogue Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.43,
      ["y"] = 0.534,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Sian'tsu",
      ["id"] = "3403",
      ["description"] = "Shaman Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.37799999999999995,
      ["y"] = 0.366,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Jandi",
      ["id"] = "3404",
      ["description"] = "Herbalism Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.5539999999999999,
      ["y"] = 0.396,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Xor'juul",
      ["id"] = "3406",
      ["description"] = "Hunter Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.67,
      ["y"] = 0.2,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Sian'dur",
      ["id"] = "3407",
      ["description"] = "Hunter Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.6779999999999999,
      ["y"] = 0.17800000000000002,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Zel'mak",
      ["id"] = "3408",
      ["description"] = "Warrior Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.802,
      ["y"] = 0.29600000000000004,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Nogg",
      ["id"] = "3412",
      ["description"] = "Expert Engineer",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.758,
      ["y"] = 0.252,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Kildar",
      ["id"] = "4752",
      ["description"] = "Wolf Riding Instructor",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.6920000000000001,
      ["y"] = 0.132,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Kamari",
      ["id"] = "5811",
      ["description"] = "Journeyman Leatherworker",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.63,
      ["y"] = 0.45,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Pephredo",
      ["id"] = "5882",
      ["description"] = "Mage Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.384,
      ["y"] = 0.8540000000000001,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Enyo",
      ["id"] = "5883",
      ["description"] = "Mage Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.38799999999999996,
      ["y"] = 0.8540000000000001,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Deino",
      ["id"] = "5885",
      ["description"] = "Mage Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.384,
      ["y"] = 0.858,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Thuul",
      ["id"] = "5958",
      ["description"] = "Portal Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.386,
      ["y"] = 0.858,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Zayus",
      ["id"] = "5994",
      ["description"] = "High Priest",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.35600000000000004,
      ["y"] = 0.872,
    },
    {
      ["category"] = "trainer",
      ["name"] = "X'yera",
      ["id"] = "6014",
      ["description"] = "Priest Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.358,
      ["y"] = 0.8759999999999999,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Ur'kyo",
      ["id"] = "6018",
      ["description"] = "Priest Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.35600000000000004,
      ["y"] = 0.8759999999999999,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Thuwd",
      ["id"] = "7088",
      ["description"] = "Skinning Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.632,
      ["y"] = 0.452,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Shayis Steelfury",
      ["id"] = "7230",
      ["description"] = "Armor Crafter",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.802,
      ["y"] = 0.23199999999999998,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Kelgruk Bloodaxe",
      ["id"] = "7231",
      ["description"] = "Weapon Crafter",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.82,
      ["y"] = 0.184,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Uthel'nay",
      ["id"] = "7311",
      ["description"] = "Mage Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.39,
      ["y"] = 0.86,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Xao'tsu",
      ["id"] = "10088",
      ["description"] = "Pet Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.664,
      ["y"] = 0.15,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Ug'thok",
      ["id"] = "10266",
      ["description"] = "Journeyman Blacksmith",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.8059999999999999,
      ["y"] = 0.23399999999999999,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Roxxik",
      ["id"] = "11017",
      ["description"] = "Artisan Engineer",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.76,
      ["y"] = 0.25,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Whuut",
      ["id"] = "11046",
      ["description"] = "Journeyman Alchemist",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.5579999999999999,
      ["y"] = 0.332,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Jhag",
      ["id"] = "11066",
      ["description"] = "Journeyman Enchanter",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.536,
      ["y"] = 0.382,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Okothos Ironrager",
      ["id"] = "11177",
      ["description"] = "Armorsmith",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.7979999999999999,
      ["y"] = 0.23800000000000002,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Borgosh Corebender",
      ["id"] = "11178",
      ["description"] = "Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.7959999999999999,
      ["y"] = 0.23600000000000002,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Sayoc",
      ["id"] = "11868",
      ["description"] = "Weapon Master",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.8140000000000001,
      ["y"] = 0.19399999999999998,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Sagorne Creststrider",
      ["id"] = "13417",
      ["description"] = "Shaman Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.386,
      ["y"] = 0.36200000000000004,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Olvia",
      ["id"] = "3312",
      ["description"] = "Meat Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.44799999999999995,
      ["y"] = 0.698,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Trak'gen",
      ["id"] = "3313",
      ["description"] = "General Goods Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.48,
      ["y"] = 0.802,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Urtharo",
      ["id"] = "3314",
      ["description"] = "Weapon Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.474,
      ["y"] = 0.6859999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Tor'phan",
      ["id"] = "3315",
      ["description"] = "Cloth & Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.626,
      ["y"] = 0.504,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Handor",
      ["id"] = "3316",
      ["description"] = "Cloth & Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.628,
      ["y"] = 0.44799999999999995,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Ollanus",
      ["id"] = "3317",
      ["description"] = "Light Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.562,
      ["y"] = 0.736,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Sana",
      ["id"] = "3319",
      ["description"] = "Mail Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.5579999999999999,
      ["y"] = 0.73,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Morgum",
      ["id"] = "3321",
      ["description"] = "Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.56,
      ["y"] = 0.732,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kaja",
      ["id"] = "3322",
      ["description"] = "Guns and Ammo Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.522,
      ["y"] = 0.624,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Horthus",
      ["id"] = "3323",
      ["description"] = "Reagents Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.45399999999999996,
      ["y"] = 0.568,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kor'jus",
      ["id"] = "3329",
      ["description"] = "Mushroom Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.49,
      ["y"] = 0.54,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Muragus",
      ["id"] = "3330",
      ["description"] = "Staff Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.444,
      ["y"] = 0.484,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kareth",
      ["id"] = "3331",
      ["description"] = "Blade Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.45399999999999996,
      ["y"] = 0.556,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Shankys",
      ["id"] = "3333",
      ["description"] = "Fishing Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.698,
      ["y"] = 0.29600000000000004,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Rekkul",
      ["id"] = "3334",
      ["description"] = "Poison Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.42200000000000004,
      ["y"] = 0.496,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Hagrus",
      ["id"] = "3335",
      ["description"] = "Reagents Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.46,
      ["y"] = 0.46,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Shan'ti",
      ["id"] = "3342",
      ["description"] = "Fruit Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.376,
      ["y"] = 0.524,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kithas",
      ["id"] = "3346",
      ["description"] = "Enchanting Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.536,
      ["y"] = 0.38,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kor'geld",
      ["id"] = "3348",
      ["description"] = "Alchemy Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.562,
      ["y"] = 0.342,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Ukra'nor",
      ["id"] = "3349",
      ["description"] = "Staff Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.298,
      ["y"] = 0.74,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Asoran",
      ["id"] = "3350",
      ["description"] = "General Goods Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.46,
      ["y"] = 0.406,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Magenius",
      ["id"] = "3351",
      ["description"] = "Reagents Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.45799999999999996,
      ["y"] = 0.406,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Sumi",
      ["id"] = "3356",
      ["description"] = "Blacksmithing Supplier",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.8240000000000001,
      ["y"] = 0.23800000000000002,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Gorina",
      ["id"] = "3358",
      ["description"] = "Mining Supplier",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.732,
      ["y"] = 0.266,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kiro",
      ["id"] = "3359",
      ["description"] = "War Harness Maker",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.73,
      ["y"] = 0.42,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Koru",
      ["id"] = "3360",
      ["description"] = "Mace & Staves Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.816,
      ["y"] = 0.188,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Shoma",
      ["id"] = "3361",
      ["description"] = "Weapon Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.8140000000000001,
      ["y"] = 0.19,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Ogunaro Wolfrunner",
      ["id"] = "3362",
      ["description"] = "Kennel Master",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.6920000000000001,
      ["y"] = 0.126,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Borya",
      ["id"] = "3364",
      ["description"] = "Tailoring Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.63,
      ["y"] = 0.512,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Tamar",
      ["id"] = "3366",
      ["description"] = "Leatherworking Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.63,
      ["y"] = 0.452,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Felika",
      ["id"] = "3367",
      ["description"] = "General Trade Goods Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.544,
      ["y"] = 0.5720000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Borstan",
      ["id"] = "3368",
      ["description"] = "Meat Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.574,
      ["y"] = 0.534,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Gotri",
      ["id"] = "3369",
      ["description"] = "Bag Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.588,
      ["y"] = 0.53,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Xen'to",
      ["id"] = "3400",
      ["description"] = "Cooking Supplier",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.574,
      ["y"] = 0.532,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Zeal'aya",
      ["id"] = "3405",
      ["description"] = "Herbalism Supplier",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.55,
      ["y"] = 0.396,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Zendo'jian",
      ["id"] = "3409",
      ["description"] = "Weapon Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.812,
      ["y"] = 0.188,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jin'sora",
      ["id"] = "3410",
      ["description"] = "Bow Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.778,
      ["y"] = 0.384,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Sovik",
      ["id"] = "3413",
      ["description"] = "Engineering Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.7559999999999999,
      ["y"] = 0.252,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Galthuk",
      ["id"] = "4043",
      ["description"] = "Two-Handed Weapons Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.82,
      ["y"] = 0.188,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Zor Lonetree",
      ["id"] = "4047",
      ["description"] = "Elder Far Seer",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.39,
      ["y"] = 0.38,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Garyl",
      ["id"] = "5188",
      ["description"] = "Tabard Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.43799999999999994,
      ["y"] = 0.7440000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Barkeep Morag",
      ["id"] = "5611",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.544,
      ["y"] = 0.68,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Tumi",
      ["id"] = "5812",
      ["description"] = "Heavy Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.8240000000000001,
      ["y"] = 0.23600000000000002,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kurgul",
      ["id"] = "5815",
      ["description"] = "Demon Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.47600000000000003,
      ["y"] = 0.46799999999999997,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Katis",
      ["id"] = "5816",
      ["description"] = "Wand Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.442,
      ["y"] = 0.484,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Shimra",
      ["id"] = "5817",
      ["description"] = "General Trade Goods Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.48,
      ["y"] = 0.802,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Innkeeper Gryshka",
      ["id"] = "6929",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.542,
      ["y"] = 0.684,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kizzak Sparks",
      ["id"] = "8122",
      ["description"] = "Holiday Fireworks Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.746,
      ["y"] = 0.27,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Xan'tish",
      ["id"] = "8404",
      ["description"] = "Snake Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.38,
      ["y"] = 0.802,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Sergeant Ba'sha",
      ["id"] = "12799",
      ["description"] = "Accessories Quartermaster",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.414,
      ["y"] = 0.688,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kaymard Copperpinch",
      ["id"] = "13418",
      ["description"] = "Smokywood Pastures",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.532,
      ["y"] = 0.6659999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Penney Copperpinch",
      ["id"] = "13420",
      ["description"] = "Smokywood Pastures",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.53,
      ["y"] = 0.66,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Alowicious Czervik",
      ["id"] = "14480",
      ["description"] = "Sweet Treats",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.52,
      ["y"] = 0.69,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Deze Snowbane",
      ["id"] = "15006",
      ["description"] = "Arathi Basin Battlemaster",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.794,
      ["y"] = 0.292,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Rachelle Gothena",
      ["id"] = "15354",
      ["description"] = "Hallow's End Treats",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.534,
      ["y"] = 0.6579999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Lunar Festival Vendor",
      ["id"] = "15898",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.414,
      ["y"] = 0.324,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jornah",
      ["id"] = "214070",
      ["description"] = "Supply Officer",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.516,
      ["y"] = 0.638,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kaymard Copperpinch",
      ["id"] = "216924",
      ["description"] = "Smokywood Pastures",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.532,
      ["y"] = 0.6659999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Rune Broker",
      ["id"] = "233428",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.494,
      ["y"] = 0.462,
    },
    {
      ["category"] = "book",
      ["name"] = "The Armor of Mannoroth",
      ["id"] = "175658",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.45299999999999996,
      ["y"] = 0.349,
    },
    {
      ["category"] = "forge",
      ["name"] = "Forge",
      ["id"] = "1685",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.718,
      ["y"] = 0.272,
    },
    {
      ["category"] = "mailbox",
      ["name"] = "Mailbox",
      ["id"] = "32349",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Orgrimmar",
      ["subLocation"] = "Orgrimmar",
      ["x"] = 0.504,
      ["y"] = 0.7070000000000001,
    },
  }
}
