DB_REDRIDGE_MOUNTAINS_GENERAL = {
  ["region"] = "Eastern Kingdoms",
  ["mapID"] = 1433,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Kimberly Hiett",
      ["id"] = "789",
      ["description"] = "Fletcher",
      ["comment"] = "",
      ["mainLocation"] = "Redridge Mountains",
      ["subLocation"] = "Redridge Mountains",
      ["x"] = 0.27,
      ["y"] = 0.456,
    },
    {
      ["category"] = "repair",
      ["name"] = "Kara Adams",
      ["id"] = "793",
      ["description"] = "Shield Crafter",
      ["comment"] = "",
      ["mainLocation"] = "Redridge Mountains",
      ["subLocation"] = "Redridge Mountains",
      ["x"] = 0.306,
      ["y"] = 0.466,
    },
    {
      ["category"] = "repair",
      ["name"] = "Dorin Songblade",
      ["id"] = "956",
      ["description"] = "Armorer",
      ["comment"] = "",
      ["mainLocation"] = "Redridge Mountains",
      ["subLocation"] = "Redridge Mountains",
      ["x"] = 0.308,
      ["y"] = 0.466,
    },
    {
      ["category"] = "repair",
      ["name"] = "Henry Chapal",
      ["id"] = "3088",
      ["description"] = "Gunsmith",
      ["comment"] = "",
      ["mainLocation"] = "Redridge Mountains",
      ["subLocation"] = "Redridge Mountains",
      ["x"] = 0.23800000000000002,
      ["y"] = 0.414,
    },
    {
      ["category"] = "repair",
      ["name"] = "Bernard Brubaker",
      ["id"] = "3097",
      ["description"] = "Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Redridge Mountains",
      ["subLocation"] = "Redridge Mountains",
      ["x"] = 0.882,
      ["y"] = 0.7120000000000001,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Innkeeper Brianna",
      ["id"] = "6727",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Redridge Mountains",
      ["subLocation"] = "Redridge Mountains",
      ["x"] = 0.268,
      ["y"] = 0.44799999999999995,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Penny",
      ["id"] = "9982",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "Redridge Mountains",
      ["subLocation"] = "Redridge Mountains",
      ["x"] = 0.268,
      ["y"] = 0.466,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Ariena Stormfeather",
      ["id"] = "931",
      ["description"] = "Gryphon Master",
      ["comment"] = "",
      ["mainLocation"] = "Redridge Mountains",
      ["subLocation"] = "Redridge Mountains",
      ["x"] = 0.306,
      ["y"] = 0.594,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Alma Jainrose",
      ["id"] = "812",
      ["description"] = "Herbalism Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Redridge Mountains",
      ["subLocation"] = "Redridge Mountains",
      ["x"] = 0.214,
      ["y"] = 0.456,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Matthew Hooper",
      ["id"] = "1680",
      ["description"] = "Fishing Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Redridge Mountains",
      ["subLocation"] = "Redridge Mountains",
      ["x"] = 0.266,
      ["y"] = 0.512,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Crystal Boughman",
      ["id"] = "3087",
      ["description"] = "Cooking Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Redridge Mountains",
      ["subLocation"] = "Redridge Mountains",
      ["x"] = 0.228,
      ["y"] = 0.436,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Wilma Ranthal",
      ["id"] = "6295",
      ["description"] = "Skinning Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Redridge Mountains",
      ["subLocation"] = "Redridge Mountains",
      ["x"] = 0.888,
      ["y"] = 0.71,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Amy Davenport",
      ["id"] = "777",
      ["description"] = "Tradeswoman",
      ["comment"] = "",
      ["mainLocation"] = "Redridge Mountains",
      ["subLocation"] = "Redridge Mountains",
      ["x"] = 0.29,
      ["y"] = 0.474,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kimberly Hiett",
      ["id"] = "789",
      ["description"] = "Fletcher",
      ["comment"] = "",
      ["mainLocation"] = "Redridge Mountains",
      ["subLocation"] = "Redridge Mountains",
      ["x"] = 0.27,
      ["y"] = 0.456,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Karen Taylor",
      ["id"] = "790",
      ["description"] = "Mining and Smithing Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Redridge Mountains",
      ["subLocation"] = "Redridge Mountains",
      ["x"] = 0.298,
      ["y"] = 0.474,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Lindsay Ashlock",
      ["id"] = "791",
      ["description"] = "General Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Redridge Mountains",
      ["subLocation"] = "Redridge Mountains",
      ["x"] = 0.28800000000000003,
      ["y"] = 0.474,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kara Adams",
      ["id"] = "793",
      ["description"] = "Shield Crafter",
      ["comment"] = "",
      ["mainLocation"] = "Redridge Mountains",
      ["subLocation"] = "Redridge Mountains",
      ["x"] = 0.306,
      ["y"] = 0.466,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Antonio Perelli",
      ["id"] = "844",
      ["description"] = "Traveling Salesman",
      ["comment"] = "",
      ["mainLocation"] = "Redridge Mountains",
      ["subLocation"] = "Redridge Mountains",
      ["x"] = 0.28800000000000003,
      ["y"] = 0.474,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Dorin Songblade",
      ["id"] = "956",
      ["description"] = "Armorer",
      ["comment"] = "",
      ["mainLocation"] = "Redridge Mountains",
      ["subLocation"] = "Redridge Mountains",
      ["x"] = 0.308,
      ["y"] = 0.466,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Lamar Veisilli",
      ["id"] = "1671",
      ["description"] = "Fruit Seller",
      ["comment"] = "",
      ["mainLocation"] = "Redridge Mountains",
      ["subLocation"] = "Redridge Mountains",
      ["x"] = 0.21,
      ["y"] = 0.46399999999999997,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Vernon Hale",
      ["id"] = "1678",
      ["description"] = "Bait and Tackle Supplier",
      ["comment"] = "",
      ["mainLocation"] = "Redridge Mountains",
      ["subLocation"] = "Redridge Mountains",
      ["x"] = 0.27399999999999997,
      ["y"] = 0.47600000000000003,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Clyde Ranthal",
      ["id"] = "2697",
      ["description"] = "Leatherworking Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Redridge Mountains",
      ["subLocation"] = "Redridge Mountains",
      ["x"] = 0.888,
      ["y"] = 0.71,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Gloria Femmel",
      ["id"] = "3085",
      ["description"] = "Cooking Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Redridge Mountains",
      ["subLocation"] = "Redridge Mountains",
      ["x"] = 0.266,
      ["y"] = 0.434,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Gretchen Vogel",
      ["id"] = "3086",
      ["description"] = "Waitress",
      ["comment"] = "",
      ["mainLocation"] = "Redridge Mountains",
      ["subLocation"] = "Redridge Mountains",
      ["x"] = 0.226,
      ["y"] = 0.442,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Henry Chapal",
      ["id"] = "3088",
      ["description"] = "Gunsmith",
      ["comment"] = "",
      ["mainLocation"] = "Redridge Mountains",
      ["subLocation"] = "Redridge Mountains",
      ["x"] = 0.23800000000000002,
      ["y"] = 0.414,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Sherman Femmel",
      ["id"] = "3089",
      ["description"] = "Butcher",
      ["comment"] = "",
      ["mainLocation"] = "Redridge Mountains",
      ["subLocation"] = "Redridge Mountains",
      ["x"] = 0.268,
      ["y"] = 0.434,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Gerald Crawley",
      ["id"] = "3090",
      ["description"] = "Poison Supplier",
      ["comment"] = "",
      ["mainLocation"] = "Redridge Mountains",
      ["subLocation"] = "Redridge Mountains",
      ["x"] = 0.25,
      ["y"] = 0.41200000000000003,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Franklin Hamar",
      ["id"] = "3091",
      ["description"] = "Tailoring Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Redridge Mountains",
      ["subLocation"] = "Redridge Mountains",
      ["x"] = 0.272,
      ["y"] = 0.45399999999999996,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Captured Servant of Azora",
      ["id"] = "3096",
      ["description"] = "Specialist Tailoring Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Redridge Mountains",
      ["subLocation"] = "Redridge Mountains",
      ["x"] = 0.7440000000000001,
      ["y"] = 0.794,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Bernard Brubaker",
      ["id"] = "3097",
      ["description"] = "Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Redridge Mountains",
      ["subLocation"] = "Redridge Mountains",
      ["x"] = 0.882,
      ["y"] = 0.7120000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Bartender Wental",
      ["id"] = "5620",
      ["description"] = "Food and Drinks",
      ["comment"] = "",
      ["mainLocation"] = "Redridge Mountains",
      ["subLocation"] = "Redridge Mountains",
      ["x"] = 0.268,
      ["y"] = 0.44,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Innkeeper Brianna",
      ["id"] = "6727",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Redridge Mountains",
      ["subLocation"] = "Redridge Mountains",
      ["x"] = 0.268,
      ["y"] = 0.44799999999999995,
    },
    {
      ["category"] = "spirithealer",
      ["name"] = "Spirit Healer",
      ["id"] = "6491",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Redridge Mountains",
      ["subLocation"] = "Redridge Mountains",
      ["x"] = 0.20800000000000002,
      ["y"] = 0.564,
    },
    {
      ["category"] = "book",
      ["name"] = "Missing: Corporal Keeshan",
      ["id"] = "1726",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Redridge Mountains",
      ["subLocation"] = "Redridge Mountains",
      ["x"] = 0.266,
      ["y"] = 0.465,
    },
    {
      ["category"] = "book",
      ["name"] = "War of the Three Hammers",
      ["id"] = "175739",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Redridge Mountains",
      ["subLocation"] = "Redridge Mountains",
      ["x"] = 0.3,
      ["y"] = 0.446,
    },
    {
      ["category"] = "book",
      ["name"] = "The Dark Portal and the Fall of Stormwind",
      ["id"] = "175745",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Redridge Mountains",
      ["subLocation"] = "Redridge Mountains",
      ["x"] = 0.268,
      ["y"] = 0.45799999999999996,
    },
    {
      ["category"] = "mailbox",
      ["name"] = "Mailbox",
      ["id"] = "32349",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Redridge Mountains",
      ["subLocation"] = "Redridge Mountains",
      ["x"] = 0.215,
      ["y"] = 0.466,
    },
  }
}
