DB_SEARING_GORGE_GENERAL = {
  ["region"] = "Eastern Kingdoms",
  ["mapID"] = 1427,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Graw Cornerstone",
      ["id"] = "11703",
      ["description"] = "Mail Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Searing Gorge",
      ["subLocation"] = "Searing Gorge",
      ["x"] = 0.414,
      ["y"] = 0.748,
    },
    {
      ["category"] = "repair",
      ["name"] = "Master Smith Burninate",
      ["id"] = "14624",
      ["description"] = "The Thorium Brotherhood",
      ["comment"] = "",
      ["mainLocation"] = "Searing Gorge",
      ["subLocation"] = "Searing Gorge",
      ["x"] = 0.386,
      ["y"] = 0.284,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Lanie Reed",
      ["id"] = "2941",
      ["description"] = "Gryphon Master",
      ["comment"] = "",
      ["mainLocation"] = "Searing Gorge",
      ["subLocation"] = "Searing Gorge",
      ["x"] = 0.37799999999999995,
      ["y"] = 0.306,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Grisha",
      ["id"] = "3305",
      ["description"] = "Wind Rider Master",
      ["comment"] = "",
      ["mainLocation"] = "Searing Gorge",
      ["subLocation"] = "Searing Gorge",
      ["x"] = 0.348,
      ["y"] = 0.308,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Sarah Tanner",
      ["id"] = "7868",
      ["description"] = "Master Elemental Leatherworker",
      ["comment"] = "",
      ["mainLocation"] = "Searing Gorge",
      ["subLocation"] = "Searing Gorge",
      ["x"] = 0.636,
      ["y"] = 0.758,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Graw Cornerstone",
      ["id"] = "11703",
      ["description"] = "Mail Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Searing Gorge",
      ["subLocation"] = "Searing Gorge",
      ["x"] = 0.414,
      ["y"] = 0.748,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Master Smith Burninate",
      ["id"] = "14624",
      ["description"] = "The Thorium Brotherhood",
      ["comment"] = "",
      ["mainLocation"] = "Searing Gorge",
      ["subLocation"] = "Searing Gorge",
      ["x"] = 0.386,
      ["y"] = 0.284,
    },
    {
      ["category"] = "spirithealer",
      ["name"] = "Spirit Healer",
      ["id"] = "6491",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Searing Gorge",
      ["subLocation"] = "Searing Gorge",
      ["x"] = 0.354,
      ["y"] = 0.22399999999999998,
    },
  }
}
