DB_SILITHUS_GENERAL = {
  ["region"] = "Kalimdor",
  ["mapID"] = 1451,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Vargus",
      ["id"] = "15176",
      ["description"] = "Blacksmith",
      ["comment"] = "",
      ["mainLocation"] = "Silithus",
      ["subLocation"] = "Silithus",
      ["x"] = 0.512,
      ["y"] = 0.38799999999999996,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Calandrath",
      ["id"] = "15174",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Silithus",
      ["subLocation"] = "Silithus",
      ["x"] = 0.518,
      ["y"] = 0.39,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Squire Leoren Mal'derath",
      ["id"] = "15722",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "Silithus",
      ["subLocation"] = "Silithus",
      ["x"] = 0.49200000000000005,
      ["y"] = 0.366,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Cloud Skydancer",
      ["id"] = "15177",
      ["description"] = "Hippogryph Master",
      ["comment"] = "",
      ["mainLocation"] = "Silithus",
      ["subLocation"] = "Silithus",
      ["x"] = 0.506,
      ["y"] = 0.344,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Runk Windtamer",
      ["id"] = "15178",
      ["description"] = "Wind Rider Master",
      ["comment"] = "",
      ["mainLocation"] = "Silithus",
      ["subLocation"] = "Silithus",
      ["x"] = 0.488,
      ["y"] = 0.366,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Zannok Hidepiercer",
      ["id"] = "12956",
      ["description"] = "Leatherworking Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Silithus",
      ["subLocation"] = "Silithus",
      ["x"] = 0.818,
      ["y"] = 0.17800000000000002,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Calandrath",
      ["id"] = "15174",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Silithus",
      ["subLocation"] = "Silithus",
      ["x"] = 0.518,
      ["y"] = 0.39,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Khur Hornstriker",
      ["id"] = "15175",
      ["description"] = "Reagent Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Silithus",
      ["subLocation"] = "Silithus",
      ["x"] = 0.488,
      ["y"] = 0.37,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Vargus",
      ["id"] = "15176",
      ["description"] = "Blacksmith",
      ["comment"] = "",
      ["mainLocation"] = "Silithus",
      ["subLocation"] = "Silithus",
      ["x"] = 0.512,
      ["y"] = 0.38799999999999996,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Mishta",
      ["id"] = "15179",
      ["description"] = "General Trade Goods Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Silithus",
      ["subLocation"] = "Silithus",
      ["x"] = 0.498,
      ["y"] = 0.364,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kania",
      ["id"] = "15419",
      ["description"] = "Enchanting Supplier",
      ["comment"] = "",
      ["mainLocation"] = "Silithus",
      ["subLocation"] = "Silithus",
      ["x"] = 0.52,
      ["y"] = 0.396,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Chief Expeditionary Requisitioner Enkles",
      ["id"] = "17068",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Silithus",
      ["subLocation"] = "Silithus",
      ["x"] = 0.332,
      ["y"] = 0.51,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Apothecary Quinard",
      ["id"] = "17070",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Silithus",
      ["subLocation"] = "Silithus",
      ["x"] = 0.508,
      ["y"] = 0.696,
    },
    {
      ["category"] = "spirithealer",
      ["name"] = "Spirit Healer",
      ["id"] = "6491",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Silithus",
      ["subLocation"] = "Silithus",
      ["x"] = 0.28,
      ["y"] = 0.8740000000000001,
    },
    {
      ["category"] = "mailbox",
      ["name"] = "Mailbox",
      ["id"] = "32349",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Silithus",
      ["subLocation"] = "Silithus",
      ["x"] = 0.517,
      ["y"] = 0.379,
    },
  }
}
