DB_SILVERPINE_FOREST_GENERAL = {
  ["region"] = "Eastern Kingdoms <Horde>",
  ["mapID"] = 1421,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Pyrewood Armorer",
      ["id"] = "3528",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Silverpine Forest",
      ["subLocation"] = "Silverpine Forest",
      ["x"] = 0.46399999999999997,
      ["y"] = 0.718,
    },
    {
      ["category"] = "repair",
      ["name"] = "Moonrage Armorer",
      ["id"] = "3529",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Silverpine Forest",
      ["subLocation"] = "Silverpine Forest",
      ["x"] = 0.46399999999999997,
      ["y"] = 0.72,
    },
    {
      ["category"] = "repair",
      ["name"] = "Pyrewood Tailor",
      ["id"] = "3530",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Silverpine Forest",
      ["subLocation"] = "Silverpine Forest",
      ["x"] = 0.466,
      ["y"] = 0.7240000000000001,
    },
    {
      ["category"] = "repair",
      ["name"] = "Moonrage Tailor",
      ["id"] = "3531",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Silverpine Forest",
      ["subLocation"] = "Silverpine Forest",
      ["x"] = 0.466,
      ["y"] = 0.726,
    },
    {
      ["category"] = "repair",
      ["name"] = "Pyrewood Leatherworker",
      ["id"] = "3532",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Silverpine Forest",
      ["subLocation"] = "Silverpine Forest",
      ["x"] = 0.44,
      ["y"] = 0.738,
    },
    {
      ["category"] = "repair",
      ["name"] = "Moonrage Leatherworker",
      ["id"] = "3533",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Silverpine Forest",
      ["subLocation"] = "Silverpine Forest",
      ["x"] = 0.44,
      ["y"] = 0.738,
    },
    {
      ["category"] = "repair",
      ["name"] = "Wallace the Blind",
      ["id"] = "3534",
      ["description"] = "Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Silverpine Forest",
      ["subLocation"] = "Silverpine Forest",
      ["x"] = 0.46399999999999997,
      ["y"] = 0.8640000000000001,
    },
    {
      ["category"] = "repair",
      ["name"] = "Alexandre Lefevre",
      ["id"] = "3552",
      ["description"] = "Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Silverpine Forest",
      ["subLocation"] = "Silverpine Forest",
      ["x"] = 0.446,
      ["y"] = 0.392,
    },
    {
      ["category"] = "repair",
      ["name"] = "Sebastian Meloche",
      ["id"] = "3553",
      ["description"] = "Armorer",
      ["comment"] = "",
      ["mainLocation"] = "Silverpine Forest",
      ["subLocation"] = "Silverpine Forest",
      ["x"] = 0.43200000000000005,
      ["y"] = 0.41200000000000003,
    },
    {
      ["category"] = "repair",
      ["name"] = "Andrea Boynton",
      ["id"] = "3554",
      ["description"] = "Clothier",
      ["comment"] = "",
      ["mainLocation"] = "Silverpine Forest",
      ["subLocation"] = "Silverpine Forest",
      ["x"] = 0.446,
      ["y"] = 0.392,
    },
    {
      ["category"] = "repair",
      ["name"] = "Nadia Vernon",
      ["id"] = "9553",
      ["description"] = "Bowyer",
      ["comment"] = "",
      ["mainLocation"] = "Silverpine Forest",
      ["subLocation"] = "Silverpine Forest",
      ["x"] = 0.45,
      ["y"] = 0.39399999999999996,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Innkeeper Bates",
      ["id"] = "6739",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Silverpine Forest",
      ["subLocation"] = "Silverpine Forest",
      ["x"] = 0.43200000000000005,
      ["y"] = 0.41200000000000003,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Sarah Goode",
      ["id"] = "9979",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "Silverpine Forest",
      ["subLocation"] = "Silverpine Forest",
      ["x"] = 0.434,
      ["y"] = 0.41200000000000003,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Karos Razok",
      ["id"] = "2226",
      ["description"] = "Bat Handler",
      ["comment"] = "",
      ["mainLocation"] = "Silverpine Forest",
      ["subLocation"] = "Silverpine Forest",
      ["x"] = 0.456,
      ["y"] = 0.424,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Johan Focht",
      ["id"] = "3555",
      ["description"] = "Miner",
      ["comment"] = "",
      ["mainLocation"] = "Silverpine Forest",
      ["subLocation"] = "Silverpine Forest",
      ["x"] = 0.434,
      ["y"] = 0.40399999999999997,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Guillaume Sorouy",
      ["id"] = "3557",
      ["description"] = "Journeyman Blacksmith",
      ["comment"] = "",
      ["mainLocation"] = "Silverpine Forest",
      ["subLocation"] = "Silverpine Forest",
      ["x"] = 0.43200000000000005,
      ["y"] = 0.41,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Edwin Harly",
      ["id"] = "2140",
      ["description"] = "General Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Silverpine Forest",
      ["subLocation"] = "Silverpine Forest",
      ["x"] = 0.44,
      ["y"] = 0.4,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Pyrewood Armorer",
      ["id"] = "3528",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Silverpine Forest",
      ["subLocation"] = "Silverpine Forest",
      ["x"] = 0.46399999999999997,
      ["y"] = 0.718,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Moonrage Armorer",
      ["id"] = "3529",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Silverpine Forest",
      ["subLocation"] = "Silverpine Forest",
      ["x"] = 0.46399999999999997,
      ["y"] = 0.72,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Pyrewood Tailor",
      ["id"] = "3530",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Silverpine Forest",
      ["subLocation"] = "Silverpine Forest",
      ["x"] = 0.466,
      ["y"] = 0.7240000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Moonrage Tailor",
      ["id"] = "3531",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Silverpine Forest",
      ["subLocation"] = "Silverpine Forest",
      ["x"] = 0.466,
      ["y"] = 0.726,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Pyrewood Leatherworker",
      ["id"] = "3532",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Silverpine Forest",
      ["subLocation"] = "Silverpine Forest",
      ["x"] = 0.44,
      ["y"] = 0.738,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Moonrage Leatherworker",
      ["id"] = "3533",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Silverpine Forest",
      ["subLocation"] = "Silverpine Forest",
      ["x"] = 0.44,
      ["y"] = 0.738,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Wallace the Blind",
      ["id"] = "3534",
      ["description"] = "Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Silverpine Forest",
      ["subLocation"] = "Silverpine Forest",
      ["x"] = 0.46399999999999997,
      ["y"] = 0.8640000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Patrice Dwyer",
      ["id"] = "3551",
      ["description"] = "Poison Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Silverpine Forest",
      ["subLocation"] = "Silverpine Forest",
      ["x"] = 0.43,
      ["y"] = 0.418,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Alexandre Lefevre",
      ["id"] = "3552",
      ["description"] = "Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Silverpine Forest",
      ["subLocation"] = "Silverpine Forest",
      ["x"] = 0.446,
      ["y"] = 0.392,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Sebastian Meloche",
      ["id"] = "3553",
      ["description"] = "Armorer",
      ["comment"] = "",
      ["mainLocation"] = "Silverpine Forest",
      ["subLocation"] = "Silverpine Forest",
      ["x"] = 0.43200000000000005,
      ["y"] = 0.41200000000000003,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Andrea Boynton",
      ["id"] = "3554",
      ["description"] = "Clothier",
      ["comment"] = "",
      ["mainLocation"] = "Silverpine Forest",
      ["subLocation"] = "Silverpine Forest",
      ["x"] = 0.446,
      ["y"] = 0.392,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Andrew Hilbert",
      ["id"] = "3556",
      ["description"] = "Trade Goods",
      ["comment"] = "",
      ["mainLocation"] = "Silverpine Forest",
      ["subLocation"] = "Silverpine Forest",
      ["x"] = 0.43200000000000005,
      ["y"] = 0.406,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Dalaran Brewmaster",
      ["id"] = "3577",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Silverpine Forest",
      ["subLocation"] = "Silverpine Forest",
      ["x"] = 0.626,
      ["y"] = 0.648,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Dalaran Miner",
      ["id"] = "3578",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Silverpine Forest",
      ["subLocation"] = "Silverpine Forest",
      ["x"] = 0.626,
      ["y"] = 0.626,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Killian Sanatha",
      ["id"] = "5748",
      ["description"] = "Fisherman",
      ["comment"] = "",
      ["mainLocation"] = "Silverpine Forest",
      ["subLocation"] = "Silverpine Forest",
      ["x"] = 0.33,
      ["y"] = 0.17800000000000002,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Lilly",
      ["id"] = "5757",
      ["description"] = "Enchanting Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Silverpine Forest",
      ["subLocation"] = "Silverpine Forest",
      ["x"] = 0.43,
      ["y"] = 0.508,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Leo Sarn",
      ["id"] = "5758",
      ["description"] = "Enchanting Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Silverpine Forest",
      ["subLocation"] = "Silverpine Forest",
      ["x"] = 0.54,
      ["y"] = 0.8220000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Gwyn Farrow",
      ["id"] = "5886",
      ["description"] = "Mushroom Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Silverpine Forest",
      ["subLocation"] = "Silverpine Forest",
      ["x"] = 0.44,
      ["y"] = 0.39799999999999996,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Innkeeper Bates",
      ["id"] = "6739",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Silverpine Forest",
      ["subLocation"] = "Silverpine Forest",
      ["x"] = 0.43200000000000005,
      ["y"] = 0.41200000000000003,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Nadia Vernon",
      ["id"] = "9553",
      ["description"] = "Bowyer",
      ["comment"] = "",
      ["mainLocation"] = "Silverpine Forest",
      ["subLocation"] = "Silverpine Forest",
      ["x"] = 0.45,
      ["y"] = 0.39399999999999996,
    },
    {
      ["category"] = "spirithealer",
      ["name"] = "Spirit Healer",
      ["id"] = "6491",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Silverpine Forest",
      ["subLocation"] = "Silverpine Forest",
      ["x"] = 0.442,
      ["y"] = 0.414,
    },
    {
      ["category"] = "book",
      ["name"] = "Yuriv's Tombstone",
      ["id"] = "24777",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Silverpine Forest",
      ["subLocation"] = "Silverpine Forest",
      ["x"] = 0.442,
      ["y"] = 0.426,
    },
    {
      ["category"] = "mailbox",
      ["name"] = "Mailbox",
      ["id"] = "32349",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Silverpine Forest",
      ["subLocation"] = "Silverpine Forest",
      ["x"] = 0.434,
      ["y"] = 0.414,
    },
  }
}
