DB_STONETALON_MOUNTAINS_GENERAL = {
  ["region"] = "Kalimdor",
  ["mapID"] = 1442,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Nizzik",
      ["id"] = "4085",
      ["description"] = "Venture Armor Salesman",
      ["comment"] = "",
      ["mainLocation"] = "Stonetalon Mountains",
      ["subLocation"] = "Stonetalon Mountains",
      ["x"] = 0.626,
      ["y"] = 0.402,
    },
    {
      ["category"] = "repair",
      ["name"] = "Veenix",
      ["id"] = "4086",
      ["description"] = "Venture Co. Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stonetalon Mountains",
      ["subLocation"] = "Stonetalon Mountains",
      ["x"] = 0.5820000000000001,
      ["y"] = 0.516,
    },
    {
      ["category"] = "repair",
      ["name"] = "Illyanie",
      ["id"] = "4188",
      ["description"] = "Cloth Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stonetalon Mountains",
      ["subLocation"] = "Stonetalon Mountains",
      ["x"] = 0.354,
      ["y"] = 0.07,
    },
    {
      ["category"] = "repair",
      ["name"] = "Borand",
      ["id"] = "9549",
      ["description"] = "Bowyer",
      ["comment"] = "",
      ["mainLocation"] = "Stonetalon Mountains",
      ["subLocation"] = "Stonetalon Mountains",
      ["x"] = 0.452,
      ["y"] = 0.5920000000000001,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Innkeeper Jayka",
      ["id"] = "7731",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Stonetalon Mountains",
      ["subLocation"] = "Stonetalon Mountains",
      ["x"] = 0.474,
      ["y"] = 0.62,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Innkeeper Faralia",
      ["id"] = "16458",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Stonetalon Mountains",
      ["subLocation"] = "Stonetalon Mountains",
      ["x"] = 0.35600000000000004,
      ["y"] = 0.057999999999999996,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Gereck",
      ["id"] = "10048",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "Stonetalon Mountains",
      ["subLocation"] = "Stonetalon Mountains",
      ["x"] = 0.478,
      ["y"] = 0.612,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Tharm",
      ["id"] = "4312",
      ["description"] = "Wind Rider Master",
      ["comment"] = "",
      ["mainLocation"] = "Stonetalon Mountains",
      ["subLocation"] = "Stonetalon Mountains",
      ["x"] = 0.452,
      ["y"] = 0.598,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Teloren",
      ["id"] = "4407",
      ["description"] = "Hippogryph Master",
      ["comment"] = "",
      ["mainLocation"] = "Stonetalon Mountains",
      ["subLocation"] = "Stonetalon Mountains",
      ["x"] = 0.364,
      ["y"] = 0.07200000000000001,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Hgarth",
      ["id"] = "11074",
      ["description"] = "Artisan Enchanter",
      ["comment"] = "",
      ["mainLocation"] = "Stonetalon Mountains",
      ["subLocation"] = "Stonetalon Mountains",
      ["x"] = 0.49200000000000005,
      ["y"] = 0.5720000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Denni'ka",
      ["id"] = "3411",
      ["description"] = "Butcher",
      ["comment"] = "",
      ["mainLocation"] = "Stonetalon Mountains",
      ["subLocation"] = "Stonetalon Mountains",
      ["x"] = 0.7340000000000001,
      ["y"] = 0.9540000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Grawnal",
      ["id"] = "4082",
      ["description"] = "General Goods",
      ["comment"] = "",
      ["mainLocation"] = "Stonetalon Mountains",
      ["subLocation"] = "Stonetalon Mountains",
      ["x"] = 0.45799999999999996,
      ["y"] = 0.586,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jeeda",
      ["id"] = "4083",
      ["description"] = "Apprentice Witch Doctor",
      ["comment"] = "",
      ["mainLocation"] = "Stonetalon Mountains",
      ["subLocation"] = "Stonetalon Mountains",
      ["x"] = 0.47600000000000003,
      ["y"] = 0.616,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Chylina",
      ["id"] = "4084",
      ["description"] = "General Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Stonetalon Mountains",
      ["subLocation"] = "Stonetalon Mountains",
      ["x"] = 0.35600000000000004,
      ["y"] = 0.062,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Nizzik",
      ["id"] = "4085",
      ["description"] = "Venture Armor Salesman",
      ["comment"] = "",
      ["mainLocation"] = "Stonetalon Mountains",
      ["subLocation"] = "Stonetalon Mountains",
      ["x"] = 0.626,
      ["y"] = 0.402,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Veenix",
      ["id"] = "4086",
      ["description"] = "Venture Co. Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stonetalon Mountains",
      ["subLocation"] = "Stonetalon Mountains",
      ["x"] = 0.5820000000000001,
      ["y"] = 0.516,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Illyanie",
      ["id"] = "4188",
      ["description"] = "Cloth Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stonetalon Mountains",
      ["subLocation"] = "Stonetalon Mountains",
      ["x"] = 0.354,
      ["y"] = 0.07,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Krond",
      ["id"] = "5870",
      ["description"] = "Butcher",
      ["comment"] = "",
      ["mainLocation"] = "Stonetalon Mountains",
      ["subLocation"] = "Stonetalon Mountains",
      ["x"] = 0.462,
      ["y"] = 0.584,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Innkeeper Jayka",
      ["id"] = "7731",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Stonetalon Mountains",
      ["subLocation"] = "Stonetalon Mountains",
      ["x"] = 0.474,
      ["y"] = 0.62,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Borand",
      ["id"] = "9549",
      ["description"] = "Bowyer",
      ["comment"] = "",
      ["mainLocation"] = "Stonetalon Mountains",
      ["subLocation"] = "Stonetalon Mountains",
      ["x"] = 0.452,
      ["y"] = 0.5920000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kulwia",
      ["id"] = "12043",
      ["description"] = "Trade Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Stonetalon Mountains",
      ["subLocation"] = "Stonetalon Mountains",
      ["x"] = 0.45399999999999996,
      ["y"] = 0.594,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Innkeeper Faralia",
      ["id"] = "16458",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Stonetalon Mountains",
      ["subLocation"] = "Stonetalon Mountains",
      ["x"] = 0.35600000000000004,
      ["y"] = 0.057999999999999996,
    },
    {
      ["category"] = "spirithealer",
      ["name"] = "Spirit Healer",
      ["id"] = "6491",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stonetalon Mountains",
      ["subLocation"] = "Stonetalon Mountains",
      ["x"] = 0.574,
      ["y"] = 0.62,
    },
    {
      ["category"] = "mailbox",
      ["name"] = "Mailbox",
      ["id"] = "32349",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stonetalon Mountains",
      ["subLocation"] = "Stonetalon Mountains",
      ["x"] = 0.36,
      ["y"] = 0.073,
    },
  }
}
