DB_STORMWIND_CITY_GENERAL = {
  ["region"] = "Eastern Kingdoms <Alliance>",
  ["mapID"] = 1453,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Marda Weller",
      ["id"] = "1287",
      ["description"] = "Weapons Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.5720000000000001,
      ["y"] = 0.57,
    },
    {
      ["category"] = "repair",
      ["name"] = "Gunther Weller",
      ["id"] = "1289",
      ["description"] = "Weapons Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.5720000000000001,
      ["y"] = 0.5720000000000001,
    },
    {
      ["category"] = "repair",
      ["name"] = "Carla Granger",
      ["id"] = "1291",
      ["description"] = "Cloth Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.55,
      ["y"] = 0.56,
    },
    {
      ["category"] = "repair",
      ["name"] = "Aldric Moore",
      ["id"] = "1294",
      ["description"] = "Mail Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.5479999999999999,
      ["y"] = 0.552,
    },
    {
      ["category"] = "repair",
      ["name"] = "Lara Moore",
      ["id"] = "1295",
      ["description"] = "Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.5479999999999999,
      ["y"] = 0.556,
    },
    {
      ["category"] = "repair",
      ["name"] = "Lina Stover",
      ["id"] = "1297",
      ["description"] = "Bow & Gun Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.504,
      ["y"] = 0.574,
    },
    {
      ["category"] = "repair",
      ["name"] = "Frederick Stover",
      ["id"] = "1298",
      ["description"] = "Bow & Arrow Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.502,
      ["y"] = 0.5760000000000001,
    },
    {
      ["category"] = "repair",
      ["name"] = "Lisbeth Schneider",
      ["id"] = "1299",
      ["description"] = "Clothier",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.496,
      ["y"] = 0.55,
    },
    {
      ["category"] = "repair",
      ["name"] = "Wynne Larson",
      ["id"] = "1309",
      ["description"] = "Robe Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.41600000000000004,
      ["y"] = 0.7659999999999999,
    },
    {
      ["category"] = "repair",
      ["name"] = "Evan Larson",
      ["id"] = "1310",
      ["description"] = "Hatter",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.424,
      ["y"] = 0.7659999999999999,
    },
    {
      ["category"] = "repair",
      ["name"] = "Ardwyn Cailen",
      ["id"] = "1312",
      ["description"] = "Wand Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.428,
      ["y"] = 0.654,
    },
    {
      ["category"] = "repair",
      ["name"] = "Duncan Cullen",
      ["id"] = "1314",
      ["description"] = "Light Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.434,
      ["y"] = 0.742,
    },
    {
      ["category"] = "repair",
      ["name"] = "Allan Hafgan",
      ["id"] = "1315",
      ["description"] = "Staves Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.43,
      ["y"] = 0.654,
    },
    {
      ["category"] = "repair",
      ["name"] = "Bryan Cross",
      ["id"] = "1319",
      ["description"] = "Shield Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.642,
      ["y"] = 0.428,
    },
    {
      ["category"] = "repair",
      ["name"] = "Seoman Griffith",
      ["id"] = "1320",
      ["description"] = "Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.6759999999999999,
      ["y"] = 0.488,
    },
    {
      ["category"] = "repair",
      ["name"] = "Osric Strang",
      ["id"] = "1323",
      ["description"] = "Heavy Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.742,
      ["y"] = 0.474,
    },
    {
      ["category"] = "repair",
      ["name"] = "Heinrich Stone",
      ["id"] = "1324",
      ["description"] = "Blade Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.742,
      ["y"] = 0.428,
    },
    {
      ["category"] = "repair",
      ["name"] = "Gerik Koen",
      ["id"] = "1333",
      ["description"] = "Two Handed Weapon Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.69,
      ["y"] = 0.424,
    },
    {
      ["category"] = "repair",
      ["name"] = "Mayda Thane",
      ["id"] = "1339",
      ["description"] = "Cobbler",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.67,
      ["y"] = 0.43200000000000005,
    },
    {
      ["category"] = "repair",
      ["name"] = "Wilhelm Strang",
      ["id"] = "1341",
      ["description"] = "Mail Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.746,
      ["y"] = 0.478,
    },
    {
      ["category"] = "repair",
      ["name"] = "Gregory Ardus",
      ["id"] = "1348",
      ["description"] = "Staff & Mace Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.37,
      ["y"] = 0.39399999999999996,
    },
    {
      ["category"] = "repair",
      ["name"] = "Agustus Moulaine",
      ["id"] = "1349",
      ["description"] = "Mail Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.43799999999999994,
      ["y"] = 0.43200000000000005,
    },
    {
      ["category"] = "repair",
      ["name"] = "Theresa Moulaine",
      ["id"] = "1350",
      ["description"] = "Robe Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.436,
      ["y"] = 0.434,
    },
    {
      ["category"] = "repair",
      ["name"] = "Kathrum Axehand",
      ["id"] = "5509",
      ["description"] = "Axe Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.514,
      ["y"] = 0.124,
    },
    {
      ["category"] = "repair",
      ["name"] = "Thulman Flintcrag",
      ["id"] = "5510",
      ["description"] = "Guns Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.544,
      ["y"] = 0.152,
    },
    {
      ["category"] = "repair",
      ["name"] = "Kaita Deepforge",
      ["id"] = "5512",
      ["description"] = "Blacksmithing Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.564,
      ["y"] = 0.17,
    },
    {
      ["category"] = "repair",
      ["name"] = "Officer Areyn",
      ["id"] = "12805",
      ["description"] = "Accessories Quartermaster",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.738,
      ["y"] = 0.534,
    },
    {
      ["category"] = "auctioneer",
      ["name"] = "Auctioneer Chilton",
      ["id"] = "8670",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.532,
      ["y"] = 0.606,
    },
    {
      ["category"] = "auctioneer",
      ["name"] = "Auctioneer Fitch",
      ["id"] = "8719",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.536,
      ["y"] = 0.604,
    },
    {
      ["category"] = "auctioneer",
      ["name"] = "Auctioneer Jaxon",
      ["id"] = "15659",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.534,
      ["y"] = 0.596,
    },
    {
      ["category"] = "banker",
      ["name"] = "Olivia Burnside",
      ["id"] = "2455",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.574,
      ["y"] = 0.7240000000000001,
    },
    {
      ["category"] = "banker",
      ["name"] = "Newton Burnside",
      ["id"] = "2456",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.57,
      ["y"] = 0.728,
    },
    {
      ["category"] = "banker",
      ["name"] = "John Burnside",
      ["id"] = "2457",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.564,
      ["y"] = 0.732,
    },
    {
      ["category"] = "battlemaster",
      ["name"] = "Thelman Slatefist",
      ["id"] = "7410",
      ["description"] = "Alterac Valley Battlemaster",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.772,
      ["y"] = 0.16399999999999998,
    },
    {
      ["category"] = "battlemaster",
      ["name"] = "Elfarran",
      ["id"] = "14981",
      ["description"] = "Warsong Gulch Battlemaster",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.7879999999999999,
      ["y"] = 0.19399999999999998,
    },
    {
      ["category"] = "battlemaster",
      ["name"] = "League of Arathor Emissary",
      ["id"] = "14991",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.544,
      ["y"] = 0.626,
    },
    {
      ["category"] = "battlemaster",
      ["name"] = "Lady Hoteshem",
      ["id"] = "15008",
      ["description"] = "Arathi Basin Battlemaster",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.782,
      ["y"] = 0.16,
    },
    {
      ["category"] = "battlemaster",
      ["name"] = "Silverwing Emissary",
      ["id"] = "15102",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.544,
      ["y"] = 0.626,
    },
    {
      ["category"] = "battlemaster",
      ["name"] = "Stormpike Emissary",
      ["id"] = "15103",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.544,
      ["y"] = 0.626,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Innkeeper Allison",
      ["id"] = "6740",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.526,
      ["y"] = 0.6559999999999999,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Sylista",
      ["id"] = "9977",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.294,
      ["y"] = 0.512,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Jenova Stoneshield",
      ["id"] = "11069",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.612,
      ["y"] = 0.172,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Dungar Longdrink",
      ["id"] = "352",
      ["description"] = "Gryphon Master",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.662,
      ["y"] = 0.624,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Maginor Dumas",
      ["id"] = "331",
      ["description"] = "Master Mage",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.38,
      ["y"] = 0.816,
    },
    {
      ["category"] = "trainer",
      ["name"] = "High Priestess Laurena",
      ["id"] = "376",
      ["description"] = "Priest Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.38799999999999996,
      ["y"] = 0.264,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Demisette Cloyce",
      ["id"] = "461",
      ["description"] = "Warlock Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.254,
      ["y"] = 0.782,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Ander Germaine",
      ["id"] = "914",
      ["description"] = "Warrior Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.782,
      ["y"] = 0.47200000000000003,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Osborne the Night Man",
      ["id"] = "918",
      ["description"] = "Rogue Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.7440000000000001,
      ["y"] = 0.528,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Lord Grayson Shadowbreaker",
      ["id"] = "928",
      ["description"] = "Paladin Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.37200000000000005,
      ["y"] = 0.33,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Dane Lindgren",
      ["id"] = "957",
      ["description"] = "Journeyman Blacksmith",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.5720000000000001,
      ["y"] = 0.16399999999999998,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Maris Granger",
      ["id"] = "1292",
      ["description"] = "Skinning Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.6779999999999999,
      ["y"] = 0.49,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Lawrence Schneider",
      ["id"] = "1300",
      ["description"] = "Journeyman Tailor",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.436,
      ["y"] = 0.738,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Lucan Cordell",
      ["id"] = "1317",
      ["description"] = "Expert Enchanter",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.43,
      ["y"] = 0.644,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Georgio Bolero",
      ["id"] = "1346",
      ["description"] = "Artisan Tailor",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.43200000000000005,
      ["y"] = 0.736,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Shaina Fuller",
      ["id"] = "2327",
      ["description"] = "First Aid Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.428,
      ["y"] = 0.264,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Larimaine Purdue",
      ["id"] = "2485",
      ["description"] = "Portal Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.39399999999999996,
      ["y"] = 0.7959999999999999,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Karrina Mekenda",
      ["id"] = "2879",
      ["description"] = "Pet Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.616,
      ["y"] = 0.158,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Wu Shen",
      ["id"] = "5479",
      ["description"] = "Warrior Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.7879999999999999,
      ["y"] = 0.456,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Ilsa Corbin",
      ["id"] = "5480",
      ["description"] = "Warrior Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.7859999999999999,
      ["y"] = 0.456,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Stephen Ryback",
      ["id"] = "5482",
      ["description"] = "Cooking Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.7559999999999999,
      ["y"] = 0.37,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Brother Benjamin",
      ["id"] = "5484",
      ["description"] = "Priest Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.414,
      ["y"] = 0.28800000000000003,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Brother Joshua",
      ["id"] = "5489",
      ["description"] = "Priest Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.38799999999999996,
      ["y"] = 0.268,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Arthur the Faithful",
      ["id"] = "5491",
      ["description"] = "Paladin Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.386,
      ["y"] = 0.326,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Katherine the Pure",
      ["id"] = "5492",
      ["description"] = "Paladin Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.374,
      ["y"] = 0.32,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Arnold Leland",
      ["id"] = "5493",
      ["description"] = "Fishing Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.45799999999999996,
      ["y"] = 0.5820000000000001,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Ursula Deline",
      ["id"] = "5495",
      ["description"] = "Warlock Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.262,
      ["y"] = 0.774,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Sandahl",
      ["id"] = "5496",
      ["description"] = "Warlock Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.258,
      ["y"] = 0.79,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Jennea Cannon",
      ["id"] = "5497",
      ["description"] = "Mage Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.386,
      ["y"] = 0.794,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Elsharin",
      ["id"] = "5498",
      ["description"] = "Mage Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.37,
      ["y"] = 0.812,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Lilyssia Nightbreeze",
      ["id"] = "5499",
      ["description"] = "Expert Alchemist",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.46399999999999997,
      ["y"] = 0.794,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Tel'Athir",
      ["id"] = "5500",
      ["description"] = "Journeyman Alchemist",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.46399999999999997,
      ["y"] = 0.79,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Shylamiir",
      ["id"] = "5502",
      ["description"] = "Herbalism Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.152,
      ["y"] = 0.498,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Sheldras Moontree",
      ["id"] = "5504",
      ["description"] = "Druid Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.21,
      ["y"] = 0.5539999999999999,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Theridran",
      ["id"] = "5505",
      ["description"] = "Druid Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.214,
      ["y"] = 0.514,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Maldryn",
      ["id"] = "5506",
      ["description"] = "Druid Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.19,
      ["y"] = 0.524,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Therum Deepforge",
      ["id"] = "5511",
      ["description"] = "Expert Blacksmith",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.568,
      ["y"] = 0.16399999999999998,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Gelman Stonehand",
      ["id"] = "5513",
      ["description"] = "Mining Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.51,
      ["y"] = 0.172,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Einris Brightspear",
      ["id"] = "5515",
      ["description"] = "Hunter Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.616,
      ["y"] = 0.154,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Ulfir Ironbeard",
      ["id"] = "5516",
      ["description"] = "Hunter Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.62,
      ["y"] = 0.15,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Thorfin Stoneshield",
      ["id"] = "5517",
      ["description"] = "Hunter Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.624,
      ["y"] = 0.146,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Lilliam Sparkspindle",
      ["id"] = "5518",
      ["description"] = "Expert Engineer",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.5479999999999999,
      ["y"] = 0.078,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Simon Tanner",
      ["id"] = "5564",
      ["description"] = "Expert Leatherworker",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.672,
      ["y"] = 0.496,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Tannysa",
      ["id"] = "5566",
      ["description"] = "Herbalism Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.44799999999999995,
      ["y"] = 0.77,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Sellandus",
      ["id"] = "5567",
      ["description"] = "Expert Tailor",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.42,
      ["y"] = 0.762,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Borgus Steelhand",
      ["id"] = "7232",
      ["description"] = "Weapon Crafter",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.514,
      ["y"] = 0.126,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Jalane Ayrole",
      ["id"] = "9584",
      ["description"] = "Master Shadoweave Tailor",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.266,
      ["y"] = 0.7759999999999999,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Sprite Jumpsprocket",
      ["id"] = "11026",
      ["description"] = "Journeyman Engineer",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.546,
      ["y"] = 0.08,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Betty Quin",
      ["id"] = "11068",
      ["description"] = "Journeyman Enchanter",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.43200000000000005,
      ["y"] = 0.638,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Randal Worth",
      ["id"] = "11096",
      ["description"] = "Journeyman Leatherworker",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.6779999999999999,
      ["y"] = 0.494,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Nara Meideros",
      ["id"] = "11397",
      ["description"] = "Priest Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.20800000000000002,
      ["y"] = 0.502,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Woo Ping",
      ["id"] = "11867",
      ["description"] = "Weapon Master",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.57,
      ["y"] = 0.5760000000000001,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Lord Tony Romano",
      ["id"] = "13283",
      ["description"] = "Rogue Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.782,
      ["y"] = 0.5720000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Roberto Pupellyverbos",
      ["id"] = "277",
      ["description"] = "Merlot Connoisseur",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.52,
      ["y"] = 0.6779999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kendor Kabonka",
      ["id"] = "340",
      ["description"] = "Master of Cooking Recipes",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.746,
      ["y"] = 0.368,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Elaine Trias",
      ["id"] = "483",
      ["description"] = "Mistress of Cheese",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.604,
      ["y"] = 0.634,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Keldric Boucher",
      ["id"] = "1257",
      ["description"] = "Arcane Goods Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.5579999999999999,
      ["y"] = 0.652,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kyra Boucher",
      ["id"] = "1275",
      ["description"] = "Reagent Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.562,
      ["y"] = 0.65,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Thurman Mullby",
      ["id"] = "1285",
      ["description"] = "General Goods Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.5820000000000001,
      ["y"] = 0.614,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Edna Mullby",
      ["id"] = "1286",
      ["description"] = "Trade Supplier",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.58,
      ["y"] = 0.606,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Marda Weller",
      ["id"] = "1287",
      ["description"] = "Weapons Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.5720000000000001,
      ["y"] = 0.57,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Gunther Weller",
      ["id"] = "1289",
      ["description"] = "Weapons Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.5720000000000001,
      ["y"] = 0.5720000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Carla Granger",
      ["id"] = "1291",
      ["description"] = "Cloth Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.55,
      ["y"] = 0.56,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Aldric Moore",
      ["id"] = "1294",
      ["description"] = "Mail Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.5479999999999999,
      ["y"] = 0.552,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Lara Moore",
      ["id"] = "1295",
      ["description"] = "Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.5479999999999999,
      ["y"] = 0.556,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Lina Stover",
      ["id"] = "1297",
      ["description"] = "Bow & Gun Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.504,
      ["y"] = 0.574,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Frederick Stover",
      ["id"] = "1298",
      ["description"] = "Bow & Arrow Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.502,
      ["y"] = 0.5760000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Lisbeth Schneider",
      ["id"] = "1299",
      ["description"] = "Clothier",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.496,
      ["y"] = 0.55,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Julia Gallina",
      ["id"] = "1301",
      ["description"] = "Wine Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.518,
      ["y"] = 0.684,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Bernard Gump",
      ["id"] = "1302",
      ["description"] = "Florist",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.642,
      ["y"] = 0.61,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Felicia Gump",
      ["id"] = "1303",
      ["description"] = "Herbalism Supplier",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.642,
      ["y"] = 0.606,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Darian Singh",
      ["id"] = "1304",
      ["description"] = "Fireworks Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.29600000000000004,
      ["y"] = 0.6779999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jarel Moor",
      ["id"] = "1305",
      ["description"] = "Bartender",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.28600000000000003,
      ["y"] = 0.75,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Charys Yserian",
      ["id"] = "1307",
      ["description"] = "Arcane Trinkets Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.324,
      ["y"] = 0.8,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Owen Vaughn",
      ["id"] = "1308",
      ["description"] = "Reagent Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.36,
      ["y"] = 0.748,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Wynne Larson",
      ["id"] = "1309",
      ["description"] = "Robe Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.41600000000000004,
      ["y"] = 0.7659999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Evan Larson",
      ["id"] = "1310",
      ["description"] = "Hatter",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.424,
      ["y"] = 0.7659999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Joachim Brenlow",
      ["id"] = "1311",
      ["description"] = "Bartender",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.408,
      ["y"] = 0.898,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Ardwyn Cailen",
      ["id"] = "1312",
      ["description"] = "Wand Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.428,
      ["y"] = 0.654,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Maria Lumere",
      ["id"] = "1313",
      ["description"] = "Alchemy Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.466,
      ["y"] = 0.7879999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Duncan Cullen",
      ["id"] = "1314",
      ["description"] = "Light Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.434,
      ["y"] = 0.742,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Allan Hafgan",
      ["id"] = "1315",
      ["description"] = "Staves Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.43,
      ["y"] = 0.654,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Adair Gilroy",
      ["id"] = "1316",
      ["description"] = "Librarian",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.414,
      ["y"] = 0.652,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jessara Cordell",
      ["id"] = "1318",
      ["description"] = "Enchanting Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.43,
      ["y"] = 0.642,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Bryan Cross",
      ["id"] = "1319",
      ["description"] = "Shield Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.642,
      ["y"] = 0.428,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Seoman Griffith",
      ["id"] = "1320",
      ["description"] = "Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.6759999999999999,
      ["y"] = 0.488,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Alyssa Griffith",
      ["id"] = "1321",
      ["description"] = "Bag Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.674,
      ["y"] = 0.49,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Osric Strang",
      ["id"] = "1323",
      ["description"] = "Heavy Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.742,
      ["y"] = 0.474,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Heinrich Stone",
      ["id"] = "1324",
      ["description"] = "Blade Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.742,
      ["y"] = 0.428,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jasper Fel",
      ["id"] = "1325",
      ["description"] = "Shady Dealer",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.782,
      ["y"] = 0.588,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Sloan McCoy",
      ["id"] = "1326",
      ["description"] = "Poison Supplier",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.764,
      ["y"] = 0.6,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Elly Langston",
      ["id"] = "1328",
      ["description"] = "Barmaid",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.732,
      ["y"] = 0.374,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Gerik Koen",
      ["id"] = "1333",
      ["description"] = "Two Handed Weapon Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.69,
      ["y"] = 0.424,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Mayda Thane",
      ["id"] = "1339",
      ["description"] = "Cobbler",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.67,
      ["y"] = 0.43200000000000005,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Wilhelm Strang",
      ["id"] = "1341",
      ["description"] = "Mail Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.746,
      ["y"] = 0.478,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Alexandra Bolero",
      ["id"] = "1347",
      ["description"] = "Tailoring Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.434,
      ["y"] = 0.74,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Gregory Ardus",
      ["id"] = "1348",
      ["description"] = "Staff & Mace Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.37,
      ["y"] = 0.39399999999999996,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Agustus Moulaine",
      ["id"] = "1349",
      ["description"] = "Mail Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.43799999999999994,
      ["y"] = 0.43200000000000005,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Theresa Moulaine",
      ["id"] = "1350",
      ["description"] = "Robe Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.436,
      ["y"] = 0.434,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Brother Cassius",
      ["id"] = "1351",
      ["description"] = "Reagent Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.434,
      ["y"] = 0.268,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Milton Sheaf",
      ["id"] = "1440",
      ["description"] = "Librarian",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.74,
      ["y"] = 0.076,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Thomas Miller",
      ["id"] = "3518",
      ["description"] = "Baker",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.578,
      ["y"] = 0.63,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Ben Trias",
      ["id"] = "4981",
      ["description"] = "Apprentice of Cheese",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.604,
      ["y"] = 0.636,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Rebecca Laughlin",
      ["id"] = "5193",
      ["description"] = "Tabard Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.574,
      ["y"] = 0.682,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Erika Tate",
      ["id"] = "5483",
      ["description"] = "Cooking Supplier",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.758,
      ["y"] = 0.368,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Catherine Leland",
      ["id"] = "5494",
      ["description"] = "Fishing Supplier",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.45799999999999996,
      ["y"] = 0.5820000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Eldraeith",
      ["id"] = "5503",
      ["description"] = "Herbalism Supplier",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.46399999999999997,
      ["y"] = 0.7859999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kathrum Axehand",
      ["id"] = "5509",
      ["description"] = "Axe Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.514,
      ["y"] = 0.124,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Thulman Flintcrag",
      ["id"] = "5510",
      ["description"] = "Guns Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.544,
      ["y"] = 0.152,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kaita Deepforge",
      ["id"] = "5512",
      ["description"] = "Blacksmithing Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.564,
      ["y"] = 0.17,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Brooke Stonebraid",
      ["id"] = "5514",
      ["description"] = "Mining Supplier",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.512,
      ["y"] = 0.168,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Billibub Cogspinner",
      ["id"] = "5519",
      ["description"] = "Engineering Supplier",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.552,
      ["y"] = 0.07400000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Spackle Thornberry",
      ["id"] = "5520",
      ["description"] = "Demon Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.258,
      ["y"] = 0.7759999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jillian Tanner",
      ["id"] = "5565",
      ["description"] = "Leatherworking Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.672,
      ["y"] = 0.494,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Innkeeper Allison",
      ["id"] = "6740",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.526,
      ["y"] = 0.6559999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Lillian Singh",
      ["id"] = "8118",
      ["description"] = "Holiday Fireworks Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.552,
      ["y"] = 0.5920000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Lil Timmy",
      ["id"] = "8666",
      ["description"] = "Boy with kittens",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.64,
      ["y"] = 0.38,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Officer Areyn",
      ["id"] = "12805",
      ["description"] = "Accessories Quartermaster",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.738,
      ["y"] = 0.534,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Khole Jinglepocket",
      ["id"] = "13435",
      ["description"] = "Smokywood Pastures",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.55,
      ["y"] = 0.5920000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Guchie Jinglepocket",
      ["id"] = "13436",
      ["description"] = "Smokywood Pastures",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.552,
      ["y"] = 0.5920000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Orphan Matron Nightingale",
      ["id"] = "14450",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.47200000000000003,
      ["y"] = 0.384,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Emmithue Smails",
      ["id"] = "14481",
      ["description"] = "Sweet Treats",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.5379999999999999,
      ["y"] = 0.652,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Lunar Festival Vendor",
      ["id"] = "15898",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.228,
      ["y"] = 0.514,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Liv Bradford",
      ["id"] = "203475",
      ["description"] = "Bartender",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.226,
      ["y"] = 0.642,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Elaine Compton",
      ["id"] = "213077",
      ["description"] = "Supply Officer",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.546,
      ["y"] = 0.612,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Rune Broker",
      ["id"] = "233335",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.5760000000000001,
      ["y"] = 0.27,
    },
    {
      ["category"] = "book",
      ["name"] = "Aftermath of the Second War",
      ["id"] = "21581",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.73,
      ["y"] = 0.096,
    },
    {
      ["category"] = "book",
      ["name"] = "Beyond the Dark Portal",
      ["id"] = "21582",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.732,
      ["y"] = 0.062,
    },
    {
      ["category"] = "book",
      ["name"] = "The Kaldorei and the Well of Eternity",
      ["id"] = "21583",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.7190000000000001,
      ["y"] = 0.071,
    },
    {
      ["category"] = "book",
      ["name"] = "Kurdran Wildhammer",
      ["id"] = "25329",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.6659999999999999,
      ["y"] = 0.8140000000000001,
    },
    {
      ["category"] = "book",
      ["name"] = "General Turalyon",
      ["id"] = "25330",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.638,
      ["y"] = 0.7509999999999999,
    },
    {
      ["category"] = "book",
      ["name"] = "Ranger Captain Alleria Windrunner",
      ["id"] = "25331",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.6559999999999999,
      ["y"] = 0.773,
    },
    {
      ["category"] = "book",
      ["name"] = "Danath Trollbane",
      ["id"] = "25332",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.674,
      ["y"] = 0.805,
    },
    {
      ["category"] = "book",
      ["name"] = "Archmage Khadgar of the Kirin Tor",
      ["id"] = "25333",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.649,
      ["y"] = 0.782,
    },
    {
      ["category"] = "book",
      ["name"] = "Horatio Montgomery, M.D.",
      ["id"] = "124374",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.7759999999999999,
      ["y"] = 0.589,
    },
    {
      ["category"] = "book",
      ["name"] = "The War of the Ancients",
      ["id"] = "175727",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.218,
      ["y"] = 0.619,
    },
    {
      ["category"] = "book",
      ["name"] = "The World Tree and the Emerald Dream",
      ["id"] = "175730",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.204,
      ["y"] = 0.504,
    },
    {
      ["category"] = "book",
      ["name"] = "The Guardians of Tirisfal",
      ["id"] = "175735",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.7290000000000001,
      ["y"] = 0.096,
    },
    {
      ["category"] = "book",
      ["name"] = "Aegwynn and the Dragon Hunt",
      ["id"] = "175738",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.732,
      ["y"] = 0.067,
    },
    {
      ["category"] = "book",
      ["name"] = "War of the Three Hammers",
      ["id"] = "175739",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.6459999999999999,
      ["y"] = 0.212,
    },
    {
      ["category"] = "book",
      ["name"] = "The Alliance of Lordaeron",
      ["id"] = "175746",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.73,
      ["y"] = 0.096,
    },
    {
      ["category"] = "book",
      ["name"] = "The New Horde",
      ["id"] = "175752",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.725,
      ["y"] = 0.096,
    },
    {
      ["category"] = "book",
      ["name"] = "War of the Spider",
      ["id"] = "175753",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.8220000000000001,
      ["y"] = 0.11599999999999999,
    },
    {
      ["category"] = "book",
      ["name"] = "Civil War in the Plaguelands",
      ["id"] = "175761",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.732,
      ["y"] = 0.1,
    },
    {
      ["category"] = "book",
      ["name"] = "Archbishop Alonsus Faol",
      ["id"] = "177199",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.46299999999999997,
      ["y"] = 0.406,
    },
    {
      ["category"] = "book",
      ["name"] = "King Llane I of the House of Wrynn",
      ["id"] = "177200",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.642,
      ["y"] = 0.068,
    },
    {
      ["category"] = "book",
      ["name"] = "Grand Admiral Daelin Proudmoore",
      ["id"] = "177201",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.647,
      ["y"] = 0.068,
    },
    {
      ["category"] = "book",
      ["name"] = "Lady Mara Fordragon",
      ["id"] = "177202",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.6409999999999999,
      ["y"] = 0.076,
    },
    {
      ["category"] = "book",
      ["name"] = "Alliance Military Ranks",
      ["id"] = "179735",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.727,
      ["y"] = 0.5379999999999999,
    },
    {
      ["category"] = "forge",
      ["name"] = "Forge",
      ["id"] = "1685",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.632,
      ["y"] = 0.375,
    },
    {
      ["category"] = "mailbox",
      ["name"] = "Mailbox",
      ["id"] = "32349",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stormwind City",
      ["subLocation"] = "Stormwind City",
      ["x"] = 0.222,
      ["y"] = 0.574,
    },
  }
}
