DB_STRANGLETHORN_VALE_GENERAL = {
  ["region"] = "Eastern Kingdoms",
  ["mapID"] = 1434,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Vharr",
      ["id"] = "1146",
      ["description"] = "Superior Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.322,
      ["y"] = 0.28,
    },
    {
      ["category"] = "repair",
      ["name"] = "Hragran",
      ["id"] = "1147",
      ["description"] = "Cloth & Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.316,
      ["y"] = 0.29,
    },
    {
      ["category"] = "repair",
      ["name"] = "Krakk",
      ["id"] = "1381",
      ["description"] = "Superior Armorer",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.324,
      ["y"] = 0.28,
    },
    {
      ["category"] = "repair",
      ["name"] = "Zarena Cromwind",
      ["id"] = "2482",
      ["description"] = "Superior Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.284,
      ["y"] = 0.754,
    },
    {
      ["category"] = "repair",
      ["name"] = "Jaquilina Dramet",
      ["id"] = "2483",
      ["description"] = "Superior Axecrafter",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.35600000000000004,
      ["y"] = 0.106,
    },
    {
      ["category"] = "repair",
      ["name"] = "Haren Kanmae",
      ["id"] = "2839",
      ["description"] = "Superior Bowyer",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.282,
      ["y"] = 0.746,
    },
    {
      ["category"] = "repair",
      ["name"] = "Kizz Bluntstrike",
      ["id"] = "2840",
      ["description"] = "Macecrafter",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.282,
      ["y"] = 0.752,
    },
    {
      ["category"] = "repair",
      ["name"] = "Jutak",
      ["id"] = "2843",
      ["description"] = "Blade Trader",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.27399999999999997,
      ["y"] = 0.774,
    },
    {
      ["category"] = "repair",
      ["name"] = "Hurklor",
      ["id"] = "2844",
      ["description"] = "Blacksmithing Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.29,
      ["y"] = 0.75,
    },
    {
      ["category"] = "repair",
      ["name"] = "Fargon Mortalak",
      ["id"] = "2845",
      ["description"] = "Superior Armorer",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.29,
      ["y"] = 0.75,
    },
    {
      ["category"] = "repair",
      ["name"] = "Jansen Underwood",
      ["id"] = "2847",
      ["description"] = "Blacksmithing Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.29,
      ["y"] = 0.754,
    },
    {
      ["category"] = "repair",
      ["name"] = "Qixdi Goodstitch",
      ["id"] = "2849",
      ["description"] = "Cloth Armor and Accessories",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.282,
      ["y"] = 0.774,
    },
    {
      ["category"] = "repair",
      ["name"] = "Rin'wosho the Trader",
      ["id"] = "14921",
      ["description"] = "Zandalar Supplies and Repair",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.15,
      ["y"] = 0.16,
    },
    {
      ["category"] = "repair",
      ["name"] = "Rix Xizzix",
      ["id"] = "214954",
      ["description"] = "Lost and Found",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.284,
      ["y"] = 0.758,
    },
    {
      ["category"] = "repair",
      ["name"] = "Zalgo the Explorer",
      ["id"] = "222413",
      ["description"] = "Purveyor of Lost Goods",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.152,
      ["y"] = 0.156,
    },
    {
      ["category"] = "repair",
      ["name"] = "Pix Xizzix",
      ["id"] = "227853",
      ["description"] = "Undermine Trader",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.284,
      ["y"] = 0.758,
    },
    {
      ["category"] = "repair",
      ["name"] = "Bubbles",
      ["id"] = "235251",
      ["description"] = "Toy Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.284,
      ["y"] = 0.754,
    },
    {
      ["category"] = "auctioneer",
      ["name"] = "Auctioneer Kresky",
      ["id"] = "9858",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.278,
      ["y"] = 0.77,
    },
    {
      ["category"] = "auctioneer",
      ["name"] = "Auctioneer Graves",
      ["id"] = "15677",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.284,
      ["y"] = 0.758,
    },
    {
      ["category"] = "auctioneer",
      ["name"] = "Auctioneer O'reely",
      ["id"] = "15681",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.266,
      ["y"] = 0.764,
    },
    {
      ["category"] = "banker",
      ["name"] = "Viznik Goldgrubber",
      ["id"] = "2625",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.266,
      ["y"] = 0.764,
    },
    {
      ["category"] = "banker",
      ["name"] = "Rickle Goldgrubber",
      ["id"] = "8123",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.266,
      ["y"] = 0.764,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Innkeeper Thulbek",
      ["id"] = "5814",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.314,
      ["y"] = 0.29600000000000004,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Innkeeper Skindle",
      ["id"] = "6807",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.27,
      ["y"] = 0.772,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Grimestack",
      ["id"] = "10060",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.272,
      ["y"] = 0.772,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Durik",
      ["id"] = "16094",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.318,
      ["y"] = 0.294,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Thysta",
      ["id"] = "1387",
      ["description"] = "Wind Rider Master",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.324,
      ["y"] = 0.292,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Gringer",
      ["id"] = "2858",
      ["description"] = "Wind Rider Master",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.268,
      ["y"] = 0.77,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Gyll",
      ["id"] = "2859",
      ["description"] = "Gryphon Master",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.27399999999999997,
      ["y"] = 0.778,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Flora Silverwind",
      ["id"] = "908",
      ["description"] = "Superior Herbalist",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.276,
      ["y"] = 0.778,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Mudduk",
      ["id"] = "1382",
      ["description"] = "Superior Cook",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.314,
      ["y"] = 0.28,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Brawn",
      ["id"] = "1385",
      ["description"] = "Expert Leatherworker",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.316,
      ["y"] = 0.28800000000000003,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Kragg",
      ["id"] = "1404",
      ["description"] = "Hunter Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.312,
      ["y"] = 0.28600000000000003,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Ian Strom",
      ["id"] = "1411",
      ["description"] = "Rogue Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.268,
      ["y"] = 0.772,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Grarnik Goodstitch",
      ["id"] = "2627",
      ["description"] = "Expert Tailor",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.28600000000000003,
      ["y"] = 0.768,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Myizz Luckycatch",
      ["id"] = "2834",
      ["description"] = "Superior Fisherman",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.27399999999999997,
      ["y"] = 0.77,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Brikk Keencraft",
      ["id"] = "2836",
      ["description"] = "Master Blacksmith",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.29,
      ["y"] = 0.754,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Jaxin Chong",
      ["id"] = "2837",
      ["description"] = "Expert Alchemist",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.28,
      ["y"] = 0.78,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Angrun",
      ["id"] = "2856",
      ["description"] = "Superior Herbalist",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.322,
      ["y"] = 0.27399999999999997,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Zudd",
      ["id"] = "3624",
      ["description"] = "Pet Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.312,
      ["y"] = 0.28800000000000003,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Oglethorpe Obnoticus",
      ["id"] = "7406",
      ["description"] = "Master Gnome Engineer",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.282,
      ["y"] = 0.762,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Se'Jib",
      ["id"] = "7871",
      ["description"] = "Master Tribal Leatherworker",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.366,
      ["y"] = 0.342,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Corporal Bluth",
      ["id"] = "734",
      ["description"] = "Camp Trader",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.38,
      ["y"] = 0.03,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Vharr",
      ["id"] = "1146",
      ["description"] = "Superior Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.322,
      ["y"] = 0.28,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Hragran",
      ["id"] = "1147",
      ["description"] = "Cloth & Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.316,
      ["y"] = 0.29,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Nerrist",
      ["id"] = "1148",
      ["description"] = "Trade Goods",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.326,
      ["y"] = 0.292,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Uthok",
      ["id"] = "1149",
      ["description"] = "General Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.316,
      ["y"] = 0.28,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Krakk",
      ["id"] = "1381",
      ["description"] = "Superior Armorer",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.324,
      ["y"] = 0.28,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Zarena Cromwind",
      ["id"] = "2482",
      ["description"] = "Superior Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.284,
      ["y"] = 0.754,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jaquilina Dramet",
      ["id"] = "2483",
      ["description"] = "Superior Axecrafter",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.35600000000000004,
      ["y"] = 0.106,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Sly Garrett",
      ["id"] = "2622",
      ["description"] = "Shady Goods",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.284,
      ["y"] = 0.768,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Old Man Heming",
      ["id"] = "2626",
      ["description"] = "Fisherman",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.27399999999999997,
      ["y"] = 0.77,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Narkk",
      ["id"] = "2663",
      ["description"] = "Pirate Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.282,
      ["y"] = 0.7440000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kelsey Yance",
      ["id"] = "2664",
      ["description"] = "Cook",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.282,
      ["y"] = 0.7440000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Xizk Goodstitch",
      ["id"] = "2670",
      ["description"] = "Tailoring Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.28600000000000003,
      ["y"] = 0.768,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Cowardly Crosby",
      ["id"] = "2672",
      ["description"] = "Tailoring Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.27,
      ["y"] = 0.8240000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Mazk Snipeshot",
      ["id"] = "2685",
      ["description"] = "Engineering Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.284,
      ["y"] = 0.75,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Gnaz Blunderflame",
      ["id"] = "2687",
      ["description"] = "Engineering Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.51,
      ["y"] = 0.35200000000000004,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Rikqiz",
      ["id"] = "2699",
      ["description"] = "Leatherworking Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.284,
      ["y"] = 0.76,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Nixxrax Fillamug",
      ["id"] = "2832",
      ["description"] = "Food and Drink",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.27,
      ["y"] = 0.772,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Crazk Sparks",
      ["id"] = "2838",
      ["description"] = "Fireworks Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.282,
      ["y"] = 0.7659999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Haren Kanmae",
      ["id"] = "2839",
      ["description"] = "Superior Bowyer",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.282,
      ["y"] = 0.746,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kizz Bluntstrike",
      ["id"] = "2840",
      ["description"] = "Macecrafter",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.282,
      ["y"] = 0.752,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Wigcik",
      ["id"] = "2842",
      ["description"] = "Superior Fisherman",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.28,
      ["y"] = 0.768,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jutak",
      ["id"] = "2843",
      ["description"] = "Blade Trader",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.27399999999999997,
      ["y"] = 0.774,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Hurklor",
      ["id"] = "2844",
      ["description"] = "Blacksmithing Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.29,
      ["y"] = 0.75,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Fargon Mortalak",
      ["id"] = "2845",
      ["description"] = "Superior Armorer",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.29,
      ["y"] = 0.75,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Blixrez Goodstitch",
      ["id"] = "2846",
      ["description"] = "Leatherworking Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.282,
      ["y"] = 0.774,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jansen Underwood",
      ["id"] = "2847",
      ["description"] = "Blacksmithing Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.29,
      ["y"] = 0.754,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Glyx Brewright",
      ["id"] = "2848",
      ["description"] = "Alchemy Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.28,
      ["y"] = 0.78,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Qixdi Goodstitch",
      ["id"] = "2849",
      ["description"] = "Cloth Armor and Accessories",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.282,
      ["y"] = 0.774,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Innkeeper Thulbek",
      ["id"] = "5814",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.314,
      ["y"] = 0.29600000000000004,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Innkeeper Skindle",
      ["id"] = "6807",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.27,
      ["y"] = 0.772,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Nargatt",
      ["id"] = "7485",
      ["description"] = "Food & Drink",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.322,
      ["y"] = 0.292,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Ziggle Sparks",
      ["id"] = "8116",
      ["description"] = "Holiday Fireworks Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.276,
      ["y"] = 0.7759999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Knaz Blunderflame",
      ["id"] = "8679",
      ["description"] = "Engineering Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.51,
      ["y"] = 0.35200000000000004,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Rin'wosho the Trader",
      ["id"] = "14921",
      ["description"] = "Zandalar Supplies and Repair",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.15,
      ["y"] = 0.16,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Rix Xizzix",
      ["id"] = "214954",
      ["description"] = "Lost and Found",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.284,
      ["y"] = 0.758,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Mai'zin",
      ["id"] = "218115",
      ["description"] = "Gurubashi Bloodchanger",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.312,
      ["y"] = 0.484,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Zalgo the Explorer",
      ["id"] = "222413",
      ["description"] = "Purveyor of Lost Goods",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.152,
      ["y"] = 0.156,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Pix Xizzix",
      ["id"] = "227853",
      ["description"] = "Undermine Trader",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.284,
      ["y"] = 0.758,
    },
    {
      ["category"] = "spirithealer",
      ["name"] = "Spirit Healer",
      ["id"] = "6491",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.3,
      ["y"] = 0.73,
    },
    {
      ["category"] = "book",
      ["name"] = "Beyond the Dark Portal",
      ["id"] = "21582",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.26899999999999996,
      ["y"] = 0.773,
    },
    {
      ["category"] = "book",
      ["name"] = "The Sentinels and the Long Vigil",
      ["id"] = "175732",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.278,
      ["y"] = 0.772,
    },
    {
      ["category"] = "book",
      ["name"] = "The Scourge of Lordaeron",
      ["id"] = "175756",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.27699999999999997,
      ["y"] = 0.7709999999999999,
    },
    {
      ["category"] = "book",
      ["name"] = "Sunwell - The Fall of Quel'Thalas",
      ["id"] = "175757",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.271,
      ["y"] = 0.777,
    },
    {
      ["category"] = "book",
      ["name"] = "The Twin Empires",
      ["id"] = "175854",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.278,
      ["y"] = 0.773,
    },
    {
      ["category"] = "book",
      ["name"] = "Empires' Fall",
      ["id"] = "175855",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.278,
      ["y"] = 0.773,
    },
    {
      ["category"] = "book",
      ["name"] = "Wrath of Soulflayer",
      ["id"] = "175856",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.278,
      ["y"] = 0.773,
    },
    {
      ["category"] = "book",
      ["name"] = "Altar of Zanza",
      ["id"] = "180367",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.134,
      ["y"] = 0.151,
    },
    {
      ["category"] = "mailbox",
      ["name"] = "Mailbox",
      ["id"] = "32349",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Stranglethorn Vale",
      ["subLocation"] = "Stranglethorn Vale",
      ["x"] = 0.267,
      ["y"] = 0.764,
    },
  }
}
