DB_SWAMP_OF_SORROWS_GENERAL = {
  ["region"] = "Eastern Kingdoms",
  ["mapID"] = 1435,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Grimnal",
      ["id"] = "980",
      ["description"] = "Mail & Plate Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Swamp of Sorrows",
      ["subLocation"] = "Swamp of Sorrows",
      ["x"] = 0.45,
      ["y"] = 0.502,
    },
    {
      ["category"] = "repair",
      ["name"] = "Hartash",
      ["id"] = "981",
      ["description"] = "Weapon Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Swamp of Sorrows",
      ["subLocation"] = "Swamp of Sorrows",
      ["x"] = 0.45799999999999996,
      ["y"] = 0.51,
    },
    {
      ["category"] = "repair",
      ["name"] = "Thralosh",
      ["id"] = "984",
      ["description"] = "Cloth & Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Swamp of Sorrows",
      ["subLocation"] = "Swamp of Sorrows",
      ["x"] = 0.44799999999999995,
      ["y"] = 0.514,
    },
    {
      ["category"] = "repair",
      ["name"] = "Gharash",
      ["id"] = "8176",
      ["description"] = "Blacksmithing Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Swamp of Sorrows",
      ["subLocation"] = "Swamp of Sorrows",
      ["x"] = 0.45399999999999996,
      ["y"] = 0.516,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Innkeeper Karakul",
      ["id"] = "6930",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Swamp of Sorrows",
      ["subLocation"] = "Swamp of Sorrows",
      ["x"] = 0.45,
      ["y"] = 0.5660000000000001,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Hekkru",
      ["id"] = "10049",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "Swamp of Sorrows",
      ["subLocation"] = "Swamp of Sorrows",
      ["x"] = 0.45399999999999996,
      ["y"] = 0.55,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Breyk",
      ["id"] = "6026",
      ["description"] = "Wind Rider Master",
      ["comment"] = "",
      ["mainLocation"] = "Swamp of Sorrows",
      ["subLocation"] = "Swamp of Sorrows",
      ["x"] = 0.46,
      ["y"] = 0.546,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Malosh",
      ["id"] = "985",
      ["description"] = "Warrior Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Swamp of Sorrows",
      ["subLocation"] = "Swamp of Sorrows",
      ["x"] = 0.44799999999999995,
      ["y"] = 0.574,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Haromm",
      ["id"] = "986",
      ["description"] = "Shaman Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Swamp of Sorrows",
      ["subLocation"] = "Swamp of Sorrows",
      ["x"] = 0.48,
      ["y"] = 0.578,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Ogromm",
      ["id"] = "987",
      ["description"] = "Hunter Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Swamp of Sorrows",
      ["subLocation"] = "Swamp of Sorrows",
      ["x"] = 0.47200000000000003,
      ["y"] = 0.532,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Kartosh",
      ["id"] = "988",
      ["description"] = "Warlock Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Swamp of Sorrows",
      ["subLocation"] = "Swamp of Sorrows",
      ["x"] = 0.484,
      ["y"] = 0.5539999999999999,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Rogvar",
      ["id"] = "1386",
      ["description"] = "Master Alchemist",
      ["comment"] = "",
      ["mainLocation"] = "Swamp of Sorrows",
      ["subLocation"] = "Swamp of Sorrows",
      ["x"] = 0.484,
      ["y"] = 0.556,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Grokor",
      ["id"] = "3622",
      ["description"] = "Pet Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Swamp of Sorrows",
      ["subLocation"] = "Swamp of Sorrows",
      ["x"] = 0.47200000000000003,
      ["y"] = 0.53,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Grimnal",
      ["id"] = "980",
      ["description"] = "Mail & Plate Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Swamp of Sorrows",
      ["subLocation"] = "Swamp of Sorrows",
      ["x"] = 0.45,
      ["y"] = 0.502,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Hartash",
      ["id"] = "981",
      ["description"] = "Weapon Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Swamp of Sorrows",
      ["subLocation"] = "Swamp of Sorrows",
      ["x"] = 0.45799999999999996,
      ["y"] = 0.51,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Thultash",
      ["id"] = "982",
      ["description"] = "Food & Drink Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Swamp of Sorrows",
      ["subLocation"] = "Swamp of Sorrows",
      ["x"] = 0.46399999999999997,
      ["y"] = 0.542,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Thultazor",
      ["id"] = "983",
      ["description"] = "Arcane Goods Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Swamp of Sorrows",
      ["subLocation"] = "Swamp of Sorrows",
      ["x"] = 0.45799999999999996,
      ["y"] = 0.53,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Thralosh",
      ["id"] = "984",
      ["description"] = "Cloth & Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Swamp of Sorrows",
      ["subLocation"] = "Swamp of Sorrows",
      ["x"] = 0.44799999999999995,
      ["y"] = 0.514,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Banalash",
      ["id"] = "989",
      ["description"] = "Trade Goods",
      ["comment"] = "",
      ["mainLocation"] = "Swamp of Sorrows",
      ["subLocation"] = "Swamp of Sorrows",
      ["x"] = 0.446,
      ["y"] = 0.568,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Innkeeper Karakul",
      ["id"] = "6930",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Swamp of Sorrows",
      ["subLocation"] = "Swamp of Sorrows",
      ["x"] = 0.45,
      ["y"] = 0.5660000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Gharash",
      ["id"] = "8176",
      ["description"] = "Blacksmithing Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Swamp of Sorrows",
      ["subLocation"] = "Swamp of Sorrows",
      ["x"] = 0.45399999999999996,
      ["y"] = 0.516,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Rartar",
      ["id"] = "8177",
      ["description"] = "Alchemy Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Swamp of Sorrows",
      ["subLocation"] = "Swamp of Sorrows",
      ["x"] = 0.45399999999999996,
      ["y"] = 0.57,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Masat T'andr",
      ["id"] = "11874",
      ["description"] = "Superior Leatherworker",
      ["comment"] = "",
      ["mainLocation"] = "Swamp of Sorrows",
      ["subLocation"] = "Swamp of Sorrows",
      ["x"] = 0.264,
      ["y"] = 0.316,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Greshka",
      ["id"] = "12807",
      ["description"] = "Demon Master",
      ["comment"] = "",
      ["mainLocation"] = "Swamp of Sorrows",
      ["subLocation"] = "Swamp of Sorrows",
      ["x"] = 0.484,
      ["y"] = 0.5539999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Amaryllis Webb",
      ["id"] = "217412",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Swamp of Sorrows",
      ["subLocation"] = "Swamp of Sorrows",
      ["x"] = 0.25,
      ["y"] = 0.542,
    },
    {
      ["category"] = "spirithealer",
      ["name"] = "Spirit Healer",
      ["id"] = "6491",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Swamp of Sorrows",
      ["subLocation"] = "Swamp of Sorrows",
      ["x"] = 0.502,
      ["y"] = 0.622,
    },
    {
      ["category"] = "book",
      ["name"] = "Rise of the Horde",
      ["id"] = "175742",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Swamp of Sorrows",
      ["subLocation"] = "Swamp of Sorrows",
      ["x"] = 0.479,
      ["y"] = 0.5489999999999999,
    },
    {
      ["category"] = "book",
      ["name"] = "The Dark Portal and the Fall of Stormwind",
      ["id"] = "175745",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Swamp of Sorrows",
      ["subLocation"] = "Swamp of Sorrows",
      ["x"] = 0.478,
      ["y"] = 0.55,
    },
    {
      ["category"] = "book",
      ["name"] = "The New Horde",
      ["id"] = "175752",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Swamp of Sorrows",
      ["subLocation"] = "Swamp of Sorrows",
      ["x"] = 0.478,
      ["y"] = 0.55,
    },
    {
      ["category"] = "mailbox",
      ["name"] = "Mailbox",
      ["id"] = "32349",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Swamp of Sorrows",
      ["subLocation"] = "Swamp of Sorrows",
      ["x"] = 0.45399999999999996,
      ["y"] = 0.55,
    },
  }
}
