DB_TANARIS_GENERAL = {
  ["region"] = "Kalimdor",
  ["mapID"] = 1446,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Krinkle Goodsteel",
      ["id"] = "5411",
      ["description"] = "Blacksmithing Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Tanaris",
      ["subLocation"] = "Tanaris",
      ["x"] = 0.514,
      ["y"] = 0.28800000000000003,
    },
    {
      ["category"] = "repair",
      ["name"] = "Wrinkle Goodsteel",
      ["id"] = "8129",
      ["description"] = "Superior Armor Crafter",
      ["comment"] = "",
      ["mainLocation"] = "Tanaris",
      ["subLocation"] = "Tanaris",
      ["x"] = 0.508,
      ["y"] = 0.276,
    },
    {
      ["category"] = "repair",
      ["name"] = "Blizrik Buckshot",
      ["id"] = "8131",
      ["description"] = "Gunsmith",
      ["comment"] = "",
      ["mainLocation"] = "Tanaris",
      ["subLocation"] = "Tanaris",
      ["x"] = 0.508,
      ["y"] = 0.276,
    },
    {
      ["category"] = "auctioneer",
      ["name"] = "Auctioneer Beardo",
      ["id"] = "8661",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Tanaris",
      ["subLocation"] = "Tanaris",
      ["x"] = 0.52,
      ["y"] = 0.29600000000000004,
    },
    {
      ["category"] = "banker",
      ["name"] = "Gimblethorn",
      ["id"] = "7799",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "Tanaris",
      ["subLocation"] = "Tanaris",
      ["x"] = 0.522,
      ["y"] = 0.28800000000000003,
    },
    {
      ["category"] = "banker",
      ["name"] = "Qizzik",
      ["id"] = "8124",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "Tanaris",
      ["subLocation"] = "Tanaris",
      ["x"] = 0.524,
      ["y"] = 0.28800000000000003,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Innkeeper Fizzgrimble",
      ["id"] = "7733",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Tanaris",
      ["subLocation"] = "Tanaris",
      ["x"] = 0.524,
      ["y"] = 0.278,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Laziphus",
      ["id"] = "9985",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "Tanaris",
      ["subLocation"] = "Tanaris",
      ["x"] = 0.522,
      ["y"] = 0.28,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Bera Stonehammer",
      ["id"] = "7823",
      ["description"] = "Gryphon Master",
      ["comment"] = "",
      ["mainLocation"] = "Tanaris",
      ["subLocation"] = "Tanaris",
      ["x"] = 0.51,
      ["y"] = 0.292,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Bulkrek Ragefist",
      ["id"] = "7824",
      ["description"] = "Wind Rider Master",
      ["comment"] = "",
      ["mainLocation"] = "Tanaris",
      ["subLocation"] = "Tanaris",
      ["x"] = 0.516,
      ["y"] = 0.254,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Nixx Sprocketspring",
      ["id"] = "8126",
      ["description"] = "Master Goblin Engineer",
      ["comment"] = "",
      ["mainLocation"] = "Tanaris",
      ["subLocation"] = "Tanaris",
      ["x"] = 0.524,
      ["y"] = 0.272,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Pikkle",
      ["id"] = "8128",
      ["description"] = "Miner",
      ["comment"] = "",
      ["mainLocation"] = "Tanaris",
      ["subLocation"] = "Tanaris",
      ["x"] = 0.51,
      ["y"] = 0.28,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Buzzek Bracketswing",
      ["id"] = "8736",
      ["description"] = "Master Engineer",
      ["comment"] = "",
      ["mainLocation"] = "Tanaris",
      ["subLocation"] = "Tanaris",
      ["x"] = 0.522,
      ["y"] = 0.276,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Krinkle Goodsteel",
      ["id"] = "5411",
      ["description"] = "Blacksmithing Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Tanaris",
      ["subLocation"] = "Tanaris",
      ["x"] = 0.514,
      ["y"] = 0.28800000000000003,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Alchemist Pestlezugg",
      ["id"] = "5594",
      ["description"] = "Alchemy Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Tanaris",
      ["subLocation"] = "Tanaris",
      ["x"] = 0.508,
      ["y"] = 0.27,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Vizzklick",
      ["id"] = "6568",
      ["description"] = "Tailoring Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Tanaris",
      ["subLocation"] = "Tanaris",
      ["x"] = 0.51,
      ["y"] = 0.27399999999999997,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Marin Noggenfogger",
      ["id"] = "7564",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Tanaris",
      ["subLocation"] = "Tanaris",
      ["x"] = 0.518,
      ["y"] = 0.28600000000000003,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Innkeeper Fizzgrimble",
      ["id"] = "7733",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Tanaris",
      ["subLocation"] = "Tanaris",
      ["x"] = 0.524,
      ["y"] = 0.278,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Dirge Quikcleave",
      ["id"] = "8125",
      ["description"] = "Butcher",
      ["comment"] = "",
      ["mainLocation"] = "Tanaris",
      ["subLocation"] = "Tanaris",
      ["x"] = 0.526,
      ["y"] = 0.28,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Wrinkle Goodsteel",
      ["id"] = "8129",
      ["description"] = "Superior Armor Crafter",
      ["comment"] = "",
      ["mainLocation"] = "Tanaris",
      ["subLocation"] = "Tanaris",
      ["x"] = 0.508,
      ["y"] = 0.276,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Blizrik Buckshot",
      ["id"] = "8131",
      ["description"] = "Gunsmith",
      ["comment"] = "",
      ["mainLocation"] = "Tanaris",
      ["subLocation"] = "Tanaris",
      ["x"] = 0.508,
      ["y"] = 0.276,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Gikkix",
      ["id"] = "8137",
      ["description"] = "Fisherman",
      ["comment"] = "",
      ["mainLocation"] = "Tanaris",
      ["subLocation"] = "Tanaris",
      ["x"] = 0.6659999999999999,
      ["y"] = 0.22,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jabbey",
      ["id"] = "8139",
      ["description"] = "General Goods",
      ["comment"] = "",
      ["mainLocation"] = "Tanaris",
      ["subLocation"] = "Tanaris",
      ["x"] = 0.67,
      ["y"] = 0.22,
    },
    {
      ["category"] = "spirithealer",
      ["name"] = "Spirit Healer",
      ["id"] = "6491",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Tanaris",
      ["subLocation"] = "Tanaris",
      ["x"] = 0.54,
      ["y"] = 0.28600000000000003,
    },
    {
      ["category"] = "book",
      ["name"] = "Ironforge - the Awakening of the Dwarves",
      ["id"] = "175736",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Tanaris",
      ["subLocation"] = "Tanaris",
      ["x"] = 0.369,
      ["y"] = 0.77,
    },
    {
      ["category"] = "book",
      ["name"] = "Old Hatreds - The Colonization of Kalimdor",
      ["id"] = "175763",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Tanaris",
      ["subLocation"] = "Tanaris",
      ["x"] = 0.51,
      ["y"] = 0.294,
    },
    {
      ["category"] = "book",
      ["name"] = "The Twin Empires",
      ["id"] = "175854",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Tanaris",
      ["subLocation"] = "Tanaris",
      ["x"] = 0.526,
      ["y"] = 0.278,
    },
    {
      ["category"] = "book",
      ["name"] = "Empires' Fall",
      ["id"] = "175855",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Tanaris",
      ["subLocation"] = "Tanaris",
      ["x"] = 0.526,
      ["y"] = 0.278,
    },
    {
      ["category"] = "book",
      ["name"] = "Wrath of Soulflayer",
      ["id"] = "175856",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Tanaris",
      ["subLocation"] = "Tanaris",
      ["x"] = 0.526,
      ["y"] = 0.278,
    },
    {
      ["category"] = "mailbox",
      ["name"] = "Mailbox",
      ["id"] = "32349",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Tanaris",
      ["subLocation"] = "Tanaris",
      ["x"] = 0.523,
      ["y"] = 0.278,
    },
  }
}
