DB_TELDRASSIL_GENERAL = {
  ["mapID"] = 1438,
  ["zoneName"] = "Teldrassil",
  ["region"] = "Kalimdor <Alliance>",
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Khardan Proudblade",
      ["id"] = "3588",
      ["description"] = "Weaponsmith",
      ["x"] = 0.588,
      ["y"] = 0.396,
    },
    {
      ["category"] = "repair",
      ["name"] = "Keina",
      ["id"] = "3589",
      ["description"] = "Bowyer",
      ["x"] = 0.594,
      ["y"] = 0.412,
    },
    {
      ["category"] = "repair",
      ["name"] = "Janna Brightmoon",
      ["id"] = "3590",
      ["description"] = "Clothier",
      ["x"] = 0.594,
      ["y"] = 0.41,
    },
    {
      ["category"] = "repair",
      ["name"] = "Freja Nightwing",
      ["id"] = "3591",
      ["description"] = "Leather Armor Merchant",
      ["x"] = 0.59,
      ["y"] = 0.396,
    },
    {
      ["category"] = "repair",
      ["name"] = "Andiss",
      ["id"] = "3592",
      ["description"] = "Armorer & Shieldcrafter",
      ["x"] = 0.586,
      ["y"] = 0.398,
    },
    {
      ["category"] = "repair",
      ["name"] = "Shalomon",
      ["id"] = "3609",
      ["description"] = "Weaponsmith",
      ["x"] = 0.562,
      ["y"] = 0.594,
    },
    {
      ["category"] = "repair",
      ["name"] = "Jeena Featherbow",
      ["id"] = "3610",
      ["description"] = "Bowyer",
      ["x"] = 0.558,
      ["y"] = 0.592,
    },
    {
      ["category"] = "repair",
      ["name"] = "Brannol Eaglemoon",
      ["id"] = "3611",
      ["description"] = "Clothier",
      ["x"] = 0.562,
      ["y"] = 0.602,
    },
    {
      ["category"] = "repair",
      ["name"] = "Sinda",
      ["id"] = "3612",
      ["description"] = "Leather Armor Merchant",
      ["x"] = 0.562,
      ["y"] = 0.596,
    },
    {
      ["category"] = "repair",
      ["name"] = "Meri Ironweave",
      ["id"] = "3613",
      ["description"] = "Armorer & Shieldcrafter",
      ["x"] = 0.562,
      ["y"] = 0.594,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Innkeeper Keldamyr",
      ["id"] = "6736",
      ["description"] = "Innkeeper",
      ["comment"] = "旅店",
      ["x"] = 0.556,
      ["y"] = 0.598,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Seriadne",
      ["id"] = "10051",
      ["description"] = "Stable Master",
      ["comment"] = "營火",
      ["x"] = 0.566,
      ["y"] = 0.596,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Vesprystus",
      ["id"] = "3838",
      ["description"] = "Hippogryph Master",
      ["x"] = 0.584,
      ["y"] = 0.94,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Keldas",
      ["id"] = "3306",
      ["description"] = "Pet Trainer",
      ["x"] = 0.568,
      ["y"] = 0.596,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Alyissia",
      ["id"] = "3593",
      ["description"] = "Warrior Trainer",
      ["comment"] = "戰士",
      ["x"] = 0.596,
      ["y"] = 0.384,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Frahun Shadewhisper",
      ["id"] = "3594",
      ["description"] = "Rogue Trainer",
      ["comment"] = "盜賊",
      ["x"] = 0.596,
      ["y"] = 0.386,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Shanda",
      ["id"] = "3595",
      ["description"] = "Priest Trainer",
      ["x"] = 0.592,
      ["y"] = 0.404,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Ayanna Everstride",
      ["id"] = "3596",
      ["description"] = "Hunter Trainer",
      ["comment"] = "獵人",
      ["x"] = 0.586,
      ["y"] = 0.404,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Mardant Strongoak",
      ["id"] = "3597",
      ["description"] = "Druid Trainer",
      ["comment"] = "德魯伊",
      ["x"] = 0.586,
      ["y"] = 0.404,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Kyra Windblade",
      ["id"] = "3598",
      ["description"] = "Warrior Trainer",
      ["x"] = 0.562,
      ["y"] = 0.592,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Jannok Breezesong",
      ["id"] = "3599",
      ["description"] = "Rogue Trainer",
      ["x"] = 0.562,
      ["y"] = 0.6,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Laurna Morninglight",
      ["id"] = "3600",
      ["description"] = "Priest Trainer",
      ["comment"] = "僧侶",
      ["x"] = 0.556,
      ["y"] = 0.568,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Dazalar",
      ["id"] = "3601",
      ["description"] = "Hunter Trainer",
      ["x"] = 0.566,
      ["y"] = 0.596,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Kal",
      ["id"] = "3602",
      ["description"] = "Druid Trainer",
      ["x"] = 0.56,
      ["y"] = 0.616,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Cyndra Kindwhisper",
      ["id"] = "3603",
      ["description"] = "Journeyman Alchemist",
      ["x"] = 0.576,
      ["y"] = 0.606,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Malorne Bladeleaf",
      ["id"] = "3604",
      ["description"] = "Herbalist",
      ["comment"] = "草藥",
      ["x"] = 0.576,
      ["y"] = 0.606,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Nadyia Maneweaver",
      ["id"] = "3605",
      ["description"] = "Journeyman Leatherworker",
      ["x"] = 0.418,
      ["y"] = 0.494,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Alanna Raveneye",
      ["id"] = "3606",
      ["description"] = "Journeyman Enchanter",
      ["x"] = 0.368,
      ["y"] = 0.342,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Androl Oakhand",
      ["id"] = "3607",
      ["description"] = "Fisherman",
      ["comment"] = "釣魚",
      ["x"] = 0.558,
      ["y"] = 0.934,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Byancie",
      ["id"] = "6094",
      ["description"] = "First Aid Trainer",
      ["comment"] = "急救",
      ["x"] = 0.552,
      ["y"] = 0.568,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Zarrin",
      ["id"] = "6286",
      ["description"] = "Cook",
      ["x"] = 0.57,
      ["y"] = 0.612,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Radnaal Maneweaver",
      ["id"] = "6287",
      ["description"] = "Skinner",
      ["comment"] = "剝皮",
      ["x"] = 0.42,
      ["y"] = 0.5,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Lyrai",
      ["id"] = "3587",
      ["description"] = "General Supplies",
      ["comment"] = "雜貨",
      ["x"] = 0.594,
      ["y"] = 0.41,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Khardan Proudblade",
      ["id"] = "3588",
      ["description"] = "Weaponsmith",
      ["x"] = 0.588,
      ["y"] = 0.396,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Keina",
      ["id"] = "3589",
      ["description"] = "Bowyer",
      ["x"] = 0.594,
      ["y"] = 0.412,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Janna Brightmoon",
      ["id"] = "3590",
      ["description"] = "Clothier",
      ["x"] = 0.594,
      ["y"] = 0.41,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Freja Nightwing",
      ["id"] = "3591",
      ["description"] = "Leather Armor Merchant",
      ["x"] = 0.59,
      ["y"] = 0.396,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Andiss",
      ["id"] = "3592",
      ["description"] = "Armorer & Shieldcrafter",
      ["x"] = 0.586,
      ["y"] = 0.398,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Shalomon",
      ["id"] = "3609",
      ["description"] = "Weaponsmith",
      ["x"] = 0.562,
      ["y"] = 0.594,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jeena Featherbow",
      ["id"] = "3610",
      ["description"] = "Bowyer",
      ["x"] = 0.558,
      ["y"] = 0.592,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Brannol Eaglemoon",
      ["id"] = "3611",
      ["description"] = "Clothier",
      ["x"] = 0.562,
      ["y"] = 0.602,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Sinda",
      ["id"] = "3612",
      ["description"] = "Leather Armor Merchant",
      ["x"] = 0.562,
      ["y"] = 0.596,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Meri Ironweave",
      ["id"] = "3613",
      ["description"] = "Armorer & Shieldcrafter",
      ["x"] = 0.562,
      ["y"] = 0.594,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Narret Shadowgrove",
      ["id"] = "3614",
      ["description"] = "Trade Supplies",
      ["x"] = 0.552,
      ["y"] = 0.57,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Nyoma",
      ["id"] = "4265",
      ["description"] = "Cooking Supplies",
      ["comment"] = "烹飪",
      ["x"] = 0.572,
      ["y"] = 0.612,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Danlyia",
      ["id"] = "4266",
      ["description"] = "Food & Drink Vendor",
      ["x"] = 0.554,
      ["y"] = 0.57,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Dellylah",
      ["id"] = "6091",
      ["description"] = "Food & Drink Vendor",
      ["x"] = 0.596,
      ["y"] = 0.408,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Innkeeper Keldamyr",
      ["id"] = "6736",
      ["description"] = "Innkeeper",
      ["x"] = 0.556,
      ["y"] = 0.598,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Nessa Shadowsong",
      ["id"] = "10118",
      ["description"] = "Fishing Supplies",
      ["comment"] = "釣魚",
      ["x"] = 0.562,
      ["y"] = 0.924,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Rune Broker",
      ["id"] = "233335",
      ["x"] = 0.588,
      ["y"] = 0.438,
    },
    {
      ["category"] = "spirithealer",
      ["name"] = "Spirit Healer",
      ["id"] = "6491",
      ["comment"] = "魂點",
      ["x"] = 0.562,
      ["y"] = 0.632,
    },
    {
      ["category"] = "mailbox",
      ["name"] = "Mailbox",
      ["id"] = "32349",
      ["x"] = 0.561,
      ["y"] = 0.584,
    },
  }
}

