DB_THE_BARRENS_GENERAL = {
  ["region"] = "Kalimdor <Horde>",
  ["mapID"] = 1413,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Hraq",
      ["id"] = "3477",
      ["description"] = "Blacksmithing Supplier",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.512,
      ["y"] = 0.29,
    },
    {
      ["category"] = "repair",
      ["name"] = "Nargal Deatheye",
      ["id"] = "3479",
      ["description"] = "Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.512,
      ["y"] = 0.292,
    },
    {
      ["category"] = "repair",
      ["name"] = "Jahan Hawkwing",
      ["id"] = "3483",
      ["description"] = "Leather & Mail Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.512,
      ["y"] = 0.29,
    },
    {
      ["category"] = "repair",
      ["name"] = "Halija Whitestrider",
      ["id"] = "3486",
      ["description"] = "Clothier",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.522,
      ["y"] = 0.318,
    },
    {
      ["category"] = "repair",
      ["name"] = "Uthrok",
      ["id"] = "3488",
      ["description"] = "Bowyer & Gunsmith",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.51,
      ["y"] = 0.29,
    },
    {
      ["category"] = "repair",
      ["name"] = "Ironzar",
      ["id"] = "3491",
      ["description"] = "Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.622,
      ["y"] = 0.374,
    },
    {
      ["category"] = "repair",
      ["name"] = "Vexspindle",
      ["id"] = "3492",
      ["description"] = "Cloth & Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.622,
      ["y"] = 0.384,
    },
    {
      ["category"] = "repair",
      ["name"] = "Grazlix",
      ["id"] = "3493",
      ["description"] = "Armorer & Shieldcrafter",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.622,
      ["y"] = 0.384,
    },
    {
      ["category"] = "repair",
      ["name"] = "Lizzarik",
      ["id"] = "3658",
      ["description"] = "Weapon Dealer",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.618,
      ["y"] = 0.382,
    },
    {
      ["category"] = "repair",
      ["name"] = "Vrang Wildgore",
      ["id"] = "3682",
      ["description"] = "Weaponsmith & Armorcrafter",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.43799999999999994,
      ["y"] = 0.122,
    },
    {
      ["category"] = "repair",
      ["name"] = "Kiknikle",
      ["id"] = "3683",
      ["description"] = "Stylish Clothier",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.418,
      ["y"] = 0.386,
    },
    {
      ["category"] = "repair",
      ["name"] = "Pizznukle",
      ["id"] = "3684",
      ["description"] = "Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.418,
      ["y"] = 0.386,
    },
    {
      ["category"] = "repair",
      ["name"] = "Sanuye Runetotem",
      ["id"] = "10380",
      ["description"] = "Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.45,
      ["y"] = 0.59,
    },
    {
      ["category"] = "repair",
      ["name"] = "Kelm Hargunth",
      ["id"] = "14754",
      ["description"] = "Warsong Supply Officer",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.466,
      ["y"] = 0.084,
    },
    {
      ["category"] = "banker",
      ["name"] = "Fuzruckle",
      ["id"] = "3496",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.626,
      ["y"] = 0.374,
    },
    {
      ["category"] = "banker",
      ["name"] = "Zikkel",
      ["id"] = "8119",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.626,
      ["y"] = 0.374,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Innkeeper Boorand Plainswind",
      ["id"] = "3934",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.52,
      ["y"] = 0.298,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Innkeeper Wiley",
      ["id"] = "6791",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.62,
      ["y"] = 0.39399999999999996,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Innkeeper Byula",
      ["id"] = "7714",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.456,
      ["y"] = 0.59,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Sikwa",
      ["id"] = "9981",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.516,
      ["y"] = 0.29600000000000004,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Kelsuwa",
      ["id"] = "9983",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.452,
      ["y"] = 0.586,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Reggifuz",
      ["id"] = "10063",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.622,
      ["y"] = 0.392,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Devrak",
      ["id"] = "3615",
      ["description"] = "Wind Rider Master",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.514,
      ["y"] = 0.302,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Omusa Thunderhorn",
      ["id"] = "10378",
      ["description"] = "Wind Rider Master",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.444,
      ["y"] = 0.59,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Bragok",
      ["id"] = "16227",
      ["description"] = "Flight Master",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.63,
      ["y"] = 0.37200000000000005,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Traugh",
      ["id"] = "3478",
      ["description"] = "Expert Blacksmith",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.512,
      ["y"] = 0.28800000000000003,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Kil'hala",
      ["id"] = "3484",
      ["description"] = "Journeyman Tailor",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.522,
      ["y"] = 0.316,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Tinkerwiz",
      ["id"] = "3494",
      ["description"] = "Journeyman Engineer",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.626,
      ["y"] = 0.36200000000000004,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Krulmoo Fullmoon",
      ["id"] = "3703",
      ["description"] = "Expert Leatherworker",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.44799999999999995,
      ["y"] = 0.594,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Mahani",
      ["id"] = "3704",
      ["description"] = "Expert Tailor",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.44799999999999995,
      ["y"] = 0.594,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Dranh",
      ["id"] = "6387",
      ["description"] = "Skinner",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.45,
      ["y"] = 0.59,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Duhng",
      ["id"] = "8306",
      ["description"] = "Cook",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.552,
      ["y"] = 0.318,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Vazario Linkgrease",
      ["id"] = "8738",
      ["description"] = "Master Goblin Engineer",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.626,
      ["y"] = 0.36200000000000004,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Hraq",
      ["id"] = "3477",
      ["description"] = "Blacksmithing Supplier",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.512,
      ["y"] = 0.29,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Nargal Deatheye",
      ["id"] = "3479",
      ["description"] = "Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.512,
      ["y"] = 0.292,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Moorane Hearthgrain",
      ["id"] = "3480",
      ["description"] = "Baker",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.522,
      ["y"] = 0.306,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Barg",
      ["id"] = "3481",
      ["description"] = "General Supplies",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.516,
      ["y"] = 0.3,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Tari'qa",
      ["id"] = "3482",
      ["description"] = "Trade Supplies",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.516,
      ["y"] = 0.3,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jahan Hawkwing",
      ["id"] = "3483",
      ["description"] = "Leather & Mail Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.512,
      ["y"] = 0.29,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Wrahk",
      ["id"] = "3485",
      ["description"] = "Tailoring Supplies",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.522,
      ["y"] = 0.316,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Halija Whitestrider",
      ["id"] = "3486",
      ["description"] = "Clothier",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.522,
      ["y"] = 0.318,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kalyimah Stormcloud",
      ["id"] = "3487",
      ["description"] = "Bags & Sacks",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.522,
      ["y"] = 0.32,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Uthrok",
      ["id"] = "3488",
      ["description"] = "Bowyer & Gunsmith",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.51,
      ["y"] = 0.29,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Zargh",
      ["id"] = "3489",
      ["description"] = "Butcher",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.526,
      ["y"] = 0.298,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Hula'mahi",
      ["id"] = "3490",
      ["description"] = "Reagents and Herbs",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.514,
      ["y"] = 0.302,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Ironzar",
      ["id"] = "3491",
      ["description"] = "Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.622,
      ["y"] = 0.374,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Vexspindle",
      ["id"] = "3492",
      ["description"] = "Cloth & Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.622,
      ["y"] = 0.384,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Grazlix",
      ["id"] = "3493",
      ["description"] = "Armorer & Shieldcrafter",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.622,
      ["y"] = 0.384,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Gagsprocket",
      ["id"] = "3495",
      ["description"] = "Engineering Goods",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.626,
      ["y"] = 0.36200000000000004,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kilxx",
      ["id"] = "3497",
      ["description"] = "Fisherman",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.628,
      ["y"] = 0.382,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jazzik",
      ["id"] = "3498",
      ["description"] = "General Supplies",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.618,
      ["y"] = 0.38799999999999996,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Ranik",
      ["id"] = "3499",
      ["description"] = "Trade Supplies",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.618,
      ["y"] = 0.386,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Zizzek",
      ["id"] = "3572",
      ["description"] = "Fisherman",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.62,
      ["y"] = 0.39,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Lizzarik",
      ["id"] = "3658",
      ["description"] = "Weapon Dealer",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.618,
      ["y"] = 0.382,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Vrang Wildgore",
      ["id"] = "3682",
      ["description"] = "Weaponsmith & Armorcrafter",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.43799999999999994,
      ["y"] = 0.122,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kiknikle",
      ["id"] = "3683",
      ["description"] = "Stylish Clothier",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.418,
      ["y"] = 0.386,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Pizznukle",
      ["id"] = "3684",
      ["description"] = "Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.418,
      ["y"] = 0.386,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Gahroot",
      ["id"] = "3705",
      ["description"] = "Butcher",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.44799999999999995,
      ["y"] = 0.594,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Innkeeper Boorand Plainswind",
      ["id"] = "3934",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.52,
      ["y"] = 0.298,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Malgin Barleybrew",
      ["id"] = "5848",
      ["description"] = "Bael'dun Morale Officer",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.494,
      ["y"] = 0.8440000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Larhka",
      ["id"] = "5871",
      ["description"] = "Beverage Merchant",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.52,
      ["y"] = 0.29600000000000004,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Yonada",
      ["id"] = "5944",
      ["description"] = "Tailoring & Leatherworking Supplies",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.45,
      ["y"] = 0.5920000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Innkeeper Wiley",
      ["id"] = "6791",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.62,
      ["y"] = 0.39399999999999996,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Innkeeper Byula",
      ["id"] = "7714",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.456,
      ["y"] = 0.59,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jaxxil Sparks",
      ["id"] = "8121",
      ["description"] = "Holiday Fireworks Vendor",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.618,
      ["y"] = 0.39399999999999996,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Tarban Hearthgrain",
      ["id"] = "8307",
      ["description"] = "Baker",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.55,
      ["y"] = 0.32,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Sanuye Runetotem",
      ["id"] = "10380",
      ["description"] = "Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.45,
      ["y"] = 0.59,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kelm Hargunth",
      ["id"] = "14754",
      ["description"] = "Warsong Supply Officer",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.466,
      ["y"] = 0.084,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Hecht Copperpinch",
      ["id"] = "14964",
      ["description"] = "Smokywood Pastures",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.466,
      ["y"] = 0.084,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Grizzby",
      ["id"] = "211653",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.618,
      ["y"] = 0.39399999999999996,
    },
    {
      ["category"] = "spirithealer",
      ["name"] = "Spirit Healer",
      ["id"] = "6491",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.452,
      ["y"] = 0.61,
    },
    {
      ["category"] = "boss",
      ["name"] = "Mad Magglish",
      ["id"] = "3655",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.46,
      ["y"] = 0.364,
    },
    {
      ["category"] = "book",
      ["name"] = "Sargeras and the Betrayal",
      ["id"] = "175724",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.619,
      ["y"] = 0.396,
    },
    {
      ["category"] = "book",
      ["name"] = "Charge of the Dragonflights",
      ["id"] = "175726",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.627,
      ["y"] = 0.363,
    },
    {
      ["category"] = "book",
      ["name"] = "Mount Hyjal and Illidan's Gift",
      ["id"] = "175729",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.618,
      ["y"] = 0.39399999999999996,
    },
    {
      ["category"] = "book",
      ["name"] = "Exile of the High Elves",
      ["id"] = "175731",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.62,
      ["y"] = 0.387,
    },
    {
      ["category"] = "book",
      ["name"] = "Ironforge - the Awakening of the Dwarves",
      ["id"] = "175736",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.495,
      ["y"] = 0.8440000000000001,
    },
    {
      ["category"] = "book",
      ["name"] = "War of the Three Hammers",
      ["id"] = "175739",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.491,
      ["y"] = 0.8420000000000001,
    },
    {
      ["category"] = "book",
      ["name"] = "Lethargy of the Orcs",
      ["id"] = "175751",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.618,
      ["y"] = 0.551,
    },
    {
      ["category"] = "book",
      ["name"] = "The New Horde",
      ["id"] = "175752",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.619,
      ["y"] = 0.5489999999999999,
    },
    {
      ["category"] = "book",
      ["name"] = "Archimonde's Return and the Flight to Kalimdor",
      ["id"] = "175758",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.624,
      ["y"] = 0.387,
    },
    {
      ["category"] = "book",
      ["name"] = "Altar of Thorns",
      ["id"] = "407347",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.5820000000000001,
      ["y"] = 0.267,
    },
    {
      ["category"] = "book",
      ["name"] = "Etched Carving",
      ["id"] = "407505",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.44799999999999995,
      ["y"] = 0.8140000000000001,
    },
    {
      ["category"] = "book",
      ["name"] = "Etched Carving",
      ["id"] = "407510",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.45399999999999996,
      ["y"] = 0.8,
    },
    {
      ["category"] = "forge",
      ["name"] = "Forge",
      ["id"] = "1685",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.498,
      ["y"] = 0.297,
    },
    {
      ["category"] = "mailbox",
      ["name"] = "Mailbox",
      ["id"] = "32349",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "The Barrens",
      ["subLocation"] = "The Barrens",
      ["x"] = 0.451,
      ["y"] = 0.5870000000000001,
    },
  }
}
