DB_THE_HINTERLANDS_GENERAL = {
  ["region"] = "Eastern Kingdoms",
  ["mapID"] = 1425,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Harggan",
      ["id"] = "8161",
      ["description"] = "Blacksmithing Supplies",
      ["comment"] = "",
      ["mainLocation"] = "The Hinterlands",
      ["subLocation"] = "The Hinterlands",
      ["x"] = 0.134,
      ["y"] = 0.44,
    },
    {
      ["category"] = "repair",
      ["name"] = "Smith Slagtree",
      ["id"] = "14737",
      ["description"] = "Blacksmithing Supplies",
      ["comment"] = "",
      ["mainLocation"] = "The Hinterlands",
      ["subLocation"] = "The Hinterlands",
      ["x"] = 0.7759999999999999,
      ["y"] = 0.802,
    },
    {
      ["category"] = "repair",
      ["name"] = "Quartermaster Alandra",
      ["id"] = "222686",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "The Hinterlands",
      ["subLocation"] = "The Hinterlands",
      ["x"] = 0.614,
      ["y"] = 0.344,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Innkeeper Thulfram",
      ["id"] = "7744",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "The Hinterlands",
      ["subLocation"] = "The Hinterlands",
      ["x"] = 0.138,
      ["y"] = 0.41600000000000004,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Lard",
      ["id"] = "14731",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "The Hinterlands",
      ["subLocation"] = "The Hinterlands",
      ["x"] = 0.782,
      ["y"] = 0.812,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Killium Bouldertoe",
      ["id"] = "10061",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "The Hinterlands",
      ["subLocation"] = "The Hinterlands",
      ["x"] = 0.14400000000000002,
      ["y"] = 0.452,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Huntsman Markhor",
      ["id"] = "14741",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "The Hinterlands",
      ["subLocation"] = "The Hinterlands",
      ["x"] = 0.79,
      ["y"] = 0.794,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Gorkas",
      ["id"] = "4314",
      ["description"] = "Wind Rider Master",
      ["comment"] = "",
      ["mainLocation"] = "The Hinterlands",
      ["subLocation"] = "The Hinterlands",
      ["x"] = 0.816,
      ["y"] = 0.818,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Guthrum Thunderfist",
      ["id"] = "8018",
      ["description"] = "Gryphon Master",
      ["comment"] = "",
      ["mainLocation"] = "The Hinterlands",
      ["subLocation"] = "The Hinterlands",
      ["x"] = 0.11,
      ["y"] = 0.46,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Drakk Stonehand",
      ["id"] = "11097",
      ["description"] = "Master Leatherworking Trainer",
      ["comment"] = "",
      ["mainLocation"] = "The Hinterlands",
      ["subLocation"] = "The Hinterlands",
      ["x"] = 0.134,
      ["y"] = 0.434,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Katoom the Angler",
      ["id"] = "14740",
      ["description"] = "Fishing Trainer & Supplies",
      ["comment"] = "",
      ["mainLocation"] = "The Hinterlands",
      ["subLocation"] = "The Hinterlands",
      ["x"] = 0.802,
      ["y"] = 0.8140000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Ruppo Zipcoil",
      ["id"] = "2688",
      ["description"] = "Engineering Supplies",
      ["comment"] = "",
      ["mainLocation"] = "The Hinterlands",
      ["subLocation"] = "The Hinterlands",
      ["x"] = 0.342,
      ["y"] = 0.37799999999999995,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Truk Wildbeard",
      ["id"] = "4782",
      ["description"] = "Bartender",
      ["comment"] = "",
      ["mainLocation"] = "The Hinterlands",
      ["subLocation"] = "The Hinterlands",
      ["x"] = 0.14400000000000002,
      ["y"] = 0.424,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Innkeeper Thulfram",
      ["id"] = "7744",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "The Hinterlands",
      ["subLocation"] = "The Hinterlands",
      ["x"] = 0.138,
      ["y"] = 0.41600000000000004,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Nioma",
      ["id"] = "8160",
      ["description"] = "Leatherworking Supplies",
      ["comment"] = "",
      ["mainLocation"] = "The Hinterlands",
      ["subLocation"] = "The Hinterlands",
      ["x"] = 0.134,
      ["y"] = 0.434,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Harggan",
      ["id"] = "8161",
      ["description"] = "Blacksmithing Supplies",
      ["comment"] = "",
      ["mainLocation"] = "The Hinterlands",
      ["subLocation"] = "The Hinterlands",
      ["x"] = 0.134,
      ["y"] = 0.44,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Gigget Zipcoil",
      ["id"] = "12958",
      ["description"] = "Trade Supplies",
      ["comment"] = "",
      ["mainLocation"] = "The Hinterlands",
      ["subLocation"] = "The Hinterlands",
      ["x"] = 0.344,
      ["y"] = 0.384,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Lard",
      ["id"] = "14731",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "The Hinterlands",
      ["subLocation"] = "The Hinterlands",
      ["x"] = 0.782,
      ["y"] = 0.812,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Primal Torntusk",
      ["id"] = "14736",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "The Hinterlands",
      ["subLocation"] = "The Hinterlands",
      ["x"] = 0.782,
      ["y"] = 0.812,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Smith Slagtree",
      ["id"] = "14737",
      ["description"] = "Blacksmithing Supplies",
      ["comment"] = "",
      ["mainLocation"] = "The Hinterlands",
      ["subLocation"] = "The Hinterlands",
      ["x"] = 0.7759999999999999,
      ["y"] = 0.802,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Otho Moji'ko",
      ["id"] = "14738",
      ["description"] = "Cooking Supplier",
      ["comment"] = "",
      ["mainLocation"] = "The Hinterlands",
      ["subLocation"] = "The Hinterlands",
      ["x"] = 0.792,
      ["y"] = 0.79,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Mystic Yayo'jin",
      ["id"] = "14739",
      ["description"] = "Reagent Vendor",
      ["comment"] = "",
      ["mainLocation"] = "The Hinterlands",
      ["subLocation"] = "The Hinterlands",
      ["x"] = 0.7879999999999999,
      ["y"] = 0.784,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Katoom the Angler",
      ["id"] = "14740",
      ["description"] = "Fishing Trainer & Supplies",
      ["comment"] = "",
      ["mainLocation"] = "The Hinterlands",
      ["subLocation"] = "The Hinterlands",
      ["x"] = 0.802,
      ["y"] = 0.8140000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Renn'az",
      ["id"] = "17598",
      ["description"] = "Ammunition Vendor",
      ["comment"] = "",
      ["mainLocation"] = "The Hinterlands",
      ["subLocation"] = "The Hinterlands",
      ["x"] = 0.768,
      ["y"] = 0.812,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Quartermaster Alandra",
      ["id"] = "222686",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "The Hinterlands",
      ["subLocation"] = "The Hinterlands",
      ["x"] = 0.614,
      ["y"] = 0.344,
    },
    {
      ["category"] = "spirithealer",
      ["name"] = "Spirit Healer",
      ["id"] = "6491",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "The Hinterlands",
      ["subLocation"] = "The Hinterlands",
      ["x"] = 0.168,
      ["y"] = 0.444,
    },
    {
      ["category"] = "book",
      ["name"] = "Shrine of the Moon",
      ["id"] = "441946",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "The Hinterlands",
      ["subLocation"] = "The Hinterlands",
      ["x"] = 0.662,
      ["y"] = 0.531,
    },
    {
      ["category"] = "mailbox",
      ["name"] = "Mailbox",
      ["id"] = "32349",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "The Hinterlands",
      ["subLocation"] = "The Hinterlands",
      ["x"] = 0.141,
      ["y"] = 0.457,
    },
  }
}
