DB_THOUSAND_NEEDLES_GENERAL = {
  ["region"] = "Kalimdor",
  ["mapID"] = 1441,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Synge",
      ["id"] = "3053",
      ["description"] = "Gun Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Thousand Needles",
      ["subLocation"] = "Thousand Needles",
      ["x"] = 0.804,
      ["y"] = 0.768,
    },
    {
      ["category"] = "repair",
      ["name"] = "Starn",
      ["id"] = "9551",
      ["description"] = "Gunsmith & Bowyer",
      ["comment"] = "",
      ["mainLocation"] = "Thousand Needles",
      ["subLocation"] = "Thousand Needles",
      ["x"] = 0.45,
      ["y"] = 0.506,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Innkeeper Abeqwa",
      ["id"] = "11116",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Thousand Needles",
      ["subLocation"] = "Thousand Needles",
      ["x"] = 0.46,
      ["y"] = 0.514,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Awenasa",
      ["id"] = "11117",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "Thousand Needles",
      ["subLocation"] = "Thousand Needles",
      ["x"] = 0.45799999999999996,
      ["y"] = 0.51,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Nyse",
      ["id"] = "4317",
      ["description"] = "Wind Rider Master",
      ["comment"] = "",
      ["mainLocation"] = "Thousand Needles",
      ["subLocation"] = "Thousand Needles",
      ["x"] = 0.45,
      ["y"] = 0.49200000000000005,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Synge",
      ["id"] = "3053",
      ["description"] = "Gun Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Thousand Needles",
      ["subLocation"] = "Thousand Needles",
      ["x"] = 0.804,
      ["y"] = 0.768,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Laer Stepperunner",
      ["id"] = "3689",
      ["description"] = "Food & Drink",
      ["comment"] = "",
      ["mainLocation"] = "Thousand Needles",
      ["subLocation"] = "Thousand Needles",
      ["x"] = 0.21,
      ["y"] = 0.318,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Turhaw",
      ["id"] = "4875",
      ["description"] = "Butcher",
      ["comment"] = "",
      ["mainLocation"] = "Thousand Needles",
      ["subLocation"] = "Thousand Needles",
      ["x"] = 0.45399999999999996,
      ["y"] = 0.51,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jawn Highmesa",
      ["id"] = "4876",
      ["description"] = "General Goods",
      ["comment"] = "",
      ["mainLocation"] = "Thousand Needles",
      ["subLocation"] = "Thousand Needles",
      ["x"] = 0.46,
      ["y"] = 0.514,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jandia",
      ["id"] = "4877",
      ["description"] = "Trade Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Thousand Needles",
      ["subLocation"] = "Thousand Needles",
      ["x"] = 0.46,
      ["y"] = 0.514,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Montarr",
      ["id"] = "4878",
      ["description"] = "Lorekeeper",
      ["comment"] = "",
      ["mainLocation"] = "Thousand Needles",
      ["subLocation"] = "Thousand Needles",
      ["x"] = 0.452,
      ["y"] = 0.506,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Riznek",
      ["id"] = "6495",
      ["description"] = "Drink Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Thousand Needles",
      ["subLocation"] = "Thousand Needles",
      ["x"] = 0.802,
      ["y"] = 0.764,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Brivelthwerp",
      ["id"] = "6496",
      ["description"] = "Ice Cream Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Thousand Needles",
      ["subLocation"] = "Thousand Needles",
      ["x"] = 0.774,
      ["y"] = 0.77,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Magus Tirth",
      ["id"] = "6548",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Thousand Needles",
      ["subLocation"] = "Thousand Needles",
      ["x"] = 0.782,
      ["y"] = 0.758,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jinky Twizzlefixxit",
      ["id"] = "6730",
      ["description"] = "Engineering Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Thousand Needles",
      ["subLocation"] = "Thousand Needles",
      ["x"] = 0.7759999999999999,
      ["y"] = 0.778,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Starn",
      ["id"] = "9551",
      ["description"] = "Gunsmith & Bowyer",
      ["comment"] = "",
      ["mainLocation"] = "Thousand Needles",
      ["subLocation"] = "Thousand Needles",
      ["x"] = 0.45,
      ["y"] = 0.506,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Innkeeper Abeqwa",
      ["id"] = "11116",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Thousand Needles",
      ["subLocation"] = "Thousand Needles",
      ["x"] = 0.46,
      ["y"] = 0.514,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Maximillian \"The Greaser\"",
      ["id"] = "222261",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Thousand Needles",
      ["subLocation"] = "Thousand Needles",
      ["x"] = 0.7979999999999999,
      ["y"] = 0.772,
    },
    {
      ["category"] = "spirithealer",
      ["name"] = "Spirit Healer",
      ["id"] = "6491",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Thousand Needles",
      ["subLocation"] = "Thousand Needles",
      ["x"] = 0.304,
      ["y"] = 0.23399999999999999,
    },
    {
      ["category"] = "mailbox",
      ["name"] = "Mailbox",
      ["id"] = "32349",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Thousand Needles",
      ["subLocation"] = "Thousand Needles",
      ["x"] = 0.45899999999999996,
      ["y"] = 0.51,
    },
  }
}
