DB_THUNDER_BLUFF_GENERAL = {
  ["region"] = "Kalimdor <Horde>",
  ["mapID"] = 1456,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Jyn Stonehoof",
      ["id"] = "2997",
      ["description"] = "Weapons Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.41200000000000003,
      ["y"] = 0.62,
    },
    {
      ["category"] = "repair",
      ["name"] = "Taur Stonehoof",
      ["id"] = "2999",
      ["description"] = "Blacksmithing Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.39799999999999996,
      ["y"] = 0.552,
    },
    {
      ["category"] = "repair",
      ["name"] = "Kuna Thunderhorn",
      ["id"] = "3015",
      ["description"] = "Bowyer & Fletching Goods",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.46799999999999997,
      ["y"] = 0.46,
    },
    {
      ["category"] = "repair",
      ["name"] = "Hogor Thunderhoof",
      ["id"] = "3018",
      ["description"] = "Guns Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.556,
      ["y"] = 0.5660000000000001,
    },
    {
      ["category"] = "repair",
      ["name"] = "Delgo Ragetotem",
      ["id"] = "3019",
      ["description"] = "Axe Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.5379999999999999,
      ["y"] = 0.5720000000000001,
    },
    {
      ["category"] = "repair",
      ["name"] = "Etu Ragetotem",
      ["id"] = "3020",
      ["description"] = "Mace & Staff Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.532,
      ["y"] = 0.578,
    },
    {
      ["category"] = "repair",
      ["name"] = "Kard Ragetotem",
      ["id"] = "3021",
      ["description"] = "Sword and Dagger Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.532,
      ["y"] = 0.568,
    },
    {
      ["category"] = "repair",
      ["name"] = "Sunn Ragetotem",
      ["id"] = "3022",
      ["description"] = "Staff Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.496,
      ["y"] = 0.49200000000000005,
    },
    {
      ["category"] = "repair",
      ["name"] = "Sura Wildmane",
      ["id"] = "3023",
      ["description"] = "War Harness Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.518,
      ["y"] = 0.546,
    },
    {
      ["category"] = "repair",
      ["name"] = "Tagain",
      ["id"] = "3092",
      ["description"] = "Cloth Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.434,
      ["y"] = 0.44,
    },
    {
      ["category"] = "repair",
      ["name"] = "Grod",
      ["id"] = "3093",
      ["description"] = "Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.428,
      ["y"] = 0.43200000000000005,
    },
    {
      ["category"] = "repair",
      ["name"] = "Fela",
      ["id"] = "3095",
      ["description"] = "Heavy Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.428,
      ["y"] = 0.444,
    },
    {
      ["category"] = "repair",
      ["name"] = "Hewa",
      ["id"] = "8358",
      ["description"] = "Cloth Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.452,
      ["y"] = 0.564,
    },
    {
      ["category"] = "repair",
      ["name"] = "Ahanu",
      ["id"] = "8359",
      ["description"] = "Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.45399999999999996,
      ["y"] = 0.5579999999999999,
    },
    {
      ["category"] = "repair",
      ["name"] = "Elki",
      ["id"] = "8360",
      ["description"] = "Mail Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.45,
      ["y"] = 0.562,
    },
    {
      ["category"] = "repair",
      ["name"] = "Ohanko",
      ["id"] = "8398",
      ["description"] = "Two Handed Weapon Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.532,
      ["y"] = 0.5720000000000001,
    },
    {
      ["category"] = "auctioneer",
      ["name"] = "Auctioneer Stampi",
      ["id"] = "8674",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.40399999999999997,
      ["y"] = 0.522,
    },
    {
      ["category"] = "auctioneer",
      ["name"] = "Auctioneer Gullem",
      ["id"] = "8722",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.39,
      ["y"] = 0.506,
    },
    {
      ["category"] = "banker",
      ["name"] = "Torn",
      ["id"] = "2996",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.474,
      ["y"] = 0.588,
    },
    {
      ["category"] = "banker",
      ["name"] = "Chesmu",
      ["id"] = "8356",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.46799999999999997,
      ["y"] = 0.5820000000000001,
    },
    {
      ["category"] = "banker",
      ["name"] = "Atepa",
      ["id"] = "8357",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.47,
      ["y"] = 0.59,
    },
    {
      ["category"] = "battlemaster",
      ["name"] = "Taim Ragetotem",
      ["id"] = "7427",
      ["description"] = "Alterac Valley Battlemaster",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.586,
      ["y"] = 0.77,
    },
    {
      ["category"] = "battlemaster",
      ["name"] = "Kergul Bloodaxe",
      ["id"] = "10360",
      ["description"] = "Warsong Gulch Battlemaster",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.568,
      ["y"] = 0.768,
    },
    {
      ["category"] = "battlemaster",
      ["name"] = "Martin Lindsey",
      ["id"] = "12198",
      ["description"] = "Arathi Basin Battlemaster",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.28800000000000003,
      ["y"] = 0.21,
    },
    {
      ["category"] = "battlemaster",
      ["name"] = "Defilers Emissary",
      ["id"] = "14990",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.44,
      ["y"] = 0.574,
    },
    {
      ["category"] = "battlemaster",
      ["name"] = "Warsong Emissary",
      ["id"] = "15105",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.44,
      ["y"] = 0.5720000000000001,
    },
    {
      ["category"] = "battlemaster",
      ["name"] = "Frostwolf Emissary",
      ["id"] = "15106",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.44,
      ["y"] = 0.5720000000000001,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Innkeeper Pala",
      ["id"] = "6746",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.45799999999999996,
      ["y"] = 0.644,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Bulrug",
      ["id"] = "10054",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.45,
      ["y"] = 0.5920000000000001,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Tal",
      ["id"] = "2995",
      ["description"] = "Wind Rider Master",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.46799999999999997,
      ["y"] = 0.5,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Pand Stonebinder",
      ["id"] = "2798",
      ["description"] = "First Aid Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.294,
      ["y"] = 0.214,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Karn Stonehoof",
      ["id"] = "2998",
      ["description"] = "Expert Blacksmith",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.396,
      ["y"] = 0.552,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Brek Stonehoof",
      ["id"] = "3001",
      ["description"] = "Mining Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.34600000000000003,
      ["y"] = 0.5760000000000001,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Tepa",
      ["id"] = "3004",
      ["description"] = "Expert Tailor",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.442,
      ["y"] = 0.45,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Una",
      ["id"] = "3007",
      ["description"] = "Artisan Leatherworker",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.418,
      ["y"] = 0.426,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Mak",
      ["id"] = "3008",
      ["description"] = "Journeyman Leatherworker",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.42200000000000004,
      ["y"] = 0.43200000000000005,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Bena Winterhoof",
      ["id"] = "3009",
      ["description"] = "Expert Alchemist",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.46799999999999997,
      ["y"] = 0.336,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Teg Dawnstrider",
      ["id"] = "3011",
      ["description"] = "Expert Enchanter",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.45,
      ["y"] = 0.38,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Komin Winterhoof",
      ["id"] = "3013",
      ["description"] = "Herbalism Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.498,
      ["y"] = 0.39799999999999996,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Aska Mistrunner",
      ["id"] = "3026",
      ["description"] = "Cooking Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.51,
      ["y"] = 0.528,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Kah Mistrunner",
      ["id"] = "3028",
      ["description"] = "Fishing Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.56,
      ["y"] = 0.46799999999999997,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Siln Skychaser",
      ["id"] = "3030",
      ["description"] = "Shaman Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.23,
      ["y"] = 0.20800000000000002,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Tigor Skychaser",
      ["id"] = "3031",
      ["description"] = "Shaman Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.23600000000000002,
      ["y"] = 0.192,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Beram Skychaser",
      ["id"] = "3032",
      ["description"] = "Shaman Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.222,
      ["y"] = 0.19,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Turak Runetotem",
      ["id"] = "3033",
      ["description"] = "Druid Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.764,
      ["y"] = 0.276,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Sheal Runetotem",
      ["id"] = "3034",
      ["description"] = "Druid Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.77,
      ["y"] = 0.27399999999999997,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Kym Wildmane",
      ["id"] = "3036",
      ["description"] = "Druid Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.768,
      ["y"] = 0.298,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Kary Thunderhorn",
      ["id"] = "3038",
      ["description"] = "Hunter Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.5820000000000001,
      ["y"] = 0.878,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Holt Thunderhorn",
      ["id"] = "3039",
      ["description"] = "Hunter Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.574,
      ["y"] = 0.892,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Urek Thunderhorn",
      ["id"] = "3040",
      ["description"] = "Hunter Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.588,
      ["y"] = 0.866,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Torm Ragetotem",
      ["id"] = "3041",
      ["description"] = "Warrior Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.5760000000000001,
      ["y"] = 0.872,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Sark Ragetotem",
      ["id"] = "3042",
      ["description"] = "Warrior Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.5720000000000001,
      ["y"] = 0.89,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Ker Ragetotem",
      ["id"] = "3043",
      ["description"] = "Warrior Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.578,
      ["y"] = 0.856,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Miles Welsh",
      ["id"] = "3044",
      ["description"] = "Priest Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.254,
      ["y"] = 0.154,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Malakai Cross",
      ["id"] = "3045",
      ["description"] = "Priest Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.248,
      ["y"] = 0.226,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Father Cobb",
      ["id"] = "3046",
      ["description"] = "Priest Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.254,
      ["y"] = 0.20800000000000002,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Archmage Shymm",
      ["id"] = "3047",
      ["description"] = "Mage Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.226,
      ["y"] = 0.14800000000000002,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Ursyn Ghull",
      ["id"] = "3048",
      ["description"] = "Mage Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.256,
      ["y"] = 0.146,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Thurston Xane",
      ["id"] = "3049",
      ["description"] = "Mage Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.25,
      ["y"] = 0.20600000000000002,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Birgitte Cranston",
      ["id"] = "5957",
      ["description"] = "Portal Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.222,
      ["y"] = 0.168,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Mooranta",
      ["id"] = "7089",
      ["description"] = "Skinning Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.446,
      ["y"] = 0.43,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Hesuwa Thunderhorn",
      ["id"] = "10086",
      ["description"] = "Pet Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.542,
      ["y"] = 0.836,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Thrag Stonehoof",
      ["id"] = "10278",
      ["description"] = "Journeyman Blacksmith",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.392,
      ["y"] = 0.562,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Kray",
      ["id"] = "11047",
      ["description"] = "Journeyman Alchemist",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.46799999999999997,
      ["y"] = 0.342,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Vhan",
      ["id"] = "11051",
      ["description"] = "Journeyman Tailor",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.44,
      ["y"] = 0.444,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Mot Dawnstrider",
      ["id"] = "11071",
      ["description"] = "Journeyman Enchanter",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.44799999999999995,
      ["y"] = 0.38799999999999996,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Tarn",
      ["id"] = "11084",
      ["description"] = "Expert Leatherworker",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.424,
      ["y"] = 0.43,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Ansekhwa",
      ["id"] = "11869",
      ["description"] = "Weapon Master",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.41,
      ["y"] = 0.622,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jyn Stonehoof",
      ["id"] = "2997",
      ["description"] = "Weapons Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.41200000000000003,
      ["y"] = 0.62,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Taur Stonehoof",
      ["id"] = "2999",
      ["description"] = "Blacksmithing Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.39799999999999996,
      ["y"] = 0.552,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kurm Stonehoof",
      ["id"] = "3002",
      ["description"] = "Mining Supplier",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.344,
      ["y"] = 0.57,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Fyr Mistrunner",
      ["id"] = "3003",
      ["description"] = "Bread Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.41200000000000003,
      ["y"] = 0.534,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Mahu",
      ["id"] = "3005",
      ["description"] = "Leatherworking & Tailoring Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.43799999999999994,
      ["y"] = 0.446,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Mani Winterhoof",
      ["id"] = "3010",
      ["description"] = "Alchemy Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.47200000000000003,
      ["y"] = 0.34,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Nata Dawnstrider",
      ["id"] = "3012",
      ["description"] = "Enchanting Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.45,
      ["y"] = 0.39,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Nida Winterhoof",
      ["id"] = "3014",
      ["description"] = "Herbalism Supplier",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.496,
      ["y"] = 0.392,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kuna Thunderhorn",
      ["id"] = "3015",
      ["description"] = "Bowyer & Fletching Goods",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.46799999999999997,
      ["y"] = 0.46,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Tand",
      ["id"] = "3016",
      ["description"] = "Basket Weaver",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.49,
      ["y"] = 0.34600000000000003,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Nan Mistrunner",
      ["id"] = "3017",
      ["description"] = "Fruit Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.47,
      ["y"] = 0.42200000000000004,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Hogor Thunderhoof",
      ["id"] = "3018",
      ["description"] = "Guns Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.556,
      ["y"] = 0.5660000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Delgo Ragetotem",
      ["id"] = "3019",
      ["description"] = "Axe Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.5379999999999999,
      ["y"] = 0.5720000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Etu Ragetotem",
      ["id"] = "3020",
      ["description"] = "Mace & Staff Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.532,
      ["y"] = 0.578,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kard Ragetotem",
      ["id"] = "3021",
      ["description"] = "Sword and Dagger Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.532,
      ["y"] = 0.568,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Sunn Ragetotem",
      ["id"] = "3022",
      ["description"] = "Staff Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.496,
      ["y"] = 0.49200000000000005,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Sura Wildmane",
      ["id"] = "3023",
      ["description"] = "War Harness Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.518,
      ["y"] = 0.546,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kaga Mistrunner",
      ["id"] = "3025",
      ["description"] = "Meat Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.522,
      ["y"] = 0.48200000000000004,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Naal Mistrunner",
      ["id"] = "3027",
      ["description"] = "Cooking Supplier",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.51,
      ["y"] = 0.528,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Sewa Mistrunner",
      ["id"] = "3029",
      ["description"] = "Fishing Supplier",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.5579999999999999,
      ["y"] = 0.47200000000000003,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Miles Welsh",
      ["id"] = "3044",
      ["description"] = "Priest Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.254,
      ["y"] = 0.154,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Tagain",
      ["id"] = "3092",
      ["description"] = "Cloth Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.434,
      ["y"] = 0.44,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Grod",
      ["id"] = "3093",
      ["description"] = "Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.428,
      ["y"] = 0.43200000000000005,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Fela",
      ["id"] = "3095",
      ["description"] = "Heavy Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.428,
      ["y"] = 0.444,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Thrumn",
      ["id"] = "5189",
      ["description"] = "Tabard Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.374,
      ["y"] = 0.628,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Innkeeper Pala",
      ["id"] = "6746",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.45799999999999996,
      ["y"] = 0.644,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Hewa",
      ["id"] = "8358",
      ["description"] = "Cloth Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.452,
      ["y"] = 0.564,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Ahanu",
      ["id"] = "8359",
      ["description"] = "Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.45399999999999996,
      ["y"] = 0.5579999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Elki",
      ["id"] = "8360",
      ["description"] = "Mail Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.45,
      ["y"] = 0.562,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Chepi",
      ["id"] = "8361",
      ["description"] = "Reagent Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.42,
      ["y"] = 0.5539999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kuruk",
      ["id"] = "8362",
      ["description"] = "General Goods Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.39,
      ["y"] = 0.642,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Shadi Mistrunner",
      ["id"] = "8363",
      ["description"] = "Trade Goods Supplier",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.40399999999999997,
      ["y"] = 0.634,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Pakwa",
      ["id"] = "8364",
      ["description"] = "Bag Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.392,
      ["y"] = 0.638,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Ohanko",
      ["id"] = "8398",
      ["description"] = "Two Handed Weapon Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.532,
      ["y"] = 0.5720000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Halpa",
      ["id"] = "8401",
      ["description"] = "Prairie Dog Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.622,
      ["y"] = 0.584,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Bashana Runetotem",
      ["id"] = "9087",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.708,
      ["y"] = 0.33799999999999997,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Whulwert Copperpinch",
      ["id"] = "13431",
      ["description"] = "Smokywood Pastures",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.43799999999999994,
      ["y"] = 0.584,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Seersa Copperpinch",
      ["id"] = "13432",
      ["description"] = "Smokywood Pastures",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.43799999999999994,
      ["y"] = 0.59,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Lunar Festival Vendor",
      ["id"] = "15898",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.706,
      ["y"] = 0.28,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Netali Proudwind",
      ["id"] = "207743",
      ["description"] = "General Goods",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.28600000000000003,
      ["y"] = 0.182,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Dokimi",
      ["id"] = "214096",
      ["description"] = "Supply Officer",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.396,
      ["y"] = 0.536,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Rune Broker",
      ["id"] = "233428",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.226,
      ["y"] = 0.128,
    },
    {
      ["category"] = "spirithealer",
      ["name"] = "Spirit Healer",
      ["id"] = "6491",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.564,
      ["y"] = 0.174,
    },
    {
      ["category"] = "book",
      ["name"] = "Sorrow of the Earthmother",
      ["id"] = "177204",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.775,
      ["y"] = 0.263,
    },
    {
      ["category"] = "book",
      ["name"] = "Forestlord and the first Druids",
      ["id"] = "177205",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.7909999999999999,
      ["y"] = 0.281,
    },
    {
      ["category"] = "book",
      ["name"] = "Mists of Dawn",
      ["id"] = "177207",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.7609999999999999,
      ["y"] = 0.267,
    },
    {
      ["category"] = "book",
      ["name"] = "The White Stag and the Moon",
      ["id"] = "177208",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.785,
      ["y"] = 0.26899999999999996,
    },
    {
      ["category"] = "book",
      ["name"] = "Hatred of the Centaur",
      ["id"] = "177209",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.79,
      ["y"] = 0.301,
    },
    {
      ["category"] = "forge",
      ["name"] = "Forge",
      ["id"] = "1685",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.391,
      ["y"] = 0.562,
    },
    {
      ["category"] = "mailbox",
      ["name"] = "Mailbox",
      ["id"] = "32349",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Thunder Bluff",
      ["subLocation"] = "Thunder Bluff",
      ["x"] = 0.45,
      ["y"] = 0.5920000000000001,
    },
  }
}
