DB_TIRISFAL_GLADES_GENERAL = {
  ["region"] = "Eastern Kingdoms <Horde>",
  ["mapID"] = 1420,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Archibald Kava",
      ["id"] = "2113",
      ["description"] = "Cloth & Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.324,
      ["y"] = 0.6559999999999999,
    },
    {
      ["category"] = "repair",
      ["name"] = "Blacksmith Rand",
      ["id"] = "2116",
      ["description"] = "Apprentice Armorer",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.324,
      ["y"] = 0.662,
    },
    {
      ["category"] = "repair",
      ["name"] = "Harold Raims",
      ["id"] = "2117",
      ["description"] = "Apprentice Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.324,
      ["y"] = 0.664,
    },
    {
      ["category"] = "repair",
      ["name"] = "Abe Winters",
      ["id"] = "2135",
      ["description"] = "Apprentice Armorer",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.602,
      ["y"] = 0.53,
    },
    {
      ["category"] = "repair",
      ["name"] = "Oliver Dwor",
      ["id"] = "2136",
      ["description"] = "Apprentice Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.602,
      ["y"] = 0.532,
    },
    {
      ["category"] = "repair",
      ["name"] = "Eliza Callen",
      ["id"] = "2137",
      ["description"] = "Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.604,
      ["y"] = 0.528,
    },
    {
      ["category"] = "repair",
      ["name"] = "Constance Brisboise",
      ["id"] = "3522",
      ["description"] = "Apprentice Clothier",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.526,
      ["y"] = 0.556,
    },
    {
      ["category"] = "repair",
      ["name"] = "Argent Quartermaster Hasana",
      ["id"] = "10856",
      ["description"] = "The Argent Dawn",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.8320000000000001,
      ["y"] = 0.682,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Innkeeper Renee",
      ["id"] = "5688",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.616,
      ["y"] = 0.52,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Morganus",
      ["id"] = "10055",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.6,
      ["y"] = 0.522,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Faruza",
      ["id"] = "2114",
      ["description"] = "Apprentice Herbalist",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.598,
      ["y"] = 0.52,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Dannal Stern",
      ["id"] = "2119",
      ["description"] = "Warrior Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.326,
      ["y"] = 0.6559999999999999,
    },
    {
      ["category"] = "trainer",
      ["name"] = "David Trias",
      ["id"] = "2122",
      ["description"] = "Rogue Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.324,
      ["y"] = 0.6559999999999999,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Dark Cleric Duesten",
      ["id"] = "2123",
      ["description"] = "Priest Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.31,
      ["y"] = 0.66,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Isabella",
      ["id"] = "2124",
      ["description"] = "Mage Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.308,
      ["y"] = 0.66,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Maximillion",
      ["id"] = "2126",
      ["description"] = "Warlock Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.308,
      ["y"] = 0.662,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Rupert Boch",
      ["id"] = "2127",
      ["description"] = "Warlock Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.616,
      ["y"] = 0.524,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Cain Firesong",
      ["id"] = "2128",
      ["description"] = "Mage Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.618,
      ["y"] = 0.524,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Dark Cleric Beryl",
      ["id"] = "2129",
      ["description"] = "Priest Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.616,
      ["y"] = 0.522,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Marion Call",
      ["id"] = "2130",
      ["description"] = "Rogue Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.616,
      ["y"] = 0.52,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Austil de Mon",
      ["id"] = "2131",
      ["description"] = "Warrior Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.618,
      ["y"] = 0.524,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Carolai Anise",
      ["id"] = "2132",
      ["description"] = "Journeyman Alchemist",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.594,
      ["y"] = 0.522,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Bowen Brisboise",
      ["id"] = "3523",
      ["description"] = "Journeyman Tailor",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.526,
      ["y"] = 0.556,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Shelene Rhobart",
      ["id"] = "3549",
      ["description"] = "Journeyman Leatherworker",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.654,
      ["y"] = 0.6,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Velma Warnam",
      ["id"] = "4773",
      ["description"] = "Undead Horse Riding Instructor",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.6,
      ["y"] = 0.524,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Clyde Kellen",
      ["id"] = "5690",
      ["description"] = "Fisherman",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.672,
      ["y"] = 0.51,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Vance Undergloom",
      ["id"] = "5695",
      ["description"] = "Journeyman Enchanter",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.616,
      ["y"] = 0.516,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Nurse Neela",
      ["id"] = "5759",
      ["description"] = "First Aid Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.618,
      ["y"] = 0.528,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Rand Rhobart",
      ["id"] = "6289",
      ["description"] = "Skinner",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.6559999999999999,
      ["y"] = 0.6,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Archibald Kava",
      ["id"] = "2113",
      ["description"] = "Cloth & Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.324,
      ["y"] = 0.6559999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Joshua Kien",
      ["id"] = "2115",
      ["description"] = "General Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.322,
      ["y"] = 0.654,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Blacksmith Rand",
      ["id"] = "2116",
      ["description"] = "Apprentice Armorer",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.324,
      ["y"] = 0.662,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Harold Raims",
      ["id"] = "2117",
      ["description"] = "Apprentice Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.324,
      ["y"] = 0.664,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Abigail Shiel",
      ["id"] = "2118",
      ["description"] = "Trade Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.61,
      ["y"] = 0.524,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Mrs. Winters",
      ["id"] = "2134",
      ["description"] = "General Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.61,
      ["y"] = 0.526,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Abe Winters",
      ["id"] = "2135",
      ["description"] = "Apprentice Armorer",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.602,
      ["y"] = 0.53,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Oliver Dwor",
      ["id"] = "2136",
      ["description"] = "Apprentice Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.602,
      ["y"] = 0.532,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Eliza Callen",
      ["id"] = "2137",
      ["description"] = "Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.604,
      ["y"] = 0.528,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Constance Brisboise",
      ["id"] = "3522",
      ["description"] = "Apprentice Clothier",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.526,
      ["y"] = 0.556,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Hamlin Atkins",
      ["id"] = "3547",
      ["description"] = "Mushroom Farmer",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.568,
      ["y"] = 0.522,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Selina Weston",
      ["id"] = "3548",
      ["description"] = "Alchemy & Herbalism Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.618,
      ["y"] = 0.5,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Martine Tramblay",
      ["id"] = "3550",
      ["description"] = "Fishing Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.6579999999999999,
      ["y"] = 0.596,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Zachariah Post",
      ["id"] = "4731",
      ["description"] = "Undead Horse Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.598,
      ["y"] = 0.526,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Innkeeper Renee",
      ["id"] = "5688",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.616,
      ["y"] = 0.52,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kayla Smithe",
      ["id"] = "5749",
      ["description"] = "Demon Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.308,
      ["y"] = 0.664,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Gina Lang",
      ["id"] = "5750",
      ["description"] = "Demon Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.616,
      ["y"] = 0.526,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Argent Quartermaster Hasana",
      ["id"] = "10856",
      ["description"] = "The Argent Dawn",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.8320000000000001,
      ["y"] = 0.682,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Apothecary Dithers",
      ["id"] = "11057",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.8320000000000001,
      ["y"] = 0.6920000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Werg Thickblade",
      ["id"] = "12943",
      ["description"] = "Leatherworking Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.8320000000000001,
      ["y"] = 0.696,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Darkcaller Yanka",
      ["id"] = "15197",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.556,
      ["y"] = 0.698,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Penny Hawkins",
      ["id"] = "208920",
      ["description"] = "Bartender",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.618,
      ["y"] = 0.52,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Rune Broker",
      ["id"] = "233428",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.314,
      ["y"] = 0.664,
    },
    {
      ["category"] = "spirithealer",
      ["name"] = "Spirit Healer",
      ["id"] = "6491",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.312,
      ["y"] = 0.648,
    },
    {
      ["category"] = "book",
      ["name"] = "Charge of the Dragonflights",
      ["id"] = "175726",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.608,
      ["y"] = 0.506,
    },
    {
      ["category"] = "book",
      ["name"] = "Aegwynn and the Dragon Hunt",
      ["id"] = "175738",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.617,
      ["y"] = 0.521,
    },
    {
      ["category"] = "forge",
      ["name"] = "Forge",
      ["id"] = "1685",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.21100000000000002,
      ["y"] = 0.457,
    },
    {
      ["category"] = "mailbox",
      ["name"] = "Mailbox",
      ["id"] = "32349",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Tirisfal Glades",
      ["subLocation"] = "Tirisfal Glades",
      ["x"] = 0.614,
      ["y"] = 0.531,
    },
  }
}
