DB_UNGORO_CRATER_GENERAL = {
  ["region"] = "Kalimdor",
  ["mapID"] = 1449,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Gibbert",
      ["id"] = "3000",
      ["description"] = "Weapon Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Un'Goro Crater",
      ["subLocation"] = "Un'Goro Crater",
      ["x"] = 0.44,
      ["y"] = 0.07200000000000001,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Gryfe",
      ["id"] = "10583",
      ["description"] = "Flight Master",
      ["comment"] = "",
      ["mainLocation"] = "Un'Goro Crater",
      ["subLocation"] = "Un'Goro Crater",
      ["x"] = 0.452,
      ["y"] = 0.057999999999999996,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Gibbert",
      ["id"] = "3000",
      ["description"] = "Weapon Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Un'Goro Crater",
      ["subLocation"] = "Un'Goro Crater",
      ["x"] = 0.44,
      ["y"] = 0.07200000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Linken",
      ["id"] = "8737",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Un'Goro Crater",
      ["subLocation"] = "Un'Goro Crater",
      ["x"] = 0.446,
      ["y"] = 0.08199999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Nergal",
      ["id"] = "12959",
      ["description"] = "General Goods Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Un'Goro Crater",
      ["subLocation"] = "Un'Goro Crater",
      ["x"] = 0.43200000000000005,
      ["y"] = 0.078,
    },
    {
      ["category"] = "spirithealer",
      ["name"] = "Spirit Healer",
      ["id"] = "6491",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Un'Goro Crater",
      ["subLocation"] = "Un'Goro Crater",
      ["x"] = 0.8,
      ["y"] = 0.498,
    },
  }
}
