DB_UNDERCITY_GENERAL = {
  ["region"] = "Eastern Kingdoms <Horde>",
  ["mapID"] = 1458,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Gordon Wendham",
      ["id"] = "4556",
      ["description"] = "Weapons Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.618,
      ["y"] = 0.418,
    },
    {
      ["category"] = "repair",
      ["name"] = "Louis Warren",
      ["id"] = "4557",
      ["description"] = "Weapons Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.614,
      ["y"] = 0.41200000000000003,
    },
    {
      ["category"] = "repair",
      ["name"] = "Lauren Newcomb",
      ["id"] = "4558",
      ["description"] = "Light Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.64,
      ["y"] = 0.38,
    },
    {
      ["category"] = "repair",
      ["name"] = "Timothy Weldon",
      ["id"] = "4559",
      ["description"] = "Heavy Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.628,
      ["y"] = 0.39799999999999996,
    },
    {
      ["category"] = "repair",
      ["name"] = "Walter Ellingson",
      ["id"] = "4560",
      ["description"] = "Heavy Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.626,
      ["y"] = 0.39,
    },
    {
      ["category"] = "repair",
      ["name"] = "Charles Seaton",
      ["id"] = "4569",
      ["description"] = "Blade Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.77,
      ["y"] = 0.5,
    },
    {
      ["category"] = "repair",
      ["name"] = "Sydney Upton",
      ["id"] = "4570",
      ["description"] = "Staff Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.698,
      ["y"] = 0.27399999999999997,
    },
    {
      ["category"] = "repair",
      ["name"] = "Lucille Castleton",
      ["id"] = "4580",
      ["description"] = "Robe Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.71,
      ["y"] = 0.292,
    },
    {
      ["category"] = "repair",
      ["name"] = "Nathaniel Steenwick",
      ["id"] = "4592",
      ["description"] = "Thrown Weapons Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.772,
      ["y"] = 0.5,
    },
    {
      ["category"] = "repair",
      ["name"] = "Samuel Van Brunt",
      ["id"] = "4597",
      ["description"] = "Blacksmithing Supplier",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.612,
      ["y"] = 0.294,
    },
    {
      ["category"] = "repair",
      ["name"] = "Geoffrey Hartwell",
      ["id"] = "4600",
      ["description"] = "Weapon Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.584,
      ["y"] = 0.326,
    },
    {
      ["category"] = "repair",
      ["name"] = "Francis Eliot",
      ["id"] = "4601",
      ["description"] = "Weapon Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.586,
      ["y"] = 0.324,
    },
    {
      ["category"] = "repair",
      ["name"] = "Benijah Fenner",
      ["id"] = "4602",
      ["description"] = "Weapon Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.584,
      ["y"] = 0.324,
    },
    {
      ["category"] = "repair",
      ["name"] = "Nicholas Atwood",
      ["id"] = "4603",
      ["description"] = "Gun Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.622,
      ["y"] = 0.27,
    },
    {
      ["category"] = "repair",
      ["name"] = "Abigail Sawyer",
      ["id"] = "4604",
      ["description"] = "Bow Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.5479999999999999,
      ["y"] = 0.38,
    },
    {
      ["category"] = "repair",
      ["name"] = "Zane Bradford",
      ["id"] = "5754",
      ["description"] = "Wand Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.7,
      ["y"] = 0.272,
    },
    {
      ["category"] = "repair",
      ["name"] = "Mirelle Tremayne",
      ["id"] = "5819",
      ["description"] = "Heavy Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.614,
      ["y"] = 0.28600000000000003,
    },
    {
      ["category"] = "repair",
      ["name"] = "Gillian Moore",
      ["id"] = "5820",
      ["description"] = "Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.7040000000000001,
      ["y"] = 0.586,
    },
    {
      ["category"] = "repair",
      ["name"] = "Sheldon Von Croy",
      ["id"] = "5821",
      ["description"] = "Cloth Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.706,
      ["y"] = 0.28800000000000003,
    },
    {
      ["category"] = "auctioneer",
      ["name"] = "Auctioneer Leeka",
      ["id"] = "8672",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.6779999999999999,
      ["y"] = 0.522,
    },
    {
      ["category"] = "auctioneer",
      ["name"] = "Auctioneer Epitwee",
      ["id"] = "8721",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.642,
      ["y"] = 0.522,
    },
    {
      ["category"] = "auctioneer",
      ["name"] = "Auctioneer Stockton",
      ["id"] = "15675",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.7120000000000001,
      ["y"] = 0.47,
    },
    {
      ["category"] = "auctioneer",
      ["name"] = "Auctioneer Yarly",
      ["id"] = "15676",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.7140000000000001,
      ["y"] = 0.414,
    },
    {
      ["category"] = "auctioneer",
      ["name"] = "Auctioneer Cain",
      ["id"] = "15682",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.6779999999999999,
      ["y"] = 0.36,
    },
    {
      ["category"] = "auctioneer",
      ["name"] = "Auctioneer Naxxremis",
      ["id"] = "15683",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.64,
      ["y"] = 0.36,
    },
    {
      ["category"] = "auctioneer",
      ["name"] = "Auctioneer Tricket",
      ["id"] = "15684",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.606,
      ["y"] = 0.41200000000000003,
    },
    {
      ["category"] = "auctioneer",
      ["name"] = "Auctioneer Rhyker",
      ["id"] = "15686",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.606,
      ["y"] = 0.46799999999999997,
    },
    {
      ["category"] = "banker",
      ["name"] = "Randolph Montague",
      ["id"] = "2458",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.66,
      ["y"] = 0.43,
    },
    {
      ["category"] = "banker",
      ["name"] = "Mortimer Montague",
      ["id"] = "2459",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.6679999999999999,
      ["y"] = 0.44,
    },
    {
      ["category"] = "banker",
      ["name"] = "William Montague",
      ["id"] = "4549",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.66,
      ["y"] = 0.452,
    },
    {
      ["category"] = "banker",
      ["name"] = "Ophelia Montague",
      ["id"] = "4550",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.652,
      ["y"] = 0.44,
    },
    {
      ["category"] = "battlemaster",
      ["name"] = "Grizzle Halfmane",
      ["id"] = "347",
      ["description"] = "Alterac Valley Battlemaster",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.562,
      ["y"] = 0.856,
    },
    {
      ["category"] = "battlemaster",
      ["name"] = "Kurden Bloodclaw",
      ["id"] = "2804",
      ["description"] = "Warsong Gulch Battlemaster",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.544,
      ["y"] = 0.958,
    },
    {
      ["category"] = "battlemaster",
      ["name"] = "Defilers Emissary",
      ["id"] = "14990",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.7340000000000001,
      ["y"] = 0.442,
    },
    {
      ["category"] = "battlemaster",
      ["name"] = "Sir Malory Wheeler",
      ["id"] = "15007",
      ["description"] = "Arathi Basin Battlemaster",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.61,
      ["y"] = 0.93,
    },
    {
      ["category"] = "battlemaster",
      ["name"] = "Warsong Emissary",
      ["id"] = "15105",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.66,
      ["y"] = 0.552,
    },
    {
      ["category"] = "battlemaster",
      ["name"] = "Frostwolf Emissary",
      ["id"] = "15106",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.66,
      ["y"] = 0.5539999999999999,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Innkeeper Norman",
      ["id"] = "6741",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.6759999999999999,
      ["y"] = 0.382,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Anya Maulray",
      ["id"] = "10053",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.674,
      ["y"] = 0.38,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Michael Garrett",
      ["id"] = "4551",
      ["description"] = "Bat Handler",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.634,
      ["y"] = 0.486,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Dan Golthas",
      ["id"] = "223",
      ["description"] = "Journeyman Leatherworker",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.708,
      ["y"] = 0.586,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Lexington Mortaim",
      ["id"] = "2492",
      ["description"] = "Portal Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.8420000000000001,
      ["y"] = 0.16,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Eunice Burch",
      ["id"] = "4552",
      ["description"] = "Cooking Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.622,
      ["y"] = 0.446,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Kaal Soulreaper",
      ["id"] = "4563",
      ["description"] = "Warlock Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.86,
      ["y"] = 0.156,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Luther Pickman",
      ["id"] = "4564",
      ["description"] = "Warlock Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.862,
      ["y"] = 0.152,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Richard Kerwin",
      ["id"] = "4565",
      ["description"] = "Warlock Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.8859999999999999,
      ["y"] = 0.16,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Kaelystia Hatebringer",
      ["id"] = "4566",
      ["description"] = "Mage Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.852,
      ["y"] = 0.142,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Pierce Shackleton",
      ["id"] = "4567",
      ["description"] = "Mage Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.8540000000000001,
      ["y"] = 0.138,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Anastasia Hartwell",
      ["id"] = "4568",
      ["description"] = "Mage Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.85,
      ["y"] = 0.102,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Armand Cromwell",
      ["id"] = "4573",
      ["description"] = "Fishing Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.8079999999999999,
      ["y"] = 0.312,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Josef Gregorian",
      ["id"] = "4576",
      ["description"] = "Artisan Tailor",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.706,
      ["y"] = 0.304,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Josephine Lister",
      ["id"] = "4578",
      ["description"] = "Master Shadoweave Tailor",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.8640000000000001,
      ["y"] = 0.222,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Carolyn Ward",
      ["id"] = "4582",
      ["description"] = "Rogue Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.838,
      ["y"] = 0.716,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Miles Dexter",
      ["id"] = "4583",
      ["description"] = "Rogue Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.85,
      ["y"] = 0.7120000000000001,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Gregory Charles",
      ["id"] = "4584",
      ["description"] = "Rogue Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.846,
      ["y"] = 0.732,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Graham Van Talen",
      ["id"] = "4586",
      ["description"] = "Journeyman Engineer",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.7559999999999999,
      ["y"] = 0.732,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Arthur Moore",
      ["id"] = "4588",
      ["description"] = "Expert Leatherworker",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.7040000000000001,
      ["y"] = 0.578,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Mary Edras",
      ["id"] = "4591",
      ["description"] = "First Aid Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.7340000000000001,
      ["y"] = 0.556,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Christoph Walker",
      ["id"] = "4593",
      ["description"] = "Warrior Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.47200000000000003,
      ["y"] = 0.15,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Angela Curthas",
      ["id"] = "4594",
      ["description"] = "Warrior Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.48200000000000004,
      ["y"] = 0.156,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Baltus Fowler",
      ["id"] = "4595",
      ["description"] = "Warrior Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.47200000000000003,
      ["y"] = 0.17,
    },
    {
      ["category"] = "trainer",
      ["name"] = "James Van Brunt",
      ["id"] = "4596",
      ["description"] = "Expert Blacksmith",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.612,
      ["y"] = 0.3,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Brom Killian",
      ["id"] = "4598",
      ["description"] = "Mining Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.56,
      ["y"] = 0.37,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Basil Frye",
      ["id"] = "4605",
      ["description"] = "Journeyman Blacksmith",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.6,
      ["y"] = 0.28600000000000003,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Aelthalyste",
      ["id"] = "4606",
      ["description"] = "Priest Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.49200000000000005,
      ["y"] = 0.182,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Father Lankester",
      ["id"] = "4607",
      ["description"] = "Priest Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.496,
      ["y"] = 0.156,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Father Lazarus",
      ["id"] = "4608",
      ["description"] = "Priest Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.474,
      ["y"] = 0.192,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Doctor Marsh",
      ["id"] = "4609",
      ["description"] = "Expert Alchemist",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.514,
      ["y"] = 0.742,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Doctor Herbert Halsey",
      ["id"] = "4611",
      ["description"] = "Artisan Alchemist",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.47600000000000003,
      ["y"] = 0.73,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Martha Alliestar",
      ["id"] = "4614",
      ["description"] = "Herbalism Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.542,
      ["y"] = 0.498,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Lavinia Crowe",
      ["id"] = "4616",
      ["description"] = "Expert Enchanter",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.622,
      ["y"] = 0.616,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Killian Hagey",
      ["id"] = "7087",
      ["description"] = "Skinning Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.7040000000000001,
      ["y"] = 0.5920000000000001,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Franklin Lloyd",
      ["id"] = "11031",
      ["description"] = "Expert Engineer",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.76,
      ["y"] = 0.738,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Doctor Martin Felben",
      ["id"] = "11044",
      ["description"] = "Journeyman Alchemist Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.466,
      ["y"] = 0.7440000000000001,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Victor Ward",
      ["id"] = "11048",
      ["description"] = "Journeyman Tailor",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.7020000000000001,
      ["y"] = 0.29600000000000004,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Rhiannon Davis",
      ["id"] = "11049",
      ["description"] = "Expert Tailor",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.7020000000000001,
      ["y"] = 0.302,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Malcomb Wynn",
      ["id"] = "11067",
      ["description"] = "Journeyman Enchanter",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.622,
      ["y"] = 0.604,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Archibald",
      ["id"] = "11870",
      ["description"] = "Weapon Master",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.57,
      ["y"] = 0.32799999999999996,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Keeper Bel'dugur",
      ["id"] = "2934",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.536,
      ["y"] = 0.54,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Ronald Burch",
      ["id"] = "4553",
      ["description"] = "Cooking Supplier",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.624,
      ["y"] = 0.434,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Tawny Grisette",
      ["id"] = "4554",
      ["description"] = "Mushroom Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.682,
      ["y"] = 0.39399999999999996,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Eleanor Rusk",
      ["id"] = "4555",
      ["description"] = "General Goods Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.69,
      ["y"] = 0.486,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Gordon Wendham",
      ["id"] = "4556",
      ["description"] = "Weapons Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.618,
      ["y"] = 0.418,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Louis Warren",
      ["id"] = "4557",
      ["description"] = "Weapons Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.614,
      ["y"] = 0.41200000000000003,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Lauren Newcomb",
      ["id"] = "4558",
      ["description"] = "Light Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.64,
      ["y"] = 0.38,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Timothy Weldon",
      ["id"] = "4559",
      ["description"] = "Heavy Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.628,
      ["y"] = 0.39799999999999996,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Walter Ellingson",
      ["id"] = "4560",
      ["description"] = "Heavy Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.626,
      ["y"] = 0.39,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Daniel Bartlett",
      ["id"] = "4561",
      ["description"] = "General Trade Supplier",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.642,
      ["y"] = 0.37799999999999995,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Thomas Mordan",
      ["id"] = "4562",
      ["description"] = "Reagent Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.6940000000000001,
      ["y"] = 0.392,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Charles Seaton",
      ["id"] = "4569",
      ["description"] = "Blade Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.77,
      ["y"] = 0.5,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Sydney Upton",
      ["id"] = "4570",
      ["description"] = "Staff Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.698,
      ["y"] = 0.27399999999999997,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Morley Bates",
      ["id"] = "4571",
      ["description"] = "Fungus Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.7759999999999999,
      ["y"] = 0.268,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Lizbeth Cromwell",
      ["id"] = "4574",
      ["description"] = "Fishing Supplier",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.812,
      ["y"] = 0.308,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Hannah Akeley",
      ["id"] = "4575",
      ["description"] = "Reagent Supplier",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.826,
      ["y"] = 0.16,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Millie Gregorian",
      ["id"] = "4577",
      ["description"] = "Tailoring Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.708,
      ["y"] = 0.29600000000000004,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Lucille Castleton",
      ["id"] = "4580",
      ["description"] = "Robe Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.71,
      ["y"] = 0.292,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Salazar Bloch",
      ["id"] = "4581",
      ["description"] = "Book Dealer",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.772,
      ["y"] = 0.386,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Ezekiel Graves",
      ["id"] = "4585",
      ["description"] = "Poison Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.7559999999999999,
      ["y"] = 0.514,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Elizabeth Van Talen",
      ["id"] = "4587",
      ["description"] = "Engineering Supplier",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.758,
      ["y"] = 0.738,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Joseph Moore",
      ["id"] = "4589",
      ["description"] = "Leatherworking Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.7040000000000001,
      ["y"] = 0.588,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jonathan Chambers",
      ["id"] = "4590",
      ["description"] = "Bag Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.696,
      ["y"] = 0.61,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Nathaniel Steenwick",
      ["id"] = "4592",
      ["description"] = "Thrown Weapons Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.772,
      ["y"] = 0.5,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Samuel Van Brunt",
      ["id"] = "4597",
      ["description"] = "Blacksmithing Supplier",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.612,
      ["y"] = 0.294,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Sarah Killian",
      ["id"] = "4599",
      ["description"] = "Mining Supplier",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.562,
      ["y"] = 0.368,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Geoffrey Hartwell",
      ["id"] = "4600",
      ["description"] = "Weapon Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.584,
      ["y"] = 0.326,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Francis Eliot",
      ["id"] = "4601",
      ["description"] = "Weapon Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.586,
      ["y"] = 0.324,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Benijah Fenner",
      ["id"] = "4602",
      ["description"] = "Weapon Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.584,
      ["y"] = 0.324,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Nicholas Atwood",
      ["id"] = "4603",
      ["description"] = "Gun Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.622,
      ["y"] = 0.27,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Abigail Sawyer",
      ["id"] = "4604",
      ["description"] = "Bow Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.5479999999999999,
      ["y"] = 0.38,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Algernon",
      ["id"] = "4610",
      ["description"] = "Alchemy Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.518,
      ["y"] = 0.7440000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Katrina Alliestar",
      ["id"] = "4615",
      ["description"] = "Herbalism Supplier",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.546,
      ["y"] = 0.494,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Thaddeus Webb",
      ["id"] = "4617",
      ["description"] = "Enchanting Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.62,
      ["y"] = 0.608,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Felicia Doan",
      ["id"] = "4775",
      ["description"] = "General Trade Goods Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.642,
      ["y"] = 0.502,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Merill Pleasance",
      ["id"] = "5190",
      ["description"] = "Tabard Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.6920000000000001,
      ["y"] = 0.444,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Joanna Whitehall",
      ["id"] = "5698",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.53,
      ["y"] = 0.35200000000000004,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Martha Strain",
      ["id"] = "5753",
      ["description"] = "Demon Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.858,
      ["y"] = 0.158,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Zane Bradford",
      ["id"] = "5754",
      ["description"] = "Wand Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.7,
      ["y"] = 0.272,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Mirelle Tremayne",
      ["id"] = "5819",
      ["description"] = "Heavy Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.614,
      ["y"] = 0.28600000000000003,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Gillian Moore",
      ["id"] = "5820",
      ["description"] = "Leather Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.7040000000000001,
      ["y"] = 0.586,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Sheldon Von Croy",
      ["id"] = "5821",
      ["description"] = "Cloth Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.706,
      ["y"] = 0.28800000000000003,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Innkeeper Norman",
      ["id"] = "6741",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.6759999999999999,
      ["y"] = 0.382,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Alessandro Luca",
      ["id"] = "7683",
      ["description"] = "Blue Moon Odds and Ends",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.5820000000000001,
      ["y"] = 0.552,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jeremiah Payson",
      ["id"] = "8403",
      ["description"] = "Cockroach Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.674,
      ["y"] = 0.43799999999999994,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Nardstrum Copperpinch",
      ["id"] = "13429",
      ["description"] = "Smokywood Pastures",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.68,
      ["y"] = 0.38799999999999996,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jaycrue Copperpinch",
      ["id"] = "13430",
      ["description"] = "Smokywood Pastures",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.6779999999999999,
      ["y"] = 0.386,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Lunar Festival Vendor",
      ["id"] = "15898",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.662,
      ["y"] = 0.358,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Gishah",
      ["id"] = "214098",
      ["description"] = "Supply Officer",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.648,
      ["y"] = 0.382,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Rune Broker",
      ["id"] = "233428",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.794,
      ["y"] = 0.198,
    },
    {
      ["category"] = "spirithealer",
      ["name"] = "Spirit Healer",
      ["id"] = "6491",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.674,
      ["y"] = 0.126,
    },
    {
      ["category"] = "book",
      ["name"] = "Here Lies King Terenas Menethil II",
      ["id"] = "175659",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.6609999999999999,
      ["y"] = 0.436,
    },
    {
      ["category"] = "book",
      ["name"] = "The Old Gods and the Ordering of Azeroth",
      ["id"] = "175725",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.5589999999999999,
      ["y"] = 0.509,
    },
    {
      ["category"] = "book",
      ["name"] = "Exile of the High Elves",
      ["id"] = "175731",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.617,
      ["y"] = 0.581,
    },
    {
      ["category"] = "book",
      ["name"] = "Icecrown and the Frozen Throne",
      ["id"] = "175749",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.5589999999999999,
      ["y"] = 0.509,
    },
    {
      ["category"] = "book",
      ["name"] = "Kel'Thuzad and the Forming of the Scourge",
      ["id"] = "175754",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.5589999999999999,
      ["y"] = 0.509,
    },
    {
      ["category"] = "book",
      ["name"] = "Civil War in the Plaguelands",
      ["id"] = "175761",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.677,
      ["y"] = 0.376,
    },
    {
      ["category"] = "forge",
      ["name"] = "Forge",
      ["id"] = "1685",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.6,
      ["y"] = 0.28600000000000003,
    },
    {
      ["category"] = "mailbox",
      ["name"] = "Mailbox",
      ["id"] = "32349",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Undercity",
      ["subLocation"] = "Undercity",
      ["x"] = 0.679,
      ["y"] = 0.384,
    },
  }
}
