DB_WESTFALL_GENERAL = {
  ["region"] = "Eastern Kingdoms",
  ["mapID"] = 1436,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "William MacGregor",
      ["id"] = "1668",
      ["description"] = "Bowyer",
      ["comment"] = "",
      ["mainLocation"] = "Westfall",
      ["subLocation"] = "Westfall",
      ["x"] = 0.5760000000000001,
      ["y"] = 0.5379999999999999,
    },
    {
      ["category"] = "repair",
      ["name"] = "Defias Profiteer",
      ["id"] = "1669",
      ["description"] = "Free Wheeling Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Westfall",
      ["subLocation"] = "Westfall",
      ["x"] = 0.434,
      ["y"] = 0.6679999999999999,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Innkeeper Heather",
      ["id"] = "8931",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Westfall",
      ["subLocation"] = "Westfall",
      ["x"] = 0.528,
      ["y"] = 0.536,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Kirk Maxwell",
      ["id"] = "10045",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "Westfall",
      ["subLocation"] = "Westfall",
      ["x"] = 0.53,
      ["y"] = 0.53,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Thor",
      ["id"] = "523",
      ["description"] = "Gryphon Master",
      ["comment"] = "",
      ["mainLocation"] = "Westfall",
      ["subLocation"] = "Westfall",
      ["x"] = 0.564,
      ["y"] = 0.526,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Farmer Saldean",
      ["id"] = "233",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Westfall",
      ["subLocation"] = "Westfall",
      ["x"] = 0.56,
      ["y"] = 0.312,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Quartermaster Lewis",
      ["id"] = "491",
      ["description"] = "Quartermaster",
      ["comment"] = "",
      ["mainLocation"] = "Westfall",
      ["subLocation"] = "Westfall",
      ["x"] = 0.568,
      ["y"] = 0.47200000000000003,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Gina MacGregor",
      ["id"] = "843",
      ["description"] = "Trade Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Westfall",
      ["subLocation"] = "Westfall",
      ["x"] = 0.5760000000000001,
      ["y"] = 0.54,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Antonio Perelli",
      ["id"] = "844",
      ["description"] = "Traveling Salesman",
      ["comment"] = "",
      ["mainLocation"] = "Westfall",
      ["subLocation"] = "Westfall",
      ["x"] = 0.574,
      ["y"] = 0.522,
    },
    {
      ["category"] = "vendor",
      ["name"] = "William MacGregor",
      ["id"] = "1668",
      ["description"] = "Bowyer",
      ["comment"] = "",
      ["mainLocation"] = "Westfall",
      ["subLocation"] = "Westfall",
      ["x"] = 0.5760000000000001,
      ["y"] = 0.5379999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Defias Profiteer",
      ["id"] = "1669",
      ["description"] = "Free Wheeling Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Westfall",
      ["subLocation"] = "Westfall",
      ["x"] = 0.434,
      ["y"] = 0.6679999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Mike Miller",
      ["id"] = "1670",
      ["description"] = "Bread Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Westfall",
      ["subLocation"] = "Westfall",
      ["x"] = 0.5760000000000001,
      ["y"] = 0.536,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kriggon Talsone",
      ["id"] = "4305",
      ["description"] = "Fisherman",
      ["comment"] = "",
      ["mainLocation"] = "Westfall",
      ["subLocation"] = "Westfall",
      ["x"] = 0.36200000000000004,
      ["y"] = 0.9,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Innkeeper Heather",
      ["id"] = "8931",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Westfall",
      ["subLocation"] = "Westfall",
      ["x"] = 0.528,
      ["y"] = 0.536,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Christopher Hewen",
      ["id"] = "8934",
      ["description"] = "General Trade Goods Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Westfall",
      ["subLocation"] = "Westfall",
      ["x"] = 0.522,
      ["y"] = 0.528,
    },
    {
      ["category"] = "spirithealer",
      ["name"] = "Spirit Healer",
      ["id"] = "6491",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Westfall",
      ["subLocation"] = "Westfall",
      ["x"] = 0.514,
      ["y"] = 0.498,
    },
    {
      ["category"] = "book",
      ["name"] = "Aegwynn and the Dragon Hunt",
      ["id"] = "175738",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Westfall",
      ["subLocation"] = "Westfall",
      ["x"] = 0.564,
      ["y"] = 0.302,
    },
    {
      ["category"] = "book",
      ["name"] = "The Last Guardian",
      ["id"] = "175740",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Westfall",
      ["subLocation"] = "Westfall",
      ["x"] = 0.525,
      ["y"] = 0.531,
    },
    {
      ["category"] = "book",
      ["name"] = "The Scourge of Lordaeron",
      ["id"] = "175756",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Westfall",
      ["subLocation"] = "Westfall",
      ["x"] = 0.569,
      ["y"] = 0.474,
    },
    {
      ["category"] = "mailbox",
      ["name"] = "Mailbox",
      ["id"] = "32349",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Westfall",
      ["subLocation"] = "Westfall",
      ["x"] = 0.53,
      ["y"] = 0.535,
    },
  }
}
