DB_WESTERN_PLAGUELANDS_GENERAL = {
  ["region"] = "Eastern Kingdoms",
  ["mapID"] = 1422,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Argent Quartermaster Lightspark",
      ["id"] = "10857",
      ["description"] = "The Argent Dawn",
      ["comment"] = "",
      ["mainLocation"] = "Western Plaguelands",
      ["subLocation"] = "Western Plaguelands",
      ["x"] = 0.428,
      ["y"] = 0.838,
    },
    {
      ["category"] = "repair",
      ["name"] = "Magnus Frostwake",
      ["id"] = "11278",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Western Plaguelands",
      ["subLocation"] = "Western Plaguelands",
      ["x"] = 0.68,
      ["y"] = 0.7759999999999999,
    },
    {
      ["category"] = "repair",
      ["name"] = "Leonard Porter",
      ["id"] = "12942",
      ["description"] = "Leatherworking Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Western Plaguelands",
      ["subLocation"] = "Western Plaguelands",
      ["x"] = 0.43,
      ["y"] = 0.8420000000000001,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Bibilfaz Featherwhistle",
      ["id"] = "12596",
      ["description"] = "Gryphon Master",
      ["comment"] = "",
      ["mainLocation"] = "Western Plaguelands",
      ["subLocation"] = "Western Plaguelands",
      ["x"] = 0.428,
      ["y"] = 0.85,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Chromie",
      ["id"] = "10667",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Western Plaguelands",
      ["subLocation"] = "Western Plaguelands",
      ["x"] = 0.39399999999999996,
      ["y"] = 0.6679999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Argent Quartermaster Lightspark",
      ["id"] = "10857",
      ["description"] = "The Argent Dawn",
      ["comment"] = "",
      ["mainLocation"] = "Western Plaguelands",
      ["subLocation"] = "Western Plaguelands",
      ["x"] = 0.428,
      ["y"] = 0.838,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Alchemist Arbington",
      ["id"] = "11056",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Western Plaguelands",
      ["subLocation"] = "Western Plaguelands",
      ["x"] = 0.426,
      ["y"] = 0.838,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Magnus Frostwake",
      ["id"] = "11278",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Western Plaguelands",
      ["subLocation"] = "Western Plaguelands",
      ["x"] = 0.68,
      ["y"] = 0.7759999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Baker Masterson",
      ["id"] = "11287",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Western Plaguelands",
      ["subLocation"] = "Western Plaguelands",
      ["x"] = 0.6940000000000001,
      ["y"] = 0.794,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Leonard Porter",
      ["id"] = "12942",
      ["description"] = "Leatherworking Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Western Plaguelands",
      ["subLocation"] = "Western Plaguelands",
      ["x"] = 0.43,
      ["y"] = 0.8420000000000001,
    },
    {
      ["category"] = "spirithealer",
      ["name"] = "Spirit Healer",
      ["id"] = "6491",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Western Plaguelands",
      ["subLocation"] = "Western Plaguelands",
      ["x"] = 0.45399999999999996,
      ["y"] = 0.8540000000000001,
    },
    {
      ["category"] = "book",
      ["name"] = "Uther the Lightbringer",
      ["id"] = "2082",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Western Plaguelands",
      ["subLocation"] = "Western Plaguelands",
      ["x"] = 0.521,
      ["y"] = 0.8320000000000001,
    },
  }
}
