DB_WETLANDS_GENERAL = {
  ["region"] = "Eastern Kingdoms",
  ["mapID"] = 1437,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Brak Durnad",
      ["id"] = "1441",
      ["description"] = "Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Wetlands",
      ["subLocation"] = "Wetlands",
      ["x"] = 0.114,
      ["y"] = 0.596,
    },
    {
      ["category"] = "repair",
      ["name"] = "Brahnmar",
      ["id"] = "1450",
      ["description"] = "Armorer",
      ["comment"] = "",
      ["mainLocation"] = "Wetlands",
      ["subLocation"] = "Wetlands",
      ["x"] = 0.114,
      ["y"] = 0.596,
    },
    {
      ["category"] = "repair",
      ["name"] = "Jennabink Powerseam",
      ["id"] = "1454",
      ["description"] = "Tailoring Supplies & Specialty Goods",
      ["comment"] = "",
      ["mainLocation"] = "Wetlands",
      ["subLocation"] = "Wetlands",
      ["x"] = 0.08,
      ["y"] = 0.5579999999999999,
    },
    {
      ["category"] = "repair",
      ["name"] = "Naela Trance",
      ["id"] = "1459",
      ["description"] = "Bowyer",
      ["comment"] = "",
      ["mainLocation"] = "Wetlands",
      ["subLocation"] = "Wetlands",
      ["x"] = 0.11199999999999999,
      ["y"] = 0.584,
    },
    {
      ["category"] = "repair",
      ["name"] = "Murndan Derth",
      ["id"] = "1461",
      ["description"] = "Gunsmith",
      ["comment"] = "",
      ["mainLocation"] = "Wetlands",
      ["subLocation"] = "Wetlands",
      ["x"] = 0.114,
      ["y"] = 0.596,
    },
    {
      ["category"] = "repair",
      ["name"] = "Edwina Monzor",
      ["id"] = "1462",
      ["description"] = "Fletcher",
      ["comment"] = "",
      ["mainLocation"] = "Wetlands",
      ["subLocation"] = "Wetlands",
      ["x"] = 0.11,
      ["y"] = 0.584,
    },
    {
      ["category"] = "repair",
      ["name"] = "Wenna Silkbeard",
      ["id"] = "2679",
      ["description"] = "Special Goods Dealer",
      ["comment"] = "",
      ["mainLocation"] = "Wetlands",
      ["subLocation"] = "Wetlands",
      ["x"] = 0.256,
      ["y"] = 0.258,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Innkeeper Helbrek",
      ["id"] = "1464",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Wetlands",
      ["subLocation"] = "Wetlands",
      ["x"] = 0.106,
      ["y"] = 0.608,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Bethaine Flinthammer",
      ["id"] = "10046",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "Wetlands",
      ["subLocation"] = "Wetlands",
      ["x"] = 0.10400000000000001,
      ["y"] = 0.596,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Shellei Brondir",
      ["id"] = "1571",
      ["description"] = "Gryphon Master",
      ["comment"] = "",
      ["mainLocation"] = "Wetlands",
      ["subLocation"] = "Wetlands",
      ["x"] = 0.094,
      ["y"] = 0.596,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Telurinon Moonshadow",
      ["id"] = "1458",
      ["description"] = "Herbalism Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Wetlands",
      ["subLocation"] = "Wetlands",
      ["x"] = 0.08,
      ["y"] = 0.5579999999999999,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Harold Riggs",
      ["id"] = "3179",
      ["description"] = "Fishing Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Wetlands",
      ["subLocation"] = "Wetlands",
      ["x"] = 0.08,
      ["y"] = 0.584,
    },
    {
      ["category"] = "trainer",
      ["name"] = "Fremal Doohickey",
      ["id"] = "3181",
      ["description"] = "First Aid Trainer",
      ["comment"] = "",
      ["mainLocation"] = "Wetlands",
      ["subLocation"] = "Wetlands",
      ["x"] = 0.10800000000000001,
      ["y"] = 0.612,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Brak Durnad",
      ["id"] = "1441",
      ["description"] = "Weaponsmith",
      ["comment"] = "",
      ["mainLocation"] = "Wetlands",
      ["subLocation"] = "Wetlands",
      ["x"] = 0.114,
      ["y"] = 0.596,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Neal Allen",
      ["id"] = "1448",
      ["description"] = "Engineering & General Goods Supplier",
      ["comment"] = "",
      ["mainLocation"] = "Wetlands",
      ["subLocation"] = "Wetlands",
      ["x"] = 0.106,
      ["y"] = 0.568,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Brahnmar",
      ["id"] = "1450",
      ["description"] = "Armorer",
      ["comment"] = "",
      ["mainLocation"] = "Wetlands",
      ["subLocation"] = "Wetlands",
      ["x"] = 0.114,
      ["y"] = 0.596,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Gruham Rumdnul",
      ["id"] = "1452",
      ["description"] = "General Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Wetlands",
      ["subLocation"] = "Wetlands",
      ["x"] = 0.12,
      ["y"] = 0.578,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Dewin Shimmerdawn",
      ["id"] = "1453",
      ["description"] = "Alchemy Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Wetlands",
      ["subLocation"] = "Wetlands",
      ["x"] = 0.08,
      ["y"] = 0.562,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Jennabink Powerseam",
      ["id"] = "1454",
      ["description"] = "Tailoring Supplies & Specialty Goods",
      ["comment"] = "",
      ["mainLocation"] = "Wetlands",
      ["subLocation"] = "Wetlands",
      ["x"] = 0.08,
      ["y"] = 0.5579999999999999,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kersok Prond",
      ["id"] = "1456",
      ["description"] = "Tradesman",
      ["comment"] = "",
      ["mainLocation"] = "Wetlands",
      ["subLocation"] = "Wetlands",
      ["x"] = 0.10400000000000001,
      ["y"] = 0.606,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Samor Festivus",
      ["id"] = "1457",
      ["description"] = "Shady Dealer",
      ["comment"] = "",
      ["mainLocation"] = "Wetlands",
      ["subLocation"] = "Wetlands",
      ["x"] = 0.10400000000000001,
      ["y"] = 0.602,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Naela Trance",
      ["id"] = "1459",
      ["description"] = "Bowyer",
      ["comment"] = "",
      ["mainLocation"] = "Wetlands",
      ["subLocation"] = "Wetlands",
      ["x"] = 0.11199999999999999,
      ["y"] = 0.584,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Unger Statforth",
      ["id"] = "1460",
      ["description"] = "Horse Breeder",
      ["comment"] = "",
      ["mainLocation"] = "Wetlands",
      ["subLocation"] = "Wetlands",
      ["x"] = 0.086,
      ["y"] = 0.544,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Murndan Derth",
      ["id"] = "1461",
      ["description"] = "Gunsmith",
      ["comment"] = "",
      ["mainLocation"] = "Wetlands",
      ["subLocation"] = "Wetlands",
      ["x"] = 0.114,
      ["y"] = 0.596,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Edwina Monzor",
      ["id"] = "1462",
      ["description"] = "Fletcher",
      ["comment"] = "",
      ["mainLocation"] = "Wetlands",
      ["subLocation"] = "Wetlands",
      ["x"] = 0.11,
      ["y"] = 0.584,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Falkan Armonis",
      ["id"] = "1463",
      ["description"] = "Reagent Vendor",
      ["comment"] = "",
      ["mainLocation"] = "Wetlands",
      ["subLocation"] = "Wetlands",
      ["x"] = 0.084,
      ["y"] = 0.564,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Innkeeper Helbrek",
      ["id"] = "1464",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Wetlands",
      ["subLocation"] = "Wetlands",
      ["x"] = 0.106,
      ["y"] = 0.608,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Wenna Silkbeard",
      ["id"] = "2679",
      ["description"] = "Special Goods Dealer",
      ["comment"] = "",
      ["mainLocation"] = "Wetlands",
      ["subLocation"] = "Wetlands",
      ["x"] = 0.256,
      ["y"] = 0.258,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Fradd Swiftgear",
      ["id"] = "2682",
      ["description"] = "Engineering Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Wetlands",
      ["subLocation"] = "Wetlands",
      ["x"] = 0.264,
      ["y"] = 0.258,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Stuart Fleming",
      ["id"] = "3178",
      ["description"] = "Fisherman",
      ["comment"] = "",
      ["mainLocation"] = "Wetlands",
      ["subLocation"] = "Wetlands",
      ["x"] = 0.08,
      ["y"] = 0.5820000000000001,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Dark Iron Entrepreneur",
      ["id"] = "3180",
      ["description"] = "Speciality Goods",
      ["comment"] = "",
      ["mainLocation"] = "Wetlands",
      ["subLocation"] = "Wetlands",
      ["x"] = 0.466,
      ["y"] = 0.182,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Kixxle",
      ["id"] = "8305",
      ["description"] = "Potions & Herbs",
      ["comment"] = "",
      ["mainLocation"] = "Wetlands",
      ["subLocation"] = "Wetlands",
      ["x"] = 0.502,
      ["y"] = 0.37799999999999995,
    },
    {
      ["category"] = "spirithealer",
      ["name"] = "Spirit Healer",
      ["id"] = "6491",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Wetlands",
      ["subLocation"] = "Wetlands",
      ["x"] = 0.114,
      ["y"] = 0.434,
    },
    {
      ["category"] = "book",
      ["name"] = "The Kaldorei and the Well of Eternity",
      ["id"] = "21583",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Wetlands",
      ["subLocation"] = "Wetlands",
      ["x"] = 0.10400000000000001,
      ["y"] = 0.605,
    },
    {
      ["category"] = "book",
      ["name"] = "The Old Gods and the Ordering of Azeroth",
      ["id"] = "175725",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Wetlands",
      ["subLocation"] = "Wetlands",
      ["x"] = 0.099,
      ["y"] = 0.575,
    },
    {
      ["category"] = "book",
      ["name"] = "Charge of the Dragonflights",
      ["id"] = "175726",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Wetlands",
      ["subLocation"] = "Wetlands",
      ["x"] = 0.1,
      ["y"] = 0.569,
    },
    {
      ["category"] = "book",
      ["name"] = "The Battle of Grim Batol",
      ["id"] = "175750",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Wetlands",
      ["subLocation"] = "Wetlands",
      ["x"] = 0.10800000000000001,
      ["y"] = 0.608,
    },
    {
      ["category"] = "forge",
      ["name"] = "Forge",
      ["id"] = "1685",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Wetlands",
      ["subLocation"] = "Wetlands",
      ["x"] = 0.115,
      ["y"] = 0.595,
    },
    {
      ["category"] = "mailbox",
      ["name"] = "Mailbox",
      ["id"] = "32349",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Wetlands",
      ["subLocation"] = "Wetlands",
      ["x"] = 0.10800000000000001,
      ["y"] = 0.597,
    },
  }
}
