DB_WINTERSPRING_GENERAL = {
  ["region"] = "Kalimdor",
  ["mapID"] = 1452,
  ["entries"] = {
    {
      ["category"] = "repair",
      ["name"] = "Nixxrak",
      ["id"] = "11182",
      ["description"] = "Heavy Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Winterspring",
      ["subLocation"] = "Winterspring",
      ["x"] = 0.616,
      ["y"] = 0.37799999999999995,
    },
    {
      ["category"] = "repair",
      ["name"] = "Blixxrak",
      ["id"] = "11183",
      ["description"] = "Light Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Winterspring",
      ["subLocation"] = "Winterspring",
      ["x"] = 0.616,
      ["y"] = 0.37799999999999995,
    },
    {
      ["category"] = "repair",
      ["name"] = "Wixxrak",
      ["id"] = "11184",
      ["description"] = "Weaponsmith & Gunsmith",
      ["comment"] = "",
      ["mainLocation"] = "Winterspring",
      ["subLocation"] = "Winterspring",
      ["x"] = 0.616,
      ["y"] = 0.38,
    },
    {
      ["category"] = "auctioneer",
      ["name"] = "Auctioneer Grizzlin",
      ["id"] = "9857",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Winterspring",
      ["subLocation"] = "Winterspring",
      ["x"] = 0.614,
      ["y"] = 0.37200000000000005,
    },
    {
      ["category"] = "banker",
      ["name"] = "Izzy Coppergrab",
      ["id"] = "13917",
      ["description"] = "Banker",
      ["comment"] = "",
      ["mainLocation"] = "Winterspring",
      ["subLocation"] = "Winterspring",
      ["x"] = 0.614,
      ["y"] = 0.37,
    },
    {
      ["category"] = "innkeeper",
      ["name"] = "Innkeeper Vizzie",
      ["id"] = "11118",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Winterspring",
      ["subLocation"] = "Winterspring",
      ["x"] = 0.612,
      ["y"] = 0.38799999999999996,
    },
    {
      ["category"] = "stablemaster",
      ["name"] = "Azzleby",
      ["id"] = "11119",
      ["description"] = "Stable Master",
      ["comment"] = "",
      ["mainLocation"] = "Winterspring",
      ["subLocation"] = "Winterspring",
      ["x"] = 0.604,
      ["y"] = 0.38,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Maethrya",
      ["id"] = "11138",
      ["description"] = "Hippogryph Master",
      ["comment"] = "",
      ["mainLocation"] = "Winterspring",
      ["subLocation"] = "Winterspring",
      ["x"] = 0.622,
      ["y"] = 0.366,
    },
    {
      ["category"] = "flightmaster",
      ["name"] = "Yugrek",
      ["id"] = "11139",
      ["description"] = "Wind Rider Master",
      ["comment"] = "",
      ["mainLocation"] = "Winterspring",
      ["subLocation"] = "Winterspring",
      ["x"] = 0.604,
      ["y"] = 0.364,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Natheril Raincaller",
      ["id"] = "2084",
      ["description"] = "General Goods",
      ["comment"] = "",
      ["mainLocation"] = "Winterspring",
      ["subLocation"] = "Winterspring",
      ["x"] = 0.514,
      ["y"] = 0.308,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Lyranne Feathersong",
      ["id"] = "2303",
      ["description"] = "Food & Drink",
      ["comment"] = "",
      ["mainLocation"] = "Winterspring",
      ["subLocation"] = "Winterspring",
      ["x"] = 0.52,
      ["y"] = 0.292,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Syurana",
      ["id"] = "3779",
      ["description"] = "Trade Goods Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Winterspring",
      ["subLocation"] = "Winterspring",
      ["x"] = 0.516,
      ["y"] = 0.298,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Rivern Frostwind",
      ["id"] = "10618",
      ["description"] = "Wintersaber Trainers",
      ["comment"] = "",
      ["mainLocation"] = "Winterspring",
      ["subLocation"] = "Winterspring",
      ["x"] = 0.498,
      ["y"] = 0.098,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Innkeeper Vizzie",
      ["id"] = "11118",
      ["description"] = "Innkeeper",
      ["comment"] = "",
      ["mainLocation"] = "Winterspring",
      ["subLocation"] = "Winterspring",
      ["x"] = 0.612,
      ["y"] = 0.38799999999999996,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Nixxrak",
      ["id"] = "11182",
      ["description"] = "Heavy Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Winterspring",
      ["subLocation"] = "Winterspring",
      ["x"] = 0.616,
      ["y"] = 0.37799999999999995,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Blixxrak",
      ["id"] = "11183",
      ["description"] = "Light Armor Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Winterspring",
      ["subLocation"] = "Winterspring",
      ["x"] = 0.616,
      ["y"] = 0.37799999999999995,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Wixxrak",
      ["id"] = "11184",
      ["description"] = "Weaponsmith & Gunsmith",
      ["comment"] = "",
      ["mainLocation"] = "Winterspring",
      ["subLocation"] = "Winterspring",
      ["x"] = 0.616,
      ["y"] = 0.38,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Xizzer Fizzbolt",
      ["id"] = "11185",
      ["description"] = "Engineering Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Winterspring",
      ["subLocation"] = "Winterspring",
      ["x"] = 0.608,
      ["y"] = 0.386,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Lunnix Sprocketslip",
      ["id"] = "11186",
      ["description"] = "Mining Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Winterspring",
      ["subLocation"] = "Winterspring",
      ["x"] = 0.618,
      ["y"] = 0.386,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Himmik",
      ["id"] = "11187",
      ["description"] = "Food & Drink",
      ["comment"] = "",
      ["mainLocation"] = "Winterspring",
      ["subLocation"] = "Winterspring",
      ["x"] = 0.612,
      ["y"] = 0.39,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Evie Whirlbrew",
      ["id"] = "11188",
      ["description"] = "Alchemy Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Winterspring",
      ["subLocation"] = "Winterspring",
      ["x"] = 0.608,
      ["y"] = 0.37799999999999995,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Qia",
      ["id"] = "11189",
      ["description"] = "Trade Goods Supplies",
      ["comment"] = "",
      ["mainLocation"] = "Winterspring",
      ["subLocation"] = "Winterspring",
      ["x"] = 0.612,
      ["y"] = 0.37200000000000005,
    },
    {
      ["category"] = "vendor",
      ["name"] = "Vi'el",
      ["id"] = "16015",
      ["description"] = "Exotic Reagent Merchant",
      ["comment"] = "",
      ["mainLocation"] = "Winterspring",
      ["subLocation"] = "Winterspring",
      ["x"] = 0.588,
      ["y"] = 0.784,
    },
    {
      ["category"] = "spirithealer",
      ["name"] = "Spirit Healer",
      ["id"] = "6491",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Winterspring",
      ["subLocation"] = "Winterspring",
      ["x"] = 0.612,
      ["y"] = 0.348,
    },
    {
      ["category"] = "mailbox",
      ["name"] = "Mailbox",
      ["id"] = "32349",
      ["description"] = "",
      ["comment"] = "",
      ["mainLocation"] = "Winterspring",
      ["subLocation"] = "Winterspring",
      ["x"] = 0.613,
      ["y"] = 0.386,
    },
  }
}
